// Offline production-shell navigation and header checks.
import assert from 'node:assert/strict';
import {appPageMetadata} from '../../lib/app-navigation.ts';
import {scopeDashboard} from '../fixtures/home-scope-evidence.mjs';
const {chromium}=await import(process.env.PLAYWRIGHT_MODULE??'playwright'),base=process.env.HOME_BASE_URL??'http://127.0.0.1:3369';
const browser=await chromium.launch({executablePath:'/usr/bin/chromium',args:['--no-sandbox']});let checks=0;
const check=(name,value)=>{assert.ok(value,name);checks++;console.log('PASS '+name)};
const expected=['development-planning','labor-market','training-coaching'];
try{for(const width of [1366,390]){
 const context=await browser.newContext({viewport:{width,height:900}}),page=await context.newPage(),errors=[];page.on('pageerror',error=>errors.push(error.message));page.setDefaultTimeout(15000);let writes=0;
 await page.route('**/*',route=>{const req=route.request(),url=new URL(req.url());if(url.origin!==base)return route.abort();if(url.pathname.startsWith('/api/')){if(req.method()!=='GET'){writes++;return route.abort()}return route.fulfill({json:url.pathname==='/api/dashboard'?scopeDashboard(url.search):{metrics:[]}})}return route.continue()});
 await page.goto(base);await page.getByLabel('Ask Workforce AI',{exact:true}).waitFor();
 await page.getByRole('button',{name:'About Home',exact:true}).click();const help=page.getByRole('tooltip');check(width+' floating Home help preserves its heading and exact new copy',await help.getByText('Home',{exact:true}).isVisible()&&await help.getByText('A workforce decision-making tool that turns dashboard insights into practical Action Plans, helping you connect workforce decisions to business outcomes.',{exact:true}).isVisible());await page.keyboard.press('Escape');
 await page.getByRole('button',{name:'Show instructions',exact:true}).click();const instructions=page.locator('#home-starting-instructions');check(width+' step five is explicitly future sharing/tracking with saved-history help retained',await instructions.locator('ol > li').count()===5&&await instructions.locator('ol > li').last().getByText('Share and track your goal (TBD)',{exact:true}).isVisible()&&await instructions.getByText('To reopen saved work, select a Pinned Goal and expand its latest plan. Earlier attachments stay in history.',{exact:true}).isVisible());await page.getByRole('button',{name:'Hide instructions',exact:true}).click();
 async function openNav(){if(width===390)await page.getByRole('button',{name:'Open navigation',exact:true}).click();}
 await openNav();for(const group of ['Intelligence — Realize your potential','Planning — Plan Our Future']){const button=page.getByRole('button',{name:group,exact:true});if(await button.getAttribute('aria-expanded')==='false')await button.click();}
 check(width+' exactly three navigation badges',JSON.stringify(await page.locator('[data-nav-destination]:has([data-limited-preview])').evaluateAll(nodes=>nodes.map(node=>node.dataset.navDestination).sort()))===JSON.stringify(expected));
 for(const key of expected){const item=page.locator(`[data-nav-destination="${key}"]`),meta=appPageMetadata[key];check(width+' '+key+' accessible label and tooltip retained',await item.getAttribute('aria-label')===`${meta.section} — ${meta.label}`&&(await item.getAttribute('title')).includes('Limited preview')&&await item.isEnabled());
  const badge=item.locator('[data-limited-preview]');check(width+' '+key+' badge readable and contained',await badge.isVisible()&&await badge.evaluate(node=>{const r=node.getBoundingClientRect(),button=node.closest('button').getBoundingClientRect();return r.right<=button.right+1&&r.height>=20&&parseFloat(getComputedStyle(node).fontSize)>=11}));
 }
 await page.locator('.app-sidebar').screenshot({path:`/tmp/limited-preview-nav-${width}.png`});
 if(width===1366){await page.getByRole('button',{name:'Collapse navigation',exact:true}).click();for(const key of expected){const item=page.locator(`[data-nav-destination="${key}"]`);check('collapsed '+key+' exposes status description and complete tooltip',await item.getAttribute('aria-describedby')===`nav-preview-${key}`&&await page.locator(`#nav-preview-${key}`).textContent()==='Limited preview'&&(await item.getAttribute('title')).includes(appPageMetadata[key].description));}await page.getByRole('button',{name:'Expand navigation',exact:true}).click();}
 for(const key of expected){await page.locator(`[data-nav-destination="${key}"]`).click();await page.locator('#app-page-title').getByText(appPageMetadata[key].label,{exact:true}).waitFor();const header=page.locator('main > header');check(width+' '+key+' header shows one compact badge and no overflow',await header.locator('[data-limited-preview]').count()===1&&await header.locator('[data-limited-preview]').isVisible()&&await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await header.screenshot({path:`/tmp/limited-preview-header-${key}-${width}.png`});await openNav();}
 await page.getByRole('button',{name:'Action Planning',exact:true}).click();check(width+' Home has no badge and runtime stays clean',await page.locator('main > header [data-limited-preview]').count()===0&&writes===0&&errors.length===0);await context.close();
}}finally{await browser.close()}console.log(JSON.stringify({checks}));
