import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import path from 'node:path';
import os from 'node:os';
import webpackPackage from 'next/dist/compiled/webpack/webpack.js';
import {encodeDecisions,DECISIONS_STORAGE_KEY} from '../../lib/local-decisions.ts';
const {chromium}=await import(process.env.PLAYWRIGHT_MODULE??'playwright');
const output=await fs.mkdtemp(path.join(os.tmpdir(),'retention-ui-'));
const compiler=webpackPackage.webpack({mode:'development',devtool:false,entry:path.resolve('tests/fixtures/retention-what-if.tsx'),output:{path:output,filename:'fixture.js',publicPath:'/assets/'},resolve:{extensions:['.tsx','.ts','.mjs','.js'],alias:{'@':process.cwd()}},module:{rules:[{test:/\.tsx?$/,exclude:/node_modules/,use:path.resolve('tests/fixtures/typescript-browser-loader.mjs')}]}});
await new Promise((resolve,reject)=>compiler.run((error,stats)=>compiler.close(()=>error?reject(error):stats.hasErrors()?reject(Error(stats.toString({all:false,errors:true}))):resolve())));
const bundle=await fs.readFile(path.join(output,'fixture.js'),'utf8'),cssRoot=process.env.RETENTION_CSS_ROOT??'.next/static/chunks';
const css=(await Promise.all((await fs.readdir(cssRoot)).filter(name=>name.endsWith('.css')).map(name=>fs.readFile(path.join(cssRoot,name),'utf8')))).join('\n');
const seed={version:1,revision:1,goals:{version:1,activeId:'retain',goals:[{id:'retain',statement:'Reduce voluntary departures in Technology'},{id:'other',statement:'Other goal'}]},workspaces:{retain:{savedAt:'2026-10-04T00:00:00.000Z',fields:{owner:'Keep owner',workforceSolution:{sentinel:'capacity unchanged'},chat:{messages:[],input:'Keep chat draft'}}},other:{savedAt:'2026-10-04T00:00:00.000Z',fields:{owner:'Other owner'}}}};
let checks=0;const check=(name,ok)=>{assert.ok(ok,name);checks++;console.log('PASS '+name)};
const browser=await chromium.launch({executablePath:'/usr/bin/chromium',headless:true,args:['--no-sandbox']});
try{for(const [mode,width,height] of [['desktop',1366,900],['mobile',390,900],['200-percent',683,450]]){
 const context=await browser.newContext({viewport:{width,height},deviceScaleFactor:mode==='200-percent'?2:1}),page=await context.newPage();const errors=[];let requests=0;page.on('pageerror',error=>errors.push(error.message));
 await page.route('**/*',route=>{if(new URL(route.request().url()).pathname==='/')return route.fulfill({contentType:'text/html',body:`<meta name="viewport" content="width=device-width, initial-scale=1"><style>${css}</style><div id="root"></div><script>${bundle.replaceAll('</script','<\\/script')}</script>`});requests++;return route.abort()});
 await page.addInitScript(({key,seed})=>{if(!localStorage.getItem(key))localStorage.setItem(key,seed)},{key:DECISIONS_STORAGE_KEY,seed:encodeDecisions(seed)});
 const state=()=>page.evaluate(key=>JSON.parse(localStorage.getItem(key)).payload,DECISIONS_STORAGE_KEY),panel=page.getByRole('region',{name:'Retention what-if',exact:true}),button=name=>panel.getByRole('button',{name,exact:true}),fill=(name,value)=>panel.getByLabel(name,{exact:true}).fill(value),saved=async()=> (await state()).workspaces.retain.fields.retentionWhatIfV1;
 await page.goto('http://127.0.0.1:3100/');await button('Start retention what-if').click();
 check(mode+' blank defaults and one group',await panel.locator('input').count()===4&&(await panel.locator('input').evaluateAll(nodes=>nodes.every(n=>n.value===''))));
 await button('Continue').click();await button('Continue').click();await button('Review assumptions').click();await button('Calculate retention what-if').click();
 check(mode+' missing scope blocks calculation',await panel.getByRole('status').filter({hasText:'Describe the aggregate population'}).isVisible()&&await button('Save retention review').count()===0);
 await button('Back').click();await button('Back').click();await button('Back').click();
 await fill('Which aggregate population?','Technology employees');await fill('Planning start month (YYYY-MM)','2026-10');await fill('Planning horizon (1–24 months)','12');await fill('Expected voluntary exits without intervention over this horizon','20');await button('Continue').click();
 check(mode+' no effect defaults',await panel.getByLabel('Lower assumed relative reduction (%)',{exact:true}).inputValue()==='');
 await fill('Whole months before an effect begins','3');await fill('Lower assumed relative reduction (%)','10');await fill('Upper assumed relative reduction (%)','20');await button('Continue').click();await button('Review assumptions').click();await button('Calculate retention what-if').click();
 check(mode+' partial lag does not silently assume timing',await panel.getByText('Choose how baseline exits fall after the lag. Uniform timing is not assumed automatically.',{exact:true}).isVisible()&&await saved()===undefined);
 await button('Back').click();await button('Back').click();await panel.getByLabel('Baseline timing after the lag',{exact:true}).selectOption('uniform');await button('Continue').click();
 for(const [name,value] of [['One-time setup cost (USD)','1000'],['Funded participants','10'],['One-time cost per participant (USD)','100'],['Monthly program cost (USD)','200'],['Funded months within this horizon','12']])await fill(name,value);
 await button('Review assumptions').click();await button('Calculate retention what-if').click();
 check(mode+' calculate is explicit and not persisted',await saved()===undefined&&await panel.getByText('1.5–3 fewer expected voluntary exits',{exact:true}).isVisible());
 check(mode+' conditional costs and timing',await panel.getByText('$4,400 USD',{exact:true}).isVisible()&&(await panel.innerText()).includes('2027-01')&&(await panel.innerText()).includes('not three strategies'));
 check(mode+' result receives focus',await panel.getByRole('heading',{name:'Calculated retention what-if — not yet saved'}).evaluate(node=>node===document.activeElement));
 await panel.getByText('Details: arithmetic and limitations',{exact:true}).click();check(mode+' limitations accessible',await panel.getByText(/Historical annualized turnover/).isVisible());
 await page.screenshot({path:path.join(output,`${mode}-result.png`),fullPage:true});
 await button('Save retention review').click();check(mode+' explicit save persists verified result',(await saved()).revisions[0].result.assumedRange.highReduction.fewerExits===3);
 check(mode+' capacity, chat and other goal isolated',JSON.stringify((await state()).workspaces.retain.fields.workforceSolution)===JSON.stringify(seed.workspaces.retain.fields.workforceSolution)&&(await state()).workspaces.retain.fields.chat.input==='Keep chat draft'&&(await state()).workspaces.other.fields.owner==='Other owner');
 await page.reload();await button('Review retention assumptions').click();check(mode+' reload restores explicitly saved inputs',await panel.getByLabel('Which aggregate population?',{exact:true}).inputValue()==='Technology employees');
 await fill('Which aggregate population?','Unsaved population');await button('Cancel review').click();await button('Review retention assumptions').click();check(mode+' cancel retains draft in current view',await panel.getByLabel('Which aggregate population?',{exact:true}).inputValue()==='Unsaved population');
 await page.reload();await button('Review retention assumptions').click();check(mode+' reload discards unsaved edits only',await panel.getByLabel('Which aggregate population?',{exact:true}).inputValue()==='Technology employees'&&(await saved()).revisions.length===1);
 await button('Continue').click();await button('Continue').click();await button('Review assumptions').click();await button('Calculate retention what-if').click();await button('Back').click();await fill('One-time setup cost (USD)','2000');check(mode+' changed input invalidates calculated save',await button('Save retention review').count()===0);
 await button('Review assumptions').click();await button('Calculate retention what-if').click();await page.getByRole('button',{name:'Rapid goal roundtrip',exact:true}).click();check(mode+' batched goal switch latches stale review',await button('Save retention review').isDisabled()&&(await saved()).revisions.length===1);
 await button('Reopen for current goal').click();await button('Review retention assumptions').click();await page.getByRole('button',{name:'Edit goal statement',exact:true}).click();check(mode+' edited goal closes old review',await button('Save retention review').count()===0&&await button('Review retention assumptions').isVisible());
 await page.getByRole('button',{name:'Other goal',exact:true}).click();await button('Start retention what-if').click();check(mode+' other goal starts blank',await panel.getByLabel('Which aggregate population?',{exact:true}).inputValue()==='');
 await page.getByRole('button',{name:'Retention goal',exact:true}).click();await page.getByRole('button',{name:'Corrupt review',exact:true}).click();check(mode+' corrupt storage blocked without repair',await panel.getByRole('alert').filter({hasText:'Original data is retained'}).isVisible()&&(await saved()).broken===true);
 check(mode+' responsive no horizontal overflow',await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));check(mode+' no network calls or runtime errors',requests===0&&errors.length===0);
 await context.close();
}console.log(`${checks} retention UI browser assertions passed; screenshots ${output}`)}finally{await browser.close()}
