import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import path from 'node:path';
import webpackPackage from 'next/dist/compiled/webpack/webpack.js';
import {selectionFixture,selectionSpec} from '../fixtures/workforce-selection.mjs';
import {searchWorkforceMixes} from '../../lib/workforce-mix-search.ts';
import {stageWorkforceMixSelection} from '../../lib/workforce-mix-selection.ts';
import {recordSolutionApproval,reviseWorkforceSolution,beginSolutionRun,completeSolutionRun} from '../../lib/workforce-solution.ts';
import {previewWorkforceAlternatives} from '../../lib/workforce-planning-agent.ts';
import {calculateWorkforceIncrement} from '../../lib/workforce-increment.ts';
import {encodeDecisions} from '../../lib/local-decisions.ts';
const {chromium}=await import(process.env.PLAYWRIGHT_MODULE??'playwright');
const output=await fs.mkdtemp('/tmp/workforce-handoff-');
const compiler=webpackPackage.webpack({mode:'development',devtool:false,entry:path.resolve('tests/fixtures/workforce-handoff.tsx'),output:{path:output,filename:'fixture.js',publicPath:'/assets/'},resolve:{extensions:['.tsx','.ts','.mjs','.js'],alias:{'@':process.cwd()}},module:{rules:[{test:/\.tsx?$/,exclude:/node_modules/,use:path.resolve('tests/fixtures/typescript-browser-loader.mjs')}]}});
await new Promise((resolve,reject)=>compiler.run((error,stats)=>compiler.close(()=>error?reject(error):stats.hasErrors()?reject(Error(stats.toString({all:false,errors:true}))):resolve())));
const bundle=await fs.readFile(path.join(output,'fixture.js'),'utf8');
const cssFiles=(await fs.readdir('.next/static/chunks')).filter(name=>name.endsWith('.css'));
assert.ok(cssFiles.length,'Use actual built app CSS for responsive checks');
const css=(await Promise.all(cssFiles.map(name=>fs.readFile(path.join('.next/static/chunks',name),'utf8')))).join('\n');
let {solution,payload}=selectionFixture();const at='2026-10-03T01:00:00.000Z';
solution=recordSolutionApproval(solution,1,'keep-approval',['source-result'],'Keep prior approval',at);
const search=searchWorkforceMixes(solution,'source-result',selectionSpec());
const oldReview=previewWorkforceAlternatives(solution,'source-result',[{...payload.input,trainingCash:'1000'}],'keep-review',at);
let nextSolution=reviseWorkforceSolution(solution,1,{scope:{...solution.versions[0].inputs.scope,budget:'26000'}},'sidebar','Change budget',at);
const nextPayload=structuredClone(payload);nextPayload.input.budget='26000';nextPayload.proposed=calculateWorkforceIncrement(nextPayload.input,nextPayload.timing);nextPayload.hireOnly=calculateWorkforceIncrement({...nextPayload.input,build:'0',move:'0',buy:'3',backfills:'0',internalAnnualCostChange:'0',trainingCash:'0',trainingHours:'0'},nextPayload.timing);
const run=beginSolutionRun(nextSolution,2,'next-run',['brief'],at);nextSolution=completeSolutionRun(run.state,run.ticket,[{id:'next-result',kind:'brief',calculator:{name:'single-role-workforce-review',version:'1'},payload:nextPayload}],at);
const seed={version:1,revision:1,goals:{version:1,activeId:'goal-search',goals:[{id:'goal-search',statement:'Synthetic bounded workforce comparison'},{id:'goal-b',statement:'Other goal'}]},workspaces:{'goal-search':{savedAt:at,fields:{workforceSolution:solution,workforceAlternativeReviews:[oldReview],owner:'Keep owner'}}}};
const browser=await chromium.launch({executablePath:'/usr/bin/chromium',headless:true,args:['--no-sandbox']});let checks=0;
const check=(name,value)=>{assert.ok(value,name);checks++;console.log('PASS '+name)};
try {for(const width of [1366,390]){
 const context=await browser.newContext({viewport:{width,height:900}}),page=await context.newPage(),errors=[],pending=[];let delay=false,calls=0,unmocked=0;
 page.on('pageerror',error=>errors.push(error.message));
 await page.route('**/*',async route=>{
  const url=new URL(route.request().url());
  if(url.pathname.startsWith('/assets/'))return route.fulfill({contentType:'application/javascript',body:await fs.readFile(path.join(output,path.basename(url.pathname)))});
  if(url.pathname==='/__fixture-only-selection-verification'){
   calls++;const {context,snapshot,ids}=route.request().postDataJSON();
   const reply=async()=>{try{await route.fulfill({json:stageWorkforceMixSelection(context,snapshot,ids)})}catch{await route.fulfill({status:400,json:{error:'Rejected'}})}};
   if(delay)pending.push(reply);else await reply();return;
  }
  if(url.origin==='http://127.0.0.1:3100'&&url.pathname==='/')return route.fulfill({contentType:'text/html',body:'<div id="root"></div>'});
  unmocked++;await route.abort();
 });
 const init=async()=>{await page.evaluate(seed=>{window.handoffSeed=seed},{encoded:encodeDecisions(seed),search,nextSolution});await page.addStyleTag({content:css});await page.addScriptTag({content:bundle})};
 const button=name=>page.getByRole('button',{name,exact:true});
 const open=async()=>{const summary=page.locator('summary').filter({hasText:'Review local alternatives'});if(await summary.count()&&!await summary.evaluate(el=>el.parentElement.open))await summary.click()};
 const load=async()=>{await button('Load selected search results').click();await open()};
 const state=()=>page.evaluate(()=>window.handoffFixture.saved());
 const drafts=()=>page.getByLabel('Alternative 1: Training cash (USD)',{exact:true});
 const staged=()=>button('Replace alternative drafts').waitFor();
 const review=async()=>{await button('Review selected mixes').click();await staged()};
 const waitPending=async count=>{for(let attempt=0;attempt<100&&pending.length!==count;attempt++)await page.waitForTimeout(20);assert.equal(pending.length,count)};
 const flush=async()=>{await pending.shift()();await page.waitForTimeout(80)};
 await page.goto('http://127.0.0.1:3100');await init();await open();
 check(width+' production default has no search entry',await page.getByRole('region',{name:'Selected scenario handoff',exact:true}).count()===0);
 await drafts().fill('1234');await load();check(width+' incoming selection preserves existing draft edits',await drafts().inputValue()==='1234');const original=JSON.stringify((await state()).workspaces['goal-search'].fields);
 await review();await page.screenshot({path:path.join(output,`staged-${width}.png`),fullPage:true});check(width+' review stages without replacing edits or saving',await drafts().inputValue()==='1234'&&JSON.stringify((await state()).workspaces['goal-search'].fields)===original);
 check(width+' clear conditional capacity and fixed-total explanation',(await page.getByRole('region',{name:'Selected scenario handoff',exact:true}).innerText()).includes('Candidate pools are not assignable employees')&&(await page.locator('main').innerText()).includes('Path totals are not scaled per person'));
 await button('Cancel selected mixes').click();check(width+' cancel preserves existing edited draft',await drafts().inputValue()==='1234');
 await review();await button('Replace alternative drafts').click();await page.waitForFunction(()=>document.querySelector('[aria-label="Alternative 1: Build count"]').value==='0');
 check(width+' explicit handoff populates exactly two temporary drafts',await page.getByLabel('Alternative 2: Move count',{exact:true}).inputValue()==='2'&&await drafts().inputValue()==='3000'&&await button('Save reviewed alternatives').count()===0);
 check(width+' handoff leaves all saved fields unchanged',JSON.stringify((await state()).workspaces['goal-search'].fields)===original);
 await button('Publish unrelated state').click();check(width+' unrelated shared state preserves staged drafts',await page.getByLabel('Alternative 1: Build count',{exact:true}).inputValue()==='0');
 await button('Calculate alternatives locally').click();await button('Save reviewed alternatives').waitFor();
 check(width+' calculate remains separate from save',(await state()).workspaces['goal-search'].fields.workforceAlternativeReviews.length===1);
 await drafts().fill('100');check(width+' edit invalidates calculated preview',await button('Save reviewed alternatives').count()===0);
 await button('Calculate alternatives locally').click();await button('Save reviewed alternatives').click();await page.waitForFunction(()=>window.handoffFixture.saved().workspaces['goal-search'].fields.workforceAlternativeReviews.length===2);
 let fields=(await state()).workspaces['goal-search'].fields;
 check(width+' explicit save retains old review and adds edited calculation',fields.workforceAlternativeReviews.length===2&&JSON.stringify(fields.workforceAlternativeReviews[0])===JSON.stringify(oldReview)&&fields.workforceAlternativeReviews[1].reviewedRevisions[0].trainingCash==='100');
 check(width+' saved plan and old versioned approval unchanged',JSON.stringify(fields.workforceSolution)===JSON.stringify(solution)&&fields.owner==='Keep owner');
 await button('Switch destination').click();await open();check(width+' shared destinations display same saved history',(await page.locator('main').innerText()).includes('Saved local alternative reviews (2)'));
 await load();await drafts().fill('999');await button('Cancel alternative edits').click();check(width+' cancel draft edits leaves saved history intact',await drafts().inputValue()==='3000'&&(await state()).workspaces['goal-search'].fields.workforceAlternativeReviews.length===2);
 await button('Try three selections').click();await open();await button('Review selected mixes').click();await page.getByText('Selections are stale, invalid or incomplete.',{exact:false}).waitFor();check(width+' three selections rejected',await page.getByLabel('Alternative 3: Build count',{exact:true}).count()===0&&await button('Replace alternative drafts').count()===0);
 await load();delay=true;await button('Review selected mixes').click();await waitPending(1);await button('Cancel selected mixes').click();await flush();check(width+' cancelled late mocked fetch cannot stage',await button('Replace alternative drafts').count()===0);
 await button('Review selected mixes').click();await waitPending(1);await button('Goal B').click();await button('Goal A').click();await open();await flush();check(width+' goal switch discards late mocked fetch',await button('Replace alternative drafts').count()===0);
 delay=false;await review();delay=true;await button('Replace alternative drafts').click();await waitPending(1);await button('Cancel selected mixes').click();await button('Review selected mixes').click();await waitPending(2);
 await pending.pop()();await staged();await flush();check(width+' late replaced request cannot apply newer stage',await page.getByLabel('Alternative 1: Build count',{exact:true}).inputValue()==='1'&&await button('Replace alternative drafts').count()===1);
 await button('Cancel selected mixes').click();await button('Review selected mixes').click();await waitPending(1);await button('Publish newer saved result').click();await open();await flush();check(width+' newer evidence discards late stage',await button('Replace alternative drafts').count()===0);
 delay=false;await button('Review selected mixes').click();await page.getByText('Selections are stale, invalid or incomplete.',{exact:false}).waitFor();check(width+' stale selected report rejected after saved version change',await button('Replace alternative drafts').count()===0);
 fields=(await state()).workspaces['goal-search'].fields;check(width+' old approvals remain bound to original version',fields.workforceSolution.versions.length===2&&fields.workforceSolution.approvals[0].version===1&&fields.workforceAlternativeReviews.length===2);
 await page.reload();await init();await open();check(width+' reload retains reviews but no staged selection',await page.getByRole('region',{name:'Selected scenario handoff',exact:true}).count()===0&&(await page.locator('main').innerText()).includes('Saved local alternative reviews (2)'));
 check(width+' responsive panel has no horizontal overflow',await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth));
 await page.screenshot({path:path.join(output,`handoff-${width}.png`),fullPage:true});
 check(width+' no browser errors or unmocked services',errors.length===0&&unmocked===0);check(width+' exercised real local verifier',calls>=10);
 await context.close();
 }console.log(`${checks} handoff browser checks passed; screenshots: ${output}`);
}finally{await browser.close()}
