import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import path from 'node:path';
import os from 'node:os';
import webpackPackage from 'next/dist/compiled/webpack/webpack.js';
import {workforceReviewFixture} from '../fixtures/workforce-review.mjs';
import {createWorkforceSolution,emptySolutionInputs,beginSolutionRun,completeSolutionRun,recordSolutionApproval,reviseWorkforceSolution} from '../../lib/workforce-solution.ts';
import {encodeDecisions,DECISIONS_STORAGE_KEY} from '../../lib/local-decisions.ts';
const {chromium,devices}=await import(process.env.PLAYWRIGHT_MODULE??'playwright');
const output=await fs.mkdtemp(path.join(os.tmpdir(),'workforce-journey-'));
const compiler=webpackPackage.webpack({mode:'development',devtool:false,entry:path.resolve('tests/fixtures/workforce-input-readiness.tsx'),output:{path:output,filename:'fixture.js',publicPath:'/assets/'},resolve:{extensions:['.tsx','.ts','.mjs','.js'],alias:{'@':process.cwd()}},module:{rules:[{test:/\.tsx?$/,exclude:/node_modules/,use:path.resolve('tests/fixtures/typescript-browser-loader.mjs')}]}});
await new Promise((resolve,reject)=>compiler.run((error,stats)=>compiler.close(()=>error?reject(error):stats.hasErrors()?reject(Error(stats.toString({all:false,errors:true}))):resolve())));
const bundle=await fs.readFile(path.join(output,'fixture.js'),'utf8');
const css=(await Promise.all((await fs.readdir('.next/static/chunks')).filter(name=>name.endsWith('.css')).map(name=>fs.readFile(path.join('.next/static/chunks',name),'utf8')))).join('\n');
assert.ok(css.length);
const goalId='goal-readiness',goalStatement='Synthetic three-role workforce goal',at='2026-10-03T01:00:00.000Z',payload=workforceReviewFixture(),inputs=emptySolutionInputs();
const sections={scope:['businessUnit','jobProfile','intent','planningMonth','months'],demand:['roles'],response:['build','move','buy','backfills'],timing:['recruitingStart','arrivalMode','arrivalDate','buildMonth','moveMonth','backfillDate'],costs:['annualHireCost','hireFee','annualBackfillCost','backfillFee','internalAnnualCostChange'],training:['trainingCash','trainingHours','loadedHourlyCost'],constraints:['budget','maxAddedEmployees','deadlineMonth']};
for(const [section,fields] of Object.entries(sections))for(const field of fields)inputs[section][field]=payload.input[field];inputs.scope.goalStatement=goalStatement;
const empty=createWorkforceSolution('empty-solution',goalId,{...emptySolutionInputs(),scope:{goalStatement}},at);
let complete=createWorkforceSolution('complete-solution',goalId,inputs,at);const run=beginSolutionRun(complete,1,'ready-run',['brief'],at);complete=completeSolutionRun(run.state,run.ticket,[{id:'ready-result',kind:'brief',calculator:{name:'single-role-workforce-review',version:'1'},payload}],at);complete=recordSolutionApproval(complete,1,'keep-approval',['ready-result'],'Synthetic approval retained',at);
const newer=reviseWorkforceSolution(complete,1,{constraints:{...inputs.constraints,budget:'26000'}},'sidebar','Synthetic new budget',at);
const data={version:1,revision:1,goals:{version:1,activeId:goalId,goals:[{id:goalId,statement:goalStatement},{id:'goal-other',statement:'Other synthetic goal'}]},workspaces:{[goalId]:{savedAt:at,fields:{workforceSolution:empty,owner:'Keep owner',workforceCatalog:{as_of:'2026-09-30',business_units:[{org_code:'TECH',org_name:'Technology'}],job_profiles:[{job_profile_code:'ENGINEER',job_profile_name:'Engineer'}]}}}}};
data.workspaces[goalId].fields.workforceSolution=complete;
const browser=await chromium.launch({executablePath:process.env.CHROMIUM_PATH??'/usr/bin/chromium',headless:true,args:['--no-sandbox']});let checks=0;
const check=(name,value)=>{assert.ok(value,name);checks++;console.log('PASS '+name)};
try{for(const width of [1366,390]){
 const context=await browser.newContext({...width===390?devices['Pixel 7']:{},viewport:{width,height:844}}),page=await context.newPage(),errors=[];let unexpected=0,model=0,calculations=0,release,questionsOnly=false;
 page.on('pageerror',error=>errors.push(error.message));
 const assets=new Map(await Promise.all((await fs.readdir(output)).filter(name=>name.endsWith('.js')).map(async name=>['http://127.0.0.1:3100/assets/'+name,await fs.readFile(path.join(output,name),'utf8')])));
 await page.route('**/*',async route=>{
  const url=route.request().url();
  if(url==='http://127.0.0.1:3100/')return route.fulfill({contentType:'text/html',body:'<meta name="viewport" content="width=device-width, initial-scale=1"><div id="root"></div>'});
  if(assets.has(url))return route.fulfill({contentType:'text/javascript',body:assets.get(url)});
  if(url==='http://127.0.0.1:3100/api/workforce-solution/intake'){model++;return route.fulfill({json:{summary:'Synthetic assumptions to review',questions:[],changes:questionsOnly?[]:[{field:'roles',value:'3',evidence:'three'}],draft:payload.input}})}
  if(url==='http://127.0.0.1:3100/api/workforce-solution'){calculations++;if(release===true)await new Promise(resolve=>release=resolve);return route.fulfill({json:payload}).catch(()=>{})}
  unexpected++;return route.abort();
 });
 const init=async(mode='complete')=>{
  await page.goto('http://127.0.0.1:3100/');await page.evaluate(key=>localStorage.removeItem(key),DECISIONS_STORAGE_KEY);
  const seed=structuredClone(data);if(mode==='fresh')delete seed.workspaces[goalId].fields.workforceSolution;
  if(mode==='empty')seed.workspaces[goalId].fields.workforceSolution=empty;
  await page.evaluate(({seed,unsupported})=>{window.readinessSeed=seed;if(unsupported)window.Worker=class{constructor(){throw Error('Unsupported worker')}};else{const NativeWorker=window.Worker;window.Worker=class extends NativeWorker{set onmessage(handler){super.onmessage=event=>setTimeout(()=>handler?.(event),window.workerDelay??0)}}}}, {seed:{encoded:encodeDecisions(seed),empty,complete,newer},unsupported:mode==='unsupported'});
  await page.addStyleTag({content:css});await page.addScriptTag({content:bundle});if(mode==='complete')await comparisonReady();else if(mode==='empty')await button('Use details from my statement').waitFor();else await button('Continue this decision').waitFor();
 };
 const button=name=>page.getByRole('button',{name,exact:true}),state=()=>page.evaluate(()=>window.readinessSaved()),solution=async()=>(await state()).workspaces[goalId].fields.workforceSolution;
 const next=()=>button('Continue this decision'),field=name=>page.getByLabel(name,{exact:true});
 const comparisonReady=async()=>{await button('Adjust saved response mix').waitFor();await next().waitFor({state:'hidden'})};
 const disclose=async text=>{const summary=page.getByText(text,{exact:true});if(!await summary.evaluate(el=>el.parentElement.open))await summary.click()};
 const focus=async locator=>locator.evaluate(el=>el===document.activeElement);
 const continueByKeyboard=async()=>{await next().focus();await page.keyboard.press('Enter')};
 const openAssumptions=async()=>{const summary=page.getByText('Review assumptions and goal statement',{exact:true});if(!await summary.evaluate(el=>el.parentElement.open))await summary.click()};
 await init('fresh');const untouched=JSON.stringify(await state());await continueByKeyboard();
 check(width+' fresh Continue focuses existing start without writing',await focus(button('Start guided workforce plan'))&&JSON.stringify(await state())===untouched);
 await button('Start guided workforce plan').click();await button('Enter inputs manually').click();await continueByKeyboard();
 check(width+' missing input gets exact keyboard focus',await focus(field('Business unit')));
 await page.keyboard.press('Tab');check(width+' no keyboard focus trap',await focus(field('Job profile')));
 await field('Planning statement').fill('Synthetic three roles');await button(/^(Clarify statement with AI|Use details from my statement)$/).click();await button('Review proposed changes').waitFor();
 await continueByKeyboard();check(width+' proposal is reviewed explicitly',await focus(button('Review proposed changes'))&&(await solution()).versions.length===1&&calculations===0);
 await button('Review proposed changes').click();await continueByKeyboard();
 check(width+' reviewed draft points to Save without saving',await focus(button('Save reviewed inputs'))&&(await solution()).versions.length===1);
 await button('Save reviewed inputs').click();await continueByKeyboard();check(width+' saved inputs point to explicit Calculate',await focus(button(/^Calculate (options|saved assumptions and compare hiring-only)$/))&&calculations===0);
 release=true;await button(/^Calculate (options|saved assumptions and compare hiring-only)$/).click();await button('Cancel pending request').waitFor();await continueByKeyboard();
 check(width+' active request Continue focuses cancellation',await focus(button('Cancel pending request')));
 await button('Cancel pending request').click();if(typeof release==='function')release();release=undefined;
 await page.waitForFunction(()=>window.readinessSaved().workspaces['goal-readiness'].fields.workforceSolution.pending===null);
 check(width+' cancelled late response saves no result',(await solution()).results.length===0);
 await button(/^Calculate (options|saved assumptions and compare hiring-only)$/).click();await page.getByRole('article',{name:'Saved response mix',exact:true}).waitFor();await comparisonReady();
 check(width+' calculation progressively collapses assumptions',!await page.getByText('Review assumptions and goal statement',{exact:true}).evaluate(el=>el.parentElement.open));
 const calculated=JSON.stringify(await solution());await disclose('Comparison preference');await field('Your comparison priority').focus();check(width+' comparison is directly accessible and read-only',await next().count()===0&&await focus(field('Your comparison priority'))&&await field('Your comparison priority').inputValue()===''&&JSON.stringify(await solution())===calculated);
 await button('Adjust saved response mix').click();await field('Shared cash budget (USD)').fill('bad');await continueByKeyboard();
 check(width+' tailoring correction focuses its own field',await focus(field('Shared cash budget (USD)')));
 await field('Shared cash budget (USD)').fill('30000');await page.getByRole('status').filter({hasText:'Temporary local comparison ready'}).waitFor();await continueByKeyboard();
 check(width+' reviewed tailoring points to explicit Save',await focus(button('Save changes to this goal'))&&JSON.stringify(await solution())===calculated);
 await button('Save changes to this goal').click();await page.waitForFunction(()=>window.readinessSaved().workspaces['goal-readiness'].fields.workforceSolution.versions.length===3);
 await comparisonReady();check(width+' saved revision retains original result',(await solution()).results.length===2&&(await solution()).versions[1].inputs.constraints.budget==='25000');
 await button('Bookmark option').click();await button('Option bookmarked').waitFor();check(width+' saved solution pin is explicit',(await state()).workspaces[goalId].fields.workforceSolutionPins.length===1);
 await page.screenshot({path:path.join(output,`journey-${width}.png`),fullPage:true});
 check(width+' mobile/desktop content fits viewport',await page.evaluate(width=>window.innerWidth===width&&document.documentElement.scrollWidth<=width,width));
 await init();await comparisonReady();await openAssumptions();await page.getByText('Review and customize inputs',{exact:true}).click();await field('Incremental cash budget over this horizon (USD)').fill('28000');
 await page.getByText('Review assumptions and goal statement',{exact:true}).click();await continueByKeyboard();
 check(width+' disclosure and Continue retain draft and focus Save',await field('Incremental cash budget over this horizon (USD)').inputValue()==='28000'&&await focus(button('Save reviewed inputs'))&&(await solution()).versions.length===1);
 await button('Publish unrelated state').click();await continueByKeyboard();check(width+' unrelated records do not discard draft',await field('Incremental cash budget over this horizon (USD)').inputValue()==='28000');
 await button('Change goal wording').click();await continueByKeyboard();check(width+' goal wording change guides review without overwriting draft',await field('Incremental cash budget over this horizon (USD)').inputValue()==='28000'&&(await solution()).versions.length===1);
 await init();await button('Publish newer input version').click();await continueByKeyboard();check(width+' historical Continue opens current input review',await page.getByText('Review and customize inputs',{exact:true}).evaluate(el=>el.parentElement===document.activeElement)&& (await solution()).results[0].version===1);
 await init();await comparisonReady();await disclose('Explore more options');await page.getByText('Review local alternatives',{exact:true}).click();await field('Alternative 1: Training cash (USD)').fill('100');await continueByKeyboard();check(width+' staged alternatives remain a separate explicit review',await page.getByRole('region',{name:'Local workforce alternatives',exact:true}).evaluate(el=>el===document.activeElement)&&!(await state()).workspaces[goalId].fields.workforceAlternativeReviews);
 await button('Cancel alternative edits').click();await comparisonReady();check(width+' alternative cancellation resumes saved comparison',(await solution()).approvals[0].id==='keep-approval');
 await page.evaluate(()=>window.workerDelay=300);await button('Adjust saved response mix').click();await field('Shared cash budget (USD)').fill('35000');await button('Goal B').click();await button('Goal A').click();await page.waitForTimeout(400);check(width+' goal interruption rejects late temporary work',(await solution()).versions.length===1&&await button('Save changes to this goal').count()===0);
 await init();const beforeMissing=JSON.stringify(await solution());await page.evaluate(()=>window.fixtureSetField('workforceInspection','missing-result'));await continueByKeyboard();check(width+' missing selection stays explicit and offers retained history',await focus(field('Inspect a saved calculation'))&&await page.getByRole('region',{name:'Workforce solution calculation',exact:true}).count()===0);await field('Inspect a saved calculation').selectOption('ready-result');await comparisonReady();check(width+' explicit history selection recovers without rewriting results',JSON.stringify(await solution())===beforeMissing);
 await init();await comparisonReady();await button('Adjust saved response mix').click();await page.getByRole('status').filter({hasText:'Temporary local comparison ready'}).waitFor();await continueByKeyboard();check(width+' unchanged what-if never directs to disabled Save',await page.getByRole('region',{name:'Tailor selected option',exact:true}).evaluate(el=>el===document.activeElement)&&await button('Save changes to this goal').isDisabled());await button('Cancel what-if').click();
 await init();await comparisonReady();await button('Adjust saved response mix').click();await field('Build count').fill('2');await continueByKeyboard();check(width+' mix-total correction focuses an editable what-if count instead of fixed role demand',await focus(field('Build count'))&&(await solution()).versions.length===1);await button('Cancel what-if').click();
 await init();await disclose('Calculate or update options');release=true;await button(/^Calculate (options|saved assumptions and compare hiring-only)$/).click();await button('Cancel pending request').waitFor();await page.waitForFunction(()=>window.readinessSaved().workspaces['goal-readiness'].fields.workforceSolution.pending!==null);await button('Batched goal roundtrip').click();if(typeof release==='function')release();release=undefined;await page.waitForTimeout(250);check(width+` batched goal roundtrip cancels pending calculation without adding a result (actual results: ${(await solution()).results.length}, pending: ${!!(await solution()).pending})`,(await solution()).pending===null&&(await solution()).results.length===1);
 await init('empty');questionsOnly=true;await field('Planning statement').fill('Synthetic question only');await button(/^(Clarify statement with AI|Use details from my statement)$/).click();await button('Review proposed changes').waitFor();await continueByKeyboard();check(width+' questions-only proposal guides an editable input',await focus(field('Business unit'))&&await button('Review proposed changes').isDisabled());
 await init('unsupported');await page.getByRole('status').filter({hasText:/unavailable|supported|worker/i}).first().waitFor();await continueByKeyboard();check(width+' unsupported worker path remains reviewable without saving',await page.getByRole('region',{name:'Workforce solution options',exact:true}).evaluate(el=>el===document.activeElement)&&(await solution()).versions.length===1);
 check(width+' no unmocked network or runtime errors',unexpected===0&&errors.length===0);check(width+' only explicit model and calculation calls',model===2&&calculations===3);
 await context.close();
}console.log(`${checks} journey browser checks passed; Chromium desktop + Pixel emulation; ${output}`)}finally{await browser.close()}
