import test from 'node:test';
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { resolveForecastConsumerView as resolve } from '../lib/forecast-consumer-view.ts';
import { forecastConsumerViewArtifact } from './manual/generate-forecast-consumer-view.mjs';
const read = async p => JSON.parse(await readFile(new URL(p, import.meta.url), 'utf8'));
const artifact = await read('../lib/data/forecast-consumer-view-v1.json'), preview = await read('../lib/data/aggregate-exit-demo-v1.json');
test('view artifact is generated by actual source metadata path', async () => {
  assert.deepEqual(artifact, await forecastConsumerViewArtifact()); const view = resolve(artifact, artifact, preview);
  assert.equal(view.status, 'ready'); assert.equal(view.domains.length, 3); assert(view.domains.every(d => d.missingInputs.length >= 3));
  assert.equal(artifact.status, 'unqualified'); assert.equal(artifact.operationalForecast, null);
});
test('stale counts, promoted status and altered missing inputs are withheld', () => {
  for (const change of [a => { a.conditionalDemo.preview.conditional.remainingTotal = 999; }, a => { a.status = 'qualified'; }, a => { a.domains.turnover.missingInputs = []; }, a => { a.identity = 'old'; }]) {
    const a = structuredClone(artifact); change(a); assert.equal(resolve(a, artifact, preview).status, 'stale');
  }
  const p = structuredClone(preview); p.methodVersion = 'new'; assert.equal(resolve(artifact, artifact, p).status, 'stale');
});
test('missing or malformed artifact fails closed without a numeric fallback', () => {
  for (const a of [null, undefined, 0, {}, { status: 'qualified' }]) assert.notEqual(resolve(a, a, preview).status, 'ready');
});
test('confirmed zero is preserved when matching a separately reviewed preview', () => {
  const a = structuredClone(artifact), p = structuredClone(preview); p.conditional.remainingTotal = 0;
  p.conditional.points.forEach(point => { point.expectedExits = 0; }); p.conditional.yearEndTotal = p.recordedSubtotal.value;
  a.conditionalDemo.preview = p; assert.equal(resolve(a, a, p).status, 'ready'); assert.equal(a.conditionalDemo.preview.conditional.remainingTotal, 0);
});
test('browser path imports only projections, not evaluator, raw fixture or source client', async () => {
  const source = await readFile(new URL('../components/synthetic-exit-count-example.tsx', import.meta.url), 'utf8');
  const helper = await readFile(new URL('../lib/forecast-consumer-view.ts', import.meta.url), 'utf8');
  assert.doesNotMatch(source + helper, /fetch\(|supabase|node:|lib\/ml|tests\/fixtures|exitForecastForConsumer/);
  assert.doesNotMatch(JSON.stringify(artifact), /employee_id|manager_employee_id|base_salary|monthEndHeadcount|"months":\[/);
});
