import test from 'node:test';
import assert from 'node:assert/strict';
import {homeForecastAnswer,homeForecastChartDomain} from '../lib/home-forecast.ts';
import {homeForecastIntent} from '../lib/home-forecast-intent.ts';
import artifact from '../lib/data/synthetic-domain-demo-v1.json' with {type:'json'};
import {demoMethodLabels} from '../lib/synthetic-domain-demo.ts';
test('only the OLS methods display as Linear Regression in forecasts and comparisons',()=>{
 assert.equal(demoMethodLabels['linear-trend-12'],'Linear Regression');assert.equal(demoMethodLabels['linear-trend-8'],'Linear Regression');
 assert.equal(demoMethodLabels['logistic-trend'],'Logistic trend');
 const comparison=homeForecastAnswer('Compare prediction methods');assert.equal((comparison.match(/\*\*Linear Regression\*\*/g)||[]).length,2);assert.match(comparison,/Damped change/);assert.doesNotMatch(comparison,/Linear trend/);
 for(const question of ['Forecast turnover','Forecast employee listening'])assert.match(homeForecastAnswer(question),/\| Linear Regression \|/);
 assert.doesNotMatch(homeForecastAnswer('Forecast hiring'),/Linear Regression/);
});
for(const [question,metric] of [['Forecast turnover','monthly voluntary-exit counts'],['Forecast employee listening','quarterly mean respondent favorable-answer share']])test(question,()=>{const answer=homeForecastAnswer(question);assert.match(answer,new RegExp(metric));assert.match(answer,/SIMULATED DEMO/);assert.match(answer,/30 Sep 2026/);assert.match(answer,/Confidence intervals.*unavailable/);assert.match(answer,/past synthetic MAE order/);});
test('generic method comparison covers implemented domains without a clarification',()=>{assert.match(homeForecastAnswer('Compare prediction methods'),/Implemented prediction methods/);const a=homeForecastAnswer('Compare forecasts across all three domains');for(const unit of ['monthly voluntary-exit counts','active requisitions at month-end','quarterly mean respondent favorable-answer share'])assert.ok(a.includes(unit));assert.match(a,/cannot be ranked or combined/);});
test('unrelated questions and goal appendices do not activate forecasting',()=>{for(const q of ['Reduce turnover','What skills do we need?','Should we hire, train, or both?','Do not forecast turnover','What happened?\n\nFocused issue: Forecast turnover'])assert.equal(homeForecastIntent(q),null,q);});
for(const [question,reason] of [['Forecast year-end turnover rate','future workforce denominators'],['Forecast how many hires next month','does not forecast hire counts'],['Forecast satisfaction as percentage of employees','not eNPS'],['Forecast turnover in 2027','October–December 2026 only'],['Predict turnover if we train managers','intervention-effect forecast is unavailable'],['Forecast turnover without simulated data','excludes simulated data']])test('unsupported: '+question,()=>{const a=homeForecastAnswer(question);assert.ok(a.includes(reason),a);assert.ok(!a.includes('| Method |'));});
test('corrupt legacy artifact fails closed; hiring uses calibrated count units',()=>{assert.match(homeForecastAnswer('Forecast turnover',{...artifact,seed:1}),/evidence is missing or differs/);const a=homeForecastAnswer('Forecast hiring');assert.match(a,/active requisitions at month-end/);assert.match(a,/synthetic-ta-calibrated-v2/);assert.match(a,/474/);assert.match(a,/475/);assert.doesNotMatch(a,/opening-cohort start percentage/);});

test('overview uses domain-correct meanings and verified evaluation scope without invented errors or winner',()=>{const answer=homeForecastAnswer('Compare prediction methods');assert.match(answer,/three most recent released quarterly waves/);assert.match(answer,/80 of 100 held-out synthetic cases/);assert.match(answer,/Historical MAE ordering is limited/);assert.doesNotMatch(answer,/undefined|random forest|gradient boost|best method/i);});
test('comparison respects exclusions and horizon; charts require exact verified supported turnover text',()=>{assert.match(homeForecastAnswer('Compare prediction methods without simulated data'),/unavailable/);assert.match(homeForecastAnswer('Compare forecasts across all three domains in 2027'),/other horizons are unavailable/);assert.equal(homeForecastChartDomain('Forecast turnover',homeForecastAnswer('Forecast turnover')),'turnover');assert.equal(homeForecastChartDomain('Forecast hiring',homeForecastAnswer('Forecast hiring')),'hiring');for(const q of ['Forecast turnover rate','Compare prediction methods'])assert.equal(homeForecastChartDomain(q,homeForecastAnswer(q)),null);assert.equal(homeForecastChartDomain('Forecast turnover','model-created forecast'),null);});
