import test from 'node:test';import assert from 'node:assert/strict';
import {normalizeHomePack} from '../lib/home-pack.mjs';
import {homeAnswerScopeViolation} from '../lib/home-answer-scope.ts';
import {inspectHomeChatResponse} from '../lib/home-chat-response.ts';
const packet=normalizeHomePack({workforceScope:'United States; All business units; All levels',sources:[{id:'W1',status:'loaded',facts:{headcount:5000}},{id:'A1',scope:'United States',status:'loaded',facts:{total_exits:100}},{id:'P1',scope:'United States',status:'loaded',facts:{headcount:15000}}]});
test('mixed US and global evidence retains canonical scopes and missing values',()=>{assert.equal(packet.sources[0].facts.headcount,5000);assert.match(packet.sources.find(s=>s.id==='A1').scope,/Company-wide/);assert.match(packet.sources.find(s=>s.id==='P1').scope,/Company/);assert.equal(packet.sources.find(s=>s.id==='R1').facts,null);});
test('clear company-source claims relabeled to the selected country are rejected',()=>{for(const text of ['The United States scenario has 15,000 employees. [P1]','U.S.-scoped turnover was 8%. [A1]','US exits were 100 [A1:summary].'])assert.equal(homeAnswerScopeViolation(text,packet),true,text);});
test('matching workforce counts, separate company figures and explicit unavailable scope remain valid',()=>{for(const text of ['United States headcount is 5,000. [W1]','United States headcount is 5,000 [W1]; company-wide exits were 100 [A1].','The United States breakdown is unavailable; company-wide exits were 100 [A1].','The company-wide scenario is not a United States forecast. [P1]','The supplied company monthly series cannot establish why people left or the selected United States monthly rate. [A1]'])assert.equal(homeAnswerScopeViolation(text,packet),false,text);});
test('runtime inspection withholds the misleading completed model answer and keeps a specific diagnostic',()=>{const response={status:'completed',output_text:JSON.stringify({answer:'The United States scenario has 15,000 employees. [P1]',next_step:'none',problem:null,problem_evidence:[],options:[],question:null})};const result=inspectHomeChatResponse(response,false,packet,4000);assert.equal(result.ok,false);assert.equal(result.body.homeReplyDiagnostic.reason,'source_scope_mismatch');assert.equal('answer' in result.body,false);assert.match(result.body.error,/question is kept/);});
