import test from 'node:test';import assert from 'node:assert/strict';
import {assumptionsOnlyBundle,validAssumptionsOnlyBundle,unavailableSourceLabels} from '../lib/home-assumptions-fallback.ts';
import {actionBinding} from '../lib/home-action-drafts.ts';
import {createBundleDraft,readBundleDraft,reconcileBundle} from '../lib/home-bundle-reconciliation.ts';
import {prepareIllustrativePilot} from '../lib/home-action-plan-pilot.ts';
import {inspectHomeBundleProposal} from '../lib/home-solution-bundles.ts';
import {saveBundleCalculationPatch,attachBundlePatch,readBundleWorkspace} from '../lib/home-bundle-records.ts';
import {actionBindingKey} from '../lib/home-action-drafts.ts';import {bundleInputKey} from '../lib/home-bundle-reconciliation.ts';
for(const goal of ['Reduce turnover by 20% relative within 12 months','Add 3 additional roles within 6 months'])test('local assumptions-only lifecycle: '+goal,async()=>{const bundle=assumptionsOnlyBundle(goal);assert.ok(validAssumptionsOnlyBundle(bundle,goal));assert.deepEqual(bundle.components[0].evidence,[]);const binding=await actionBinding('fallback',goal,{sources:[]},{}),draft=prepareIllustrativePilot(createBundleDraft(bundle,binding),'2026-10-05T00:00:00Z'),result=reconcileBundle(draft);assert.ok(readBundleDraft(draft));assert.equal(draft.inputs.whatIf.baseline.kind,'illustrative');assert.match(draft.bundle.limitation,/not evidence-based/);assert.equal(inspectHomeBundleProposal({version:1,goal,bundles:[bundle],question:null,unavailableReason:null},goal,{sources:[]}).proposal,null);let store=saveBundleCalculationPatch(undefined,draft,result).value;store=attachBundlePatch(store,draft,{confirmed:true,bindingKey:actionBindingKey(binding),inputKey:bundleInputKey(draft),acknowledgeUnknowns:true},'snapshot','2026-10-05T00:00:00Z').value;assert.ok(readBundleWorkspace(JSON.parse(JSON.stringify(store)),'fallback'));for(const change of [d=>delete d.bundle.origin,d=>d.bundle.components[0].evidence.push('W1:headcount'),d=>d.bundle.components[0].firstStep='This is proven to reduce turnover.',d=>d.bundle.origin='model',d=>d.binding.goal='Improve happiness']){const invalid=structuredClone(draft);change(invalid);assert.equal(readBundleDraft(invalid),null)}});
test('fallback stays bounded to supported goals and reports failed sources, never usable evidence',()=>{for(const goal of ['Replace 3 roles','Reduce turnover and add roles','Improve satisfaction','Retain staff without hiring'])assert.equal(assumptionsOnlyBundle(goal),null);assert.deepEqual(unavailableSourceLabels({sources:[{id:'A',label:'Attrition',status:'timeout'},{id:'B',label:'Exit survey',status:'unavailable'},{id:'C',label:'Workforce',status:'loaded'},{id:'D',status:'budget-excluded'}]}),['Attrition','Exit survey']);});

test('saved local context is bounded, isolated from model preparation, and identified as a prepared draft',async()=>{const {readAssumptionsFallback,assumptionsFallbackField}=await import('../lib/home-assumptions-fallback.ts'),{pinnedGoalPlanStatus}=await import('../lib/home-pinned-goals.ts');const goal='Add 3 additional roles',sourceBinding=await actionBinding('local-goal',goal,{sources:[]},{}),binding=await actionBinding('local-goal',goal,{sources:[]},{origin:'local-assumptions-v1',sourceBinding}),record={version:1,binding,sourceBinding,preparedAt:'2026-10-05T00:00:00Z',missingSources:['Attrition'],planningContext:{goal,notes:[]}};assert.notEqual(binding.planningDigest,sourceBinding.planningDigest);assert.ok(readAssumptionsFallback(record,'local-goal'));assert.equal(pinnedGoalPlanStatus('local-goal',{[assumptionsFallbackField]:record},{sources:[]}),'saved');for(const bad of [{...record,missingSources:[]},{...record,preparedAt:'bad'},{...record,extra:true},{...record,sourceBinding:{...sourceBinding,goal:'Replace 3 roles'}}])assert.equal(readAssumptionsFallback(bad,'local-goal'),null);assert.equal(readAssumptionsFallback(record,'another-goal'),null)});

test('long display-goal normalization cannot hide mixed scope',async()=>{const {assumptionsGoalFromStatements}=await import('../lib/home-assumptions-fallback.ts');assert.equal(assumptionsGoalFromStatements(['Synthetic planning test: reduce turnover and add 3 roles within 12 months.']),null);assert.equal(assumptionsGoalFromStatements(['Synthetic planning test: reduce turnover by 20% relative within 12 months.']),'Reduce employee turnover by 20% relative within 12 months');});
