import test from 'node:test';
import assert from 'node:assert/strict';
import {actionBinding} from '../lib/home-action-drafts.ts';
import {createBundleDraft,reconcileBundle} from '../lib/home-bundle-reconciliation.ts';
import {prepareIllustrativePilot} from '../lib/home-action-plan-pilot.ts';
import {planningStatements,resolveHomePlanningIntent} from '../lib/home-planning-intent.ts';
import {createPlanAlternatives,proposeEditedAlternative,proposeCombinedAlternative,attachPlanAlternative,packPlanAlternatives,readPlanAlternatives} from '../lib/home-plan-alternatives.ts';
import {bundleInputKey} from '../lib/home-bundle-reconciliation.ts';
import {retentionProposal} from './fixtures/home-retention-proposal.mjs';
const goal='Reduce company-wide turnover by 2 percentage points over 12 months with a $100,000 demo budget';
const context={goalId:'retention-target',goal};
async function plans(at='2026-10-07T00:00:00Z',goalContext={goal}){const binding=await actionBinding(context.goalId,goal,{sources:[]},goalContext);return retentionProposal(goal).bundles.map(bundle=>({id:bundle.id,draft:prepareIllustrativePilot(createBundleDraft(bundle,binding),at,{goalContext,includeDeliveryEstimate:true})}));}
function exact(draft){assert.equal(draft.binding.goal,goal);assert.equal(draft.inputs.scope.months.value,12);assert.equal(draft.inputs.budget.amount.value,100000);assert.equal(draft.inputs.budget.basis.value,'cash');assert.equal(draft.inputs.successMeasure.target.value,'2 percentage-point reduction');assert.equal(draft.inputs.successMeasure.baseline.value,null);assert.equal(draft.inputs.whatIf,undefined);assert.equal(draft.inputs.deliveryEstimate.hourlyRate.value,null);assert.doesNotMatch(JSON.stringify(draft.inputs.successMeasure),/15%|12%|100 people/);}
test('reported 2-point / 12-month / $100,000 request and regeneration never acquire template rates or population',async()=>{for(const date of ['2026-10-07T00:00:00Z','2026-11-07T00:00:00Z'])for(const {draft} of await plans(date)){exact(draft);assert.equal(draft.inputs.groups[0].count.value,null);assert.equal(reconcileBundle(draft).deliveryEstimate.participants,null);assert.equal(reconcileBundle(draft).budget.headroom,null);}});
test('split user constraints retain exact point units, budget and explicit participants',async()=>{const goalContext={goal:'Reduce turnover',notes:[{text:'Two percentage points over twelve months.'}],constraints:'Use 250 participants with a $100,000 demo budget.'};const intent=resolveHomePlanningIntent(planningStatements(goalContext));assert.equal(intent.pointReduction,2);assert.equal(intent.months,12);assert.equal(intent.budgetCap,100000);assert.equal(intent.participants,250);for(const {draft} of await plans(undefined,goalContext)){exact(draft);assert.equal(draft.inputs.groups[0].count.value,250);}});
test('relative percent stays distinct and a negated percentage-point example is not adopted',()=>{const intent=resolveHomePlanningIntent(['Reduce turnover by 20% relative, not 20 percentage points, over 12 months.']);assert.equal(intent.pointReduction,null);assert.equal(intent.relativeReduction,20);});
test('numbered edits, combination, attachment and reload retain one shared target and never sum it',async()=>{let catalog=createPlanAlternatives(context,await plans());const source=catalog.plans[0];let result=proposeEditedAlternative(catalog,context,{requestId:'edit-four',text:'set coordination hours to 24',sourceIds:[source.id],expectedInputs:{[source.id]:bundleInputKey(source.draft)}});assert.equal(result.status,'ready');assert.equal(result.plan.number,4);exact(result.plan.draft);catalog=result.catalog;const left=catalog.plans[0],right=catalog.plans[1];result=proposeCombinedAlternative(catalog,context,{requestId:'combine-five',text:'Combine Action Plan #1 and #2',sourceIds:[left.id,right.id],expectedInputs:{[left.id]:bundleInputKey(left.draft),[right.id]:bundleInputKey(right.draft)},review:{}});assert.equal(result.status,'ready');assert.equal(result.plan.number,5);exact(result.plan.draft);catalog=attachPlanAlternative(result.catalog,context,result.plan.id,{inputKey:bundleInputKey(result.plan.draft),attachmentId:'attached-five',at:'2026-10-07T01:00:00Z',acknowledgeUnknowns:true});const reloaded=readPlanAlternatives(JSON.parse(JSON.stringify(packPlanAlternatives(catalog))),context);assert.ok(reloaded);assert.equal(reloaded.attachments[0].planId,result.plan.id);exact(reloaded.plans[4].draft);assert.equal(reloaded.plans[0].applied,false);});

test('an explicitly negated relative-percent example cannot replace the requested point target',()=>{for(const text of ['Reduce turnover by 2 percentage points, not 20% relative, over 12 months.','Use 2 percentage points rather than 20% relative.','Replace 20% relative with 2 percentage points.']){const intent=resolveHomePlanningIntent([text]);assert.equal(intent.pointReduction,2);assert.equal(intent.relativeReduction,null);}});
