import test from 'node:test';
import assert from 'node:assert/strict';
import {createRequire} from 'node:module';
import {actionEvidenceCatalog,buildHomeActionFormat,readHomeActionProposal,decodeHomeActionProposal,proposedActionPresentation} from '../lib/home-action-proposal.ts';
import {actionBinding,readActionDraft,actionUsage,actionDraftPatch,actionSignature,actionCalculatorRoute} from '../lib/home-action-drafts.ts';
import {createHomeActionPreparation} from '../lib/home-action-preparation.ts';
const require=createRequire(import.meta.url),Ajv=require('ajv');
const packet={workforceScope:'Synthetic workforce',sources:[{id:'S2',status:'loaded',facts:{exit_respondents:12,rows:[{kind:'reason',primary_reason:'Manager support',exits:4,pct_of_exit_responses:33},{primary_reason:'Suppressed',exits:2,suppressed:true}]}},{id:'W1',status:'loaded',facts:{headcount:100}}]};
const goal='Address recorded manager-support concerns';
const action={name:'Manager coaching pilot',firstStep:'Draft a manager-coaching pilot for review.',evidence:['S2:row:0'],limitation:'Exit-survey associations do not establish causes or program effectiveness.',route:'retention_what_if'};
const proposal={version:1,goal,actions:[action],question:null,unavailableReason:null};
const binding=await actionBinding('goal-a',goal,packet,{retention:null});
const draft={version:1,status:'proposed',binding,preparedAt:'2026-10-04T22:00:00Z',proposal,localEvaluations:[],usage:actionUsage(null,12)};
test('catalog references only existing loaded nonsuppressed aggregate evidence and deterministic row positions',()=>{assert.deepEqual(actionEvidenceCatalog(packet).map(x=>x.id),['W1:summary','S2:summary','S2:row:0']);assert.equal(actionEvidenceCatalog(packet).find(x=>x.id==='S2:row:0').location,'facts.rows[0]');assert.equal(actionEvidenceCatalog({sources:[]}).length,0)});
test('dynamic strict schema and parser accept supported action with exact goal',()=>{assert.ok(new Ajv().compile(buildHomeActionFormat(goal,packet).schema)(proposal));assert.deepEqual(readHomeActionProposal(proposal,goal,packet),proposal)});
for(const mutation of [{goal:'Another goal'},{version:2},{actions:Array(4).fill(action)},{question:'What? When?'},{unavailableReason:'Not consistent with nonempty actions'}])test('reject invalid proposal envelope '+Object.keys(mutation)[0],()=>assert.equal(readHomeActionProposal({...proposal,...mutation},goal,packet),null));
for(const mutation of [{cost:100},{route:'execute'},{name:'x'.repeat(81)},{firstStep:'x'.repeat(361)},{limitation:''},{evidence:['S2:row:1']},{evidence:['S2:row:0','S2:row:0']},{evidence:['__proto__']},{evidence:[]}])test('reject invalid action field '+JSON.stringify(mutation),()=>assert.equal(readHomeActionProposal({...proposal,actions:[{...action,...mutation}]},goal,packet),null));
test('zero candidates need an honest reason; no fallback actions are invented',()=>{const empty={...proposal,actions:[],unavailableReason:'No supported aggregate evidence is available.'};assert.deepEqual(readHomeActionProposal(empty,goal,{sources:[]}),empty);assert.ok(new Ajv().compile(buildHomeActionFormat(goal,{sources:[]}).schema)(empty));assert.equal(readHomeActionProposal({...empty,unavailableReason:null},goal,packet),null)});
test('exact duplicate names reject rather than pad a menu',()=>assert.equal(readHomeActionProposal({...proposal,actions:[action,{...action,name:' manager coaching pilot '}]},goal,packet),null));
test('malformed JSON never echoes content in errors',()=>assert.throws(()=>decodeHomeActionProposal('PRIVATE_RAW_SENTINEL',goal,packet),error=>!String(error).includes('PRIVATE')));
for(const claim of ['This will reduce exits by 20%.','This guarantees retention.','The intervention is not proven but will save $500.'])test('semantic-risk evaluation: structural acceptance does not validate '+claim,()=>{const parsed=readHomeActionProposal({...proposal,actions:[{...action,firstStep:claim}]},goal,packet);assert.ok(parsed);const display=proposedActionPresentation(parsed.actions[0]);assert.equal(display.semanticReviewRequired,true);assert.equal(display.status,'AI-proposed pilot — not validated');for(const key of ['cost','timing','staffing','effect'])assert.equal(display[key],null)});
test('draft slot is separate and cannot carry confirmed plans or model-owned results',()=>{assert.equal(actionDraftPatch(draft).field,'homeActionDraftV1');assert.deepEqual(readActionDraft(draft,binding,packet),draft);assert.equal(readActionDraft({...draft,status:'approved'},binding,packet),null);assert.equal(readActionDraft({...draft,localEvaluations:[{effect:10}]},binding,packet),null);assert.equal(readActionDraft({...draft,workforceSolution:{}},binding,packet),null)});
test('bindings include exact goal evidence and local planning inputs without sending them anywhere',async()=>{const changed=await actionBinding('goal-a',goal,packet,{retention:{effect:10}});assert.notEqual(changed.planningDigest,binding.planningDigest);assert.equal(changed.evidenceDigest,binding.evidenceDigest);assert.equal(readActionDraft(draft,changed,packet),null);assert.equal(readActionDraft(draft,{...binding,goal:'Changed'},packet),null)});
test('usage stores only bounded counts and latency, never response content',()=>{const usage=actionUsage({input_tokens:80,input_tokens_details:{cached_tokens:40},output_tokens:20,output_tokens_details:{reasoning_tokens:5},total_tokens:100,raw:'PRIVATE'},20);assert.equal(usage.totalTokens,100);assert.ok(!JSON.stringify(usage).includes('PRIVATE'));assert.equal(actionUsage({input_tokens:-1,output_tokens:Infinity},-1).latencyMs,null)});
test('route requires independent exact action review and compatible scope',()=>{assert.equal(actionCalculatorRoute(action,binding,null),'review_required');const review={confirmed:true,binding,actionSignature:actionSignature(action),scope:'retention_program'};assert.equal(actionCalculatorRoute(action,binding,review),'retention_what_if');assert.equal(actionCalculatorRoute({...action,name:'Different program'},binding,review),'review_required');assert.equal(actionCalculatorRoute(action,binding,{...review,scope:'additional_capacity'}),'scope_mismatch')});
function harness(){let commits=[],calls=0,release;const coordinator=createHomeActionPreparation();const args={mode:'new-pin',binding,packet,stored:null,isCurrent:()=>true,prepare:async()=>{calls++;return await new Promise(resolve=>release=()=>resolve({proposal,usage:{total_tokens:99}}))},commit:patch=>commits.push(patch)};return {coordinator,args,commits,get calls(){return calls},release:()=>release()}}
test('simultaneous Pin events share one call and one draft write',async()=>{const h=harness(),a=h.coordinator.run(h.args),b=h.coordinator.run(h.args);assert.equal(a,b);await Promise.resolve();assert.equal(h.calls,1);h.release();assert.equal((await a).status,'ready');assert.equal(h.commits.length,1)});
test('passive old-goal/reload and exact cache hits never call preparation',async()=>{const h=harness();assert.equal((await h.coordinator.run({...h.args,mode:'passive'})).status,'explicit_required');assert.equal((await h.coordinator.run({...h.args,mode:'passive',stored:draft})).status,'cached');assert.equal(h.calls,0)});
test('failed preparation keeps prior work, has no automatic retry, permits explicit retry',async()=>{const h=harness();const args={...h.args,prepare:async()=>{throw Error('PRIVATE_RAW_FAILURE')}};assert.equal((await h.coordinator.run(args)).status,'failed');assert.equal((await h.coordinator.run(args)).status,'explicit_required');assert.equal((await h.coordinator.run({...args,mode:'explicit'})).status,'failed');assert.equal(h.commits.length,0)});
test('goal switch and switch-back invalidate late output even when binding matches again',async()=>{const h=harness(),pending=h.coordinator.run(h.args);await Promise.resolve();h.coordinator.invalidate();h.release();assert.equal((await pending).status,'stale');assert.equal(h.commits.length,0)});
test('changed evidence cannot automatically re-prepare an already pinned goal',async()=>{const h=harness(),pending=h.coordinator.run(h.args);await Promise.resolve();h.release();await pending;assert.equal((await h.coordinator.run({...h.args,binding:{...binding,evidenceDigest:'a'.repeat(64)}})).status,'explicit_required');assert.equal(h.calls,1)});

test('action draft round-trips through legacy goal migration without changing plans or other goals',async()=>{
 const {DecisionStore}=await import('../lib/local-decisions.ts');
 const values=new Map([['insights-to-action.goals.v1',JSON.stringify({version:1,activeId:'goal-a',goals:[{id:'goal-a',statement:goal},{id:'goal-b',statement:'Other goal'}]})]]);
 const port={getItem:key=>values.get(key)??null,setItem:(key,value)=>values.set(key,value),removeItem:key=>values.delete(key)};
 const store=new DecisionStore();store.initialize(port);store.setField('goal-a','workforceSolution',{sentinel:'Existing confirmed plan'});store.setField('goal-b','chat',{messages:[],input:'Keep another goal draft'});
 const patch=actionDraftPatch(draft);store.setField('goal-a',patch.field,patch.value);
 const reload=new DecisionStore();reload.initialize(port);
 assert.deepEqual(readActionDraft(reload.getField('goal-a',patch.field,null),binding,packet),draft);
 assert.deepEqual(reload.getField('goal-a','workforceSolution',null),{sentinel:'Existing confirmed plan'});
 assert.equal(reload.getField('goal-b','chat',null).input,'Keep another goal draft');
 assert.equal(reload.getField('goal-b',patch.field,null),null);
});

for(const firstStep of ['Draft a role-specific pilot.', 'Discuss “readiness — not certainty” with HR.', 'Ask the owner: “Can we review this?”', 'Review the plan (including follow-up).', 'Review the team’s draft; retain its caveats!', 'Review the “cost … timing” notes.', 'Review the literal label “Follow-up—”.', 'Discuss the quoted note “more…”.', 'Draft a pilot for HR', 'Check the U.S. scope.'])test('legitimate first-step punctuation is preserved: '+firstStep,()=>{const value={...proposal,actions:[{...action,firstStep}]};assert.ok(new Ajv().compile(buildHomeActionFormat(goal,packet).schema)(value));assert.equal(readHomeActionProposal(value,goal,packet).actions[0].firstStep,firstStep);});
for(const firstStep of ['Draft a pilot to avoid net—','Draft an evidence-','Draft a pilot –  ','Draft a pilot…','Draft a pilot...\n'])test('reject only obvious bare unfinished endings: '+firstStep,()=>{assert.equal(readHomeActionProposal({...proposal,actions:[{...action,firstStep}]},goal,packet),null);});
test('first-step schema/parser preserve full bounded text and reject overflow without clipping',()=>{const validate=new Ajv().compile(buildHomeActionFormat(goal,packet).schema);for(const length of [240,241,359,360]){const firstStep='Review '+ 'a'.repeat(length-8)+'.',value={...proposal,actions:[{...action,firstStep}]};assert.equal(firstStep.length,length);assert.equal(validate(value),true);assert.equal(readHomeActionProposal(value,goal,packet).actions[0].firstStep,firstStep);assert.equal(readActionDraft({...draft,proposal:value},binding,packet).proposal.actions[0].firstStep,firstStep);}const value={...proposal,actions:[{...action,firstStep:'a'.repeat(360)+'.'}]};assert.equal(validate(value),false);assert.equal(readHomeActionProposal(value,goal,packet),null);});
