import test from 'node:test';
import assert from 'node:assert/strict';
import {readInvestigationProposal,renderInvestigationCandidate,readInvestigationRecord,investigationMetrics,investigationOperations,buildInvestigationCandidateSchema,availableInvestigationMetrics} from '../lib/home-investigation-contract.ts';
import {normalizeHomePack,homeDefinitions} from '../lib/home-pack.mjs';
const pack={workforceScope:'Engineering / UK',sources:[
 {id:'W1',status:'loaded',date:'2026-09-30',facts:{headcount:12,fte:10.5,open_positions:0}},
 {id:'R1',status:'loaded',date:'2026-09-29',facts:{open_requisitions:4,median_time_to_fill_days:32.5,offer_acceptance_pct:70}},
 {id:'S1',status:'loaded',facts:{manager_favorable_pct:62}},
]};
const capacity={operation:'review_capacity',evidence:['W1.headcount']};
const hiring={operation:'review_hiring_pipeline',evidence:['R1.median_time_to_fill_days']};
const proposal={version:2,problem:'Investigate engineering capacity',problem_evidence:['W1.headcount','R1.open_requisitions'],options:[capacity,hiring],question:null};
test('specific distinct operations round-trip without prose/model values',()=>assert.deepEqual(readInvestigationProposal(proposal,pack),proposal));
test('candidate rendering uses actual metric values with separate canonical context',()=>{const card=renderInvestigationCandidate(capacity,pack);assert.equal(card.title,'Review workforce headcount');assert.match(card.why,/12 employees/);assert.equal(card.cost,'Unknown — not calculated.');assert.equal(card.evidence[0].scope,'Selected workforce snapshot: Engineering / UK');assert.equal(card.evidence[0].date,'2026-09-30');assert.equal(card.evidence[0].population,'Snapshot employees; FTE capacity; open positions');assert.match(card.evidence[0].limitation,/synthetic aggregate/)});
test('company-wide source does not inherit selected workforce filters',()=>{const card=renderInvestigationCandidate(hiring,pack);assert.equal(card.evidence[0].scope,'Company-wide; unfiltered');assert.match(card.evidence[0].limitation,/not guaranteed future capacity/);assert.match(card.why,/32.5 days/)});
test('metadata labels and caveats cannot be supplied by candidate or forged source labels',()=>{const forged={...pack,sources:pack.sources.map(s=>({...s,label:'Guaranteed effect',scope:'Local team',population:'Ready workers',limitation:'Certain benefits'}))};assert.deepEqual(renderInvestigationCandidate(hiring,forged),renderInvestigationCandidate(hiring,pack));assert.equal(renderInvestigationCandidate({...capacity,scope:'Local team'},pack),null)});
for(const id of ['__proto__','constructor','W1.__proto__','W1.facts.headcount','W1.headcount.value','W1.rows.0.headcount','FAKE.headcount'])test('reject arbitrary metric path '+id,()=>assert.equal(readInvestigationProposal({...proposal,options:[{...capacity,evidence:[id]}]},pack),null));
test('every metric is a fixed root field already in normalized packet',()=>{assert.equal(Object.keys(investigationMetrics).length,21);for(const [id,m] of Object.entries(investigationMetrics)){assert.equal(id,m.source+'.'+m.field);assert.ok(homeDefinitions.find(s=>s[0]===m.source)[7].split(' ').includes(m.field));assert.ok(investigationOperations.includes(m.operation))}});
test('wrong operation rejects without fallback candidates',()=>{for(const option of [{...capacity,evidence:['R1.open_requisitions']},{operation:'invent',evidence:['W1.headcount']}])assert.equal(readInvestigationProposal({...proposal,options:[capacity,option]},pack),null)});
test('unknown null unavailable suppressed numeric string and invalid types reject',()=>{for(const [status,value,suppressed] of [['unavailable',12,false],['loaded',null,false],['loaded','12',false],['loaded',NaN,false],['loaded',Infinity,false],['loaded',-1,false],['loaded',1.5,false],['loaded',12,true]]){const input={...pack,sources:[{id:'W1',status,facts:{headcount:value,suppressed}}]};assert.equal(renderInvestigationCandidate(capacity,input),null)}});
test('counts FTE and percentages retain their distinct types',()=>{const fte=renderInvestigationCandidate({...capacity,evidence:['W1.fte']},pack);assert.match(fte.why,/10.5 FTE/);assert.match(renderInvestigationCandidate({...capacity,evidence:['W1.open_positions']},pack).why,/0 positions/);const c={operation:'review_employee_feedback',evidence:['S1.manager_favorable_pct']};assert.match(renderInvestigationCandidate(c,pack).why,/62%/);assert.equal(renderInvestigationCandidate(c,{sources:[{id:'S1',status:'loaded',facts:{manager_favorable_pct:101}}]}),null)});
test('no model number or estimate fields can enter the contract',()=>{for(const field of ['value','cost','timing','staffing','title','outcome','why','scope','date','effect'])assert.equal(readInvestigationProposal({...proposal,options:[{...capacity,[field]:99}]},pack),null)});
test('one or two useful candidates stay one or two; equivalent ref sets deduplicate',()=>{const double={...capacity,evidence:['W1.headcount','W1.fte']};const p={...proposal,options:[double,{...double,evidence:[...double.evidence].reverse()}]};assert.equal(readInvestigationProposal(p,pack).options.length,1);assert.equal(readInvestigationProposal(proposal,pack).options.length,2)});
test('empty options require one bounded clarification; no replacement generated',()=>{assert.equal(readInvestigationProposal({...proposal,options:[]},pack),null);assert.equal(readInvestigationProposal({...proposal,options:[],question:'Which capacity constraint should we investigate?'},pack).options.length,0);assert.equal(readInvestigationProposal({...proposal,question:'What? When?'},pack),null)});
test('problem evidence must resolve; selection is binding not proof of causal relevance',()=>{assert.equal(readInvestigationProposal({...proposal,problem_evidence:['S1.unknown']},pack),null);assert.equal(readInvestigationProposal({...proposal,problem_evidence:[]},pack),null)});
test('old freeform v1 proposals and records cannot be interpreted as v2',()=>{assert.equal(readInvestigationProposal({...proposal,version:1},pack),null);assert.equal(readInvestigationProposal({...proposal,options:[{title:'Review capacity',outcome:'Clarify capacity',why:'12 employees',source_ids:['W1']}]},pack),null);const record={version:1,goalId:'a',goal:proposal.problem,sourceKey:'snapshot',selectionGoal:'',proposal};const snapshot=structuredClone(record);assert.equal(readInvestigationRecord(record,'a',proposal.problem,'snapshot',pack),null);assert.deepEqual(record,snapshot)});
test('saved v2 candidates preserve exact goal and evidence snapshot binding',()=>{const record={version:2,goalId:'a',goal:proposal.problem,sourceKey:'snapshot',selectionGoal:'original',proposal};assert.deepEqual(readInvestigationRecord(record,'a',proposal.problem,'snapshot',pack),record);assert.equal(readInvestigationRecord(record,'b',proposal.problem,'snapshot',pack),null);assert.equal(readInvestigationRecord(record,'a','Changed','snapshot',pack),null);assert.equal(readInvestigationRecord(record,'a',proposal.problem,'changed',pack),null)});
test('normalization round-trip preserves server/client contract and metadata',()=>{assert.deepEqual(readInvestigationProposal(proposal,normalizeHomePack(pack)),proposal);assert.deepEqual(renderInvestigationCandidate(capacity,normalizeHomePack(pack)),renderInvestigationCandidate(capacity,pack))});
test('schema accepts only operation and catalog IDs, not free-form claims',()=>{const schema=buildInvestigationCandidateSchema(availableInvestigationMetrics(pack));for(const branch of schema.anyOf){assert.deepEqual(branch.required,['operation','evidence']);assert.equal(branch.additionalProperties,false);assert.ok(branch.properties.evidence.items.enum.every(id=>availableInvestigationMetrics(pack).includes(id)))}});
const contracts=[
 ['W1.headcount','employees','count'],['W1.fte','FTE','number'],['W1.open_positions','positions','count'],['P2.vacant_positions','positions','count'],
 ['R1.open_requisitions','requisitions','count'],['R1.median_time_to_fill_days','days','number'],['R1.offer_acceptance_pct','%','percent'],
 ['A1.voluntary_exits','exits','count'],['A1.regrettable_exits','exits','count'],['A1.voluntary_turnover_ytd_pct','%','percent'],
 ['S1.engagement_favorable_pct','%','percent'],['S1.manager_favorable_pct','%','percent'],['S1.pulse_favorable_pct','%','percent'],['S2.exit_respondents','respondents','count'],
 ['T1.skills_below_75_pct','skills','count'],['T1.weighted_requirement_met_pct','%','percent'],['T2.gap_pathway_coverage_pct','%','percent'],['T2.active_courses_on_gap_skills','courses','count'],
 ['T3.preference_record_coverage_pct','%','percent'],['T3.relocation_willing_pct','%','percent'],['T4.total_recorded_events','events','count'],
];
for(const [id,unit,kind] of contracts)test('metric contract: '+id,()=>{
 const [source,field]=id.split('.'),operation=investigationMetrics[id].operation,candidate={operation,evidence:[id]};
 const input=value=>({workforceScope:'UK engineering',sources:[{id:source,status:'loaded',date:'2026-09-30',facts:{[field]:value}}]});
 const card=renderInvestigationCandidate(candidate,input(12));assert.equal(card.evidence[0].unit,unit);assert.equal(card.evidence[0].date,'2026-09-30');assert.equal(card.evidence[0].value,12);assert.equal(card.evidence[0].scope,source==='W1'?'Selected workforce snapshot: UK engineering':homeDefinitions.find(d=>d[0]===source)[4]);assert.equal(card.evidence[0].limitation,homeDefinitions.find(d=>d[0]===source)[6]);
 for(const value of [null,undefined,'12',NaN,-1])assert.equal(renderInvestigationCandidate(candidate,input(value)),null);
 assert.equal(renderInvestigationCandidate(candidate,input(0)).evidence[0].value,0);
 assert.equal(renderInvestigationCandidate(candidate,{sources:[{id:source,status:'loaded',facts:{[field]:12}}]}).evidence[0].date,null);
 assert.equal(renderInvestigationCandidate(candidate,input(kind==='count'?1.5:kind==='percent'?101:Infinity)),null);
 assert.equal(renderInvestigationCandidate(candidate,{sources:[{id:source,status:'loaded',facts:{[field]:12,suppressed:true}}]}),null);
});
test('bounded exact problem has no numerical claims; user-confirmed goals are untouched',()=>{for(const problem of ['Investigate 12 departures','Investigate twelve departures','Investigate ２０％ savings'])assert.equal(readInvestigationProposal({...proposal,problem},pack),null);assert.equal(readInvestigationProposal({...proposal,problem:'Investigate the recorded engineering constraint'},pack).problem,'Investigate the recorded engineering constraint')});
test('three distinct metrics remain three and repeated refs are not fabricated alternatives',()=>{const options=[capacity,{...capacity,evidence:['W1.fte']},{...capacity,evidence:['W1.open_positions']}];assert.equal(readInvestigationProposal({...proposal,options},pack).options.length,3);assert.equal(readInvestigationProposal({...proposal,options:Array(4).fill(capacity)},pack),null);assert.equal(readInvestigationProposal({...proposal,options:[{...capacity,evidence:['W1.headcount','W1.headcount']}]},pack),null)});

test('independent problem and candidate evidence accepts distinct available sources',()=>{const independent={...proposal,problem_evidence:['W1.headcount'],options:[hiring,{operation:'review_employee_feedback',evidence:['S1.manager_favorable_pct']}]};assert.deepEqual(readInvestigationProposal(independent,pack),independent);for(const source of ['R1','S1']){const missing={...pack,sources:pack.sources.map(item=>item.id===source?{...item,status:'unavailable'}:item)};assert.equal(readInvestigationProposal(independent,missing),null);const suppressed={...pack,sources:pack.sources.map(item=>item.id===source?{...item,facts:{...item.facts,suppressed:true}}:item)};assert.equal(readInvestigationProposal(independent,suppressed),null);}});
