import test from 'node:test';import assert from 'node:assert/strict';
import {conversationBoundary,resetConversationMarks} from '../lib/conversation-reset.ts';
import {workforceChoiceDiscoveryGoal} from '../lib/home-planning-intent.ts';
import {isDifferentHomeIssue} from '../lib/home-alternative-issue.ts';
import {planDeliveryEstimate,withDeliveryAssumptions} from '../lib/home-plan-delivery-estimate.ts';
import {prepareIllustrativePilot} from '../lib/home-action-plan-pilot.ts';
import {createBundleDraft,reconcileBundle,reviseBundleDraft} from '../lib/home-bundle-reconciliation.ts';
import {previewBundleChatEdit,acceptBundleChatEdit} from '../lib/home-bundle-chat-edit.ts';
import {bundleProposalFixture} from './fixtures/home-bundles.mjs';import {actionBinding} from '../lib/home-action-drafts.ts';
const binding=await actionBinding('test','Investigate skills and career pathways',{sources:[{id:'W1',status:'loaded',facts:{headcount:20}}]},{});
const base=()=>{const bundle=bundleProposalFixture(binding.goal).bundles[0];bundle.components=bundle.components.slice(0,2).map((c,i)=>({...c,name:i?'Career pathways':'Skills assessment',domain:i?'mobility':'learning',firstStep:i?'Audit career pathways':'Assess skill gaps',dependsOn:[]}));return createBundleDraft(bundle,binding)};
test('reset boundaries are scoped, repeatable and do not alter archived messages',()=>{const history=['a','b','c'];let marks=resetConversationMarks({},'home',2);assert.equal(conversationBoundary(marks,'home',3),2);assert.equal(conversationBoundary(marks,'workforce',3),0);marks=resetConversationMarks(marks,'workforce',3);marks=resetConversationMarks(marks,'home',3);assert.deepEqual(history,['a','b','c']);assert.equal(conversationBoundary(marks,'home',3),3);for(const value of [-1,4,'2',NaN])assert.equal(conversationBoundary({home:value},'home',3),0)});
test('hire/train question becomes a proposed decision goal without turning informational questions into goals',()=>{for(const q of ['Should we hire, train, or both?','Could we recruit or upskill?','Help us decide between hiring and training'])assert.equal(workforceChoiceDiscoveryGoal(q),'Choose a hiring, training, or combined approach for our workforce needs');for(const q of ['What is training?','How does hiring compare with training?','Do not hire or train','Should we hire?'])assert.equal(workforceChoiceDiscoveryGoal(q),null)});
test('another issue requires changed focus and supporting evidence',()=>{const old={problem:'Investigate retention and exit patterns',problem_evidence:['A1.voluntary_exits']};assert.equal(isDifferentHomeIssue(old,{problem:'Review retention and exit patterns',problem_evidence:['A1.voluntary_exits']}),false);assert.equal(isDifferentHomeIssue(old,{problem:'Investigate hiring pipeline bottlenecks',problem_evidence:['R1.open_requisitions']}),true)});
test('analysis plan has concrete deliverables, reconciled staffing and costs, preserved in calculation',()=>{const draft=prepareIllustrativePilot(base(),'2026-10-06T00:00:00Z',{includeDeliveryEstimate:true}),e=planDeliveryEstimate(draft);assert.equal(e.participants,10);assert.equal(e.hours,36);assert.equal(e.employeeTime,2160);assert.equal(e.cash,3000);assert.equal(e.finish,'2026-11-14');assert.deepEqual(e.deliverables,['10 skills assessments and one evidence-ranked skill-gap list','one documented pathway audit']);assert.deepEqual(reconcileBundle(draft).deliveryEstimate,e);assert.equal(draft.inputs.scope.startMonth.value,'2026-11');assert.equal(draft.inputs.scope.months.value,3);assert.equal(draft.inputs.capacity,null);assert.equal(draft.inputs.whatIf,undefined)});
test('explicit staffing rates and employee-time costs win; intervention work is not labelled an assessment',()=>{const draft=prepareIllustrativePilot(base(),'2026-10-06T00:00:00Z',{includeDeliveryEstimate:true}),input=structuredClone(draft.inputs),entered=value=>({value,kind:'user-entered',basis:'User requested'});input.deliveryEstimate.hourlyRate=entered(90);input.expenses.push({id:'time',label:'Existing staff allocation',kind:'employee_time',amount:entered(500),months:entered(1),startMonth:entered('2026-11')});const edited=reviseBundleDraft(draft,input);assert.equal(planDeliveryEstimate(edited).employeeTime,500);assert.deepEqual(withDeliveryAssumptions(input,9),input);edited.bundle.components[0].firstStep='Deliver a training programme';assert.equal(planDeliveryEstimate(edited).deliverables[0],'one completed work package: Skills assessment')});
test('old snapshots are unchanged unless delivery assumptions are explicitly requested, then chat edits need acceptance',()=>{const draft=prepareIllustrativePilot(base(),'2026-10-06T00:00:00Z',{includeDeliveryEstimate:true});delete draft.inputs.deliveryEstimate;const before=JSON.stringify(draft);assert.equal(reconcileBundle(draft).deliveryEstimate,undefined);const preview=previewBundleChatEdit(draft,'Make all the assumptions so you have an outcome');assert.equal(JSON.stringify(draft),before);const next=acceptBundleChatEdit(draft,preview);assert.equal(planDeliveryEstimate(next).employeeTime,2160);const rate=previewBundleChatEdit(next,'Set Staff hourly rate to $75');const revised=acceptBundleChatEdit(next,rate);assert.equal(planDeliveryEstimate(revised).employeeTime,2700);assert.notEqual(reconcileBundle(next).inputKey,reconcileBundle(revised).inputKey)});

test('bulk assumption request never discards supplied amounts or extra edits',()=>{for(const request of ['Use budget assumptions of $5000','Make all assumptions and set Staff hourly rate to $75','Do not make all assumptions'])assert.throws(()=>previewBundleChatEdit(base(),request));});

test('an explicit overlapping-cost choice overrides the starting cash assumption',()=>{const draft=prepareIllustrativePilot(base(),'2026-10-06T00:00:00Z',{includeDeliveryEstimate:true});draft.inputs.costsDistinct={value:false,kind:'user-entered',basis:'These costs overlap'};assert.equal(planDeliveryEstimate(draft).cash,null);});
