import test from 'node:test';
import assert from 'node:assert/strict';
import {pilotCalendar,prepareIllustrativePilot} from '../lib/home-action-plan-pilot.ts';
import {createBundleDraft,reviseBundleDraft,reconcileBundle,bundleInputKey,readBundleDraft} from '../lib/home-bundle-reconciliation.ts';
import {bundleProposalFixture} from './fixtures/home-bundles.mjs';
import {actionBinding} from '../lib/home-action-drafts.ts';
import {saveBundleCalculationPatch,saveBundleDraftPatch,readBundleWorkspace} from '../lib/home-bundle-records.ts';
const binding=await actionBinding('pilot-goal','Develop a voluntary-turnover pilot',{sources:[{id:'W1',status:'loaded',facts:{headcount:20}}]},{}),stamp='2026-12-31T23:59:59.000Z',base=()=>createBundleDraft(bundleProposalFixture(binding.goal).bundles[0],binding),entered=value=>({value,kind:'user-entered',basis:'Reviewed exact draft assumption.'});
test('UTC next-full-month dates are frozen across year and leap boundaries',()=>{assert.deepEqual(pilotCalendar(stamp),{preparedAt:stamp,timezone:'UTC',startMonth:'2027-01',endDate:'2027-03-31'});assert.equal(pilotCalendar('2027-11-30T23:00:00Z').endDate,'2028-02-29');assert.equal(pilotCalendar('2026-12-31T23:30:00-02:00').startMonth,'2027-02');assert.throws(()=>pilotCalendar('invalid'));});
test('prepared assumptions have versioned demo provenance and no forced capacity/effects',()=>{const draft=prepareIllustrativePilot(base(),stamp);assert.equal(draft.inputs.scope.months.value,3);assert.equal(draft.inputs.scope.startMonth.value,'2027-01');assert.equal(draft.inputs.groups[0].count.value,10);assert.equal(draft.inputs.groups[0].count.kind,'illustrative');assert.match(draft.inputs.groups[0].count.basis,/illustrative-pilot-v1/);assert.equal(draft.inputs.capacity,null);assert.equal(draft.inputs.scope.capacityRequired.value,null);assert.equal(draft.inputs.scope.demand.value,null);assert.equal(draft.inputs.expenses.length,6);assert.ok(draft.inputs.expenses.every(expense=>expense.kind==='cash'&&expense.amount.kind==='illustrative'));assert.equal(draft.pilot.timezone,'UTC');assert.ok(readBundleDraft(draft));assert.equal(reconcileBundle(draft).cashTotal,null);assert.equal(reconcileBundle(draft).knownCashSubtotal,null);assert.equal(reconcileBundle(draft).uniqueParticipants,null);});
test('one allowance per domain links repeated components once without assuming distinct budgets',()=>{const draft=base();draft.bundle.components[1].domain='manager_workload';const result=prepareIllustrativePilot(createBundleDraft(draft.bundle,binding),stamp);assert.equal(result.inputs.expenses.length,5);assert.equal(result.inputs.expenses.find(item=>item.id==='pilot-manager_workload').amount.value,1000);assert.deepEqual(result.inputs.expenseLinks.find(item=>item.expenseId==='pilot-manager_workload').componentIds,['c1','c2']);assert.equal(result.inputs.costsDistinct.value,null);});
test('exact known scope, amounts and participant groups take priority; unassigned costs prevent guessing overlaps',()=>{const draft=base(),input=structuredClone(draft.inputs);input.scope.population=entered('Reviewed existing cohort');input.scope.startMonth=entered('2028-02');input.scope.months=entered(6);input.groups=[{id:'reviewed',label:'Reviewed group',count:entered(21)}];input.expenses=[{id:'known-cost',label:'Existing cost with unresolved mapping',kind:'cash',amount:entered(3210),startMonth:entered('2028-02'),months:entered(1)}];const prepared=prepareIllustrativePilot(reviseBundleDraft(draft,input),stamp);assert.deepEqual(prepared.inputs.scope.population,input.scope.population);assert.deepEqual(prepared.inputs.groups,input.groups);assert.deepEqual(prepared.inputs.expenses,input.expenses);assert.equal(prepared.inputs.scope.startMonth.value,'2028-02');assert.equal(prepared.inputs.scope.months.value,6);});
test('linked existing cost suppresses same-domain allowance',()=>{const draft=base(),input=structuredClone(draft.inputs);input.expenses=[{id:'learning-cost',label:'Known learning',kind:'cash',amount:entered(4500),startMonth:entered('2027-01'),months:entered(1)}];input.expenseLinks=[{expenseId:'learning-cost',componentIds:['c2'],allocations:null}];const prepared=prepareIllustrativePilot(reviseBundleDraft(draft,input),stamp);assert.ok(!prepared.inputs.expenses.some(item=>item.id==='pilot-learning'));assert.equal(prepared.inputs.expenses.find(item=>item.id==='learning-cost').amount.value,4500);});
test('dependency stages use actual inclusive dates and preserve an out-of-horizon known start for explicit review',()=>{const draft=base();draft.bundle.components.forEach((item,index)=>item.dependsOn=index?[`c${index}`]:[]);const result=prepareIllustrativePilot(createBundleDraft(draft.bundle,binding),'2027-01-10T00:00:00Z');assert.equal(result.inputs.timing[0].start.value,'2027-02-01');assert.equal(result.inputs.timing[5].finish.value,'2027-04-25');const input=structuredClone(result.inputs);input.timing[0].start=entered('2027-05-01');input.timing[0].finish=entered('2027-05-14');const edited=reviseBundleDraft(result,input);assert.throws(()=>reconcileBundle(edited),/horizon/);assert.deepEqual(prepareIllustrativePilot(edited,'2030-01-01T00:00:00Z'),edited);});
test('later edits, cleared values and removal persist; preset never reapplies or refreshes dates',()=>{const original=prepareIllustrativePilot(base(),stamp),input=structuredClone(original.inputs);input.expenses[0].amount=entered(1700);input.expenses=input.expenses.filter(item=>item.id!=='pilot-learning');input.expenseLinks=input.expenseLinks.filter(item=>item.expenseId!=='pilot-learning');const edited=reviseBundleDraft(original,input);assert.deepEqual(prepareIllustrativePilot(edited,'2030-06-01T00:00:00Z'),edited);assert.equal(edited.pilot.preparedAt,stamp);});
test('edited demo budget stales explicit calculation and saved snapshots survive reload',()=>{const draft=prepareIllustrativePilot(base(),stamp),result=reconcileBundle(draft),saved=saveBundleCalculationPatch(undefined,draft,result),input=structuredClone(draft.inputs);input.expenses[0].amount=entered(1800);const edited=reviseBundleDraft(draft,input),next=saveBundleDraftPatch(saved.value,edited),loaded=readBundleWorkspace(next.value,binding.goalId);assert.notEqual(result.inputKey,bundleInputKey(edited));assert.equal(loaded.calculations[0].result.inputKey,result.inputKey);assert.equal(loaded.drafts[0].inputs.expenses[0].amount.value,1800);assert.equal(loaded.drafts[0].pilot.preparedAt,stamp);});

test('date edits preserve intermediate drafts but invalid date order blocks explicit calculation',()=>{const draft=prepareIllustrativePilot(base(),stamp),input=structuredClone(draft.inputs);input.timing[0].start=entered('2027-02-01');const edited=reviseBundleDraft(draft,input);assert.ok(readBundleDraft(edited));assert.throws(()=>reconcileBundle(edited),/finish cannot precede/);input.timing[0].finish=entered('2027-02-14');assert.equal(reviseBundleDraft(edited,input).inputs.timing[0].finish.value,'2027-02-14');});
