import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {savedPilotCorrection,savedPilotReviewNotes} from '../lib/home-saved-pilot-correction.ts';
import {readBundleDraft,reconcileBundle,reviseBundleDraft,bundleInputKey} from '../lib/home-bundle-reconciliation.ts';
import {createPlanAlternatives,proposeCorrectedPilotAlternative,attachPlanAlternative,readPlanAlternatives,packPlanAlternatives,changeAlternativeView} from '../lib/home-plan-alternatives.ts';
import {saveBundleDraftPatch,attachBundlePatch,readBundleWorkspace} from '../lib/home-bundle-records.ts';
import {actionBindingKey} from '../lib/home-action-drafts.ts';
import {successMeasureText} from '../lib/home-success-measures.ts';
import {prepareIllustrativePilot} from '../lib/home-action-plan-pilot.ts';
const fixture=JSON.parse(readFileSync(new URL('./fixtures/home-saved-pilot-before-pr175.json',import.meta.url),'utf8'));
const context={goalId:fixture.drafts[0].binding.goalId,goal:fixture.planningContext.goal};
const catalog=()=>createPlanAlternatives(context,fixture.drafts.map(draft=>({id:draft.bundle.id,draft})));
const request=(value,id='repair-one')=>({requestId:id,text:'Restore unchanged starting defaults from original goal',sourceIds:[value.order[0]],expectedInputs:{[value.order[0]]:bundleInputKey(value.plans.find(plan=>plan.id===value.order[0]).draft)}});
const entered=value=>({value,kind:'user-entered',basis:'Explicit saved user edit.'});
function checkTarget(draft){assert.equal(draft.inputs.scope.months.value,12);assert.equal(draft.inputs.budget.amount.value,100000);assert.equal(draft.inputs.successMeasure.target.value,'2 percentage-point reduction');assert.equal(draft.inputs.successMeasure.baseline.value,null);assert.equal(draft.inputs.whatIf,undefined);assert.equal(draft.inputs.groups[0].count.value,null);assert.match(draft.inputs.scope.population.value,/Population unspecified/);assert.equal(reconcileBundle(draft).budget.limit,100000);assert.equal(reconcileBundle(draft).budget.headroom,null);}
test('real pre-fix saved fixture retains 15→12 / 3 months / 100 denominator before an explicit correction',()=>{
 assert.equal(fixture.sourceCommit,'979570af119f74ef5b019b3a73474fcbf8cddb81');
 for(const draft of fixture.drafts){assert.ok(readBundleDraft(draft));assert.equal(draft.inputs.scope.months.value,3);assert.equal(draft.inputs.whatIf.baseline.value,15);assert.equal(draft.inputs.whatIf.target.value,12);assert.equal(draft.inputs.whatIf.population.value,100);assert.deepEqual(prepareIllustrativePilot(draft,'2026-10-07T00:00:00Z',{goalContext:fixture.planningContext}),draft);const before=JSON.stringify(draft),offer=savedPilotCorrection(draft,fixture.planningContext);checkTarget(offer.draft);assert.equal(JSON.stringify(draft),before);assert.deepEqual(offer.draft.inputs.expenses,draft.inputs.expenses);assert.deepEqual(offer.draft.inputs.timing,draft.inputs.timing);assert.deepEqual(offer.draft.pilot,draft.pilot);}
});
test('correction appends #4, survives packing/reload, supports explicit attachment and keeps original legacy snapshots byte-for-byte',()=>{
 let legacy;for(const draft of fixture.drafts)legacy=saveBundleDraftPatch(legacy,draft).value;const first=fixture.drafts[0];legacy=attachBundlePatch(legacy,first,{confirmed:true,bindingKey:actionBindingKey(first.binding),inputKey:bundleInputKey(first),acknowledgeUnknowns:true},'legacy-attachment','2026-10-01T12:00:00Z').value;
 const originalLegacy=JSON.stringify(legacy),before=catalog(),original=JSON.stringify(before),out=proposeCorrectedPilotAlternative(before,context,request(before),fixture.planningContext);assert.equal(out.status,'ready');assert.equal(out.plan.number,4);assert.equal(out.plan.operation.kind,'goal-correction');assert.equal(out.plan.applied,false);assert.deepEqual(out.plan.sourceRefs,[{id:'A',revision:first.revision}]);assert.deepEqual(out.catalog.plans.slice(0,3),before.plans);assert.equal(JSON.stringify(before),original);assert.equal(out.catalog.attachments.length,0);
 const attached=attachPlanAlternative(out.catalog,context,out.plan.id,{inputKey:bundleInputKey(out.plan.draft),attachmentId:'corrected-attachment',at:'2026-10-07T01:00:00Z',acknowledgeUnknowns:true});const reload=readPlanAlternatives(JSON.parse(JSON.stringify(packPlanAlternatives(attached))),context);assert.equal(reload.nextNumber,5);assert.equal(reload.attachments[0].planId,out.plan.id);checkTarget(reload.plans[3].draft);assert.equal(JSON.stringify(readBundleWorkspace(JSON.parse(originalLegacy),context.goalId)),originalLegacy);assert.equal(JSON.stringify(legacy),originalLegacy);
});
test('retry and a new session reuse an existing matching correction without duplicate plans or attachments',()=>{const before=catalog(),out=proposeCorrectedPilotAlternative(before,context,request(before),fixture.planningContext);for(const id of ['repair-one','new-session']){const retry=proposeCorrectedPilotAlternative(out.catalog,context,request(out.catalog,id),fixture.planningContext);assert.equal(retry.reused,true);assert.equal(retry.plan.number,4);assert.equal(retry.catalog.nextNumber,5);}const removed=changeAlternativeView(out.catalog,context,{deleteId:out.plan.id});const next=proposeCorrectedPilotAlternative(removed,context,request(removed,'after-delete'),fixture.planningContext);assert.equal(next.plan.number,5);assert.equal(next.catalog.plans[3].deleted,true);});
test('explicit saved edits and populations win; correction never refreshes activity dates or cash allowances',()=>{const input=structuredClone(fixture.drafts[0].inputs);input.scope.months=entered(6);input.budget={amount:entered(80000),basis:entered('cash')};input.groups[0].count=entered(250);input.deliveryEstimate.coordinationHours=entered(24);const source=reviseBundleDraft(fixture.drafts[0],input),offer=savedPilotCorrection(source,fixture.planningContext);assert.equal(offer.draft.inputs.scope.months.value,6);assert.equal(offer.draft.inputs.budget.amount.value,80000);assert.equal(offer.draft.inputs.groups[0].count.value,250);assert.equal(offer.draft.inputs.deliveryEstimate.coordinationHours.value,24);assert.deepEqual(offer.draft.inputs.expenses,source.inputs.expenses);assert.deepEqual(offer.draft.inputs.timing,source.inputs.timing);assert.equal(offer.draft.inputs.successMeasure.baseline.value,null);});
test('an explicit original participant count is restored while a user-edited scenario is never replaced',()=>{const source=fixture.drafts[0],offer=savedPilotCorrection(source,{...fixture.planningContext,constraints:fixture.request+' for 250 participants'});assert.equal(offer.draft.inputs.groups[0].count.value,250);const input=structuredClone(source.inputs);input.whatIf.baseline=entered(18);input.whatIf.target=entered(16);const edited=reviseBundleDraft(source,input);const corrected=savedPilotCorrection(edited,fixture.planningContext).draft;assert.deepEqual(corrected.inputs.whatIf.baseline,edited.inputs.whatIf.baseline);assert.deepEqual(corrected.inputs.whatIf.target,edited.inputs.whatIf.target);assert.equal(corrected.inputs.whatIf.population.value,null);assert.equal(corrected.inputs.groups[0].count.value,null);});
test('a corrected plan has no repeat offer; stale source, deleted source and different goal allocate no number',()=>{const before=catalog(),out=proposeCorrectedPilotAlternative(before,context,request(before),fixture.planningContext);assert.equal(savedPilotCorrection(out.plan.draft,fixture.planningContext),null);const stale=request(before);stale.expectedInputs.A='stale';assert.throws(()=>proposeCorrectedPilotAlternative(before,context,stale,fixture.planningContext),/revision changed/);assert.throws(()=>proposeCorrectedPilotAlternative(before,{...context,goal:'Different'},request(before),fixture.planningContext),/active goal changed/);const removed=changeAlternativeView(before,context,{deleteId:'A'});assert.throws(()=>proposeCorrectedPilotAlternative(removed,context,request(before),fixture.planningContext),/no longer available/);assert.equal(before.nextNumber,4);});

test('partial saved edits retain an explicit workforce denominator separately from participant counts',()=>{const input=structuredClone(fixture.drafts[0].inputs);input.whatIf.population=entered(200);const source=reviseBundleDraft(fixture.drafts[0],input),offer=savedPilotCorrection(source,fixture.planningContext);assert.equal(offer.draft.inputs.whatIf.population.value,200);assert.equal(offer.draft.inputs.whatIf.baseline.value,null);assert.equal(offer.draft.inputs.whatIf.target.value,null);assert.equal(offer.draft.inputs.groups[0].count.value,null);assert.equal(offer.draft.inputs.successMeasure.target.value,'2 percentage-point reduction');assert.equal(reconcileBundle(offer.draft).deliveryEstimate.participants,null);input.whatIf.baseline=entered(18);const explicitBaseline=savedPilotCorrection(reviseBundleDraft(fixture.drafts[0],input),fixture.planningContext);assert.equal(explicitBaseline.draft.inputs.successMeasure.baseline.value,'18%');assert.equal(explicitBaseline.draft.inputs.whatIf.baseline.value,18);input.whatIf.baseline=structuredClone(fixture.drafts[0].inputs.whatIf.baseline);input.whatIf.target=entered(10);assert.match(savedPilotReviewNotes(reviseBundleDraft(fixture.drafts[0],input)).join(' '),/will not replace your target/);});


test('corrected measures preserve explicit annualized and YTD baselines instead of relabelling them as six-month rates',()=>{
 for(const ratePeriod of ['annualized','ytd'])for(const kind of ['user-entered','adopted']){
  const input=structuredClone(fixture.drafts[0].inputs);input.scope.months=entered(6);input.whatIf.baseline={value:8.2,kind,basis:`Explicit ${ratePeriod} baseline from original conversation.`};input.whatIf.ratePeriod=ratePeriod;
  const source=reviseBundleDraft(fixture.drafts[0],input),before=JSON.stringify(source),offer=savedPilotCorrection(source,fixture.planningContext),corrected=offer.draft,periodLabel=ratePeriod==='ytd'?'YTD':ratePeriod;
  assert.equal(corrected.inputs.scope.months.value,6);assert.deepEqual(corrected.inputs.whatIf.baseline,source.inputs.whatIf.baseline);assert.equal(corrected.inputs.whatIf.ratePeriod,ratePeriod);assert.equal(corrected.inputs.whatIf.target.value,null);assert.equal(corrected.inputs.whatIf.population.value,null);assert.equal(corrected.inputs.successMeasure.baseline.value,`8.2% ${periodLabel}`);assert.equal(corrected.inputs.successMeasure.baseline.kind,kind);assert.equal(corrected.inputs.successMeasure.target.value,'2 percentage-point reduction');assert.match(successMeasureText(corrected.inputs.successMeasure),/not a confirmed 6-month baseline/);assert.match(offer.changes.join(' '),/no automatic conversion/);assert.equal(JSON.stringify(source),before);
  const value=createPlanAlternatives(context,fixture.drafts.map((draft,index)=>({id:draft.bundle.id,draft:index===0?source:draft}))),out=proposeCorrectedPilotAlternative(value,context,request(value),fixture.planningContext),reloaded=readPlanAlternatives(JSON.parse(JSON.stringify(packPlanAlternatives(out.catalog))),context);assert.equal(reloaded.plans[3].draft.inputs.whatIf.ratePeriod,ratePeriod);assert.equal(reloaded.plans[3].draft.inputs.successMeasure.baseline.value,`8.2% ${periodLabel}`);assert.deepEqual(reloaded.plans[0].draft,source);
 }
});
test('generated populations are corrected independently when saved rates, horizon and budget have already been edited',()=>{
 const input=structuredClone(fixture.drafts[0].inputs);input.scope.months=entered(12);input.budget={amount:entered(100000),basis:entered('cash')};input.whatIf.baseline=entered(18);input.whatIf.target=entered(16);input.whatIf.ratePeriod='annualized';
 const source=reviseBundleDraft(fixture.drafts[0],input),before=JSON.stringify(source),offer=savedPilotCorrection(source,fixture.planningContext);assert.ok(offer);assert.equal(offer.draft.inputs.whatIf.population.value,null);assert.equal(offer.draft.inputs.groups[0].count.value,null);assert.deepEqual(offer.draft.inputs.whatIf.baseline,source.inputs.whatIf.baseline);assert.deepEqual(offer.draft.inputs.whatIf.target,source.inputs.whatIf.target);assert.equal(offer.draft.inputs.whatIf.ratePeriod,'annualized');assert.deepEqual(offer.draft.inputs.scope.months,source.inputs.scope.months);assert.deepEqual(offer.draft.inputs.budget,source.inputs.budget);assert.match(offer.changes.join(' '),/100-person workforce denominator/);assert.match(offer.changes.join(' '),/ten-person pilot group/);assert.equal(JSON.stringify(source),before);assert.equal(savedPilotCorrection(offer.draft,fixture.planningContext),null);
 const participants=savedPilotCorrection(source,{...fixture.planningContext,constraints:fixture.request+' for 250 participants'});assert.equal(participants.draft.inputs.groups[0].count.value,250);assert.equal(participants.draft.inputs.whatIf.population.value,null);
 input.whatIf.population=entered(350);input.groups[0].count=entered(250);const reviewed=reviseBundleDraft(fixture.drafts[0],input);assert.equal(savedPilotCorrection(reviewed,fixture.planningContext),null);
});
