import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {solutionRequest,candidate,based,retained,activity,quantity,constraint,final,evaluate,project,projectionSpec,projectionInputs,fixtureRuntime} from './fixtures/home-solution-conversation.mjs';
import {converseSolutions,solutionModelContext} from '../lib/home-solution-conversation-service.ts';
import {evaluateSolutionCandidate,readSolutionState,mergeSolutionConstraints,saveSolutionCandidate,emptySolutionState,solutionConversationEnabled} from '../lib/home-solution-conversation.ts';
import {readPlanAlternatives,changeAlternativeView,applyPlanAlternative,attachPlanAlternative} from '../lib/home-plan-alternatives.ts';
import {calculateHeadcountProjection} from '../lib/home-solution-projection.ts';
const signal=()=>new AbortController().signal;
const run=(request,steps,inputs)=>converseSolutions(request,fixtureRuntime(steps,inputs),signal());
const currentForSave=(request,reply)=>({...request,state:reply.state});

// Fixed outputs exercise software contracts, not model semantic or conversation quality.
test('open problem, no goal or saved plans, substantive answer without a candidate',async()=>{const request=solutionRequest('Our team is overwhelmed. Where should we begin?'),before=JSON.stringify(request),runtime=fixtureRuntime([final('Start by distinguishing queue volume, handoffs and avoidable rework. Which is most visible?')]);const reply=await converseSolutions(request,runtime,signal());assert.match(reply.answer,/handoffs/);assert.equal(reply.state.working.length,0);assert.equal(reply.state.turns.length,2);assert.equal(runtime.reads,0);assert.equal(JSON.stringify(request),before);});
test('new creative candidate without existing plan has honest unknown resources',async()=>{const reply=await run(solutionRequest(),[evaluate(candidate()),final('Try a volunteer mentoring trial.',['mentoring'])]),item=reply.state.working[0];assert.deepEqual(item.blocking,[]);assert.equal(item.draft.bundle.origin,'conversation-v1');assert.equal(item.result.cashEstimate.cash,null);assert.equal(item.result.uniqueParticipants,null);assert.equal(item.draft.inputs.timing[0].start.value,null);assert.ok(item.issues.length);});
test('actual scoped evidence and goal context reach the model, with current plan IDs and inputs',()=>{const request=solutionRequest('Compare learning and manager support.',true);request.goalContext={constraints:'Keep workload bounded.'};const context=solutionModelContext(request);assert.deepEqual(context.currentEvidence,request.evidence);assert.equal(context.goal.statement,'Reduce turnover');assert.equal(context.savedPlans[0].id,'A');assert.equal(context.selectedPlan.inputs,undefined);assert.equal(context.selectedPlan.draft.inputs.budget.amount.value,10000);assert.equal(context.goalContext.constraints,'Keep workload bounded.');});
test('descriptive blend does not need a pair selector and retains lineage/unknown overlap',async()=>{const request=solutionRequest('Combine the manager support and learning approach.',true),c=based();c.activities.push(retained('B','c2'));const reply=await run(request,[evaluate(c),final('Combine support with practice.',['mentoring'])]),item=reply.state.working[0];assert.deepEqual(item.blocking,[]);assert.deepEqual(item.sourceRefs.map(ref=>ref.id),['A','B']);assert.equal(item.result.uniqueParticipants,null);assert.equal(item.result.cashEstimate.cash,null);assert.equal(item.draft.inputs.deliveryEstimate.hoursPerParticipant.value,null);assert.equal(item.draft.inputs.timing[0].start.value,'2026-11-01');});
test('unchanged single-plan activity retains valid timing, effort, costs and population',async()=>{const request=solutionRequest('Keep the current approach, but review it.',true),item=await evaluateSolutionCandidate(request,based(),[]);assert.deepEqual(item.blocking,[]);assert.equal(item.result.cashEstimate.cash,3000);assert.equal(item.result.deliveryEstimate.hours,28);assert.equal(item.result.uniqueParticipants,10);assert.equal(item.draft.inputs.scope.startMonth.value,'2026-11');});
test('multi-turn blend then replace one component preserves mentoring and invalidates affected inputs',async()=>{const request=solutionRequest('Blend support with learning.',true),c=based();c.activities.push(retained('B','c2'));const first=await run(request,[evaluate(c),final('Combine them.',['mentoring'])]);const next=solutionRequest('Keep mentoring, replace the manager workshop with an office hour.',true,first.state,2),changed=candidate();changed.base={kind:'working',id:'mentoring',revision:1};changed.activities=[{...activity('c1','Office hour'),mode:'adapt',source:{...changed.base,activityId:'c1'}},{...activity('c2'),mode:'retain',source:{...changed.base,activityId:'c2'}}];const reply=await run(next,[evaluate(changed),final('Keep the learning activity and try office hours.',['mentoring'])]),item=reply.state.working.at(-1);assert.deepEqual(item.blocking,[]);assert.equal(item.revision,2);assert.equal(item.draft.inputs.timing[0].start.value,null);assert.equal(item.draft.inputs.timing[1].start.value,'2026-11-01');assert.equal(item.result.deliveryEstimate.hours,null);assert.equal(item.result.cashEstimate.cash,null);assert.equal(first.state.working[0].candidate.activities[0].mode,'retain');assert.equal(reply.state.turns.length,4);});
test('same people uses one identity and a relative halve reads the previous numeric input',async()=>{const request=solutionRequest('Use the same people for both activities.',true),c=based();c.activities.push({...retained('B','c2'),audienceOf:'c1'});const first=await run(request,[evaluate(c),final('The group is shared.',['mentoring'])]);assert.equal(first.state.working[0].result.uniqueParticipants,10);const next=solutionRequest('Halve that participant count; keep both activities.',true,first.state,2),updated=structuredClone(c);updated.base={kind:'working',id:'mentoring',revision:1};updated.activities=updated.activities.map(part=>({...part,source:{...updated.base,activityId:part.id}}));updated.quantities=[{...quantity('participants',null,'people','all','user-2'),kind:'scale',source:{...updated.base,field:'participants',target:'c1'},factor:.5}];const reply=await run(next,[evaluate(updated),final('That is five people, shared.',['mentoring'])]);assert.deepEqual(reply.state.working.at(-1).blocking,[]);assert.equal(reply.state.working.at(-1).result.uniqueParticipants,5);assert.match(reply.state.working.at(-1).interpretations.join(' '),/factor 0.5/);});
test('corrected current constraint wins; an older turn cannot undo it',async()=>{const request=solutionRequest('Budget is 8000.',true),c=based(),first=await run(request,[evaluate(c,[constraint(8000)]),final('Budget noted.',['mentoring'])]);const next=solutionRequest('Correction: the ceiling is 2500.',true,first.state,2);const reply=await run(next,[evaluate(c,[constraint(2500,'user-2')]),final('The existing 3000 allowance exceeds 2500.',['mentoring'])]);assert.equal(reply.state.working.at(-1).draft.inputs.budget.amount.value,2500);assert.match(reply.state.working.at(-1).blocking.join(' '),/exceeds/);assert.throws(()=>mergeSolutionConstraints({...next,state:reply.state},reply.state.constraints,[constraint(8000)]),/older/);});
test('calculator failure is fed back to model and recovered within the bounded turn',async()=>{const request=solutionRequest('Use a cash ceiling of 2500 and reduce the fee to 2000.',true),c=based();const runtime=fixtureRuntime([evaluate(c,[constraint(2500)]),input=>{const feedback=JSON.parse(input.at(-1).output);assert.match(feedback.blocking.join(' '),/exceeds/);const fixed=based();fixed.quantities=[quantity('cash',2000,'USD','c1')];return evaluate(fixed);},final('With the reviewed 2000 fee it fits the known ceiling.',['mentoring'])]);const reply=await converseSolutions(request,runtime,signal());assert.deepEqual(reply.state.working.at(-1).blocking,[]);assert.equal(reply.state.working.at(-1).result.cashEstimate.cash,2000);assert.equal(reply.usage.modelRounds,3);});
test('malformed references and units produce feedback without fabricated totals',async()=>{for(const mutate of [c=>c.activities[0].source.id='imaginary',c=>c.quantities=[quantity('participants',12,'FTE','c1')],c=>c.activities.push(structuredClone(c.activities[0])),c=>c.activities[0].dependsOn=['c1']]){const c=based();mutate(c);const item=await evaluateSolutionCandidate(solutionRequest('Review',true),c,[]);assert.ok(item.blocking.length);assert.equal(item.result,null);}});
test('no candidate may be named by final answer without evaluation in this turn',async()=>{await assert.rejects(()=>run(solutionRequest(),[final('Done',['invented'])]),/not checked/);});
test('explicit Save appends and repeat Save is idempotent; original snapshots immutable',async()=>{const request=solutionRequest('Keep this plan and a 9000 ceiling.',true),before=JSON.stringify(request.catalog),c=based();c.quantities=[quantity('budget_usd',9000,'USD')];const reply=await run(request,[evaluate(c),final('Review the updated ceiling.',['mentoring'])]),req=currentForSave(request,reply),item=reply.state.working.at(-1);const result=await saveSolutionCandidate(req,request.catalog,item,request.goal,request.evidence,true),again=await saveSolutionCandidate(req,result.catalog,item,request.goal,request.evidence,true);assert.equal(result.status,'ready');assert.equal(result.catalog.plans.length,4);assert.equal(again.reused,true);assert.equal(JSON.stringify(request.catalog),before);assert.equal(result.plan.applied,false);assert.equal(result.catalog.attachments.length,0);assert.ok(readPlanAlternatives(result.catalog,result.catalog));});
test('new zero-source candidate can be saved under an explicitly reviewed new goal',async()=>{const request=solutionRequest(),reply=await run(request,[evaluate(candidate()),final('Review the trial.',['mentoring'])]),item=reply.state.working[0],goal={id:'new-goal',statement:'Improve mentoring'};const result=await saveSolutionCandidate(currentForSave(request,reply),null,item,goal,request.evidence,true);assert.equal(result.plan.number,1);assert.equal(result.plan.sourceRefs.length,0);assert.equal(result.plan.draft.binding.goalId,'new-goal');assert.ok(readPlanAlternatives(result.catalog,result.catalog));assert.equal(result.plan.result.calculationStatus,'awaiting-scope');assert.throws(()=>applyPlanAlternative(result.catalog,result.catalog,result.plan.id,result.plan.result.inputKey),/qualitative proposal/);assert.throws(()=>attachPlanAlternative(result.catalog,result.catalog,result.plan.id,{inputKey:result.plan.result.inputKey,attachmentId:'x',at:new Date().toISOString(),acknowledgeUnknowns:true}),/qualitative proposal/);});
test('stale catalog, evidence, constraints and discarded revisions cannot save',async()=>{const request=solutionRequest('Review this',true),reply=await run(request,[evaluate(based()),final('Review.',['mentoring'])]),req=currentForSave(request,reply),item=reply.state.working[0];await assert.rejects(()=>saveSolutionCandidate(req,changeAlternativeView(request.catalog,request.catalog,{order:['C','B','A']}),item,request.goal,request.evidence,true),/catalog changed/);const evidence=structuredClone(request.evidence);evidence.workforceScope='Changed workforce scope';await assert.rejects(()=>saveSolutionCandidate(req,request.catalog,item,request.goal,evidence,true),/changed/);const constraints=structuredClone(req);constraints.state.constraints=[constraint(1)];await assert.rejects(()=>saveSolutionCandidate(constraints,request.catalog,item,request.goal,request.evidence,true),/current reviewed/);const rejected=structuredClone(req);rejected.state.rejected=[{candidateId:item.id,revision:item.revision,reason:'No',turnId:'user-1'}];await assert.rejects(()=>saveSolutionCandidate(rejected,request.catalog,item,request.goal,request.evidence,true),/current reviewed/);});
test('unknowns need explicit acknowledgement and a discussion-only turn keeps working candidates',async()=>{const request=solutionRequest(),first=await run(request,[evaluate(candidate()),final('Review.',['mentoring'])]),item=first.state.working[0];await assert.rejects(()=>saveSolutionCandidate(currentForSave(request,first),null,item,{id:'goal',statement:'Improve mentoring'},request.evidence,false),/Acknowledge/);const second=await run(solutionRequest('Why would this help?',false,first.state,2),[final('A mentor can shorten the feedback loop; test that hypothesis.')]);assert.deepEqual(second.state.working,first.state.working);assert.equal(second.state.turns.length,4);});
test('cancelled provider output cannot change state or trigger tools',async()=>{const request=solutionRequest(),controller=new AbortController(),runtime=fixtureRuntime([()=>{controller.abort();return evaluate(candidate());}]);await assert.rejects(()=>converseSolutions(request,runtime,controller.signal),/cancelled/);assert.deepEqual(request.state,emptySolutionState());assert.equal(runtime.reads,0);});
test('tool loop is bounded, stops without retry, and rejects write tools',async()=>{const request=solutionRequest(),runtime=fixtureRuntime([{name:'push_plan',args:{}},final('That tool is unavailable.')]);const reply=await converseSolutions(request,runtime,signal());assert.match(JSON.parse(runtime.contexts[1].at(-1).output).error,/Unsupported/);assert.equal(reply.usage.toolCalls,1);const loops=fixtureRuntime(Array(4).fill(evaluate(candidate())));await assert.rejects(()=>converseSolutions(request,loops,signal()),/bounded calculation limit/);assert.equal(loops.rounds,4);});
test('configured headcount projection uses active opening, deterministic engine and explicit provenance',async()=>{const spec=projectionSpec(),runtime=fixtureRuntime([project(spec),final('Here is a scenario using current configured assumptions.',[],['headcount'])]),reply=await converseSolutions(solutionRequest('Project headcount'),runtime,signal()),analysis=reply.state.analyses[0];assert.equal(analysis.inputs.opening,100);assert.equal(analysis.points.at(-1).headcount,103);assert.equal(analysis.inputs.datasetVersion,null);assert.equal(analysis.inputDigest.length,64);assert.match(analysis.limitations.join(' '),/stored hires\/exits do not reconcile/);assert.equal(runtime.reads,1);});
test('follow-up slower hiring changes fill rate relative to exact prior analysis',async()=>{const request=solutionRequest('Project headcount'),first=await run(request,[project(projectionSpec()),final('Baseline.',[],['headcount'])]),next=solutionRequest('Assume hiring fills at half that rate.',false,first.state,2),spec={...projectionSpec(),base:{id:'headcount',revision:1},changes:[{field:'fill_rate_pct',kind:'scale',value:.5,basis:'user',turnId:'user-2',interpretation:'Half the prior scenario fill rate.'}]};const second=await run(next,[project(spec),final('With a 50% fill rate, the scenario grows more slowly.',[],['headcount'])]);assert.equal(second.state.analyses.at(-1).assumptions.fill_rate_pct,50);assert.ok(second.state.analyses.at(-1).points.at(-1).headcount<103);assert.equal(second.state.analyses.at(-1).revision,2);});
test('monthly stock-flow reconciles; internal transfers cannot raise organization headcount',async()=>{const spec={...projectionSpec(),method:'monthly_flow',changes:['monthly_hires','monthly_exits','monthly_transfers_in','monthly_transfers_out'].map((field,index)=>({field,kind:'literal',value:[5,2,3,1][index],basis:'illustrative',turnId:null,interpretation:'Explicit hypothetical fixture.'}))};await assert.rejects(()=>calculateHeadcountProjection(spec,projectionInputs(),[],[]),/Internal transfers/);const inputs=projectionInputs({country:'all',org:'ENG',level:'all'}),result=await calculateHeadcountProjection(spec,inputs,[],[]);assert.equal(result.points[0].headcount,105);assert.equal(result.points[2].headcount,115);for(const p of result.points)assert.equal(p.headcount,p.opening+p.hires-p.exits+p.transfersIn-p.transfersOut);assert.match(result.interpretations[0],/Illustrative assumption/);});
test('projection rejects missing flows, unsupported scope and incoherent dates rather than inventing inputs',async()=>{await assert.rejects(()=>calculateHeadcountProjection({...projectionSpec(),method:'monthly_flow'},projectionInputs(),[],[]),/unknown/);await assert.rejects(()=>calculateHeadcountProjection(projectionSpec(),projectionInputs({country:'US',org:'all',level:'all'}),[],[]),/company-wide/);const inputs=projectionInputs();inputs.asOf='2026-09-30';await assert.rejects(()=>calculateHeadcountProjection(projectionSpec(),inputs,[],[]),/forward window/);inputs.opening=null;await assert.rejects(()=>calculateHeadcountProjection(projectionSpec(),inputs,[],[]),/unavailable/);});
test('state readers reject corrupted totals and unsupported metadata',async()=>{const reply=await run(solutionRequest(),[evaluate(candidate()),final('Review.',['mentoring'])]),bad=structuredClone(reply.state);bad.working[0].result.cashTotal=123;assert.throws(()=>readSolutionState(bad),/verified/);const bad2=structuredClone(reply.state);bad2.working[0].issues=[{unexpected:true}];assert.throws(()=>readSolutionState(bad2),/metadata/);});
test('default-off route gates before body/provider, configured model unchanged, no old phrase gate',()=>{assert.equal(solutionConversationEnabled,false);const route=readFileSync(new URL('../app/api/home-solution-conversation/route.ts',import.meta.url),'utf8');assert.ok(route.indexOf('if(!solutionConversationEnabled)')<route.indexOf('request.text()'));assert.match(route,/model:CHAT_MODEL/);assert.match(route,/maxRetries:0/);const source=readFileSync(new URL('../lib/home-solution-conversation-service.ts',import.meta.url),'utf8');assert.doesNotMatch(source,/planConversationQuantity|combinationIntent|bundleChatEditIntent/);});
test('ordinary time answer is clock-grounded, then a deadline request reviews the discussed plan in the same conversation',async()=>{
 const firstRequest=solutionRequest('What time is it?');firstRequest.timeZone='America/New_York';
 const runtime=fixtureRuntime([{name:'read_clock',args:{}},input=>{const clock=JSON.parse(input.at(-1).output);assert.equal(clock.utc,'2026-10-08T15:24:00.000Z');assert.equal(clock.timeZone,'America/New_York');assert.match(clock.local,/11:24:00/);return final('It is 11:24 AM in New York.');}]);runtime.now=()=>new Date('2026-10-08T15:24:00Z');
 const first=await converseSolutions(firstRequest,runtime,signal());assert.equal(first.state.working.length,0);assert.equal(runtime.reads,0);
 const request=solutionRequest('Change the deadline of the selected plan to November 20, 2026.',true,first.state,2),c=based();c.quantities=[{...quantity('activity_finish',null,'YYYY-MM-DD','c1','user-2'),text:'2026-11-20'}];
 const reply=await run(request,[evaluate(c),final('The discussed plan now has a proposed November 20 deadline for your review.',['mentoring'])]);assert.equal(reply.state.turns[1].text,'It is 11:24 AM in New York.');assert.deepEqual(reply.state.working.at(-1).blocking,[]);assert.equal(reply.state.working.at(-1).draft.inputs.timing[0].finish.value,'2026-11-20');assert.equal(request.catalog.plans[0].draft.inputs.timing[0].finish.value,'2026-11-14');
});

test('quantity-only saved and working sources enter lineage and reject mutation before selection',async()=>{
 const request=solutionRequest('Use half the budget from saved plan one for a fresh mentoring trial.',true),c=candidate();
 c.quantities=[{...quantity('budget_usd',null,'USD'),kind:'scale',source:{kind:'saved',id:'B',revision:request.catalog.plans[1].draft.revision,field:'budget_usd',target:null},factor:.5}];
 const item=await evaluateSolutionCandidate(request,c,[]);assert.deepEqual(item.blocking,[]);assert.deepEqual(item.sourceRefs.map(ref=>ref.id),['B']);assert.ok(item.sourceKeys.B);assert.equal(item.draft.inputs.budget.amount.value,5000);
 request.state.working=[item];const saved=await saveSolutionCandidate(request,request.catalog,item,request.goal,request.evidence,true);assert.deepEqual(saved.plan.sourceRefs,item.sourceRefs);
 const changed=structuredClone(request.catalog);changed.plans[1].draft.inputs.budget.amount.value=8000;
 await assert.rejects(()=>saveSolutionCandidate(request,changed,item,request.goal,request.evidence,true),/source plan changed/);
 const next=solutionRequest('Use that same proposed budget.',true,request.state,2),derived=candidate('derived');derived.quantities=[{...quantity('budget_usd',null,'USD',null,'user-2'),kind:'reference',source:{kind:'working',id:item.id,revision:item.revision,field:'budget_usd',target:null}}];
 const evaluated=await evaluateSolutionCandidate(next,derived,[]);assert.deepEqual(evaluated.sourceRefs,item.sourceRefs);assert.deepEqual(evaluated.sourceKeys,item.sourceKeys);
 next.state.working.push(evaluated);await assert.rejects(()=>saveSolutionCandidate(next,changed,evaluated,next.goal,next.evidence,true),/source plan changed/);
});
test('changing one formerly shared membership clears disjoint certainty',async()=>{
 const request=solutionRequest('Add office hours with the same ten people.',true),c=based();c.activities.push({...activity('c2','Office hours'),audienceOf:'c1'});
 const first=await evaluateSolutionCandidate(request,c,[]);assert.deepEqual(first.blocking,[]);assert.equal(first.result.uniqueParticipants,10);assert.equal(first.draft.inputs.groupsDisjoint.value,true);
 request.state.working=[first];const next=solutionRequest('Change only mentoring to twenty participants.',true,request.state,2),change=candidate();change.base={kind:'working',id:first.id,revision:first.revision};change.activities=['c1','c2'].map(id=>({...activity(id),mode:'retain',source:{...change.base,activityId:id}}));change.quantities=[quantity('participants',20,'people','c1','user-2')];
 const second=await evaluateSolutionCandidate(next,change,[]);assert.deepEqual(second.blocking,[]);assert.equal(second.draft.inputs.groupsDisjoint.value,null);assert.equal(second.result.uniqueParticipants,null);assert.equal(second.draft.inputs.groups.length,2);
});
test('typed constraint removal clears inherited cap, keeps provenance and blocks older resurrection',async()=>{
 const request=solutionRequest('Set a budget cap.',true);request.state.constraints=[constraint(4000)];request.state.turns=[{id:'user-1',role:'user',text:'Cap it at four thousand.'}];request.message={id:'user-2',text:'Drop the budget cap.'};
 const removed={...constraint(null,'user-2'),action:'remove'},constraints=mergeSolutionConstraints(request,request.state.constraints,[removed]);assert.deepEqual(constraints,[removed]);
 const item=await evaluateSolutionCandidate(request,based(),constraints);assert.deepEqual(item.blocking,[]);assert.equal(item.draft.inputs.budget.amount.value,null);assert.match(item.interpretations.join(' '),/Removed budget_usd/);
 assert.throws(()=>mergeSolutionConstraints(request,constraints,[constraint(4000,'user-1')]),/older statement/);
 request.state.turns.push({id:'user-2',role:'user',text:'Drop the cap.'});request.message={id:'user-3',text:'Use a six thousand cap instead.'};assert.equal(mergeSolutionConstraints(request,constraints,[constraint(6000,'user-3')])[0].number,6000);
});
test('intentional qualitative association is idempotent, survives reload and never enables Apply',async()=>{
 const {associatePlanProposal}=await import('../lib/home-plan-alternatives.ts');
 const request=solutionRequest('I want to reduce turnover.'),reply=await run(request,[evaluate(candidate()),final('Consider a mentoring trial.',['mentoring'])]),item=reply.state.working[0];assert.equal(item.binding.goal,'Reduce turnover');assert.notEqual(item.binding.goal,item.candidate.objective);
 const outcome=await saveSolutionCandidate(currentForSave(request,reply),null,item,{id:'turnover',statement:item.candidate.goal.statement},request.evidence,true),confirmation={inputKey:outcome.plan.result.inputKey,attachmentId:outcome.plan.requestId,at:'2026-10-08T12:00:00Z',acknowledgeUnknowns:true};
 const selected=associatePlanProposal(outcome.catalog,outcome.catalog,outcome.plan.id,confirmation),again=associatePlanProposal(selected,selected,outcome.plan.id,confirmation);assert.deepEqual(again,selected);assert.equal(selected.attachments[0].purpose,'proposal-selection');assert.ok(readPlanAlternatives(JSON.parse(JSON.stringify(selected)),selected));assert.equal(selected.plans[0].applied,false);
 assert.throws(()=>applyPlanAlternative(selected,selected,outcome.plan.id,confirmation.inputKey),/qualitative/);
});
test('computed claims accept only exact checked metric references; invented savings cannot be verified',async()=>{
 const {resolveSolutionMetric}=await import('../lib/home-solution-conversation.ts');
 const request=solutionRequest('Review plan one.',true),answer=final('A mentoring approach may help.',['mentoring']);answer.verifiedMetrics=[{kind:'candidate',id:'mentoring',revision:1,metric:'cash_usd'}];const reply=await run(request,[evaluate(based()),answer]);assert.equal(resolveSolutionMetric(reply.state,reply.state.verifiedMetrics[0]).value,3000);
 const invented={...answer,answer:'Verified savings are $500,000.',verifiedMetrics:[{kind:'candidate',id:'mentoring',revision:1,metric:'savings_usd'}]};await assert.rejects(()=>run(request,[evaluate(based()),invented]),/Unsupported answer.verifiedMetrics/);
 const unchecked={...answer,verifiedMetrics:[{kind:'candidate',id:'invented',revision:1,metric:'cash_usd'}]};await assert.rejects(()=>run(request,[evaluate(based()),unchecked]),/not checked/);
 const prose=await run(solutionRequest(),[final('The untrusted model asserts $500,000 savings.')]);assert.deepEqual(prose.state.verifiedMetrics,[]);const view=readFileSync(new URL('../components/pages/overall-overview-page.tsx',import.meta.url),'utf8');assert.match(view,/Discussion · interpretations and hypotheses. Checked quantities appear in the result cards./);
});
