import test from 'node:test';import assert from 'node:assert/strict';
import {actionBinding} from '../lib/home-action-drafts.ts';
import {createBundleDraft,readBundleDraft,reconcileBundle,bundleInputKey} from '../lib/home-bundle-reconciliation.ts';
import {prepareIllustrativePilot} from '../lib/home-action-plan-pilot.ts';
import {calculatePlanWhatIf,whatIfOutcomeText} from '../lib/home-plan-what-if.ts';
import {previewBundleChatEdit,acceptBundleChatEdit} from '../lib/home-bundle-chat-edit.ts';
import {saveBundleCalculationPatch,attachBundlePatch,readBundleWorkspace} from '../lib/home-bundle-records.ts';
import {actionBindingKey} from '../lib/home-action-drafts.ts';
import {bundleProposalFixture} from './fixtures/home-bundles.mjs';
const pack={sources:[{id:'W1',status:'loaded',facts:{headcount:100}}]};
async function draft(goal='Reduce turnover'){const binding=await actionBinding('scenario',goal,pack,{});return prepareIllustrativePilot(createBundleDraft(bundleProposalFixture(goal).bundles[0],binding),'2026-10-05T00:00:00Z')}
test('visible turnover assumptions produce dimensional conditional arithmetic without evidence claims',async()=>{const d=await draft(),r=calculatePlanWhatIf(d.inputs);assert.equal(r.status,'ready');assert.equal(r.cash,7500);assert.equal(r.baselineCount,15);assert.equal(r.targetCount,12);assert.equal(r.change,-3);assert.match(whatIfOutcomeText(d.inputs),/3 percentage points lower/);assert.match(whatIfOutcomeText(d.inputs),/not a predicted or causal effect/);assert.equal(reconcileBundle(d).cashTotal,null);assert.equal(d.inputs.whatIf.baseline.kind,'illustrative');});
test('capacity scenario honors explicit roles and months without claiming approved scope or availability',async()=>{const d=await draft('Add 5 additional roles over 12 months'),r=calculatePlanWhatIf(d.inputs);assert.equal(r.target,5);assert.equal(r.months,12);assert.equal(r.roleCash,480000);assert.equal(d.inputs.whatIf.target.kind,'user-entered');assert.equal(d.inputs.scope.capacityRequired.value,null);assert.match(whatIfOutcomeText(d.inputs),/does not confirm the role\/BU scope/);});
test('ambiguous percentage targets stay unknown; explicit relative targets preserve their meaning',async()=>{assert.equal(calculatePlanWhatIf((await draft('Reduce turnover by 20%')).inputs).status,'missing');const d=await draft('Reduce turnover by 20% relative over 12 months');assert.equal(d.inputs.whatIf.target.value,12);assert.equal(d.inputs.scope.months.value,12);});
test('unsupported replacement/mixed goals do not acquire an effect model',async()=>{for(const goal of ['Replace 5 roles','Improve satisfaction','Reduce turnover and add roles'])assert.equal((await draft(goal)).inputs.whatIf,undefined);});
test('chat edits remain staged, reject ambiguous/invalid edits atomically, and invalidate results',async()=>{const d=await draft(),before=JSON.stringify(d),p=previewBundleChatEdit(d,'set baseline turnover to 18%; set target turnover to 10%; set average workforce to 200');assert.equal(JSON.stringify(d),before);const next=acceptBundleChatEdit(d,p),r=calculatePlanWhatIf(next.inputs);assert.equal(r.baselineCount,36);assert.equal(r.targetCount,20);assert.notEqual(bundleInputKey(next),bundleInputKey(d));assert.throws(()=>previewBundleChatEdit(d,'set target turnover to 101%'));assert.throws(()=>previewBundleChatEdit(d,'set turnover to 10%'));assert.equal(previewBundleChatEdit(d,'set budget to 5000').inputs.budget.amount.value,5000);assert.equal(JSON.stringify(d),before);});
test('scope changes require explicit outcome-scope confirmation; zero and unknown remain distinct',async()=>{let d=await draft();d=acceptBundleChatEdit(d,previewBundleChatEdit(d,'make it four months'));assert.equal(calculatePlanWhatIf(d.inputs).status,'scope_changed');d=acceptBundleChatEdit(d,previewBundleChatEdit(d,'use this period for the what-if'));assert.equal(calculatePlanWhatIf(d.inputs).months,4);d=acceptBundleChatEdit(d,previewBundleChatEdit(d,'set target turnover to 0%'));assert.equal(calculatePlanWhatIf(d.inputs).targetCount,0);d=acceptBundleChatEdit(d,previewBundleChatEdit(d,'set target turnover to Unknown'));assert.equal(calculatePlanWhatIf(d.inputs).status,'missing');});
test('reviewed result and its assumptions survive attachment/reload without rewriting history',async()=>{const d=await draft(),r=reconcileBundle(d);let store=saveBundleCalculationPatch(undefined,d,r).value;store=attachBundlePatch(store,d,{confirmed:true,bindingKey:actionBindingKey(d.binding),inputKey:bundleInputKey(d),acknowledgeUnknowns:true},'attachment','2026-10-05T00:00:00Z').value;const original=JSON.stringify(store.attachments[0]),next=acceptBundleChatEdit(d,previewBundleChatEdit(d,'set target turnover to 9%'));store=saveBundleCalculationPatch(store,next,reconcileBundle(next)).value;assert.equal(JSON.stringify(store.attachments[0]),original);assert.equal(readBundleWorkspace(JSON.parse(JSON.stringify(store)),'scenario').attachments[0].result.whatIf.target,12);const malformed=structuredClone(d);malformed.inputs.whatIf.target.kind='adopted';assert.equal(readBundleDraft(malformed),null);});
test('explicit goal assumptions take priority without being relabeled observed',async()=>{const d=await draft('Add 1 additional role over 12 months at $7,000 per role per month');assert.equal(d.inputs.whatIf.unitCost.value,7000);assert.equal(d.inputs.whatIf.unitCost.kind,'user-entered');assert.equal(calculatePlanWhatIf(d.inputs).roleCash,84000);const r=await draft('Reduce turnover by 20% relative; baseline turnover is 18%');assert.equal(r.inputs.whatIf.baseline.value,18);assert.equal(r.inputs.whatIf.target.value,14.4);assert.equal(r.inputs.whatIf.baseline.kind,'user-entered');assert.deepEqual(prepareIllustrativePilot(r,'2027-01-01T00:00:00Z'),r);});

test('number words retain explicit quantities and conflicting rate statements require clarification',async()=>{const d=await draft('Add five additional roles over twelve months');assert.equal(d.inputs.whatIf.target.value,5);assert.equal(d.inputs.scope.months.value,12);assert.equal(calculatePlanWhatIf((await draft('Reduce turnover by 20% relative; target turnover is 9%')).inputs).status,'missing');});
