import test from 'node:test';
import assert from 'node:assert/strict';
import {readHomeCandidateProposal,readHomeCandidateRecord,candidateSourceKey} from '../lib/home-candidate-options.ts';
import {decodeHomeModelReply} from '../lib/home-chat-reply.ts';
const pack={version:1,workforceScope:'Synthetic',sources:[{id:'W1',status:'loaded',facts:{workforce:12}},{id:'X1',status:'unavailable',facts:null},{id:'T1',status:'loaded',facts:{count:null}}]};
const option={title:'Investigate internal capacity',outcome:'Assess available capacity against the goal',why:'The workforce snapshot supports reviewing the current team.',source_ids:['W1']};
const proposal={version:1,problem:'Investigate additional engineering capacity',options:[option],question:null};
test('bounded qualitative proposal retains exact problem and supplied source',()=>assert.deepEqual(readHomeCandidateProposal(proposal,pack),proposal));
test('candidate failure preserves ordinary answer and old prose never becomes cards',()=>{for(const fields of [{},{...proposal,options:[{...option,source_ids:['FAKE']}]},{...proposal,options:[{...option,cost:0}]}]){const decoded=decodeHomeModelReply(JSON.stringify({answer:'Keep this ordinary answer [W1].',next_step:'none',...fields}),false,pack);assert.equal(decoded.answer,'Keep this ordinary answer [W1].');assert.equal(decoded.candidateProposal,null)}});
test('reject unknown, unavailable and all-unknown source references',()=>{for(const id of ['X1','T1','FAKE'])assert.equal(readHomeCandidateProposal({...proposal,options:[{...option,source_ids:[id]}]},pack),null);assert.equal(readHomeCandidateProposal(proposal,null),null)});
test('reject quantified predictions, efficacy claims and extra model fields',()=>{for(const field of ['title','outcome','why'])for(const text of ['Test saving 10%','Test saving ten percent','Test costs $100','Test this will improve retention','Test a proven effect'])assert.equal(readHomeCandidateProposal({...proposal,options:[{...option,[field]:text}]},pack),null);assert.equal(readHomeCandidateProposal({...proposal,options:[{...option,staffing:'ready'}]},pack),null)});
test('no fixed cardinality; de-duplicate without manufacturing alternatives',()=>{assert.equal(readHomeCandidateProposal({...proposal,options:[option,{...option}]},pack).options.length,1);assert.equal(readHomeCandidateProposal({...proposal,options:Array(4).fill(option)},pack),null);assert.equal(readHomeCandidateProposal({...proposal,options:[]},pack),null);assert.equal(readHomeCandidateProposal({...proposal,options:[],question:'What outcome matters most?'},pack).options.length,0)});
test('one bounded clarification and bounded proposal text',()=>{for(const question of ['What? When?','x'.repeat(201),''])assert.equal(readHomeCandidateProposal({...proposal,question},pack),null);assert.equal(readHomeCandidateProposal({...proposal,problem:'x'.repeat(241)},pack),null)});
test('saved candidates bind exact goal, version and source snapshot without migration',()=>{const record={version:1,goalId:'a',goal:proposal.problem,selectionGoal:'Original selection',sourceKey:candidateSourceKey(pack),proposal};assert.deepEqual(readHomeCandidateRecord(record,'a',proposal.problem,pack),record);for(const changed of [{...record,version:2},{...record,goalId:'b'},{...record,goal:proposal.problem+' changed'},{...record,sourceKey:'old'},{...record,selectionGoal:'x'.repeat(12001)}])assert.equal(readHomeCandidateRecord(changed,'a',proposal.problem,pack),null);assert.equal(readHomeCandidateRecord(record,'a',proposal.problem,{...pack,workforceScope:'Other'}),null);assert.equal(readHomeCandidateRecord(record,'a',proposal.problem,{...pack,sources:[{...pack.sources[0],facts:{workforce:13}}]}),null);assert.equal(record.version,1)});

test('source identity survives server normalization of the existing packet',async()=>{const {buildHomePack,normalizeHomePack}=await import('../lib/home-pack.mjs');const original=buildHomePack({dashboard:{status:'loaded',data:{overview:{headcount:12,snapshot_date:'2026-09-30'}}}},'Synthetic','Engineering',{});assert.equal(candidateSourceKey(original),candidateSourceKey(normalizeHomePack(original)));assert.ok(readHomeCandidateProposal(proposal,normalizeHomePack(original)))});
test('schema-valid empty discovery output is not a prepared problem despite qualified prose',()=>{const answer='A recorded workforce pattern is worth investigating, not a proven problem. [W1]';const reply=decodeHomeModelReply(JSON.stringify({answer,next_step:'choose_goal',problem:null,options:[],question:null}),false,pack);assert.equal(reply.answer,answer);assert.equal(reply.candidateProposal,null);assert.equal(reply.nextStep,'choose_goal')});
test('a well-written discovery answer cannot rescue invalid structured options',()=>{const answer='Investigate capacity using the supplied workforce snapshot. [W1]';const reply=decodeHomeModelReply(JSON.stringify({answer,next_step:'none',...proposal,options:[{...option,why:'The pattern is not proof of a cause.'}]}),false,pack);assert.equal(reply.answer,answer);assert.equal(reply.candidateProposal,null)});
test('valid raw model discovery fields prepare the exact provisional problem',()=>{const reply=decodeHomeModelReply(JSON.stringify({answer:'Review the supported investigation. [W1]',next_step:'none',problem:proposal.problem,options:proposal.options,question:null}),false,pack);assert.deepEqual(reply.candidateProposal,proposal);assert.equal(reply.nextStep,'none')});

test('a validated problem wins over a conflicting choose-goal hint',()=>{const reply=decodeHomeModelReply(JSON.stringify({answer:'Review this investigation.',next_step:'choose_goal',...proposal}),false,pack);assert.deepEqual(reply.candidateProposal,proposal);assert.equal(reply.nextStep,'none')});
