import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs/promises';import os from 'node:os';import path from 'node:path';import vm from 'node:vm';import {createRequire} from 'node:module';import webpackPackage from 'next/dist/compiled/webpack/webpack.js';
const require=createRequire(import.meta.url),out=await fs.mkdtemp(path.join(os.tmpdir(),'post175-dashboard-route-')),isolation=path.resolve('tests/fixtures/dashboard-route-isolation.ts');
const compiler=webpackPackage.webpack({mode:'development',devtool:false,target:'node',entry:path.resolve('app/api/dashboard/route.ts'),output:{path:out,filename:'route.cjs',library:{type:'commonjs2'}},resolve:{extensions:['.ts','.mjs','.js'],alias:{'next/server$':isolation,'../../../lib/supabase-server$':isolation}},module:{rules:[{test:/\.ts$/,exclude:/node_modules/,use:path.resolve('tests/fixtures/typescript-browser-loader.mjs')}]}});
await new Promise((resolve,reject)=>compiler.run((error,stats)=>compiler.close(()=>error?reject(error):stats.hasErrors()?reject(Error(stats.toString({all:false,errors:true}))):resolve())));
const sandbox={exports:{},require,Response,URL,URLSearchParams,console,__dashboardCalls:[],__dashboardPayload:null,__dashboardError:null};sandbox.module={exports:sandbox.exports};vm.runInNewContext(await fs.readFile(path.join(out,'route.cjs'),'utf8'),sandbox);
const fixture=()=>({overview:{snapshot_date:'2026-09-30',headcount:130,fte:129.8,voluntary_turnover_ytd_pct:3.2},trend:[{snapshot_date:'2026-09-30',headcount:130,fte:129.8}],filter_options:{countries:[{value:'US',label:'United States'}],business_units:[{value:'BU-DATAAI',label:'Data & AI'}],levels:[{value:'IC2',label:'Analyst / Specialist'}]}});
const get=async(raw,query,error=null)=>{sandbox.__dashboardPayload=raw;sandbox.__dashboardCalls=[];sandbox.__dashboardError=error;const response=await sandbox.module.exports.GET({nextUrl:new URL('http://fixture.invalid/api/dashboard?'+query)});return {response,data:await response.json(),calls:JSON.parse(JSON.stringify(sandbox.__dashboardCalls))}};
test('actual dashboard GET dispatches all three verified scalar filters and returns effective catalogue scope',async()=>{
 const {response,data,calls}=await get(fixture(),'country=US&org=BU-DATAAI&level=IC2');assert.equal(response.status,200);assert.equal(response.headers.get('cache-control'),'no-store');assert.deepEqual(calls,[{name:'dashboard_overview_filtered',args:{p_country_code:'US',p_org_code:'BU-DATAAI',p_level_code:'IC2'}}]);assert.equal(data.workforce_filter_scope.label,'United States; Data & AI; Analyst / Specialist');assert.equal(data.overview.headcount,130);assert.equal(data.performance_rating,null);
});
test('actual dashboard GET suppresses unsupported codes, contradictory echo and absent observations',async()=>{
 for(const [raw,query,status] of [[fixture(),'country=ZZ','unsupported'],[{...fixture(),applied_filters:{country:'CA',org:'BU-DATAAI',level:'IC2'}},'country=US&org=BU-DATAAI&level=IC2','mismatch'],[{...fixture(),trend:[],overview:{...fixture().overview,headcount:0,voluntary_turnover_ytd_pct:0}},'country=US','unavailable']]){
  const {response,data,calls}=await get(raw,query);assert.equal(response.status,200);assert.equal(data.workforce_filter_scope.status,status);assert.equal(data.workforce_filter_scope.effective,null);assert.equal(data.overview,null);assert.deepEqual(data.trend,[]);assert.equal(data.performance_rating,null);assert.equal(calls.length,1);
 }
});
test('actual dashboard GET preserves all-filter semantics and source errors stay errors, not zeros',async()=>{
 const ok=await get(fixture(),'country=all&org=all&level=all');assert.deepEqual(ok.calls[0].args,{p_country_code:null,p_org_code:null,p_level_code:null});assert.equal(ok.data.workforce_filter_scope.label,'All countries; All business units; All levels');
 const failed=await get(null,'country=US',{message:'Synthetic denied evidence'});assert.equal(failed.response.status,500);assert.equal(failed.data.overview,undefined);assert.equal(failed.data.workforce_filter_scope,undefined);
});
