import test from 'node:test';
import assert from 'node:assert/strict';
import {DecisionStore,DECISIONS_STORAGE_KEY,parseDecisions,encodeDecisions,validateJson} from '../lib/local-decisions.ts';
const legacy={version:1,activeId:'a',goals:[{id:'a',statement:'Goal A'},{id:'b',statement:'Goal B'}]};
function port(){const map=new Map([['insights-to-action.goals.v1',JSON.stringify(legacy)]]);return {map,getItem:k=>map.get(k)??null,setItem:(k,v)=>map.set(k,v),removeItem:k=>map.delete(k)}}
function setup(){const p=port(),s=new DecisionStore();s.initialize(p);return {p,s}}
test('legacy goals migrate without changing IDs or the legacy copy',()=>{const {p,s}=setup();assert.deepEqual(s.getSnapshot().data.goals,legacy);assert.equal(p.getItem('insights-to-action.goals.v1'),JSON.stringify(legacy));assert.equal(s.getSnapshot().saved,true)});
test('conversation, source versions and independent scenario inputs survive a fresh store',()=>{const {p,s}=setup();s.setField('a','chat',{messages:[{role:'user',content:'A private draft'}],input:'continue',problem:null});s.setField('a','evidence',[{source:'BLS',period:'May 2025'}]);s.setField('a','planning.customAssumptions',{annual_growth_pct:0});s.setField('b','planning.customAssumptions',{annual_growth_pct:5});const reopened=new DecisionStore();reopened.initialize(p);assert.equal(reopened.getField('a','chat',null).messages[0].content,'A private draft');assert.equal(reopened.getField('b','chat',null),null);assert.equal(reopened.getField('a','planning.customAssumptions',null).annual_growth_pct,0);assert.equal(reopened.getField('b','planning.customAssumptions',null).annual_growth_pct,5);assert.equal(reopened.getField('a','evidence',[])[0].period,'May 2025')});
test('deleting one goal removes only its records',()=>{const {p,s}=setup();s.setField('a','draft','A');s.setField('b','draft','B');s.saveGoals({...legacy,activeId:'b',goals:[legacy.goals[1]]});const data=parseDecisions(p.getItem(DECISIONS_STORAGE_KEY));assert.equal(data.workspaces.a,undefined);assert.equal(data.workspaces.b.fields.draft,'B');assert.deepEqual(JSON.parse(p.getItem('insights-to-action.goals.v1')).goals,[legacy.goals[1]]);s.setField('a','draft','late result');assert.equal(s.getField('a','draft',null),null)});
test('quota failure keeps prior persisted bytes and current working copy',()=>{const {p,s}=setup();s.setField('a','draft','saved');const before=p.getItem(DECISIONS_STORAGE_KEY);p.setItem=()=>{throw Error('Quota exceeded')};s.setField('a','draft','unsaved');assert.equal(s.getSnapshot().saved,false);assert.match(s.getSnapshot().notice,/Quota/);assert.equal(s.getField('a','draft',null),'unsaved');assert.equal(p.getItem(DECISIONS_STORAGE_KEY),before)});
test('storage unavailable remains visibly unsaved without crashing',()=>{const s=new DecisionStore();s.initialize({getItem:()=>{throw Error('Storage denied')},setItem:()=>assert.fail(),removeItem:()=>assert.fail()});assert.equal(s.getSnapshot().ready,true);assert.equal(s.getSnapshot().saved,false);assert.match(s.getSnapshot().notice,/denied/)});
test('corrupt and newer records are not overwritten by subsequent editing',()=>{for(const raw of ['broken',JSON.stringify({payload:{version:99},checksum:'bad'})]){const p=port();p.map.set(DECISIONS_STORAGE_KEY,raw);const s=new DecisionStore();s.initialize(p);s.saveGoals(legacy);s.setField('a','draft','working only');assert.equal(p.getItem(DECISIONS_STORAGE_KEY),raw);assert.equal(s.getSnapshot().saved,false)}});
test('checksum detects well-formed accidental value corruption',()=>{const {p}=setup();const raw=JSON.parse(p.getItem(DECISIONS_STORAGE_KEY));raw.payload.goals.goals[0].statement='Changed';assert.throws(()=>parseDecisions(JSON.stringify(raw)),/corrupt/)});
test('cross-tab conflict never overwrites the other tab',()=>{const {p,s}=setup();const other=new DecisionStore();other.initialize(p);s.setField('a','draft','tab one');const before=p.getItem(DECISIONS_STORAGE_KEY);other.setField('b','draft','tab two');assert.equal(p.getItem(DECISIONS_STORAGE_KEY),before);assert.match(other.getSnapshot().notice,/Another tab/)});
test('message limit stops persistence without dropping old or new working messages',()=>{const {p,s}=setup();const before=p.getItem(DECISIONS_STORAGE_KEY);const messages=Array.from({length:201},(_,i)=>({role:'user',content:String(i)}));s.setField('a','chat',{messages,input:'',problem:null});assert.equal(s.getField('a','chat',null).messages.length,201);assert.equal(p.getItem(DECISIONS_STORAGE_KEY),before);assert.match(s.getSnapshot().notice,/200-message/)});
test('invalid numbers and prototype keys are rejected',()=>{assert.equal(validateJson({n:Infinity}),false);assert.equal(validateJson(JSON.parse('{"__proto__":{}}')),false);const {s}=setup();s.setField('a','value',NaN);assert.equal(s.getField('a','value',null),null);assert.equal(s.getSnapshot().saved,false)});
test('oversized decision retains its working copy with a visible save failure',()=>{const {p,s}=setup(),before=p.getItem(DECISIONS_STORAGE_KEY);s.setField('a','big',Array.from({length:4},()=> 'x'.repeat(150000)));assert.equal(p.getItem(DECISIONS_STORAGE_KEY),before);assert.match(s.getSnapshot().notice,/512 KiB/);assert.equal(s.getField('a','big',[]).length,4)});
test('clear all writes an empty record and removes legacy goal fallback',()=>{const {p,s}=setup();s.setField('a','draft','saved');s.clearAll();assert.deepEqual(parseDecisions(p.getItem(DECISIONS_STORAGE_KEY)).goals.goals,[]);assert.equal(p.getItem('insights-to-action.goals.v1'),null)});

test('retry saves the intact working copy after storage becomes writable',()=>{const {p,s}=setup();const original=p.setItem;p.setItem=()=>{throw Error('Quota exceeded')};s.setField('a','draft','working copy');assert.equal(s.getSnapshot().saved,false);p.setItem=original;s.retry();assert.equal(s.getSnapshot().saved,true);assert.equal(parseDecisions(p.getItem(DECISIONS_STORAGE_KEY)).workspaces.a.fields.draft,'working copy')});

test('legacy cleanup failure is visible and retry removes only the deleted goal',()=>{const {p,s}=setup();const set=p.setItem;p.setItem=(k,v)=>{if(k==='insights-to-action.goals.v1')throw Error('Legacy cleanup denied');return set(k,v)};s.saveGoals({...legacy,activeId:'b',goals:[legacy.goals[1]]});assert.equal(s.getSnapshot().saved,false);assert.match(s.getSnapshot().notice,/cleanup/);assert.equal(parseDecisions(p.getItem(DECISIONS_STORAGE_KEY)).goals.goals.length,1);const reopened=new DecisionStore();reopened.initialize(p);assert.equal(reopened.getSnapshot().saved,false);p.setItem=set;reopened.retry();assert.equal(reopened.getSnapshot().saved,true);assert.deepEqual(JSON.parse(p.getItem('insights-to-action.goals.v1')).goals,[legacy.goals[1]])});
