import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {fileURLToPath} from 'node:url';
import {unarmedManifest,validateManifest,reservationAmount,runAcceptance,limits,apiBase,modelPayload,sha256} from './helpers/swp-preview-acceptance.mjs';
import {fixture,scenarioRequest} from './fixtures/swp-preview-scenario.mjs';
import {illustrativeServiceReview} from '../lib/swp-demand.ts';
import {encodeReceipt,decodeReceipt} from './helpers/swp-preview-receipt-log.mjs';
const root=fileURLToPath(new URL('../',import.meta.url)),clock=Date.parse(fixture.clock),guardFetch=globalThis.fetch;globalThis.fetch=()=>{throw Error('Network forbidden in offline tests');};
process.on('exit',()=>{globalThis.fetch=guardFetch;});
function armed(){const m=unarmedManifest(root);Object.assign(m,{parentReserved:true,pricingApprovalPending:false,runId:'11111111-1111-4111-8111-111111111111',reservationId:'22222222-2222-4222-8222-222222222222',trancheAuthorization:'parent-offline-fixture-only',projectId:'prj_fixture',createdAt:fixture.clock,expiresAt:'2026-10-08T13:00:00.000Z'});m.model.testedConfigReceiptSha256='a'.repeat(64);m.pricing={basis:'TEST ONLY invented rates, never a Sol pricing receipt',inputUsdPerMillion:1,outputUsdPerMillion:2,countAllowanceMicrousd:1000};m.reservedMicrousd=reservationAmount(m.pricing);m.trancheCapMicrousd=m.reservedMicrousd;return m;}
const env=m=>({VERCEL:'1',VERCEL_ENV:'preview',VERCEL_PROJECT_ID:m.projectId,VERCEL_DEPLOYMENT_ID:'dpl_fixture',SOLUTION_ACCEPTANCE_RUN_ID:m.runId,SWP_DEMO_MODEL_PROFILE:m.model.profile,SWP_DEMO_MODEL_ID:m.model.id});
const answer={verifiedMetrics:[],answer:'These are provisional assumptions; internal release, readiness, funding and service outcomes remain unverified.',candidateIds:[],analysisIds:[],questions:[],constraintUpdates:[],rejected:[],focusCandidateId:null};
function fakeClient({fullRounds=false,failCount=false,failGeneration=false,oversizedCount=false,badTier=false,longObjective=false}={}){let countCalls=0,generationCalls=0;const perTurn=new Map(),payloads=[];
 const wrapped=fn=>({withResponse:async()=>({data:await fn(),response:{status:200},request_id:'req_fixture'})});
 return {baseURL:apiBase,payloads,get calls(){return {countCalls,generationCalls};},responses:{inputTokens:{count:(payload,options)=>wrapped(()=>{countCalls++;assert.equal(options.maxRetries,0);if(failCount)throw Object.assign(Error('Not returned raw'),{status:401});return {object:'response.input_tokens',input_tokens:oversizedCount?100001:2000};})},create:(payload,options)=>wrapped(()=>{generationCalls++;assert.equal(options.maxRetries,0);assert.equal(payload.max_output_tokens,5000);assert.equal(payload.service_tier,'default');assert.equal(payload.reasoning.effort,'medium');assert.equal(payload.temperature,undefined);assert.equal(payload.top_p,undefined);payloads.push(payload);if(failGeneration)throw Object.assign(Error('Not returned raw'),{status:429});const data=JSON.parse(payload.input[0].content.split('\n').slice(1).join('\n')),id=data.currentMessage.id,index=Number(id.split('-').at(-1))-1,round=(perTurn.get(id)??0)+1;perTurn.set(id,round);let call;
 const finalRound=fullRounds?4:2;
 if(round<finalRound){if(fullRounds&&round<3)call={name:'read_clock',args:{}};else if(index===0){const c=data.goalContext.scenarioReview,spec=illustrativeServiceReview(c,fixture.clock).spec;spec.objective=longObjective?'We are considering two new managed-services contracts next year. Could our teams cover the client-operations work? Use proposed assumptions where effort and capacity are unknown.':data.currentMessage.text;spec.objectiveTurnId=id;for(const v of Object.values(spec)){if(v?.kind==='illustrative')v.kind='model-proposed';if(v?.basis?.kind==='illustrative')v.basis.kind='model-proposed';}call={name:'review_service_demand',args:{spec}};}else{const r=data.goalContext.scenarioReview.demandProposal,basis={kind:'user-supplied',turnId:id,quote:data.currentMessage.text,explanation:'Explicit fictional user edit, not verified.'},fields=index===1?['months']:['existingRoles','availabilityPct'];call={name:'revise_service_demand',args:{edit:{baseKey:r.key,changes:fields.map(field=>({field,quantity:field==='months'?null:{...r.spec[field],value:field==='existingRoles'?4:25,basis},number:field==='months'?9:null,text:null,basis}))}}};}}
 const output=call?[{type:'function_call',call_id:'call-'+generationCalls,name:call.name,arguments:JSON.stringify(call.args)}]:[];return {status:'completed',service_tier:badTier?'priority':'default',usage:{input_tokens:2000,output_tokens:300},output,output_text:call?'':JSON.stringify(answer)};
 })}};}
async function run(options={}){const m=armed(),client=fakeClient(options),records=[],claimed=[];let now=clock;const result=await runAcceptance({manifest:m,env:env(m),client,claim:()=>claimed.push(true),record:(s,r)=>records.push({stage:s,...r}),now:()=>now,sleep:async ms=>{now+=ms;}});return {m,client,records,claimed,result};}
test('preparation stays unarmed with known model and a proposed envelope, no accepted receipt or tranche',()=>{const m=unarmedManifest(root);assert.equal(m.model.id,'gpt-6.1-sol');assert.equal(m.model.reasoning,'medium');assert.equal(m.parentReserved,false);assert.equal(m.pricingApprovalPending,true);assert.equal(m.reservedMicrousd,null);assert.equal(m.pricing.inputUsdPerMillion,5);assert.match(m.pricing.basis,/PROPOSED/);assert.equal(reservationAmount(m.pricing),18900000);assert.equal(m.model.testedConfigReceiptSha256,null);assert.throws(()=>validateManifest(m,env(m),clock));assert.equal(m.priorTotalMicrousd,11250960);assert.equal(m.files['app/api/home-solution-conversation/route.ts'],sha256(readFileSync(new URL('../app/api/home-solution-conversation/route.ts',import.meta.url))));});
test('three real-state fixture turns recalculate only intended fields and exclude double counting',async()=>{const r=await run();assert.equal(r.result.executionComplete,true,JSON.stringify({failure:r.result.failure,last:r.records.at(-2)}));assert.equal(r.result.fullAcceptance,false);assert.equal(r.result.semanticReview,'pending');assert.deepEqual(r.client.calls,{countCalls:6,generationCalls:6});assert.equal(r.result.projectionReads,0);assert.equal(r.claimed.length,1);const final=r.records.find(v=>v.stage==='local-acceptance-3'),review=JSON.parse(final.review.text);assert.equal(review.spec.months,9);assert.equal(review.spec.existingRoles.value,4);assert.equal(review.spec.availabilityPct.value,25);assert.equal(review.spec.startBasis.kind,'model-proposed');assert.equal(review.result.additionalRoles,4);assert(final.comparison.every(o=>o.mix.build===0&&o.mix.move===0));assert.equal(final.goalSaved,false);assert.deepEqual(decodeReceipt(encodeReceipt('fixture',final)).receipt,final);});
test('worst four rounds each turn saturates exactly12+12 calls without an automatic extension',async()=>{const r=await run({fullRounds:true});assert.equal(r.result.executionComplete,true,JSON.stringify({failure:r.result.failure,last:r.records.at(-2)}));assert.deepEqual(r.client.calls,{countCalls:12,generationCalls:12});assert.equal(r.result.reservedMicrousd,r.m.reservedMicrousd);});
test('count, generation, count-bound and tier failures stop all later turns without retries or refund',async()=>{for(const options of [{failCount:true},{failGeneration:true},{oversizedCount:true},{badTier:true}]){const r=await run(options);assert.equal(r.result.executionComplete,false);assert.equal(r.result.completedTurns.length,0);assert.equal(r.client.calls.countCalls,1);assert.equal(r.client.calls.generationCalls,options.failCount||options.oversizedCount?0:1);assert.equal(r.result.reservedMicrousd,r.m.reservedMicrousd);assert.equal(r.result.retainedCumulativeMicrousd,11250960+r.m.reservedMicrousd);}});
test('changed model, receipt, source identity, reservation, pricing and environment fail before claim',async()=>{for(const mutate of [m=>m.pricingApprovalPending=true,m=>m.model.id='gpt-5.6-luna',m=>m.model.testedConfigReceiptSha256=null,m=>m.application={...m.application,commit:'0'.repeat(40)},m=>m.reservedMicrousd--,m=>m.priorTotalMicrousd=0,m=>m.trancheCapMicrousd=50000000,m=>m.pricing.inputUsdPerMillion=null,m=>m.expiresAt=m.createdAt]){const m=armed();mutate(m);await assert.rejects(()=>runAcceptance({manifest:m,env:env(m),client:fakeClient(),claim:()=>assert.fail('claim must not run'),record:()=>{},now:()=>clock}));}const m=armed();assert.throws(()=>validateManifest(m,{...env(m),VERCEL_ENV:'production'},clock));assert.throws(()=>validateManifest(m,{...env(m),OPENAI_BASE_URL:'alternate'},clock));});
test('payload matches scoped application config and exposes only bounded read/demand tools',()=>{const p=modelPayload(scenarioRequest(0),[],false,'gpt-6.1-sol');assert.deepEqual(p.tools.map(t=>t.name),['read_clock','read_evidence','review_service_demand','revise_service_demand']);assert.equal(p.model,'gpt-6.1-sol');assert.deepEqual(p.reasoning,{effort:'medium'});assert(!Object.hasOwn(p,'temperature'));assert.equal(limits.generationCalls*limits.inputTokensPerCall,1200000);assert.equal(limits.generationCalls*limits.outputTokensPerCall,60000);});
test('persistence failure prevents next provider call; abort prevents any dispatch',async()=>{const m=armed(),client=fakeClient();await assert.rejects(()=>runAcceptance({manifest:m,env:env(m),client,claim:()=>{},record:()=>{throw Error('disk unavailable');},now:()=>clock}));assert.deepEqual(client.calls,{countCalls:0,generationCalls:0});const ac=new AbortController();ac.abort();const report=await runAcceptance({manifest:m,env:env(m),client,claim:()=>{},record:()=>{},now:()=>clock,signal:ac.signal});assert.equal(report.executionComplete,false);assert.deepEqual(client.calls,{countCalls:0,generationCalls:0});});

test('frozen long-objective limit stops with its failure receipt without truncation or continuation',async()=>{const r=await run({longObjective:true});assert.equal(r.result.executionComplete,false);assert.equal(r.result.failure.stage,'checks');assert.match(r.result.failure.localDiagnostic.text,/Supply a reviewed value/);assert.equal(r.result.completedTurns.length,0);assert.deepEqual(r.client.calls,{countCalls:2,generationCalls:2});const receipt=r.records.find(v=>v.stage==='tool-1-1');assert(receipt.result.text.includes('Use proposed assumptions where effort and capacity are unknown.'));assert.equal(r.result.fullAcceptance,false);});

test('fixture carries no workforce facts or inherited provider quote catalogue',()=>{const request=scenarioRequest(0),pack=request.evidence;assert.equal(pack.coverage.available,0);assert.equal(pack.sources.length,pack.coverage.total);assert(pack.sources.every(source=>source.facts===null));assert(!/Cedar|Lantern|Harbor/.test(JSON.stringify(request)));});
