import test from 'node:test';import assert from 'node:assert/strict';import {readFile} from 'node:fs/promises';
import {resolveWorkforcePerformance} from '../lib/workforce-performance.ts';
const filters={country:'all',org:'all',level:'all'};
const valid={source:'employee_snapshots.performance_rating',snapshotDate:'2026-09-30',reviewPeriod:'2026 YTD',periodKind:'ytd',filters,status:'available',counts:{population:70,ratings:[10,10,10,10,10],notRated:10,unavailable:10}};
test('ratings contract uses complete same-population counts without semantic thresholds',()=>{assert.deepEqual(resolveWorkforcePerformance(valid,filters),valid);assert.equal(resolveWorkforcePerformance(null,filters),null)});
test('changed top filters reject previous selection before replacement arrives',()=>{for(const key of Object.keys(filters))assert.equal(resolveWorkforcePerformance(valid,{...filters,[key]:'changed'}),null)});
test('unknown, suppressed, small and malformed data cannot become ratings or zero',()=>{for(const value of [{...valid,source:'demo'}, {...valid,periodKind:'annual'}, {...valid,employee_id:123}, {...valid,status:'suppressed'}, {...valid,counts:{...valid.counts,ratings:[1,19,10,10,10]}}, {...valid,counts:{...valid.counts,population:71}}, {...valid,counts:{...valid.counts,ratings:[10,10,10,10,NaN]}}])assert.equal(resolveWorkforcePerformance(value,filters),null);for(const status of ['unavailable','suppressed'])assert.equal(resolveWorkforcePerformance({...valid,status,counts:null},filters)?.counts,null)});
test('integration reuses dashboard response, top filters and request guard without new source access',async()=>{const [app,route,page]=await Promise.all(['app/page.tsx','app/api/dashboard/route.ts','components/pages/career-growth-mobility-page.tsx'].map(p=>readFile(p,'utf8')));assert.match(app,/setWorkforcePerformance\(null\)/);assert.match(app,/performanceFilters=\{\{ country: selectedCountry, org: selectedOrg, level: selectedLevel \}\}/);assert.match(app,/requestId !== dashboardRequestIdRef.current/);assert.doesNotMatch(route,/performance_reviews|workforce_performance|\.from\(/);assert.doesNotMatch(page,/SyntheticCareerDemoPanel/)});
test('proposal neither backfills protected ratings nor modifies grants/RLS',async()=>{const sql=await readFile('database/workforce_performance_rating.proposed.sql','utf8');assert.doesNotMatch(sql,/\b(grant|revoke|security definer|create policy|disable row|update public|insert into)\b/i);assert.match(sql,/add column performance_rating smallint/)});

test('rating counts must match the dashboard workforce denominator when provided',()=>{assert.equal(resolveWorkforcePerformance(valid,filters,5000),null);assert.equal(resolveWorkforcePerformance(valid,filters,null),null);assert.deepEqual(resolveWorkforcePerformance(valid,filters,70),valid)});
