import test from 'node:test';import assert from 'node:assert/strict';
import {workloadFixture} from './fixtures/workload-capacity.mjs';
import {createWorkloadIllustration} from '../lib/workload-capacity-illustration.ts';
import {calculateWorkloadCapacity} from '../lib/workload-capacity.ts';
import {workloadValues,previewWorkloadValues,workloadChatChange} from '../lib/workload-capacity-edit.ts';
test('configured illustrative factory shares reviewed calculator and current binding',async()=>{const f=await workloadFixture(),i=createWorkloadIllustration(f.identity,f.currentBinding),r=calculateWorkloadCapacity(i);assert.deepEqual(r.options.map(o=>o.cash),[228400,156800]);assert.equal(i.workload.minutesPerTicket.kind,'illustrative');assert.equal(i.profile.code,'OPS-CLIENT');});
test('chat preview preserves untouched provenance and increments exact revision without mutation',async()=>{const i=await workloadFixture(),before=structuredClone(i),p=workloadChatChange(i,'Use 6000 tickets per month');assert.deepEqual(i,before);assert.equal(p.input.identity.revision,2);assert.ok(p.input.options.every(o=>o.draft.revision===2));assert.deepEqual(p.input.options[0].draft.inputs.capacity.origins,i.options[0].draft.inputs.capacity.origins);assert.deepEqual(p.input.workload.minutesPerTicket,i.workload.minutesPerTicket);assert.equal(p.input.workload.ticketsByMonth[0].kind,'user-entered');});
test('editor unknown is null, rejects invalid/unchanged and unsupported messages',async()=>{const i=await workloadFixture(),v=workloadValues(i),p=previewWorkloadValues(i,{...v,managerHours:''});assert.equal(p.input.managers[0].uncommittedHoursByMonth[0].value,null);assert.equal(calculateWorkloadCapacity(p.input).options[0].rows[0].managerGapHours,null);assert.throws(()=>previewWorkloadValues(i,v),/No assumption/);assert.throws(()=>previewWorkloadValues(i,{...v,tickets:'-1'}));for(const text of ['Use 50% graded readiness','Add a second manager pool','Start hires January 15'])assert.throws(()=>workloadChatChange(i,text),/unsupported|separate review/);});
test('focused route follows existing Planning catalog and URL conventions',async()=>{const {appNavigationSections,appPageMetadata}=await import('../lib/app-navigation.ts'),{appPageFromSearch,appPageHref}=await import('../lib/app-page-url.ts');assert.ok(appNavigationSections.find(s=>s.key==='strategy').pages.includes('workload-capacity'));assert.equal(appPageMetadata['workload-capacity'].status,'Limited preview');assert.equal(appPageFromSearch('?page=workload-capacity'),'workload-capacity');assert.equal(appPageHref({pathname:'/',search:'?goal=kept',hash:'#kept'},'workload-capacity'),'/?goal=kept&page=workload-capacity#kept');});
