"use client";
import {useEffect,useRef,useState} from "react";
import {decisionStore,useDecisionStorage} from "@/components/decision-store";
import {appendJourneyToBrief,emptyJourneyLimits,journeyFingerprint,prepareJourney,runCapabilityJourney,validateJourneySource,type JourneyLimits,type JourneyProposal,type JourneyRun} from "@/lib/capability-journey";
import {emptyDecisionBrief,type DecisionBrief} from "@/lib/decision-brief";
import type {DevelopmentSession} from "@/components/development-workspace";
import type {AppPage,ScenarioModelResponse} from "@/lib/types";
type Saved={limits:JourneyLimits;proposal:JourneyProposal|null;run:JourneyRun|null;imported:string[]};
const empty=():Saved=>({limits:emptyJourneyLimits(),proposal:null,run:null,imported:[]});
const button="min-h-10 rounded border px-3 py-2 text-sm font-medium disabled:opacity-50";
export function CapabilityJourney({goalId,goal,onNavigate}:{goalId:string;goal:string;onNavigate:(p:AppPage)=>void}){
 const storage=useDecisionStorage(),fields=storage.data.workspaces[goalId]?.fields??{};
 const saved=(fields.capabilityJourney as unknown as Saved|undefined)??empty();
 const options=(fields.development as unknown as DevelopmentSession|undefined)?.options??[];
 const [busy,setBusy]=useState(false),[error,setError]=useState(""),[trace,setTrace]=useState<string[]>([]);
 const controller=useRef<AbortController|null>(null);
 useEffect(()=>()=>controller.current?.abort(),[]);
 const current=()=>decisionStore.getField<Saved>(goalId,"capabilityJourney",empty());
 const persist=(patch:Partial<Saved>)=>decisionStore.setField(goalId,"capabilityJourney",{...current(),...patch});
 const fingerprint=journeyFingerprint(goal,options,saved.limits);
 const proposalCurrent=saved.proposal?.fingerprint===fingerprint;
 const runCurrent=saved.run?.proposal.fingerprint===fingerprint;
 const stillHere=(c:AbortController)=>!c.signal.aborted&&controller.current===c&&decisionStore.getSnapshot().data.goals.activeId===goalId&&decisionStore.getSnapshot().data.goals.goals.some(g=>g.id===goalId&&g.statement===goal);
 async function perform(kind:"prepare"|"run"){
  if(controller.current)return;
  const c=new AbortController();controller.current=c;setBusy(true);setError("");setTrace([]);
  const timer=setTimeout(()=>c.abort(new Error("Calculation timed out after 45 seconds; prior results retained.")),45000);
  try{
   if(kind==="prepare"){
    const r=await fetch("/api/scenario-modeler",{signal:c.signal,cache:"no-store"});if(!r.ok)throw Error("Existing scenario source unavailable. Prior results retained; try again later.");
    const source=validateJourneySource(await r.json()),proposal=prepareJourney(goal,options,saved.limits,source);
    if(stillHere(c)){persist({proposal});setTrace(["Existing scenario defaults read. Proposals prepared; no scenario calculation or allocation has run."])}
   }else{
    if(!proposalCurrent||!saved.proposal)throw Error("Inputs changed. Prepare and review proposals again.");
    const run=await runCapabilityJourney(saved.proposal,async(assumptions,signal)=>{const r=await fetch("/api/scenario-modeler",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({assumptions}),signal});if(!r.ok)throw Error("Existing scenario calculation failed. No replacement result saved.");return await r.json() as ScenarioModelResponse},c.signal,t=>{if(stillHere(c))setTrace(t)});
    if(stillHere(c))persist({run});
   }
  }catch(e){if(controller.current===c)setError(c.signal.aborted?(c.signal.reason instanceof Error?c.signal.reason.message:"Cancelled; prior saved results retained."):(e instanceof Error?e.message:"Calculation unavailable."))}
  finally{clearTimeout(timer);if(controller.current===c){controller.current=null;setBusy(false)}}
 }
 function append(){if(!saved.run||!runCurrent)return;try{const b=decisionStore.getField<DecisionBrief>(goalId,"brief",emptyDecisionBrief());const next=appendJourneyToBrief(b,saved.run);decisionStore.setField(goalId,"brief",next);persist({imported:[...saved.imported,saved.run.id].slice(-20)});setError("")}catch(e){setError((e as Error).message)}}
 return <details className="rounded-lg border border-primary/50 p-4" open><summary className="cursor-pointer text-lg font-semibold">Build AI capability without net headcount</summary>
 <p className="mt-3 text-sm">Guided planning prototype for your selected goal. A bounded rule-based workflow prepares fixed proposals, calculates, compares and optionally revises once. AI does not choose tools or revisions. It cannot establish AI proficiency or recommend people. Existing tools run only when you press Run bounded comparison.</p>
 <ol className="my-4 space-y-3 text-sm"><li><strong>1. Review evidence.</strong> Check recorded skills and the goal. An AI skill gap is not assumed. <button className={button} onClick={()=>onNavigate("skills")}>Review Skills evidence</button></li><li><strong>2. Select relevant options.</strong> Carry one or two quotes and enter participants, sessions, hours and known costs. Fictional quotes are examples, not validated AI programs. <button className={button} onClick={()=>onNavigate("training-coaching")}>Choose development quotes</button> <button className={button} onClick={()=>onNavigate("development-planning")}>Edit development inputs</button></li></ol>
 <p className="text-sm font-medium">3. Set comparison limits in {options[0]?.quote.currency??"the quote currency"}.</p><p className="mt-1 text-xs text-muted-foreground">Company scenario uses the synthetic enterprise Baseline; country, business-unit and level filters do not apply. Program totals include employee time value, which is not necessarily added cash spending. No exchange conversion or automatic cost ranking.</p>
 <fieldset disabled={busy} className="mt-3 grid gap-3 md:grid-cols-3">{([["budget","Total program budget incl. employee time (blank = unknown)"],["employeeHours","Maximum employee hours (blank = unknown)"],["minimumParticipants","Minimum required participants"]] as const).map(([k,label])=><label key={k} className="text-sm">{label}<input value={saved.limits[k]} maxLength={16} inputMode="decimal" className="mt-1 w-full rounded border bg-background p-2" onChange={e=>persist({limits:{...saved.limits,[k]:e.target.value}})}/></label>)}<label className="flex items-start gap-2 text-sm md:col-span-3"><input type="checkbox" checked={saved.limits.allowRevision} onChange={e=>persist({limits:{...saved.limits,allowRevision:e.target.checked}})}/>Allow one automatic cost/time revision: halve participants on the first over-limit option, rounded down but never below my minimum. Keep the original; stop even if still infeasible.</label></fieldset>
 <div className="mt-4 flex flex-wrap gap-2"><button className={button} disabled={busy||!options.length} onClick={()=>void perform("prepare")}>Prepare structured proposals</button><button className={button} disabled={busy||!proposalCurrent} onClick={()=>void perform("run")}>Run bounded comparison</button>{busy&&<button className={button} onClick={()=>controller.current?.abort(new Error("Cancelled; prior saved results retained."))}>Cancel comparison</button>}</div>
 <p className="mt-2 text-xs text-muted-foreground">Per preparation: one existing source read. Per run: one company-scenario request, up to three local development-cost evaluations, no AI-model calls. Stops after 45 seconds; switching goals or leaving this page cancels. No enrollment, staffing changes, external actions or backend writes.</p>
 {saved.proposal&&<section aria-label="Structured proposals" className="mt-4 rounded border p-3 text-sm"><h3 className="font-semibold">Review proposed assumptions {proposalCurrent?"":"(inputs changed; prepare again)"}</h3><p>Source as of {saved.proposal.source.as_of}. Annual growth 0%; productivity hiring reduction 0%. Retained baseline salary inflation {saved.proposal.assumptions.salary_inflation_pct}%, attrition {saved.proposal.assumptions.annual_attrition_pct}%, fill rate {saved.proposal.assumptions.fill_rate_pct}%. Zero growth is a model input, not a guarantee of flat headcount.</p>{saved.proposal.options.map((o,i)=><p className="mt-2" key={i}>{i+1}. {o.quote.provider} — {o.quote.provenance==="simulated"?"Fictional quote":"User-provided, unverified"}; {o.quote.focus}; {o.inputs.participants} participants × {o.inputs.sessions} sessions × {o.inputs.hours} hours. Fee {o.quote.currency} {o.inputs.fee||"unknown"} per {o.quote.basis} per session; additional fees {o.inputs.additionalFees||"unknown"}; loaded hourly cost {o.inputs.hourlyCost||"unknown"}.</p>)}</section>}
 {error&&<p role="alert" className="mt-3 text-sm text-destructive">{error}</p>}<p role="status" aria-live="polite" className="mt-2 text-sm">{busy?"Working within the stated call limit…":trace.at(-1)??""}</p>
 {saved.run&&<section aria-label="Journey comparison" className="mt-5 space-y-3"><h3 className="font-semibold">4. Review calculated comparison {runCurrent?"":"— historical inputs; prepare again to update"}</h3><p className="text-sm">Calculated {new Date(saved.run.completedAt).toLocaleString()}; synthetic source as of {saved.run.scenario.as_of}. Starting headcount {saved.run.scenario.summary.starting_headcount}; ending {saved.run.scenario.summary.modeled_end_headcount}. Final-month labor cost USD {saved.run.scenario.summary.modeled_end_labor_cost_usd.toLocaleString()} is separate from program costs and is not added to them.</p>{saved.run.candidates.map((c,i)=><article key={i} className="rounded border p-3 text-sm"><h4 className="font-semibold">{c.option.quote.provider}{c.revision?" — one-step revision":" — original"}: {c.status}</h4><p>{c.option.inputs.participants} participants; {c.cost.employeeHours??"unknown"} employee hours; {c.option.quote.currency} {c.cost.cashCost??"unknown"} cash cost; {c.option.quote.currency} {c.cost.timeCost??"unknown"} time value; {c.option.quote.currency} {c.cost.total??"unknown"} total.</p><ul className="mt-2 list-disc space-y-1 pl-5">{c.reasons.map(r=><li key={r}>{r}</li>)}</ul></article>)}<details><summary className="cursor-pointer text-sm font-medium">Calculation trace and retained inputs</summary><ol className="mt-2 list-decimal pl-5 text-xs">{saved.run.trace.map((t,i)=><li key={i}>{t}</li>)}</ol><pre className="mt-2 max-h-72 overflow-auto whitespace-pre-wrap break-words text-xs">{JSON.stringify({goal:saved.run.proposal.goal,source:saved.run.proposal.source,limits:saved.run.proposal.limits,assumptions:saved.run.scenario.assumptions,options:saved.run.candidates.map(c=>c.option)},null,2)}</pre></details><button className={button} disabled={busy||!runCurrent||saved.imported.includes(saved.run.id)} onClick={append}>{saved.imported.includes(saved.run.id)?"Comparison appended to brief":"Append reviewed comparison to brief"}</button><p className="text-xs text-muted-foreground">Adds labeled notes below without replacing your writing, owner or approvals. Constraint checks do not establish capability improvement or unchanged delivery capacity.</p></section>}
 </details>;
}
