"use client";
import {useState} from "react";
import {decisionStore,useDecisionStorage} from "@/components/decision-store";
import {briefFields,emptyDecisionBrief,recordExplicitApproval,type DecisionBrief as Brief} from "@/lib/decision-brief";
import {developmentCost,type DevelopmentOption} from "@/lib/development-costs";
import type {ProblemConversation} from "@/components/problem-conversation";
import type {ScenarioModelResponse} from "@/lib/types";
import {type Json} from "@/lib/local-decisions";
const readable=(s:string)=>s.replace(/-/g," ").replace(/\b\w/g,c=>c.toUpperCase());
export function DecisionBrief({conversation}:{conversation:ProblemConversation}){
 const storage=useDecisionStorage(),id=conversation.activeGoalId;
 const [approval,setApproval]=useState("");
 if(!id)return <section className="p-6"><h1 className="text-2xl font-semibold">Decision brief</h1><p className="mt-3">Select or create a goal above to keep a separate decision brief.</p></section>;
 const fields=storage.data.workspaces[id]?.fields??{};
 const brief=(fields.brief as unknown as Brief|undefined)??emptyDecisionBrief();
 const save=(next:Brief)=>decisionStore.setField(id,"brief",next);
 const refs=(fields.evidence??[]) as unknown as Array<{page:string;capturedAt:string;schemaVersion:number;evidence:Record<string,unknown>}>;
 const scenario=fields['planning.customScenario'] as unknown as ScenarioModelResponse|undefined;
 const development=fields.development as unknown as {options:DevelopmentOption[]}|undefined;
 const results=Object.keys(fields).filter(k=>k.startsWith('planning.')&&/Result$|customScenario$/.test(k)&&fields[k]);
 return <section aria-label="Decision brief" className="mx-auto max-w-5xl space-y-6 p-6"><header><h1 className="text-2xl font-semibold">Decision brief</h1><p className="mt-2 break-words font-medium">{conversation.focusedIssue}</p><p className="mt-2 text-sm text-muted-foreground">Your editable decision record. Notes are user-authored; evidence and calculations retain their own sources and dates. Nothing here approves or executes an action automatically.</p></header>
 <label className="block text-sm font-semibold">Decision owner (optional)<input value={brief.owner} maxLength={120} onChange={e=>save({...brief,owner:e.target.value})} className="mt-2 block w-full rounded border bg-background p-2 font-normal"/><span className="mt-1 block text-xs font-normal text-muted-foreground">Saved locally with this goal. Brief fields are not sent to AI automatically.</span></label>
 <div className="grid gap-5 md:grid-cols-2">{Object.entries(briefFields).map(([key,label])=><label key={key} className="block text-sm font-semibold">{label}<textarea rows={4} maxLength={3000} value={brief[key as keyof typeof briefFields]} onChange={e=>save({...brief,[key]:e.target.value})} className="mt-2 block w-full rounded border bg-background p-3 font-normal"/>{key==="observed"&&<span className="text-xs font-normal text-muted-foreground">Reference source, period and population. Company evidence is synthetic; BLS observations are real public data.</span>}{key==="calculations"&&<span className="text-xs font-normal text-muted-foreground">Your interpretation, separate from the calculated values below. Modeled costs are not realized results.</span>}{key==="proposals"&&<span className="text-xs font-normal text-muted-foreground">Options for review, not approved actions.</span>}</label>)}</div>
 <section aria-label="Explicit approvals" className="rounded-lg border p-4"><h2 className="text-lg font-semibold">Explicit approvals</h2><p className="mt-1 text-sm text-muted-foreground">Only statements you deliberately record below appear here. This is your local note, not an authorization workflow or proof of organizational approval.</p>{!brief.approvals.length&&<p className="my-3 text-sm">No approvals recorded.</p>}<ol className="my-3 space-y-2">{brief.approvals.map((item,i)=><li key={i} className="break-words text-sm">{item.text}<span className="ml-2 text-xs text-muted-foreground">Recorded {new Date(item.recordedAt).toLocaleDateString()}</span><button className="ml-3 min-h-9 text-primary underline" onClick={()=>save({...brief,approvals:brief.approvals.filter((_,n)=>n!==i)})}>Remove approval {i+1}</button></li>)}</ol><label className="block text-sm">Approval to record<textarea value={approval} onChange={e=>setApproval(e.target.value)} maxLength={1000} rows={2} className="mt-2 w-full rounded border bg-background p-2"/></label><button disabled={!approval.trim()||brief.approvals.length>=20} className="mt-2 min-h-10 rounded border px-3 font-semibold text-primary disabled:opacity-50" onClick={()=>{save(recordExplicitApproval(brief,approval,new Date().toISOString()));setApproval("")}}>Record this approval</button></section>
 <section aria-label="Saved calculations" className="rounded-lg border p-4"><h2 className="text-lg font-semibold">Saved calculations</h2><p className="mt-1 text-sm text-muted-foreground">Historical deterministic model outputs on synthetic company data, not predictions or approvals. Editing assumptions does not rerun a stored result. Run the relevant model explicitly to update it.</p>{!results.length&&!development?.options.length&&<p className="mt-3 text-sm">No completed calculations saved for this goal.</p>}{scenario&&<div className="my-3 text-sm"><h3 className="font-semibold">Company scenario · source as of {scenario.as_of}</h3><p>Modeled end headcount: {scenario.summary.modeled_end_headcount.toLocaleString()}; modeled end labor cost: {new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(scenario.summary.modeled_end_labor_cost_usd)}.</p><p className="mt-1">Uses recorded annual growth {scenario.assumptions.annual_growth_pct}% and attrition {scenario.assumptions.annual_attrition_pct}%, with the other saved scenario assumptions.</p></div>}{development?.options.map((option,i)=>{const cost=developmentCost(option.quote,option.inputs);return <p key={i} className="mt-3 text-sm">{option.quote.provider} · {option.quote.provenance==='simulated'?'Fictional quote':'User-provided, unverified'} · deterministic cost from saved inputs: {cost.errors.length?'Invalid inputs':cost.total===null?'Unknown':new Intl.NumberFormat('en-US',{style:'currency',currency:option.quote.currency}).format(cost.total)} including employee time. No outcome or ROI claim.</p>})}<p className="mt-2 text-xs text-muted-foreground">{results.length} saved core-model result(s). Full result tables and captured assumptions remain in their Planning destinations.</p></section>
 <details className="rounded-lg border p-4"><summary className="cursor-pointer font-semibold">Saved evidence references ({refs.length})</summary><p className="my-3 text-sm text-muted-foreground">Captured versions used in this goal&apos;s conversations or explicit carries. They remain historical when current sources change; revisit the source page to compare. Saved references are not merged into new AI answers automatically.</p><ol className="space-y-3">{refs.map((ref,i)=>{const source=ref.evidence as Record<string,Json>;return <li key={i} className="text-sm"><strong>{readable(ref.page)}</strong> · {ref.page==='labor-market'?'Real public BLS reference; periods and geography retained':ref.page==='training-coaching'?'Fictional or user-provided quotes':ref.page==='development-planning'?'User assumptions and deterministic costs':ref.page==='home'?'Mixed sources; each captured source retains its label':'Synthetic company aggregate evidence'}<p className="text-xs text-muted-foreground">Captured {new Date(ref.capturedAt).toLocaleString()} · saved reference {i+1} · format v{ref.schemaVersion}{typeof source.period==='string'?` · ${source.period}`:''}{typeof source.releaseDate==='string'?` · released ${source.releaseDate}`:''}</p></li>})}</ol></details>
 </section>;
}
