"use client";
import {solutionConversationEnabled} from '@/lib/home-solution-conversation';
import {pinnedActionPlans} from '@/lib/pinned-action-plans';
import {alternativeViewField} from '@/lib/home-plan-alternative-chat';
import {decisionStore,useDecisionStorage} from '@/components/decision-store';
import { useEffect, useRef, useState } from "react";
import type { ProblemConversation } from "@/components/problem-conversation";
import { MAX_GOALS } from "@/lib/local-goals";
import { validateFocusedIssue } from "@/lib/problem-session";

export function FocusedIssue({ conversation, page="", scope="" }: { conversation: ProblemConversation;page?:string;scope?:string }) {
  const storage=useDecisionStorage(),planMode=solutionConversationEnabled;
  const plans=planMode?pinnedActionPlans(conversation.goals,storage.data.workspaces):[];
  const selectedView=storage.data.workspaces[conversation.activeGoalId]?.fields[alternativeViewField] as {selectedId?:string}|undefined;
  const selectedPlan=plans.find(item=>item.goal.id===conversation.activeGoalId&&item.planId===selectedView?.selectedId)??plans.find(item=>item.goal.id===conversation.activeGoalId);
  const dialog = useRef<HTMLDialogElement>(null);
  const trigger = useRef<HTMLButtonElement>(null);
  const [error, setError] = useState<string | null>(null);
  const editor = conversation.issueEditor;
  useEffect(() => { if (editor && !dialog.current?.open) dialog.current?.showModal(); if (!editor && dialog.current?.open) dialog.current.close(); }, [editor]);
  const close = () => { if(editor)conversation.closeIssueEditor(editor.id); setError(null); trigger.current?.focus(); };
  return <><div className="goal-toolbar flex min-w-0 flex-wrap items-center gap-x-3 gap-y-1">    <details className="goal-storage min-w-0 text-xs text-muted-foreground"><summary className="min-h-9 cursor-pointer py-2">Browser storage details</summary><p role="status" aria-live="polite" className="mt-1 text-xs">{!conversation.storageReady?"Loading saved decisions…":conversation.saved?(conversation.activeGoalId?"Saved in this browser":"Goals saved; exploration stays in this tab"):"Unsaved changes — keep this tab open"}</p><p className="my-2">Up to 20 goals with separate conversations, carried references and Planning inputs are saved in this browser only; no account or sync. General exploration stays in this tab. Limits: 200 messages and 512 KiB per goal, 3 MiB total. Exceeding a limit stops saving without deleting the working copy. Shared workforce filters do not change saved evidence scope. Unsaved drafts can be recovered in this tab after reload. Conflicting saved versions require review. Legacy unassigned scenarios remain in General exploration. Avoid sensitive information on shared devices.</p><button type="button" disabled={!conversation.storageReady} onClick={()=>{if(window.confirm("Delete all saved goals and their conversations, evidence, briefs and Planning scenarios from this browser?"))conversation.clearAllGoals();}} className="mb-2 rounded border px-2 py-1">Clear all saved goals</button></details><div className="flex min-w-0 flex-1 flex-wrap items-center gap-2" aria-label="Goal controls">
    {planMode?<><label className="flex min-w-0 flex-1 items-center gap-2 text-sm font-semibold">Action Plan<select aria-label="Selected Action Plan" disabled={!conversation.storageReady} value={selectedPlan?.key??''} onChange={event=>{const plan=plans.find(item=>item.key===event.target.value);conversation.selectGoal(plan?.goal.id??'');if(plan?.planId&&decisionStore.getSnapshot().data.goals.activeId===plan.goal.id)decisionStore.setField(plan.goal.id,alternativeViewField,{version:1,selectedId:plan.planId,collapsed:false});}} className="min-h-11 w-full min-w-0 rounded border bg-card px-2 text-sm"><option value="">General exploration</option>{plans.filter(item=>!item.legacy).map(item=><option key={item.key} value={item.key}>{item.name} · Goal: {item.goal.statement}</option>)}{!!plans.filter(item=>item.legacy).length&&<optgroup label="Earlier saved goals and drafts">{plans.filter(item=>item.legacy).map(item=><option key={item.key} value={item.key}>{item.goal.statement}</option>)}</optgroup>}</select></label>{conversation.focusedIssue&&<button type="button" disabled={!conversation.storageReady} onClick={()=>conversation.selectGoal('')} className="min-h-11 rounded border px-3 text-sm">Explore a new plan</button>}</>:<label className="flex min-w-0 flex-1 items-center gap-2 text-xs font-semibold">Goal<select aria-label="Selected goal" title={conversation.focusedIssue||"General exploration"} disabled={!conversation.storageReady} value={conversation.activeGoalId} onChange={e=>conversation.selectGoal(e.target.value)} className="h-9 w-full min-w-0 rounded border bg-card px-2 text-sm focus-visible:ring-2 focus-visible:ring-ring"><option value="">General exploration</option>{conversation.goals.map(g=><option key={g.id} value={g.id}>{g.statement}</option>)}</select></label>}
    {!planMode&&conversation.focusedIssue && <button type="button" disabled={!conversation.storageReady || conversation.goals.length>=MAX_GOALS} onClick={()=>{setError(null);conversation.openIssueEditor(true,{page,scope});}} className="h-9 shrink-0 rounded border px-3 text-sm hover:bg-accent focus-visible:ring-2 focus-visible:ring-ring disabled:opacity-50">New goal</button>}
    {(!planMode||conversation.focusedIssue)&&<button ref={trigger} disabled={!conversation.storageReady || (!conversation.focusedIssue && conversation.goals.length>=MAX_GOALS)} type="button" aria-haspopup="dialog" aria-label={planMode?'Edit plan goal and context':conversation.focusedIssue ? `Read or edit Focused issue: ${conversation.focusedIssue}` : "New goal"} onClick={() => {setError(null);conversation.openIssueEditor(false,{page,scope});}} className="min-h-11 shrink-0 rounded border px-3 text-sm focus-visible:ring-2 focus-visible:ring-ring hover:bg-accent">
      <span>{planMode?'Edit plan goal':conversation.focusedIssue ? "Edit goal" : "New goal"}</span>
    </button>}</div></div>
    {(!conversation.storageReady||!conversation.saved)&&<p role="status" className="text-xs">{!conversation.storageReady?"Loading saved decisions…":"Unsaved changes — keep this tab open"}</p>}
    {conversation.storageNotice&&<button type="button" onClick={conversation.retrySave} className="min-h-9 rounded border px-2 text-xs">Retry saving</button>}
    {!!conversation.recovery?.conflicts.length&&<div role="region" aria-label="Review recovered draft" className="w-full rounded border p-3 text-sm"><p>Another tab changed {new Set(conversation.recovery.conflicts.map(item=>item.goalId)).size} of the same goals. Your recovered draft remains visible for review. Continuing keeps saved plan versions and attachment history, carries your unsent request into chat, and discards conflicting unsaved changes.</p><button type="button" className="mt-2 min-h-11 rounded border px-3" onClick={conversation.recoverSaved}>Keep saved versions and my request</button></div>}
    {conversation.storageNotice && <p role="alert" className="text-xs text-destructive">{conversation.storageNotice}</p>}
    <dialog ref={dialog} aria-labelledby="focused-issue-title" onCancel={close} onClose={close} className="m-auto max-h-[80dvh] w-[calc(100vw-2rem)] max-w-xl overflow-y-auto rounded-xl border bg-card p-5 text-foreground shadow-xl backdrop:bg-black/60">
      <form onSubmit={e=>{e.preventDefault();const validation=validateFocusedIssue(editor?.draft ?? "");setError(validation);if(!validation)setError(conversation.updateFocusedIssue(editor!.draft,editor!.id));}}>
        <div className="flex items-start justify-between gap-3"><h2 id="focused-issue-title" className="text-xl font-semibold">{planMode?'Plan goal and context':'Focused issue'}</h2><button type="button" aria-label="Close Focused issue" onClick={close} className="rounded border px-3 py-2">Close</button></div>
        <p className="my-3 text-sm text-muted-foreground">State the problem or decision you want help with, who it concerns, and the desired outcome. Add a timeframe if known. This focuses AI across pages; it does not filter data, change assumptions, or run actions.</p>
        <label htmlFor="focused-issue-statement" className="text-sm font-semibold">Problem statement</label>
        <textarea autoFocus id="focused-issue-statement" value={editor?.draft ?? ""} onChange={e=>conversation.updateIssueDraft(e.target.value,editor!.id)} maxLength={240} rows={4} className="mt-2 w-full rounded border bg-background p-3" placeholder="For example: How can our managers improve feedback by Q3?" />
        {editor&&<details key={editor.id} open={editor.create||undefined} className="my-3 text-sm"><summary className="cursor-pointer">Goal context</summary><label className="mt-3 block">Constraints, assumptions and context<textarea aria-label="Constraints, assumptions and context" value={editor.requirements.constraints} maxLength={600} rows={3} onChange={e=>conversation.updateIssueContext({...editor.requirements,constraints:e.target.value},editor.id)} className="mt-1 w-full rounded border bg-background p-2" /></label><label className="mt-3 block">Decisions you have confirmed<textarea aria-label="Decisions you have confirmed" value={editor.requirements.decisions} maxLength={600} rows={2} onChange={e=>conversation.updateIssueContext({...editor.requirements,decisions:e.target.value},editor.id)} className="mt-1 w-full rounded border bg-background p-2" /></label><p className="mt-2 text-xs">Draft context. Save to keep these changes; Close cancels them. Prefilled text comes from retained user statements, not verified facts. Their original page and scope remain below; longer statements may continue there. Only decisions you enter in the separate field are saved as confirmed decisions.</p>{editor.requirements.notes.map((note,index)=><p key={index} className="mt-2 break-words text-xs">{note.text}{note.truncated?" (truncated)":""} <span className="text-muted-foreground">(User statement; {note.page||'Page unavailable'}; {note.scope||'Scope unavailable'})</span></p>)}<button type="button" onClick={()=>conversation.updateIssueContext({constraints:"",decisions:"",notes:[]},editor.id)} className="mt-3 rounded border px-2 py-1">Clear goal context draft</button></details>}

        <p className="text-xs text-muted-foreground">{editor?.draft.length ?? 0}/240 · Goal and context save together in this browser when you save these changes. Editing starts fresh AI context; the goal conversation stays visible for reference. Switching never changes data filters.</p>
        {(editor?.create || !conversation.activeGoalId) && conversation.goals.length >= MAX_GOALS && <p role="alert" className="mt-2 text-sm">The 20-goal limit is reached. Remove a goal before adding another.</p>}
        {error && <p role="alert" className="mt-2 text-sm text-destructive">{error}</p>}
        <div className="mt-4 flex flex-wrap gap-3"><button type="submit" disabled={(editor?.create || !conversation.activeGoalId) && conversation.goals.length >= MAX_GOALS} className="rounded bg-primary px-4 py-2 font-semibold text-primary-foreground">{planMode?"Save goal and context":conversation.focusedIssue && !editor?.create ? "Save Focused issue" : "Pin Focused issue"}</button>{conversation.focusedIssue && !editor?.create && <><button type="button" onClick={()=>conversation.updateFocusedIssue("",editor!.id)} className="rounded border px-4 py-2">Clear Focused issue</button><button type="button" onClick={()=>{if(window.confirm("Remove this goal and its saved conversation, evidence, brief and Planning scenarios from this browser?"))conversation.removeGoal(editor!.id);}} className="rounded border px-4 py-2">Remove goal</button></>}</div>
      </form>
    </dialog>
  </>;
}
