"use client";
import {useEffect,useRef,useState} from 'react';
import {decisionStore,useDecisionStorage} from '@/components/decision-store';
import {actionBindingKey,actionCalculatorRoute,actionSignature,type ActionBinding} from '@/lib/home-action-drafts';
import type {HomeAction} from '@/lib/home-action-proposal';
import {createActionScenario,editActionAssumption,calculateActionScenario,actionCalculationIsCurrent,readActionScenario,readActionScenarioStore,saveActionScenarioPatch,adoptActionAssumptions,savedScenarioSourceKey,nextActionInput,homeActionScenarioField,type ActionScenario} from '@/lib/home-action-scenarios';
import {savedActionInputSource} from '@/lib/home-action-saved-inputs';
import type {RetentionResult} from '@/lib/retention-what-if';
import type {WorkforceIncrement} from '@/lib/workforce-increment';
const button='min-h-11 rounded border px-3 py-2 text-sm font-medium disabled:opacity-50 focus-visible:ring-2 focus-visible:ring-ring';
const control='mt-1 min-h-11 w-full rounded border bg-background px-2 py-1';
const labels:Record<string,string>={businessUnit:'Business unit',jobProfile:'Role',roles:'Additional roles',planningMonth:'Planning start month (YYYY-MM)',months:'Planning horizon (1–24 months)',build:'Roles filled through development',move:'Roles filled through internal moves',buy:'Roles filled through external hires',backfills:'External backfills for internal moves/development',arrivalMode:'Hire arrival basis',arrivalDate:'Assumed hire arrival (YYYY-MM-DD)',recruitingStart:'Recruiting launch (YYYY-MM-DD)',buildMonth:'Development readiness assumption (YYYY-MM)',moveMonth:'Internal move month (YYYY-MM)',backfillDate:'Backfill arrival assumption (YYYY-MM-DD)',annualHireCost:'Annual cost per new hire (USD)',hireFee:'One-time fee per hire (USD)',annualBackfillCost:'Annual cost per backfill (USD)',backfillFee:'One-time fee per backfill (USD)',internalAnnualCostChange:'Total annual internal salary change (USD)',trainingCash:'Total training cash (USD)',trainingHours:'Total training participant-hours',loadedHourlyCost:'Loaded hourly employee cost (USD)',budget:'Incremental cash budget (USD)',maxAddedEmployees:'Maximum added employees',deadlineMonth:'Coverage deadline (YYYY-MM)',population:'Aggregate population',startMonth:'Planning start month (YYYY-MM)',baselineExpectedExits:'Expected exits without intervention',lagMonths:'Whole months before assumed effect',activeBaselineMode:'Baseline timing after the lag',activeBaselineExpectedExits:'Expected exits during effect-active period',effectLowPct:'Lower assumed reduction (%)',effectHighPct:'Upper assumed reduction (%)',setupCost:'One-time setup cost (USD)',participants:'Funded participants',perParticipantCost:'One-time cost per participant (USD)',monthlyProgramCost:'Monthly program cost (USD)',fundedMonths:'Funded months within horizon'};
const display=(value:number|null|undefined)=>value==null?'Unknown':value.toLocaleString(undefined,{maximumFractionDigits:6});
const money=(value:number|null|undefined)=>value==null?'Unknown':`$${value.toLocaleString(undefined,{maximumFractionDigits:2})} USD`;
type Catalog={business_units:{org_code:string;org_name:string}[];job_profiles:{job_profile_code:string;job_profile_name:string}[]};
export function HomeActionAssumptions({action,binding,disabled,contextCurrent,isCurrent,cache}:{action:HomeAction;binding:ActionBinding;disabled:boolean;contextCurrent:boolean;isCurrent:()=>boolean;cache:Map<string,ActionScenario>}){
 const storage=useDecisionStorage(),key=JSON.stringify([actionBindingKey(binding),actionSignature(action)]),raw=storage.data.workspaces[binding.goalId]?.fields[homeActionScenarioField],store=readActionScenarioStore(raw);
 const saved=store?.entries.map(item=>readActionScenario(item,action,binding)).find(Boolean)??null;
 const [draft,setDraft]=useState<ActionScenario|null>(()=>cache.get(key)??saved),[open,setOpen]=useState(false),[scope,setScope]=useState(''),[step,setStep]=useState(0),[notice,setNotice]=useState(''),[adopt,setAdopt]=useState<string|null>(null),[catalog,setCatalog]=useState<Catalog|null>(null),[catalogError,setCatalogError]=useState(false),[alignmentOpen,setAlignmentOpen]=useState(false),[actionType,setActionType]=useState(''),[alignmentReview,setAlignmentReview]=useState<string|null>(null),[aligned,setAligned]=useState<string|null>(null);
 const root=useRef<HTMLDivElement>(null),heading=useRef<HTMLHeadingElement>(null),resultHeading=useRef<HTMLHeadingElement>(null),invalid=useRef(false);
 useEffect(()=>decisionStore.subscribe(()=>{const snapshot=decisionStore.getSnapshot();if(snapshot.data.goals.activeId!==binding.goalId||snapshot.data.goals.goals.find(item=>item.id===binding.goalId)?.statement!==binding.goal)invalid.current=true;}),[binding.goalId,binding.goal]);
 useEffect(()=>{
  if(!open||action.route!=='capacity')return;
  const controller=new AbortController();
  void fetch('/api/position-structure',{signal:controller.signal}).then(async response=>{if(!response.ok)throw Error();const data=await response.json();if(!Array.isArray(data.business_units)||!Array.isArray(data.job_profiles))throw Error();if(!controller.signal.aborted)setCatalog({business_units:data.business_units,job_profiles:data.job_profiles});}).catch(()=>{if(!controller.signal.aborted)setCatalogError(true)});
  return()=>controller.abort();
 },[open,action.route]);
 function current(){if(disabled||invalid.current||!isCurrent()||!storage.saved)throw Error('The goal or evidence changed, or browser storage is unavailable. Your proposal draft is kept.');}
 function remember(next:ActionScenario){if(!cache.has(key)&&cache.size>=12)throw Error('This tab already holds twelve proposal drafts. Save your work before opening more.');cache.set(key,next);setDraft(next);setNotice('');}
 function change(field:string,value:string,kind?:'user-entered'|'illustrative'){try{current();if(draft)remember(editActionAssumption(draft,field,value,kind??(draft.origins[field].kind==='illustrative'?'illustrative':'user-entered')));}catch(error){setNotice((error as Error).message)}}
 function begin(){try{current();if(scope!=='additional_capacity'&&scope!=='retention_program')return;remember(createActionScenario(action,binding,{confirmed:true,binding,actionSignature:actionSignature(action),scope}));setStep(0);}catch(error){setNotice((error as Error).message)}}
 function calculate(){try{current();if(!draft)return;remember(calculateActionScenario(draft));requestAnimationFrame(()=>{resultHeading.current?.focus({preventScroll:true});resultHeading.current?.scrollIntoView({block:'nearest'});});}catch(error){setNotice((error as Error).message)}}
 function save(){try{current();if(!draft)return;const latest=decisionStore.getSnapshot().data.workspaces[binding.goalId]?.fields[homeActionScenarioField],patch=saveActionScenarioPatch(latest,draft);decisionStore.setField(binding.goalId,patch.field,patch.value);if(!decisionStore.getSnapshot().saved)throw Error('Browser storage did not save. Your working proposal remains in this tab.');setNotice('Proposal assumptions and any displayed calculation saved locally. Confirmed plans are unchanged.');}catch(error){setNotice((error as Error).message)}}
 const currentResult=contextCurrent&&draft&&actionCalculationIsCurrent(draft)?draft.calculation:null,retention=draft?.route==='retention_what_if'?currentResult?.result as RetentionResult|undefined:undefined,capacity=draft?.route==='capacity'?currentResult?.result as WorkforceIncrement|undefined:undefined;
 const rows: [string,string][] = retention?[
  ['Cost',money(retention.programNoEffect.programCost)],['Timing',retention.effectStartMonth?`Assumed effect from ${retention.effectStartMonth}`:'Unknown'],['Staffing',draft!.inputs.participants?`${draft!.inputs.participants} funded participants; availability unverified`:'Unknown'],['Effect',retention.assumedRange.lowReduction.fewerExits===null?'Unknown':`${display(retention.assumedRange.lowReduction.fewerExits)}–${display(retention.assumedRange.highReduction.fewerExits)} fewer exits under your assumptions`],
 ]:[['Cost','Unknown'],['Timing','Unknown'],['Staffing','Unknown'],['Effect','Unknown']];
 const capacityKey=capacity&&draft?JSON.stringify([key,draft.revision,draft.calculation]):null;
 const capacityAligned=!!capacityKey&&aligned===capacityKey;
 const required=draft?nextActionInput(draft):null;
 const input=draft?.inputs;
 const optionalOrder=!draft?[]:draft.route==='retention_what_if'?['baselineExpectedExits','lagMonths','effectLowPct','effectHighPct',...(Number(input!.lagMonths)>0&&Number(input!.lagMonths)<Number(input!.months)?['activeBaselineMode',...(input!.activeBaselineMode==='direct'?['activeBaselineExpectedExits']:[])]:[]),'setupCost','participants','perParticipantCost','monthlyProgramCost','fundedMonths']:[...(Number(input!.buy)>0?['arrivalMode',...(input!.arrivalMode==='explicit'?['arrivalDate']:[]),'annualHireCost','hireFee']:[]),...(Number(input!.build)>0?['buildMonth','trainingCash','trainingHours',...(Number(input!.trainingHours)>0?['loadedHourlyCost']:[])]:[]),...(Number(input!.move)>0?['moveMonth']:[]),...(Number(input!.build)+Number(input!.move)>0?['internalAnnualCostChange']:[]),...(Number(input!.backfills)>0?['backfillDate','annualBackfillCost','backfillFee']:[])];
 const optionalField=optionalOrder.find(field=>!input![field].trim()),nextField=required?.field??optionalField;
 function jumpTo(field:string){
  const group=draft?.route==='capacity'?(['businessUnit','jobProfile','roles','planningMonth','months'].includes(field)?0:['build','move','buy','backfills'].includes(field)?1:2):(['population','startMonth','months'].includes(field)?0:['baselineExpectedExits','lagMonths','effectLowPct','effectHighPct','activeBaselineMode','activeBaselineExpectedExits'].includes(field)?1:2);
  setStep(group);requestAnimationFrame(()=>{const target=root.current?.querySelector<HTMLElement>(`[data-action-field="${field}"]`);let parent=target?.parentElement;while(parent&&parent!==root.current){if(parent instanceof HTMLDetailsElement)parent.open=true;parent=parent.parentElement;}target?.querySelector<HTMLElement>('input,select')?.focus();target?.scrollIntoView({block:'nearest'});});
 }
 const offered=draft?savedActionInputSource(draft.route,binding,storage.data.workspaces[binding.goalId]?.fields??{}):null;
 const canBegin=scope==='additional_capacity'||scope==='retention_program'?['capacity','retention_what_if'].includes(actionCalculatorRoute(action,binding,{confirmed:true,binding,actionSignature:actionSignature(action),scope})):false;
 function field(name:string){
  if(!draft)return null;const origin=draft.origins[name],label=labels[name],value=draft.inputs[name],numeric=!['population','businessUnit','jobProfile','activeBaselineMode','arrivalMode'].includes(name)&&!name.toLowerCase().includes('month')&&!name.toLowerCase().includes('date')&&name!=='recruitingStart';
  const options=name==='businessUnit'?(catalog?.business_units.map(item=>[item.org_code,item.org_name])??[]):name==='jobProfile'?(catalog?.job_profiles.map(item=>[item.job_profile_code,item.job_profile_name])??[]):name==='arrivalMode'?[['','Unknown'],['explicit','Explicit planning assumption']]:name==='activeBaselineMode'?[['','Unknown'],['direct','Enter active-period expected exits'],['uniform','Explicitly assume uniform exit timing']]:null;
  return <div key={name} data-action-field={name} className="min-w-0 space-y-1"><label className="block">{label}{options?<select aria-label={label} className={control} value={value} onChange={event=>change(name,event.target.value)}>{name==='businessUnit'||name==='jobProfile'?<option value="">Choose from available catalogue</option>:null}{value&&!options.some(([id])=>id===value)&&<option value={value}>{value} — retained assumption</option>}{options.map(([id,text])=><option key={id} value={id}>{text}</option>)}</select>:<input aria-label={label} className={control} value={value} maxLength={name==='population'?240:100} inputMode={numeric?'decimal':'text'} onChange={event=>change(name,event.target.value)}/>}</label><label className="block text-xs text-muted-foreground">Basis<select aria-label={`Basis for ${label}`} value={origin.kind} disabled={!value.trim()} onChange={event=>change(name,value,event.target.value as 'user-entered'|'illustrative')} className="ml-2 max-w-full rounded border bg-background p-1">{origin.kind==='unknown'&&<option value="unknown">Unknown</option>}{origin.kind==='adopted'&&<option value="adopted">Adopted saved assumption</option>}<option value="user-entered">User assumption</option><option value="illustrative">Illustrative assumption — not evidence</option></select></label>{origin.kind==='adopted'&&<p className="text-xs text-muted-foreground">{origin.basis}</p>}</div>;
 }
 function optional(title:string,names:string[]){return <details key={title}><summary className="min-h-11 cursor-pointer py-2 font-medium">{title}</summary><div className="grid gap-3 sm:grid-cols-2">{names.map(field)}</div></details>}
 return <div ref={root} className="space-y-3" aria-label="Action assumptions and calculation">
  {retention&&currentResult&&<><h4 ref={resultHeading} tabIndex={-1} className="font-semibold">Provisional calculation — not an approved plan</h4><p className="text-xs">{Object.values(currentResult.origins).some(origin=>origin.kind==='illustrative')?'Includes illustrative assumptions — editable scenario choices, not evidence.':Object.values(currentResult.origins).some(origin=>origin.kind==='adopted')?'Includes saved assumptions explicitly adopted for this action.':'Based on your entered planning assumptions.'}</p></>}
  <dl aria-label="Action estimates" className="grid grid-cols-2 gap-2">{rows.map(([label,value])=><div key={label}><dt className="font-semibold">{label}</dt><dd>{value}</dd></div>)}</dl>
  {retention&&<div className="text-xs"><p>No intervention: {display(retention.noIntervention.expectedExits)} expected exits; {money(retention.noIntervention.programCost)} program cost.</p><p>Program with no effect: {display(retention.programNoEffect.expectedExits)} expected exits; {money(retention.programNoEffect.programCost)} cost.</p><p>Assumed reductions are conditional arithmetic, not a forecast. The no-effect case is not a worst-case guarantee.</p></div>}
  {capacity&&<section aria-label="Additional-capacity what-if for this goal" className="space-y-3 rounded border border-primary/40 bg-muted/30 p-3">
   <h4 ref={resultHeading} tabIndex={-1} className="font-semibold">Additional-capacity what-if for this goal</h4>
   <p className="font-medium">These numbers describe your chosen staffing scenario, not the cost or effect of “{action.name}”.</p>
   <p className="text-xs">Provisional calculation — not an approved plan. {Object.values(currentResult!.origins).some(origin=>origin.kind==='illustrative')?'Includes illustrative assumptions, not evidence.':'Based on your reviewed planning assumptions.'}</p>
   <dl aria-label="Capacity scenario estimates" className="grid gap-3 sm:grid-cols-2">
    <div><dt className="font-semibold">Scenario incremental cash</dt><dd>{money(capacity.totalCash)}</dd></div>
    <div><dt className="font-semibold">Scenario timing</dt><dd>Horizon through {capacity.rows.at(-1)?.month}; hire: {capacity.arrivalDate??'Unknown'}; development: {capacity.input.buildMonth||'Unknown'}; move: {capacity.input.moveMonth||'Unknown'}.</dd></div>
    <div><dt className="font-semibold">Conditional role coverage</dt><dd>{display(capacity.rows.at(-1)?.conditionalRoleCoverage)} conditional roles covered / {capacity.input.roles} required; availability unverified</dd></div>
    <div><dt className="font-semibold">Planned added employees</dt><dd>{capacity.maxAddedEmployees}; retention effect unknown</dd></div>
   </dl>
   <p className="text-xs">Employee time value: {money(capacity.totalTime)}, separate from cash. Planned counts do not establish readiness or availability.</p>
   {capacityAligned?<p role="status">You linked this scenario to the staffing action in this tab after reviewing its scope and mix. It remains conditional scenario arithmetic, not the action’s total cost or proven effect.</p>:<button className={button} disabled={disabled} onClick={()=>setAlignmentOpen(value=>!value)}>Link scenario to a staffing action</button>}
   {alignmentOpen&&!capacityAligned&&<div className="space-y-3 border-t pt-3"><p><strong>Review the action itself:</strong> {action.firstStep}</p><label className="block">What does this action itself propose?<select aria-label="Action type for scenario alignment" className={control} value={actionType} onChange={event=>{setActionType(event.target.value);setAlignmentReview(null);}}><option value="">Choose after reviewing the first step</option><option value="staffing">Hiring, developing or moving people into additional roles</option><option value="diagnostic">Diagnosis or investigation only</option><option value="unsure">Another action or unsure</option></select></label>
    {actionType==='staffing'?<><p>Review this scenario: {capacity.input.businessUnit} / {capacity.input.jobProfile}; {capacity.input.roles} additional roles; hire {capacity.input.buy}, develop {capacity.input.build}, move {capacity.input.move}; {capacity.input.planningMonth}, {capacity.input.months} months.</p><label className="flex items-start gap-2"><input type="checkbox" checked={alignmentReview===capacityKey} onChange={event=>setAlignmentReview(event.target.checked?capacityKey:null)}/><span>I confirm the action explicitly proposes this staffing change and this exact scope, mix and timing describe it.</span></label><button className={button} disabled={disabled||alignmentReview!==capacityKey} onClick={()=>{try{current();if(alignmentReview!==capacityKey)throw Error('Review the current scenario again.');setAligned(capacityKey);setAlignmentOpen(false);}catch(error){setNotice((error as Error).message)}}}>Confirm scenario alignment</button></>:actionType&&<p>This scenario cannot be linked to a diagnostic or unconfirmed action. It remains a separate what-if for the goal; action estimates stay Unknown.</p>}
   </div>}
  </section>}
  {currentResult&&<details><summary className="min-h-11 cursor-pointer py-2">Calculation tradeoffs and limitations</summary><ul className="list-disc space-y-1 pl-5">{(retention?.limitations??capacity?.warnings??[]).map(text=><li key={text}>{text}</li>)}</ul></details>}
  {draft?.calculation&&!currentResult&&<p role="status">Assumptions changed. The earlier calculation is retained as stale; recalculate this proposal to show current numbers.</p>}
  {notice&&<p role="status">{notice}</p>}
  {!store&&raw!==undefined&&<p role="alert">Saved action assumptions cannot be verified. Their record is kept; saving is blocked.</p>}
  <button className={button} disabled={disabled} onClick={()=>{setOpen(value=>!value);requestAnimationFrame(()=>heading.current?.focus({preventScroll:true}));}}>{open?'Close assumptions':'Tailor assumptions'}</button>
  {open&&<div className="space-y-3 rounded border p-3"><h4 ref={heading} tabIndex={-1} className="font-semibold">{action.route==='capacity'?'Assumptions for the additional-capacity what-if':`Assumptions for ${action.name}`}</h4><p className="text-xs">Planning assumptions are separate from observed evidence. Illustrative values are editable scenario choices, not facts. Edits and calculations stay in this tab until Save proposal; confirmed plans are unchanged.</p>
   {!draft?<><label className="block">Which scope do you want to explore?<select aria-label="Action planning scope" className={control} value={scope} onChange={event=>setScope(event.target.value)}><option value="">Review the action and choose</option><option value="additional_capacity">Additional role capacity</option><option value="retention_program">A retention program with user-assumed effects</option><option value="unsupported">Replacement only, another scope, or unsure</option></select></label>{canBegin?<button className={button} disabled={disabled} onClick={begin}>Confirm scope and tailor proposal</button>:scope&&<p>This action and scope do not have a compatible calculator. Its numerical results remain unknown.</p>}</>:<>
    <div role="group" aria-label="Assumption groups" className="flex flex-wrap gap-2">{['Scope',draft.route==='capacity'?'Staffing mix':'Baseline and effect','Costs and timing'].map((label,index)=><button key={label} className={button} aria-pressed={step===index} onClick={()=>setStep(index)}>{label}</button>)}</div>
    {nextField&&<div><p className="font-medium">{required?`Next input: ${required.question}`:`What assumption should we use for ${labels[nextField].toLowerCase()}?`}</p><button className={button} onClick={()=>jumpTo(nextField)}>Edit this assumption</button></div>}
    <fieldset disabled={disabled} className="space-y-3">{step===2&&<p className="text-xs">Blank amounts remain Unknown. Enter zero only when you explicitly assume no cost or activity.</p>}
    {step===0&&<div className="grid gap-3 sm:grid-cols-2">{(draft.route==='capacity'?['businessUnit','jobProfile','roles','planningMonth','months']:['population','startMonth','months']).map(field)}</div>}
    {step===0&&draft.route==='capacity'&&!catalog&&<p className="text-xs">{catalogError?'Role catalogue unavailable. Retained saved selections remain assumptions; try reopening this editor.':'Loading the available role catalogue…'}</p>}
    {step===1&&draft.route==='capacity'&&<div className="grid gap-3 sm:grid-cols-2">{['build','move','buy',...(Number(draft.inputs.build)+Number(draft.inputs.move)>0?['backfills']:[])].map(field)}</div>}
    {step===1&&draft.route==='retention_what_if'&&<><div className="grid gap-3 sm:grid-cols-2">{['baselineExpectedExits','lagMonths','effectLowPct','effectHighPct'].map(field)}</div><p className="text-xs">No effect range is supplied automatically. Enter a what-if range only with a basis you are willing to review; observed turnover and survey feedback do not establish an intervention effect.</p>{Number(draft.inputs.lagMonths)>0&&Number(draft.inputs.lagMonths)<Number(draft.inputs.months)&&field('activeBaselineMode')}{(draft.inputs.activeBaselineMode==='direct'||draft.inputs.activeBaselineExpectedExits)&&field('activeBaselineExpectedExits')}</>}
    {step===2&&draft.route==='retention_what_if'&&<div className="grid gap-3 sm:grid-cols-2">{['setupCost','participants','perParticipantCost','monthlyProgramCost','fundedMonths'].map(field)}</div>}
    {step===2&&draft.route==='capacity'&&<>{Number(draft.inputs.buy)>0&&optional('Hiring assumptions',['arrivalMode',...(draft.inputs.arrivalMode==='explicit'?['arrivalDate']:[]),'annualHireCost','hireFee'])}{Number(draft.inputs.build)>0&&optional('Development assumptions',['buildMonth','trainingCash','trainingHours',...(Number(draft.inputs.trainingHours)>0?['loadedHourlyCost']:[])])}{Number(draft.inputs.move)>0&&optional('Internal move timing',['moveMonth'])}{Number(draft.inputs.build)+Number(draft.inputs.move)>0&&optional('Internal cost change',['internalAnnualCostChange'])}{Number(draft.inputs.backfills)>0&&optional('Backfill assumptions',['backfillDate','annualBackfillCost','backfillFee'])}{optional('Optional constraints',['budget','maxAddedEmployees','deadlineMonth'])}</>}
    </fieldset>
    <div className="flex flex-wrap gap-2">{step<2&&<button className={button} onClick={()=>setStep(step+1)}>Next assumptions</button>}<button className={button} disabled={disabled} onClick={calculate}>{draft.calculation?'Recalculate proposal':'Calculate proposal'}</button><button className={button} disabled={disabled||!store} onClick={save}>Save proposal</button></div>
    {offered&&<details><summary className="min-h-11 cursor-pointer py-2">Review compatible saved inputs for reuse</summary><p>Source: {offered.sourceId}. Scope: {offered.inputs.population??`${offered.inputs.businessUnit} / ${offered.inputs.jobProfile}`}; {offered.inputs.startMonth??offered.inputs.planningMonth}, {offered.inputs.months} months. Adoption replaces this proposal’s assumptions and does not copy its result.</p><details><summary className="min-h-11 cursor-pointer py-2">Saved assumption values</summary><p>These are saved planning assumptions, not independently verified facts.</p><dl className="grid gap-2 sm:grid-cols-2">{Object.entries(offered.inputs).map(([field,value])=><div key={field}><dt className="font-medium">{labels[field]??field}</dt><dd>{value||'Unknown'}</dd></div>)}</dl></details><label className="my-2 flex items-start gap-2"><input type="checkbox" checked={adopt===savedScenarioSourceKey(offered)} onChange={event=>setAdopt(event.target.checked?savedScenarioSourceKey(offered):null)}/><span>{draft.route==='capacity'?'I confirm these saved assumptions describe this exact additional-capacity scenario, including its role, scope and mix. This does not link it to the action.':'I confirm these saved assumptions describe this exact action, including its program, population or role. Matching a goal alone is not sufficient.'}</span></label><button className={button} disabled={disabled||adopt!==savedScenarioSourceKey(offered)} onClick={()=>{try{current();if(adopt!==savedScenarioSourceKey(offered))throw Error('Saved inputs changed. Review their current values again.');remember(adoptActionAssumptions(draft,offered,{confirmed:true,binding,actionSignature:actionSignature(action),sourceKey:savedScenarioSourceKey(offered)}));setAdopt(null);}catch(error){setNotice((error as Error).message)}}}>Adopt into this proposal</button></details>}
   </>}
  </div>}
 </div>;
}
