"use client";
import {prepareIllustrativePilot,pilotAllowances} from '@/lib/home-action-plan-pilot';
import {useRef,useState} from 'react';
import {decisionStore,useDecisionStorage} from '@/components/decision-store';
import {bundleDisplayText,bundleComponentLabels} from '@/lib/home-bundle-display';
import {HomeBundleEditor} from '@/components/home-bundle-editor';
import {actionBindingKey,type ActionBinding} from '@/lib/home-action-drafts';
import type {BundleProposal,SolutionBundle} from '@/lib/home-solution-bundles';
import {createBundleDraft,reviseBundleDraft,reviseBundleProposal,reconcileBundle,bundleInputKey,compareCurrentBundleResults,type BundleDraft,type BundleInputs,type BundleResult} from '@/lib/home-bundle-reconciliation';
import {readBundleWorkspace,saveBundleDraftPatch,saveBundleCalculationPatch,attachBundlePatch,attachedBundleState,bundleWorkspaceField} from '@/lib/home-bundle-records';
export const bundleButton='min-h-11 rounded border px-3 py-2 text-sm font-medium disabled:opacity-50 focus-visible:ring-2 focus-visible:ring-ring';
export type BundleSession={drafts:Record<string,BundleDraft>;results:Record<string,BundleResult>};
export type BundleDiscussion={option:number;id:string;revision:number;name:string;isCurrent:()=>boolean};
const money=(value:number|null|undefined)=>value==null?'Unknown':`$${value.toLocaleString(undefined,{maximumFractionDigits:2})} USD`;
export function HomeBundlePlans({proposal,binding,preparedAt,contextCurrent,disabled,isCurrent,cache,onDiscuss}:{preparedAt:string;proposal:BundleProposal;binding:ActionBinding;contextCurrent:boolean;disabled:boolean;isCurrent:()=>boolean;cache:Map<string,BundleSession>;onDiscuss:(request:BundleDiscussion)=>void}){
 const optionNumber=(id:string)=>proposal.bundles.findIndex(bundle=>bundle.id===id)+1;
 const storage=useDecisionStorage(),raw=storage.data.workspaces[binding.goalId]?.fields[bundleWorkspaceField],workspace=readBundleWorkspace(raw,binding.goalId),key=actionBindingKey(binding);
 const [session,setSession]=useState<BundleSession>(()=>cache.get(key)??{drafts:Object.fromEntries(proposal.bundles.map(bundle=>{const saved=workspace?.drafts.filter(item=>actionBindingKey(item.binding)===key&&item.bundle.id===bundle.id).sort((a,b)=>b.revision-a.revision)[0];return [bundle.id,prepareIllustrativePilot(saved??createBundleDraft(bundle,binding),preparedAt)]})),results:Object.fromEntries((workspace?.calculations??[]).filter(item=>actionBindingKey(item.draft.binding)===key).map(item=>[item.draft.bundle.id,item.result]))});
 const liveSession=useRef(session);
 const [pendingInput,setPendingInput]=useState(false);
 const [selected,setSelected]=useState(proposal.bundles[0]?.id??'A'),[editor,setEditor]=useState(false),[notice,setNotice]=useState(''),[reviewed,setReviewed]=useState<string|null>(null),[unknowns,setUnknowns]=useState<string|null>(null);
 const heading=useRef<HTMLHeadingElement>(null),draft=session.drafts[selected],result=session.results[selected],currentResult=draft&&contextCurrent&&result?.inputKey===bundleInputKey(draft)?result:null;
 function guard(){if(disabled||!contextCurrent||!isCurrent()||!decisionStore.getSnapshot().saved)throw Error('The goal, evidence or saved planning context changed. Your draft is kept; review the current context first.');}
 function remember(next:BundleSession){if(!cache.has(key)&&cache.size>=12)throw Error('This tab already holds twelve bundle contexts. Save your work before opening more.');cache.set(key,next);liveSession.current=next;setSession(next);setNotice('');}
 function edit(inputs:BundleInputs){try{guard();remember({...session,drafts:{...session.drafts,[selected]:reviseBundleDraft(draft,inputs)}});}catch(error){setNotice((error as Error).message)}}
 function editProposal(bundle:SolutionBundle){try{guard();remember({...session,drafts:{...session.drafts,[selected]:reviseBundleProposal(draft,bundle)}});}catch(error){setNotice((error as Error).message)}}
 function calculate(){try{guard();if(pendingInput)throw Error('Complete the month entry before calculating.');const calculated=reconcileBundle(draft);remember({...session,results:{...session.results,[selected]:calculated}});requestAnimationFrame(()=>{heading.current?.focus({preventScroll:true});heading.current?.scrollIntoView({block:'nearest'});});}catch(error){setNotice((error as Error).message);setEditor(true);}}
 function persist(attach=false){try{guard();if(pendingInput)throw Error('Complete the month entry before saving or attaching.');const previous=decisionStore.getSnapshot().data.workspaces[binding.goalId]?.fields[bundleWorkspaceField];let patch=currentResult?saveBundleCalculationPatch(previous,draft,currentResult):saveBundleDraftPatch(previous,draft);
  if(attach){if(!currentResult||reviewed!==bundleInputKey(draft))throw Error('Calculate and review this exact version before attaching it.');const store=patch.value,superseded=new Set(store.attachments.map(item=>item.supersedes)),prior=store.attachments.findLast(item=>!superseded.has(item.id)&&item.draft.bundle.id===selected);patch=attachBundlePatch(store,draft,{confirmed:true,bindingKey:key,inputKey:bundleInputKey(draft),acknowledgeUnknowns:unknowns===bundleInputKey(draft)},crypto.randomUUID(),new Date().toISOString(),prior?.id??null);}
  decisionStore.setField(binding.goalId,patch.field,patch.value);if(!decisionStore.getSnapshot().saved)throw Error('Browser storage could not save. Your working draft is kept in this tab.');setNotice(attach?'Reviewed Action Plan attached to this goal. It is not operational approval.':'Action Plan draft and any current calculation saved locally. Existing plans and pins are unchanged.');
 }catch(error){setNotice((error as Error).message)}}
 function discuss(){try{guard();const inputKey=bundleInputKey(draft);onDiscuss({option:optionNumber(selected),id:selected,revision:draft.revision,name:draft.bundle.name,isCurrent:()=>isCurrent()&&bundleInputKey(liveSession.current.drafts[selected])===inputKey});}catch(error){setNotice((error as Error).message)}}
 const activeAttachments=workspace?.attachments.filter(item=>!workspace.attachments.some(next=>next.supersedes===item.id))??[],existing=activeAttachments.find(item=>item.draft.bundle.id===selected);
 if(!draft)return <p>{proposal.unavailableReason??'No coordinated options were prepared.'}</p>;
 return <div className="space-y-4">
  <section aria-label="Combined option comparison" className="space-y-2"><h3 className="font-semibold">{proposal.bundles.length} coordinated {proposal.bundles.length===1?'option':'options'}</h3><p className="text-xs text-muted-foreground">Objectives are not proven winners. Cost and deployment tradeoffs appear only for current calculations with matching reviewed scope.</p>
   {proposal.bundles.map(bundle=>{const item=session.drafts[bundle.id],own=session.results[bundle.id];let pro=`Objective: ${bundleDisplayText(item.bundle.objective,item.bundle)}`,con='Comparison not established; review matching costs and readiness.';
    if(contextCurrent&&own)for(const other of proposal.bundles){if(other.id===bundle.id||!session.results[other.id])continue;const comparison=compareCurrentBundleResults(own,session.results[other.id],item,session.drafts[other.id]);if(!comparison.comparable)continue;
     if(comparison.cashDifference!==null&&comparison.cashDifference<0)pro=`${money(-comparison.cashDifference)} lower incremental cash than Option ${optionNumber(other.id)}, under reviewed assumptions.`;
     if(comparison.cashDifference!==null&&comparison.cashDifference>0)con=`${money(comparison.cashDifference)} higher incremental cash than Option ${optionNumber(other.id)}, under reviewed assumptions.`;
     if(comparison.capacityMonthsDifference!==null&&comparison.capacityMonthsDifference<0)pro=`Conditional capacity ${-comparison.capacityMonthsDifference} months earlier than Option ${optionNumber(other.id)}.`;
     if(comparison.capacityMonthsDifference!==null&&comparison.capacityMonthsDifference>0)con=`Conditional capacity ${comparison.capacityMonthsDifference} months later than Option ${optionNumber(other.id)}.`;
    }
    return <div key={bundle.id} className="rounded border p-3"><button className={bundleButton} aria-pressed={selected===bundle.id} onClick={()=>{setSelected(bundle.id);setEditor(false);setNotice('');}}>Option {optionNumber(bundle.id)} · {item.bundle.name}</button><p className="mt-2 text-xs">{pro}</p><p className="text-xs">{con}</p></div>;
   })}
  </section>
  <article aria-label={`Action Plan option ${optionNumber(selected)}`} className="space-y-3 border-t pt-3"><h3 ref={heading} tabIndex={-1} className="text-base font-semibold">Option {optionNumber(selected)}: {draft.bundle.name}</h3>
   {draft.pilot&&<PilotAssumptions draft={draft}/>}
   <ul className="list-disc space-y-2 pl-5">
    <li><strong>Approach:</strong> {bundleDisplayText(draft.bundle.coordination,draft.bundle)}</li>
    <li><strong>Working together:</strong> {draft.bundle.components.map(item=>item.name).join('; ')}. Details show which steps can run in parallel.</li>
    <li><strong>Combined incremental cash:</strong> {money(currentResult?.cashTotal)}{currentResult?.cashTotal===null?`; reconciled known subtotal ${money(currentResult.knownCashSubtotal)}`:''}. <strong>Employee time:</strong> {money(currentResult?.employeeTimeTotal)}, separate from cash.</li>
    <li><strong>Capacity and people:</strong> {currentResult?.conditionalCoverage?.at(-1)??'Unknown'} conditional roles covered; {currentResult?.plannedAddedEmployees??'Unknown'} planned added employees. Availability and combined retention impact are not established.</li>
    <li><strong>Timeline:</strong> {currentResult?.planFinish?`Reviewed components finish ${currentResult.planFinish}`:'Unknown until dependencies and readiness are reviewed'}{currentResult?.capacityReadyMonth?`; conditional capacity from ${currentResult.capacityReadyMonth}`:''}.</li>
    <li><strong>Suggested stakeholders:</strong> {[...new Set(draft.bundle.components.map(item=>item.ownerRole))].join('; ')}. <strong>Review needed:</strong> {currentResult?.issues[0]??bundleDisplayText(draft.bundle.limitation,draft.bundle)} Proposed owner roles are not assigned people or operational approvals.</li>
   </ul>
   {result&&!currentResult&&<p role="status">The previous calculation is retained as stale. Calculate this reviewed revision to show current totals.</p>}
   <details><summary className="min-h-11 cursor-pointer py-2 font-medium">Details: components, evidence and shared assumptions</summary><div className="space-y-3">{draft.bundle.components.map(component=><section key={component.id} className="rounded border p-3"><h4 className="font-semibold">{component.name}</h4><p>{bundleDisplayText(component.firstStep,draft.bundle)}</p><p className="text-xs">Suggested stakeholder role: {component.ownerRole}. Proposed responsibility: coordinate “{component.name}” and its first step. Prerequisites: {bundleComponentLabels(component.dependsOn,draft.bundle)||'None proposed'}.</p><p className="text-xs">References: {component.evidence.join(', ')}. {contextCurrent?'Observed context only; these references do not establish effectiveness.':'Original evidence context changed; references require review.'}</p><p className="text-xs">{bundleDisplayText(component.limitation,draft.bundle)}</p></section>)}
    {result&&<section><h4 className="font-semibold">{currentResult?'Current':'Stale'} shared ledger</h4><p>Shared entries count once. Employee time is separate. All amounts are planning assumptions.</p><ul>{result.ledger.map(line=><li key={line.id}>{line.label}: {money(line.total)} · {line.kind==='cash'?'cash':'employee time'} · linked to {bundleComponentLabels(line.componentIds,draft.bundle)||'unassigned'}</li>)}</ul><p>Distinct reviewed participants: {result.uniqueParticipants??'Unknown'}.</p>{result.issues.map(issue=><p key={issue}>{issue}</p>)}</section>}
   </div></details>
   {notice&&<p role="status">{notice}</p>}{!workspace&&<p role="alert">Saved bundle records cannot be verified. They are kept; saving is blocked.</p>}
   <p className="font-medium">Want to change anything, including the assumptions? Tell me what you’d like to adjust.</p>
   <div className="flex flex-wrap gap-2"><button className={bundleButton} disabled={disabled||!contextCurrent} onClick={()=>setEditor(value=>!value)}>{editor?'Close editor':'Edit assumptions and plan'}</button><button className={bundleButton} disabled={disabled||!contextCurrent} onClick={discuss}>Discuss changes</button></div>
   {editor&&<HomeBundleEditor onPendingInput={setPendingInput} optionNumber={optionNumber(selected)} draft={draft} disabled={disabled||!contextCurrent} onChange={edit} onProposalChange={editProposal}/>}
   {pendingInput&&<p role="status" className="text-xs">Complete the month as YYYY-MM before calculating, saving or attaching.</p>}
   {(editor||currentResult)&&<div className="flex flex-wrap gap-2"><button className={bundleButton} disabled={disabled||!contextCurrent||pendingInput} onClick={calculate}>Calculate combined plan</button><button className={bundleButton} disabled={disabled||!contextCurrent||!workspace||pendingInput} onClick={()=>persist()}>Save Action Plan draft</button></div>}
   {currentResult&&<details><summary className="min-h-11 cursor-pointer py-2 font-medium">Review and attach Action Plan to goal</summary><p>Attach option {optionNumber(selected)}, revision {draft.revision}, with these exact assumptions and results. Later edits stay drafts; previous attached versions remain in history.</p><label className="my-2 flex items-start gap-2"><input type="checkbox" checked={reviewed===bundleInputKey(draft)} onChange={event=>setReviewed(event.target.checked?bundleInputKey(draft):null)}/><span>I reviewed this Action Plan for “{binding.goal}”. This is not operational approval.</span></label>{currentResult.issues.length>0&&<label className="my-2 flex items-start gap-2"><input type="checkbox" checked={unknowns===bundleInputKey(draft)} onChange={event=>setUnknowns(event.target.checked?bundleInputKey(draft):null)}/><span>I acknowledge the unresolved assumptions listed in Details.</span></label>}<button className={bundleButton} disabled={disabled||pendingInput||reviewed!==bundleInputKey(draft)||currentResult.issues.length>0&&unknowns!==bundleInputKey(draft)} onClick={()=>persist(true)}>{existing?'Replace attached Action Plan with this version':'Attach Action Plan to goal'}</button></details>}
  </article>
  {!!workspace?.attachments.length&&<details><summary className="min-h-11 cursor-pointer py-2 font-medium">Attached Action Plans and version history ({workspace.attachments.length})</summary>{workspace.attachments.map(item=><div key={item.id} className="mb-3 rounded border p-3"><p>{item.draft.bundle.name} · revision {item.draft.revision} · {workspace.attachments.some(next=>next.supersedes===item.id)?'Previous attached version':contextCurrent?attachedBundleState(item,binding,session.drafts[item.draft.bundle.id]??null).replaceAll('_',' '):'context changed'}</p><p>Snapshot cash: {money(item.result.cashTotal)}. Timeline: {item.result.planFinish??'Unknown'}. Attached {item.attachedAt.slice(0,10)}.</p><p className="text-xs">{bundleDisplayText(item.draft.bundle.coordination,item.draft.bundle)} This preserved proposal is not operational approval.</p></div>)}</details>}
 </div>;
}

function PilotAssumptions({draft}:{draft:BundleDraft}){
 const input=draft.inputs,pilotGroup=draft.inputs.groups.find(group=>group.id==='pilot-group'),allowances=input.expenses.filter(expense=>expense.id.startsWith('pilot-'));
 const end=input.scope.startMonth.value&&input.scope.months.value?new Date(Date.UTC(Number(input.scope.startMonth.value.slice(0,4)),Number(input.scope.startMonth.value.slice(5))-1+input.scope.months.value,0)).toISOString().slice(0,10):null;
 const lastFinish=input.timing.map(item=>item.finish.value).filter((date):date is string=>!!date).sort().at(-1);
 return <section aria-label="Editable illustrative starting assumptions" className="space-y-2 rounded border bg-muted/20 p-3 text-xs">
  <p className="font-semibold">Illustrative pilot — editable assumptions, not observed facts or market estimates</p>
  <p>Shared start: {input.scope.startMonth.value??'Unknown'} · horizon: {input.scope.months.value??'Unknown'} months · finish: {end??'Unknown'}. {pilotGroup?`${pilotGroup.count.value??'Unknown'} hypothetical pilot participants; not workforce headcount or selected employees.`:'Existing participant assumptions retained; review Participants.'}</p>
  {allowances.length>0&&<div className="grid gap-1 sm:grid-cols-2">{allowances.map(expense=><p key={expense.id}>{pilotAllowances[expense.id.slice(6) as keyof typeof pilotAllowances]?.label??expense.label}: {money(expense.amount.value)}{expense.months.value&&expense.months.value>1?` per month × ${expense.months.value}`:' one-time'} · {expense.amount.kind}</p>)}</div>}
  <p>Allowances exclude salaries, pay changes, backfill, recruiting fees and vendor quotes. Employee time, availability and retention effects remain unresolved. Review overlap and cost completeness before treating any total as a budget.</p>
  {lastFinish&&end&&lastFinish>end&&<p role="alert">Proposed component dates extend beyond the shared horizon. Review the actual dates before calculating.</p>}
  <details><summary className="cursor-pointer py-1">Assumption provenance and dates</summary><p>{draft.pilot!.version} · frozen at {draft.pilot!.preparedAt} · UTC calendar. New demo dates begin next full month; two-week dependency stages are activity assumptions, not readiness guarantees. Existing values and later edits take precedence.</p>{input.timing.map(item=><p key={item.componentId}>{bundleComponentLabels([item.componentId],draft.bundle)}: {item.start.value??'Unknown'}–{item.finish.value??'Unknown'} ({item.start.kind}/{item.finish.kind})</p>)}</details>
 </section>;
}
