"use client";
import {useSyncExternalStore} from 'react';
import type {BundleDiscussion} from '@/components/home-bundle-plans';
import type {BundleEditPreview} from '@/lib/home-bundle-chat-edit';
import {bundleAssumptionText} from '@/lib/home-bundle-display';
const button='min-h-11 rounded border px-3 py-2 text-sm font-medium disabled:opacity-50 focus-visible:ring-2 focus-visible:ring-ring';
export function HomeBundleChatReview({target,preview,text,busy,notice,onClose}:{target:BundleDiscussion;preview:BundleEditPreview|null;text:string;busy:boolean;notice:string;onClose:()=>void}){
 const current=useSyncExternalStore(target.subscribe,target.isCurrent,()=>false),sameText=preview?.request===text.trim();
 return <section aria-label="Review chat changes" className="space-y-2 rounded border border-primary/50 p-3 text-sm">
  <h3 className="font-semibold">Adjust Action Plan #{target.option} · revision {target.revision}</h3><p>Goal: {target.goal}</p>
  {!preview&&<><p>Use the chat box to describe changes for this plan, then Send to review them here.</p>{current&&<div className="space-y-2 text-xs"><p>Examples for this plan only. Sample values demonstrate syntax, not recommendations. Type your chosen change in the chat box; nothing is sent or filled automatically.</p><ul aria-label="Examples for selected plan" className="space-y-2">{target.examples.map(example=><li key={example.field} className="min-w-0 break-words"><p><strong>{example.field}</strong> · {example.unit} · Current: {bundleAssumptionText(example.current)}</p><code className="block whitespace-normal">{example.command}</code></li>)}</ul></div>}<details className="text-xs"><summary className="min-h-11 cursor-pointer py-2">Supported changes</summary><p>Common phrases work for the shared start month, duration and a single participant group. If there are multiple groups, name the group. For an expense amount, use its displayed name and cost basis, or use a component name followed by start or finish for an exact date. Unknown clears a value; starting estimates remain assumptions. Turnover scenarios accept baseline turnover, target turnover and average workforce; capacity scenarios accept target additional roles and monthly cost per role. Values are assumptions, not predicted effects. Ambiguous budgets need clarification. Staffing, total budget limits and plan wording use Attach Action Plan → Review plan fields. Shared date changes do not move component or funding dates automatically.</p></details></>}
  {!current&&<p role="status">The selected plan or context changed. Your text is kept. Select the intended Plan tab and send the change again for a fresh review.</p>}
  {notice&&<p role="status">{notice}</p>}
  {preview&&<><ul className="list-disc space-y-2 pl-5">{preview.changes.map(change=><li key={change.field}><strong>{change.field}:</strong> {bundleAssumptionText(change.before)} → {bundleAssumptionText(change.after)}</li>)}</ul><p className="text-xs">Accept into the working draft, then use Attach Action Plan to review the calculation and confirm attachment. Attached versions stay in history.</p>{!sameText&&<p role="status">Your text changed after this preview. Send it again to review the current request.</p>}<p>{busy||!current||!sameText?'Apply changes is unavailable until this review matches the current plan and chat text.':'Choose Apply changes on the Action Plan panel above to accept this exact review.'}</p></>}
  <button type="button" className={button} onClick={onClose}>Return to general chat</button>
 </section>;
}
