"use client";
import { datasetFetch } from "@/lib/dataset-client.mjs";

import {bundleAssumptionCopy} from '@/lib/home-bundle-display';
import {HomeSuccessMeasureReview} from '@/components/home-success-measure-review';
import {useEffect,useState} from 'react';
import {emptyWorkforcePlanInput,planDate,type WorkforcePlanField} from '@/lib/workforce-increment';
import {cashHoursInputs,unknownAssumption,type Assumption,type BundleDraft,type BundleInputs,type ExpenseLink} from '@/lib/home-bundle-reconciliation';
import type {SolutionBundle} from '@/lib/home-solution-bundles';
const button='min-h-11 rounded border px-3 py-2 text-sm font-medium disabled:opacity-50 focus-visible:ring-2 focus-visible:ring-ring';
const control='mt-1 min-h-11 w-full rounded border bg-background px-2 py-1 text-sm';
const capacityLabels:Partial<Record<WorkforcePlanField,string>>={roles:'Additional roles',build:'Development transitions',move:'Direct internal moves',buy:'External hires',backfills:'External backfills',arrivalDate:'Hire arrival date',buildMonth:'Development readiness month',moveMonth:'Move month',backfillDate:'Backfill arrival date',annualHireCost:'Annual cost per hire (USD)',hireFee:'Fee per hire (USD)',annualBackfillCost:'Annual cost per backfill (USD)',backfillFee:'Fee per backfill (USD)',internalAnnualCostChange:'Total annual internal salary uplift (USD)',trainingCash:'Training cash (USD)',trainingHours:'Employee training hours',loadedHourlyCost:'Loaded hourly cost (USD)',budget:'Incremental cash budget (USD)',maxAddedEmployees:'Maximum added employees',deadlineMonth:'Coverage deadline month'};
const sources=[['capacity:hireStaffingCost','Hire staffing'],['capacity:backfillStaffingCost','Backfill staffing'],['capacity:internalSalaryUplift','Internal salary uplift'],['capacity:recruitingFees','Recruiting fees'],['capacity:trainingCash','Training cash']];
type Catalog={business_units:{org_code:string;org_name:string}[];job_profiles:{job_profile_code:string;job_profile_name:string}[]};
function MonthAssumptionInput({value,label,onChange,onPending}:{value:string;label:string;onChange:(value:string)=>void;onPending:(pending:boolean)=>void}){
 useEffect(()=>()=>onPending(false),[onPending]);
 const [edit,setEdit]=useState({committed:value,text:value}),[touched,setTouched]=useState(false);
 if(edit.committed!==value)setEdit({committed:value,text:value});
 const valid=(text:string)=>/^\d{4}-(0[1-9]|1[0-2])$/.test(text)&&planDate(text+'-01')!==null;
 const invalid=!!edit.text&&!valid(edit.text);
 return <><input className={control} type="text" inputMode="text" aria-label={label} placeholder="YYYY-MM" maxLength={7} value={edit.text} aria-invalid={invalid&&touched} onChange={event=>{const text=event.target.value;setEdit({committed:value,text});setTouched(false);onPending(!!text&&!valid(text));if(!text||valid(text))onChange(text);}} onBlur={()=>setTouched(true)}/><span className="block text-xs text-muted-foreground">Year and month: YYYY-MM (for example, 2027-01).</span>{invalid&&touched&&<span role="alert" className="block text-xs text-destructive">Enter a complete month as YYYY-MM. This text is not applied; the last valid month is kept.</span>}</>;
}
export function HomeBundleEditor({draft,optionNumber,disabled,onChange,onProposalChange,onPendingInput,measurePack}:{measurePack?:unknown;onPendingInput:(pending:boolean)=>void;optionNumber:number;draft:BundleDraft;disabled:boolean;onChange:(inputs:BundleInputs)=>void;onProposalChange:(bundle:SolutionBundle)=>void}){
 const input=draft.inputs,[tab,setTab]=useState('Scope'),[basis,setBasis]=useState<'user-entered'|'illustrative'>('user-entered'),[catalog,setCatalog]=useState<Catalog|null>(null);
 useEffect(()=>{const controller=new AbortController();void datasetFetch('/api/position-structure',{signal:controller.signal}).then(response=>response.ok?response.json():null).then(data=>{if(data&&Array.isArray(data.business_units)&&Array.isArray(data.job_profiles)&&!controller.signal.aborted)setCatalog(data)}).catch(()=>{});return()=>controller.abort();},[]);
 const assumption=<T,>(value:T|null):Assumption<T>=>value===null?unknownAssumption<T>():{value,kind:basis,basis:basis==='illustrative'?'Editable illustrative scenario assumption; not evidence.':'Explicitly entered or confirmed for this bundle; not independently verified.'};
 function update(run:(next:BundleInputs)=>void){const next=cashHoursInputs(input);run(next);onChange(next);}
 function scope(field:keyof BundleInputs['scope'],value:string){update(next=>{
  if(field==='currency')return;
  if(field==='months'||field==='demand')next.scope[field]=assumption(value===''?null:Number(value));else if(field==='capacityRequired'||field==='comparisonConfirmed')next.scope[field]=assumption(value===''?null:value==='true');else next.scope[field]=assumption(value||null);
  if(field==='capacityRequired'&&value==='true'&&!next.capacity){const capacity=emptyWorkforcePlanInput();capacity.intent='additional';for(const [key,source] of [['businessUnit','businessUnit'],['jobProfile','jobProfile'],['planningMonth','startMonth'],['months','months'],['roles','demand']] as const)capacity[key]=String(next.scope[source].value??'');next.capacity={input:capacity,origins:Object.fromEntries(Object.entries(capacity).map(([key,value])=>[key,value?{kind:'user-entered',basis:'Explicit additional-capacity scope confirmation.'}:{kind:'unknown',basis:null}])),flows:[]};}
  const map:Partial<Record<keyof BundleInputs['scope'],WorkforcePlanField>>={businessUnit:'businessUnit',jobProfile:'jobProfile',startMonth:'planningMonth',months:'months',demand:'roles'};const capacityField=map[field];if(next.capacity&&capacityField){next.capacity.input[capacityField]=value;next.capacity.origins[capacityField]=value?{kind:basis,basis:'Explicit shared scope assumption.'}:{kind:'unknown',basis:null};}
 });}
 function capacity(field:WorkforcePlanField,value:string){update(next=>{if(!next.capacity)return;next.capacity.input[field]=value;next.capacity.origins[field]=value?{kind:basis,basis:'Explicit staffing scenario assumption; availability unverified.'}:{kind:'unknown',basis:null};if(field==='arrivalDate'){next.capacity.input.arrivalMode=value?'explicit':'';next.capacity.origins.arrivalMode=value?{kind:basis,basis:'Explicit arrival-date assumption.'}:{kind:'unknown',basis:null};}if(['build','move','buy','backfills'].includes(field)&&Number(value)===0)next.capacity.flows=next.capacity.flows.filter(flow=>flow.path!==field);});}
 function scopeField(field:'population'|'businessUnit'|'jobProfile'|'startMonth'|'months'|'demand'|'requirements',label:string,type='text'){
  const options=field==='businessUnit'?catalog?.business_units.map(item=>[item.org_code,item.org_name]):field==='jobProfile'?catalog?.job_profiles.map(item=>[item.job_profile_code,item.job_profile_name]):null,value=String(input.scope[field].value??'');
  return <label className="block" key={field}>{label}{options?<select className={control} aria-label={label} value={value} onChange={event=>scope(field,event.target.value)}><option value="">Choose</option>{value&&!options.some(([id])=>id===value)&&<option value={value}>{value} — retained assumption</option>}{options.map(([id,name])=><option key={id} value={id}>{name}</option>)}</select>:type==='month'?<MonthAssumptionInput onPending={onPendingInput} value={value} label={label} onChange={value=>scope(field,value)}/>:<input className={control} type={type} aria-label={label} value={value} onChange={event=>scope(field,event.target.value)} maxLength={240}/>}<span className="text-xs text-muted-foreground">{bundleAssumptionCopy(input.scope[field].kind)}</span></label>;
 }
 function capField(field:WorkforcePlanField){const label=capacityLabels[field]??field,type=field.toLowerCase().includes('date')?'date':field.toLowerCase().includes('month')?'month':'number';return <label key={field} className="block">{label}<input className={control} type={type} aria-label={label} value={input.capacity?.input[field]??''} onChange={event=>capacity(field,event.target.value)}/><span className="text-xs text-muted-foreground">{input.capacity?.origins[field].kind}</span></label>}
 function linkEditor(expenseId:string,label:string){const link=input.expenseLinks.find(item=>item.expenseId===expenseId);return <details key={expenseId}><summary className="min-h-11 cursor-pointer py-2">Link shared cost: {label}</summary><p className="text-xs">Count this expense once and select every component it supports. Changing membership clears its optional percentage split, keeping the amount.</p>{draft.bundle.components.map(component=><label className="my-2 flex items-start gap-2" key={component.id}><input type="checkbox" aria-label={`${label} supports ${component.name}`} checked={link?.componentIds.includes(component.id)??false} onChange={event=>update(next=>{const prior=next.expenseLinks.find(item=>item.expenseId===expenseId),ids=event.target.checked?[...prior?.componentIds??[],component.id]:(prior?.componentIds??[]).filter(id=>id!==component.id);next.expenseLinks=next.expenseLinks.filter(item=>item.expenseId!==expenseId);if(ids.length)next.expenseLinks.push({expenseId,componentIds:ids,allocations:null});})}/>{component.name}</label>)}{link&&link.componentIds.length>1&&<AllocationEditor key={JSON.stringify(link)} link={link} bundle={draft.bundle} onChange={allocations=>update(next=>{next.expenseLinks.find(item=>item.expenseId===expenseId)!.allocations=allocations;})}/>}</details>}
 const nextQuestion=!input.scope.population.value?'Which aggregate population should this combined plan cover?':!input.scope.startMonth.value?'When should the shared planning horizon start?':!input.scope.months.value?'How many months should the combined plan cover?':input.scope.capacityRequired.value===null?'Does this Action Plan require additional role capacity?':null;
 return <section aria-label="Action Plan editor" className="space-y-3 rounded border p-3"><h4 className="font-semibold">Review option {optionNumber} · revision {draft.revision}</h4><p className="text-xs">Edits stay in this tab until Save Action Plan draft. Blank values remain Unknown; enter zero only when you explicitly assume none. Calculations and attachment are separate actions.</p>
  <label className="block text-xs">Basis for new edits<select className={control} value={basis} onChange={event=>setBasis(event.target.value as typeof basis)}><option value="user-entered">My planning assumption</option><option value="illustrative">Assumed — not evidence</option></select></label>
  <div className="flex flex-wrap gap-2" role="group" aria-label="Bundle assumption sections">{['Scope','Staffing','Budget','Timeline','Participants','Plan wording'].map(label=><button className={button} key={label} aria-pressed={tab===label} onClick={()=>setTab(label)}>{label}</button>)}</div>
  {nextQuestion&&<p className="font-medium">Next: {nextQuestion}</p>}
  <fieldset disabled={disabled} className="space-y-3">
   {tab==='Scope'&&<><HomeSuccessMeasureReview key={JSON.stringify([draft.revision,measurePack])} draft={draft} pack={measurePack} basis={basis} disabled={disabled} onAccept={onChange}/><div className="grid gap-3 sm:grid-cols-2">{scopeField('population','Aggregate population')}{scopeField('startMonth','Shared start month','month')}{scopeField('months','Shared horizon (months)','number')}</div><label className="block">Additional role capacity required?<select aria-label="Additional role capacity required?" className={control} value={input.scope.capacityRequired.value===null?'':String(input.scope.capacityRequired.value)} onChange={event=>scope('capacityRequired',event.target.value)}><option value="">Unknown — review scope</option><option value="true">Yes, additional roles</option><option value="false">No additional roles in this solution</option></select></label>{input.scope.capacityRequired.value&&<div className="grid gap-3 sm:grid-cols-2">{scopeField('businessUnit','Business unit')}{scopeField('jobProfile','Role')}{scopeField('demand','Additional role requirement','number')}</div>}{input.scope.capacityRequired.value===false&&input.capacity&&<><p>The previous staffing inputs are retained. Remove them explicitly to calculate a plan without additional capacity.</p><button className={button} onClick={()=>update(next=>{next.capacity=null;next.expenseLinks=next.expenseLinks.filter(item=>!item.expenseId.startsWith('capacity:'));})}>Remove capacity mix from this draft</button></>}{scopeField('requirements','Common requirements for comparing options')}<label className="flex items-start gap-2"><input type="checkbox" checked={input.scope.comparisonConfirmed.value===true} onChange={event=>scope('comparisonConfirmed',String(event.target.checked))}/><span>I reviewed this scope and requirements as the same comparison basis for the options.</span></label><button className={button} onClick={()=>setTab(input.capacity?'Staffing':'Budget')}>Next relevant assumptions</button></>}
   {tab==='Staffing'&&(input.capacity?<><div className="grid gap-3 sm:grid-cols-2">{(['build','move','buy','backfills'] as WorkforcePlanField[]).map(capField)}</div><p className="text-xs">Development, direct moves and external hires must sum to the additional requirement. Learning plus the same internal transition is one flow, not two people. Backfills are separate external hires.</p>{(['build','move','buy','backfills'] as const).filter(path=>Number(input.capacity!.input[path])>0).map(path=>{const flow=input.capacity!.flows.find(item=>item.path===path);return <details key={path} open><summary className="min-h-11 cursor-pointer py-2">Coordinate {capacityLabels[path]}</summary><p>Select the components whose completion is required for this flow.</p>{draft.bundle.components.map(component=><label key={component.id} className="my-2 flex items-start gap-2"><input type="checkbox" aria-label={`${path} depends on ${component.name}`} checked={flow?.componentIds.includes(component.id)??false} onChange={event=>update(next=>{const flows=next.capacity!.flows,prior=flows.find(item=>item.path===path),ids=event.target.checked?[...prior?.componentIds??[],component.id]:(prior?.componentIds??[]).filter(id=>id!==component.id);next.capacity!.flows=flows.filter(item=>item.path!==path);if(ids.length)next.capacity!.flows.push({id:`flow-${path}`,path,componentIds:ids,groupId:prior?.groupId??null});})}/>{component.name}</label>)}{(path==='build'||path==='move')&&<label className="block">Aggregate source group<select aria-label={`Source group for ${path}`} className={control} value={flow?.groupId??''} disabled={!flow} onChange={event=>update(next=>{next.capacity!.flows.find(item=>item.path===path)!.groupId=event.target.value||null;})}><option value="">Review groups in Participants</option>{input.groups.map(group=><option key={group.id} value={group.id}>{group.label}</option>)}</select></label>}</details>})}<div className="grid gap-3 sm:grid-cols-2">{[...(Number(input.capacity.input.buy)>0?['arrivalDate']:[]),...(Number(input.capacity.input.build)>0?['buildMonth']:[]),...(Number(input.capacity.input.move)>0?['moveMonth']:[]),...(Number(input.capacity.input.backfills)>0?['backfillDate']:[])].map(field=>capField(field as WorkforcePlanField))}</div><button className={button} onClick={()=>setTab('Budget')}>Next: shared budget</button></>:<p>Review whether additional capacity is required in Scope first. Other components can still have a shared budget and timeline.</p>)}
   {tab==='Budget'&&<><p>Review every component’s incremental cash costs. Staff effort is tracked in hours. Shared expenses belong in one record; they can support multiple components.</p>{input.capacity&&<details><summary className="min-h-11 cursor-pointer py-2 font-medium">Staffing and learning costs</summary><div className="grid gap-3 sm:grid-cols-2">{[...(Number(input.capacity.input.buy)>0?['annualHireCost','hireFee']:[]),...(Number(input.capacity.input.build)+Number(input.capacity.input.move)>0?['internalAnnualCostChange']:[]),...(Number(input.capacity.input.build)>0?['trainingCash','trainingHours']:[]),...(Number(input.capacity.input.backfills)>0?['annualBackfillCost','backfillFee']:[])].map(field=>capField(field as WorkforcePlanField))}</div>{sources.map(([id,label])=>linkEditor(id,label))}</details>}
    {input.expenses.filter(expense=>expense.kind==='cash').map(expense=><section key={expense.id} className="space-y-2 rounded border p-3"><label className="block">Expense label<input className={control} aria-label={`Label for ${expense.id}`} value={expense.label} onChange={event=>update(next=>{next.expenses.find(item=>item.id===expense.id)!.label=event.target.value;})}/></label><label className="block">Type<select className={control} aria-label={`Type for ${expense.id}`} value={expense.kind} onChange={event=>update(next=>{next.expenses.find(item=>item.id===expense.id)!.kind=event.target.value as typeof expense.kind;})}><option value="cash">Incremental cash</option></select></label><div className="grid gap-3 sm:grid-cols-3">{(['amount','startMonth','months'] as const).map(field=><label key={field} className="block">{field==='amount'?'Amount per occurrence (USD)':field==='months'?'Monthly occurrences (1 for one-time)':'Funding start month'}<input className={control} aria-label={`${field} for ${expense.id}`} type={field==='startMonth'?'month':'number'} value={expense[field].value??''} onChange={event=>update(next=>{const item=next.expenses.find(item=>item.id===expense.id)!;if(field==='startMonth')item.startMonth=assumption(event.target.value||null);else item[field]=assumption(event.target.value===''?null:Number(event.target.value));})}/><span className="text-xs">{bundleAssumptionCopy(expense[field].kind)}</span></label>)}</div>{linkEditor(expense.id,expense.label)}<button className={button} onClick={()=>update(next=>{next.expenses=next.expenses.filter(item=>item.id!==expense.id);next.expenseLinks=next.expenseLinks.filter(item=>item.expenseId!==expense.id);})}>Remove {expense.label}</button></section>)}
    <button className={button} onClick={()=>update(next=>{next.expenses.push({id:`expense-${crypto.randomUUID()}`,label:'New shared expense',kind:'cash',amount:unknownAssumption(),startMonth:unknownAssumption(),months:unknownAssumption()});next.costReviews=next.costReviews.map(item=>({...item,complete:unknownAssumption()}));next.costsDistinct=unknownAssumption();})}>Add component or shared expense</button>
    <label className="flex items-start gap-2"><input type="checkbox" checked={input.costReviews.every(item=>item.complete.value===true)} onChange={event=>update(next=>{next.costReviews=next.costReviews.map(item=>({...item,complete:assumption(event.target.checked)}));})}/><span>I reviewed costs for every component, including explicit no-additional-cost assumptions where no expense applies. Missing known amounts still remain Unknown.</span></label><label className="flex items-start gap-2"><input type="checkbox" checked={input.costsDistinct.value===true} onChange={event=>update(next=>{next.costsDistinct=assumption(event.target.checked);})}/><span>Each expense is counted once. Manual expenses are additional to the staffing, training and salary lines; shared costs use the same record.</span></label><button className={button} onClick={()=>setTab('Timeline')}>Next: coordinated timeline</button></>}
   {tab==='Timeline'&&<><p>Review proposed prerequisites and dates. Unknown readiness stays Unknown; paid arrival is not automatically deployment.</p>{draft.bundle.components.map(component=>{const timing=input.timing.find(item=>item.componentId===component.id)!;return <section key={component.id} className="rounded border p-3"><h5 className="font-semibold">{component.name}</h5><p className="text-xs">After: {component.dependsOn.map(id=>draft.bundle.components.find(item=>item.id===id)?.name).join(', ')||'No proposed prerequisite'}.</p><div className="grid gap-3 sm:grid-cols-2">{(['start','finish'] as const).map(field=><label key={field}>{field==='start'?'Planned start':'Readiness/finish assumption'}<input className={control} aria-label={`${field} for ${component.name}`} type="date" value={timing[field].value??''} onChange={event=>update(next=>{next.timing.find(item=>item.componentId===component.id)![field]=assumption(event.target.value||null);})}/></label>)}</div></section>})}<label className="flex items-start gap-2"><input type="checkbox" checked={input.dependenciesConfirmed.value===true} onChange={event=>update(next=>{next.dependenciesConfirmed=assumption(event.target.checked);})}/><span>I reviewed these dependencies and readiness assumptions. Dates are not guarantees of availability or effectiveness.</span></label></>}
   {tab==='Participants'&&<><p>Reuse the same group for overlapping components. Split partially overlapping populations into reviewed disjoint groups before claiming a unique total. No individual people are entered.</p>{input.groups.map(group=><div key={group.id} className="grid gap-3 rounded border p-3 sm:grid-cols-2"><label>Aggregate group label<input className={control} aria-label={`Label for ${group.id}`} value={group.label} onChange={event=>update(next=>{next.groups.find(item=>item.id===group.id)!.label=event.target.value;})}/></label><label>Reviewed participant count<input className={control} aria-label={`Count for ${group.id}`} type="number" value={group.count.value??''} onChange={event=>update(next=>{next.groups.find(item=>item.id===group.id)!.count=assumption(event.target.value===''?null:Number(event.target.value));})}/></label></div>)}<button className={button} onClick={()=>update(next=>{next.groups.push({id:`group-${crypto.randomUUID()}`,label:`Aggregate group ${next.groups.length+1}`,count:unknownAssumption()});next.groupsDisjoint=unknownAssumption();})}>Add aggregate group</button>{draft.bundle.components.map(component=>{const membership=input.memberships.find(item=>item.componentId===component.id);return <details key={component.id}><summary className="min-h-11 cursor-pointer py-2">Participants: {component.name}</summary>{input.groups.map(group=><label key={group.id} className="my-2 flex gap-2"><input type="checkbox" checked={membership?.groupIds.includes(group.id)??false} onChange={event=>update(next=>{const prior=next.memberships.find(item=>item.componentId===component.id),ids=event.target.checked?[...prior?.groupIds??[],group.id]:(prior?.groupIds??[]).filter(id=>id!==group.id);next.memberships=next.memberships.filter(item=>item.componentId!==component.id);next.memberships.push({componentId:component.id,groupIds:ids,complete:unknownAssumption()});})}/>{group.label}</label>)}<label className="my-2 flex gap-2"><input type="checkbox" checked={membership?.complete.value===true} onChange={event=>update(next=>{let prior=next.memberships.find(item=>item.componentId===component.id);if(!prior){prior={componentId:component.id,groupIds:[],complete:unknownAssumption()};next.memberships.push(prior);}prior.complete=assumption(event.target.checked);})}/><span>I reviewed all participating groups for this component, including none if no group applies.</span></label></details>})}<label className="flex gap-2"><input type="checkbox" checked={input.groupsDisjoint.value===true} onChange={event=>update(next=>{next.groupsDisjoint=assumption(event.target.checked);})}/><span>Different group records are disjoint; shared participants reuse a group record.</span></label></>}
   {tab==='Plan wording'&&<><p>Editing the plan keeps your numbers but requires fresh cost and dependency review. Adding or removing components requires a separate explicit reconciliation.</p>{draft.bundle.components.map(component=><ComponentEditor key={draft.signature+component.id} bundle={draft.bundle} componentId={component.id} onSave={onProposalChange}/>)}</>}
  </fieldset>
 </section>;
}
function AllocationEditor({link,bundle,onChange}:{link:ExpenseLink;bundle:SolutionBundle;onChange:(allocation:ExpenseLink['allocations'])=>void}){
 const [values,setValues]=useState<Record<string,string>>(()=>Object.fromEntries(link.componentIds.map(id=>[id,String(link.allocations?.find(item=>item.componentId===id)?.percent??'')])));
 return <details><summary className="min-h-11 cursor-pointer py-2">Optional component percentage allocation</summary><p className="text-xs">The combined expense still counts once. Apply a complete split totaling 100%.</p>{link.componentIds.map(id=><label className="block" key={id}>{bundle.components.find(item=>item.id===id)?.name} (%)<input className={control} type="number" value={values[id]} onChange={event=>setValues({...values,[id]:event.target.value})}/></label>)}<button className={button} disabled={Object.values(values).some(value=>value==='')} onClick={()=>onChange(link.componentIds.map(componentId=>({componentId,percent:Number(values[componentId])})))}>Apply percentage allocation</button></details>;
}
function ComponentEditor({bundle,componentId,onSave}:{bundle:SolutionBundle;componentId:string;onSave:(bundle:SolutionBundle)=>void}){
 const component=bundle.components.find(item=>item.id===componentId)!,[wording,setWording]=useState(component.firstStep),[dependencies,setDependencies]=useState(component.dependsOn);
 return <details><summary className="min-h-11 cursor-pointer py-2">Edit {component.name}</summary><label className="block">Complete first step<textarea className={control} aria-label={`First step for ${component.name}`} maxLength={360} value={wording} onChange={event=>setWording(event.target.value)}/></label><p>Prerequisites</p>{bundle.components.filter(item=>item.id!==componentId).map(item=><label key={item.id} className="my-2 flex gap-2"><input type="checkbox" checked={dependencies.includes(item.id)} onChange={event=>setDependencies(event.target.checked?[...dependencies,item.id]:dependencies.filter(id=>id!==item.id))}/>{item.name}</label>)}<button className={button} disabled={!wording.trim()} onClick={()=>onSave({...bundle,components:bundle.components.map(item=>item.id===componentId?{...item,firstStep:wording,dependsOn:dependencies}:item)})}>Save component wording</button></details>;
}
