"use client";
import {homePlanPanelField,readHomePlanPanel} from '@/lib/home-plan-panel';
import {calculatePlanWhatIf,whatIfOutcomeText} from '@/lib/home-plan-what-if';
import {suggestSuccessMeasure,successMeasureText,measurementScope} from '@/lib/home-success-measures';
import {preferredSavedBundleId,restoredBundleDraft,restoredBundleResult} from "@/lib/home-pinned-goals";
import {prepareIllustrativePilot,pilotAllowances} from '@/lib/home-action-plan-pilot';
import {useId,useLayoutEffect,useRef,useState} from 'react';
import {previewBundleChatEdit,acceptBundleChatEdit,bundleChatEditExamples,type BundleEditExample,type BundleEditPreview} from '@/lib/home-bundle-chat-edit';
import {decisionStore,useDecisionStorage} from '@/components/decision-store';
import {bundleIsAnalysisOnly,bundleDisplayText,bundleComponentLabels,bundleDisplayName,bundleAssumptionText,bundleHorizonEnd} from '@/lib/home-bundle-display';
import {HomePlanIntegration} from '@/components/home-plan-integration';
import {HomeBundleEditor} from '@/components/home-bundle-editor';
import {HomeActionPlanApplication} from '@/components/home-action-plan-application';
import {HomeLinkedAttachment} from '@/components/home-linked-attachment';
import type {ProjectPlanningBinding} from '@/lib/home-linked-attachment';
import {actionBindingKey,type ActionBinding} from '@/lib/home-action-drafts';
import type {BundleProposal,SolutionBundle} from '@/lib/home-solution-bundles';
import {createBundleDraft,reviseBundleDraft,reviseBundleProposal,reconcileBundle,bundleInputKey,compareCurrentBundleResults,type BundleDraft,type BundleInputs,type BundleResult} from '@/lib/home-bundle-reconciliation';
import {readBundleWorkspace,saveBundleDraftPatch,saveBundleCalculationPatch,attachBundlePatch,attachedBundleState,bundleWorkspaceField} from '@/lib/home-bundle-records';
export const bundleButton='min-h-11 rounded border px-3 py-2 text-sm font-medium disabled:opacity-50 focus-visible:ring-2 focus-visible:ring-ring';
export type PlanChatChange={goalId:string;planId:string;inputKey:string;ready:boolean;isCurrent:()=>boolean;apply:()=>void};
export type BundleSession={drafts:Record<string,BundleDraft>;results:Record<string,BundleResult>};
export type BundleDiscussion={examples:BundleEditExample[];option:number;id:string;revision:number;name:string;goalId:string;goal:string;subscribe:(listener:()=>void)=>()=>void;isCurrent:()=>boolean;preview:(text:string)=>BundleEditPreview;accept:(preview:BundleEditPreview)=>void};
const money=(value:number|null|undefined)=>value==null?'Unknown':`$${value.toLocaleString(undefined,{maximumFractionDigits:2})} USD`;
export function HomeBundlePlans({chatChange,planningContext,proposal,binding,preparedAt,contextCurrent,disabled,isCurrent,cache,onDiscuss,projectBinding,measurePack}:{chatChange?:PlanChatChange|null;planningContext?:unknown;measurePack?:unknown;projectBinding?:ProjectPlanningBinding;preparedAt:string;proposal:BundleProposal;binding:ActionBinding;contextCurrent:boolean;disabled:boolean;isCurrent:()=>boolean;cache:Map<string,BundleSession>;onDiscuss:(request:BundleDiscussion)=>void}){
 const optionNumber=(id:string)=>proposal.bundles.findIndex(bundle=>bundle.id===id)+1;
 const storage=useDecisionStorage(),raw=storage.data.workspaces[binding.goalId]?.fields[bundleWorkspaceField],workspace=readBundleWorkspace(raw,binding.goalId),key=actionBindingKey(binding);
 const [session,setSession]=useState<BundleSession>(()=>{
  const cached=cache.get(key);if(cached)return cached;
  const drafts=Object.fromEntries(proposal.bundles.map(bundle=>[bundle.id,restoredBundleDraft(workspace,binding,bundle.id)??prepareIllustrativePilot(createBundleDraft(bundle,binding),preparedAt,{goalContext:planningContext})]));
  const results:Record<string,BundleResult>={};for(const [id,draft] of Object.entries(drafts)){const result=restoredBundleResult(workspace,draft);if(result)results[id]=result;}
  return {drafts,results};
 });
 const savedView=readHomePlanPanel(storage.data.workspaces[binding.goalId]?.fields[homePlanPanelField]);
 const [collapsed,setCollapsed]=useState(savedView.collapsed),[comparing,setComparing]=useState(false);const panelId=useId(),applyHintId=useId(),comparisonRef=useRef<HTMLElement>(null);
 function saveView(next:{collapsed?:boolean;appliedId?:'A'|'B'|'C'}){const snapshot=decisionStore.getSnapshot();if(snapshot.data.goals.activeId!==binding.goalId||!snapshot.saved)return;decisionStore.setField(binding.goalId,homePlanPanelField,{...readHomePlanPanel(snapshot.data.workspaces[binding.goalId]?.fields[homePlanPanelField]),...next});}
 const liveSession=useRef(session);
 const [pendingInput,setPendingInput]=useState(false);
 const [attachmentOpen,setAttachmentOpen]=useState<string|null>(null);
 const [attachFlow,setAttachFlow]=useState<string|null>(null);
 const attachmentReview=useRef<HTMLElement>(null);
 const [selected,setSelected]=useState(()=>savedView.appliedId&&proposal.bundles.some(bundle=>bundle.id===savedView.appliedId)?savedView.appliedId:preferredSavedBundleId(workspace,binding,proposal.bundles.map(bundle=>bundle.id))),[editor,setEditor]=useState(false),[notice,setNotice]=useState(''),[reviewed,setReviewed]=useState<string|null>(null),[unknowns,setUnknowns]=useState<string|null>(null);
 const heading=useRef<HTMLHeadingElement>(null),draft=session.drafts[selected],result=session.results[selected],currentResult=draft&&contextCurrent&&result?.inputKey===bundleInputKey(draft)?result:null;
 const liveSelection=useRef(selected),selectionEpoch=useRef(0),livePending=useRef(pendingInput),mounted=useRef(true),editListeners=useRef(new Set<()=>void>()),liveAvailable=useRef(contextCurrent&&!disabled);
 useLayoutEffect(()=>{if(liveSelection.current!==selected||liveAvailable.current&&(!contextCurrent||disabled))selectionEpoch.current++;liveSelection.current=selected;liveSession.current=session;livePending.current=pendingInput;liveAvailable.current=contextCurrent&&!disabled;for(const listener of editListeners.current)listener();});
 useLayoutEffect(()=>{mounted.current=true;const listeners=editListeners.current;return()=>{mounted.current=false;for(const listener of listeners)listener();};},[]);
 function guard(){if(disabled||!contextCurrent||!isCurrent()||!decisionStore.getSnapshot().saved)throw Error('The goal, evidence or saved planning context changed. Your draft is kept; review the current context first.');}
 function remember(next:BundleSession){if(!cache.has(key)&&cache.size>=12)throw Error('This tab already holds twelve bundle contexts. Save your work before opening more.');cache.set(key,next);liveSession.current=next;setSession(next);setNotice('');}
 function edit(inputs:BundleInputs){try{guard();const measureChanged=JSON.stringify(inputs.successMeasure??null)!==JSON.stringify(draft.inputs.successMeasure??null);remember({...session,drafts:{...session.drafts,[selected]:reviseBundleDraft(draft,inputs)}});if(measureChanged){setNotice('Reviewed success measure accepted into the working draft. Use Attach Action Plan to review the revised calculation and attachment.');requestAnimationFrame(()=>{heading.current?.focus({preventScroll:true});heading.current?.scrollIntoView({block:'nearest'});});}}catch(error){setNotice((error as Error).message)}}
 function editProposal(bundle:SolutionBundle){try{guard();remember({...session,drafts:{...session.drafts,[selected]:reviseBundleProposal(draft,bundle)}});}catch(error){setNotice((error as Error).message)}}
 function calculate(){try{guard();if(pendingInput)throw Error('Complete the month entry before calculating.');const calculated=reconcileBundle(draft);remember({...session,results:{...session.results,[selected]:calculated}});requestAnimationFrame(()=>{attachmentReview.current?.focus({preventScroll:true});attachmentReview.current?.scrollIntoView({block:'nearest'});});}catch(error){setNotice((error as Error).message);setEditor(true);}}
 function persist(attach=false){try{guard();if(pendingInput)throw Error('Complete the month entry before saving or attaching.');const previous=decisionStore.getSnapshot().data.workspaces[binding.goalId]?.fields[bundleWorkspaceField];let patch=currentResult?saveBundleCalculationPatch(previous,draft,currentResult):saveBundleDraftPatch(previous,draft);
  if(attach){if(!currentResult||reviewed!==bundleInputKey(draft))throw Error('Calculate and review this exact version before attaching it.');const store=patch.value,superseded=new Set(store.attachments.map(item=>item.supersedes)),prior=store.attachments.findLast(item=>!superseded.has(item.id)&&item.draft.bundle.id===selected);patch=attachBundlePatch(store,draft,{confirmed:true,bindingKey:key,inputKey:bundleInputKey(draft),acknowledgeUnknowns:unknowns===bundleInputKey(draft)},crypto.randomUUID(),new Date().toISOString(),prior?.id??null);}
  decisionStore.setField(binding.goalId,patch.field,patch.value);if(!decisionStore.getSnapshot().saved)throw Error('Browser storage could not save. Your working draft is kept in this tab.');if(attach)saveView({appliedId:draft.bundle.id});setNotice(attach?'Reviewed Action Plan attached to this goal. It is not operational approval.':'Action Plan draft and any current calculation saved locally. Existing plans and pins are unchanged.');return true;
 }catch(error){setNotice((error as Error).message);return false}}
 function registerChatTarget(){const inputKey=bundleInputKey(draft),epoch=selectionEpoch.current,current=()=>mounted.current&&liveAvailable.current&&!livePending.current&&selectionEpoch.current===epoch&&liveSelection.current===selected&&isCurrent()&&bundleInputKey(liveSession.current.drafts[selected])===inputKey;
  onDiscuss({examples:bundleChatEditExamples(draft),option:optionNumber(selected),id:selected,revision:draft.revision,name:draft.bundle.name,goalId:binding.goalId,goal:binding.goal,isCurrent:current,subscribe:listener=>{editListeners.current.add(listener);return()=>{editListeners.current.delete(listener);};},
   preview:text=>{guard();if(!current())throw Error('The selected plan changed. Select the intended Plan tab and send the change again.');return previewBundleChatEdit(liveSession.current.drafts[selected],text);},
   accept:preview=>{guard();if(!current())throw Error('The selected plan changed. Review a new proposal.');const next=acceptBundleChatEdit(liveSession.current.drafts[selected],preview),raw=decisionStore.getSnapshot().data.workspaces[binding.goalId]?.fields[bundleWorkspaceField],patch=saveBundleDraftPatch(raw,next);decisionStore.setField(binding.goalId,patch.field,patch.value);if(!decisionStore.getSnapshot().saved)throw Error('The reviewed draft could not be saved. Your proposed changes are kept for retry.');remember({...liveSession.current,drafts:{...liveSession.current.drafts,[selected]:next}});saveView({appliedId:next.bundle.id});setNotice('Reviewed changes applied and saved to this goal. Recalculate and review before replacing an attachment; prior versions stay in history.');}
  });}
 useLayoutEffect(()=>{if(draft&&contextCurrent&&!disabled&&!pendingInput)registerChatTarget();});
 const canApply=!!chatChange&&chatChange.goalId===binding.goalId&&chatChange.planId===selected&&chatChange.inputKey===bundleInputKey(draft)&&chatChange.ready&&chatChange.isCurrent()&&!disabled&&contextCurrent;
 const whatIf=calculatePlanWhatIf(draft.inputs);
 const suggestedMeasure=suggestSuccessMeasure(binding.goal,measurePack);
 const activeAttachments=workspace?.attachments.filter(item=>!workspace.attachments.some(next=>next.supersedes===item.id))??[],existing=activeAttachments.find(item=>item.draft.bundle.id===selected);
 if(!draft)return <p>{proposal.unavailableReason??'No coordinated options were prepared.'}</p>;
 return <div className="space-y-4" data-plan-current={contextCurrent&&!disabled?'true':'false'}>
  <section aria-label="Combined option comparison" className="space-y-2">
   <div role="tablist" aria-label="Suggested plans" className="flex flex-wrap gap-2">{proposal.bundles.map((bundle,index)=><button key={bundle.id} id={`plan-tab-${bundle.id}`} role="tab" aria-selected={selected===bundle.id} aria-controls="selected-home-plan" tabIndex={selected===bundle.id?0:-1} className={bundleButton+' aria-selected:border-primary aria-selected:bg-accent'} onClick={()=>{setSelected(bundle.id);setEditor(false);setAttachFlow(null);setAttachmentOpen(null);setNotice('');}} onKeyDown={event=>{const direction=event.key==='ArrowRight'?1:event.key==='ArrowLeft'?-1:0;if(!direction&&event.key!=='Home'&&event.key!=='End')return;event.preventDefault();const next=event.key==='Home'?0:event.key==='End'?proposal.bundles.length-1:(index+direction+proposal.bundles.length)%proposal.bundles.length;setSelected(proposal.bundles[next].id);setEditor(false);setAttachFlow(null);setAttachmentOpen(null);setNotice('');(event.currentTarget.parentElement?.children[next] as HTMLElement)?.focus();}}>Action Plan #{index+1}</button>)}</div>
   <p className="text-xs text-muted-foreground">{proposal.bundles.some(bundle=>{const item=session.drafts[bundle.id],own=session.results[bundle.id];return contextCurrent&&own&&own.inputKey===bundleInputKey(item)&&proposal.bundles.some(other=>other.id!==bundle.id&&session.results[other.id]&&compareCurrentBundleResults(own,session.results[other.id],item,session.drafts[other.id]).comparable)})?'Drafts for review. Comparisons use matching reviewed assumptions.':"Drafts for review. Costs and readiness aren’t yet comparable."}</p>
  </section>
  <div className="flex flex-wrap items-center justify-between gap-2"><p className="text-sm font-medium">Selected: Action Plan #{optionNumber(selected)} · {bundleDisplayName(draft.bundle.name)}</p><button type="button" className={bundleButton} aria-expanded={!collapsed} aria-controls={panelId} onClick={()=>{setCollapsed(!collapsed);saveView({collapsed:!collapsed});if(!collapsed){setAttachFlow(null);setAttachmentOpen(null);}}}>{collapsed?'Show Action Plan':'Collapse Action Plan'}</button></div>
  <div id={panelId} hidden={collapsed}><section id="selected-home-plan" role="tabpanel" aria-labelledby={`plan-tab-${selected}`}><article aria-label={`Action Plan option ${optionNumber(selected)}`} className="space-y-3 border-t pt-3"><h3 ref={heading} tabIndex={-1} className="text-base font-semibold">{bundleDisplayName(draft.bundle.name)}</h3>
   <p aria-label="Plan description" className="text-sm leading-relaxed">{bundleDisplayText(draft.bundle.objective,draft.bundle)}</p>
   {bundleIsAnalysisOnly(draft.bundle)&&<p className="text-sm font-medium">The listed first steps are analytical; a delivery intervention still needs review.</p>}
   <ul aria-label="Selected plan summary" className="list-disc space-y-1.5 pl-5 text-sm">
    <li><strong>Approach:</strong> {bundleDisplayText(draft.bundle.coordination,draft.bundle)}</li>
    <li><strong>Stakeholders:</strong> {[...new Set(draft.bundle.components.map(item=>item.ownerRole))].slice(0,2).join('; ')} (proposed roles){new Set(draft.bundle.components.map(item=>item.ownerRole)).size>2?`; ${new Set(draft.bundle.components.map(item=>item.ownerRole)).size-2} more in details`:''}. Owners are not assigned.</li>
    <li><strong>People needed:</strong> {currentResult?.conditionalCoverage?`${currentResult.conditionalCoverage.at(-1)??'Not yet assessed'} conditional roles covered; ${currentResult.plannedAddedEmployees??'Not yet assessed'} planned added employees`:draft.inputs.groups.find(group=>group.id==='pilot-group')?`${bundleAssumptionText(draft.inputs.groups.find(group=>group.id==='pilot-group')!.count,value=>`${value} hypothetical pilot participants`)}; staffing not yet assessed`:'Not yet assessed'}.</li>
    <li><strong>Cost:</strong> {whatIf?.status==='ready'&&<span><strong>Illustrative what-if: {money(whatIf.cash)}.</strong> Listed cash allowances {money(whatIf.listedCash)}{whatIf.kind==='capacity'?`; plus ${whatIf.target} roles × ${money(whatIf.unitCost)} per role per month × ${whatIf.months} months = ${money(whatIf.roleCash)}`:''}. Assumes listed cash lines are distinct and funded as shown; excludes unentered costs and employee time. This is not a complete reviewed budget. Change assumptions in chat, then use Attach Action Plan to review this scenario. </span>}{draft.inputs.whatIf&&'Full budget review: '}{currentResult?.cashTotal==null?(currentResult?'Complete budget unknown':result?'Previous calculation is stale':'Not calculated'):`${money(currentResult.cashTotal)} incremental cash under planning assumptions`}{currentResult?.cashTotal===null&&currentResult.knownCashSubtotal!==null?`; known assumption subtotal ${money(currentResult.knownCashSubtotal)}, not a complete budget`:''}. Employee time: {currentResult?.employeeTimeTotal==null?'Not yet assessed':money(currentResult.employeeTimeTotal)}, separate from cash. {!currentResult&&!draft.inputs.whatIf&&<span>{draft.inputs.expenses.length?'Starting allowances are listed in Show assumptions. ':'No cost allowances have been entered. '}Use Attach Action Plan → Review plan fields → Budget to review costs, then Review calculation.</span>}{currentResult?.cashTotal===null&&!draft.inputs.whatIf&&<span> Review missing amounts and confirm component coverage and shared costs in Review plan fields → Budget.</span>}</li>
    <li><strong>Timeline:</strong> {currentResult?.planFinish?`${draft.inputs.timing.some(item=>item.finish.kind==='illustrative')?'Illustrative':'Assumed'} component finish ${currentResult.planFinish}${currentResult.capacityReadyMonth?`; conditional capacity from ${currentResult.capacityReadyMonth}`:''}`:`Start ${bundleAssumptionText(draft.inputs.scope.startMonth)}; duration ${bundleAssumptionText(draft.inputs.scope.months,value=>`${value} months`)}; horizon end ${bundleAssumptionText(bundleHorizonEnd(draft.inputs.scope))}; readiness not yet assessed`}.</li>
    <li><strong>Expected outcome:</strong> {draft.inputs.whatIf&&<span>{whatIfOutcomeText(draft.inputs)} </span>}Intended contribution to “{binding.goal}”. This is a proposed outcome, not a predicted effect. Retention effects are not established.</li>
    <li><strong>How success is measured:</strong> {whatIf?.status==='ready'&&!draft.inputs.successMeasure&&<span>Proposed target: {whatIf.target}{whatIf.kind==='turnover'?'% turnover using voluntary exits / average workforce for the same period':' additional roles covered from the planning start'}, over {whatIf.months} months from {whatIf.start}. Track the same population and period; this is a target, not a prediction. </span>}{!draft.inputs.successMeasure&&!draft.inputs.whatIf&&<span>Suggested measure: {suggestedMeasure.name}. {suggestedMeasure.baseline?'A recorded contextual baseline is available for review; confirm the plan population and period before adopting it.':'No matching recorded baseline is available.'} Set a target as a planning assumption, not a prediction. </span>}{(draft.inputs.successMeasure||!draft.inputs.whatIf)&&successMeasureText(draft.inputs.successMeasure,!draft.inputs.successMeasure||draft.inputs.successMeasure.scopeKey===measurementScope(draft.inputs))}{draft.inputs.successMeasure?.baseline.value!==null&&draft.inputs.successMeasure?.baseline.basis&&<span className="block text-xs">{contextCurrent?'Saved baseline provenance:':'Historical baseline; current context needs review: '}{draft.inputs.successMeasure.baseline.basis}</span>}</li>
   </ul>
   {draft.inputs.scope.requirements.value&&<p className="text-sm"><strong>Planning constraints:</strong> {draft.inputs.scope.requirements.value}</p>}
   <PlanAssumptions key={key+selected} draft={draft}/>
   {currentResult&&proposal.bundles.filter(bundle=>bundle.id!==selected&&session.results[bundle.id]).map(other=>{const comparison=compareCurrentBundleResults(currentResult,session.results[other.id],draft,session.drafts[other.id]);if(!comparison.comparable)return null;return <p key={other.id} className="text-xs">Compared with {bundleDisplayName(session.drafts[other.id].bundle.name)} under matching reviewed assumptions: {comparison.cashDifference===null?'cash difference unknown':`${money(Math.abs(comparison.cashDifference))} ${comparison.cashDifference<0?'lower':comparison.cashDifference>0?'higher':'difference in'} incremental cash`}; {comparison.capacityMonthsDifference===null?'capacity timing difference unknown':`${Math.abs(comparison.capacityMonthsDifference)} months ${comparison.capacityMonthsDifference<0?'earlier':comparison.capacityMonthsDifference>0?'later':'difference in capacity timing'}`}. Conditional estimates.</p>;})}
   {result&&!currentResult&&<p role="status">The previous calculation is retained as stale. Calculate this reviewed revision to show current totals.</p>}
   <details><summary className="min-h-11 cursor-pointer py-2 font-medium">Why these plans</summary><div className="space-y-3"><p className="text-xs">Plans start with one preparation response and can include reviewed local edits. Calculate checks the selected draft; the separate local staffing search reports its own executed combinations.</p><p className="text-xs">References describe observed context; they do not establish causes, effectiveness or a ranking. Availability and combined retention impact are not established. Proposed roles are not assigned people or operational approvals.</p><ul className="list-disc space-y-2 pl-5">
    <li><strong>Working together:</strong> {draft.bundle.components.map(item=>item.name).join('; ')}. Dependencies below show which steps can run in parallel.</li>
    <li><strong>Suggested stakeholders:</strong> {[...new Set(draft.bundle.components.map(item=>item.ownerRole))].join('; ')}. <strong>Review needed:</strong> {currentResult?.issues[0]??bundleDisplayText(draft.bundle.limitation,draft.bundle)} Proposed owner roles are not assigned people or operational approvals.</li></ul><p className="text-xs">Costs exclude unentered salaries, pay changes, backfill, recruiting fees and vendor quotes. Availability, retention effects, overlap and complete-budget coverage require review.</p>{draft.pilot&&<p className="text-xs">{draft.pilot.version} · frozen at {draft.pilot.preparedAt} · UTC calendar. Preset dates and allowances are illustrative assumptions, not readiness guarantees.</p>}{draft.inputs.timing.map(item=><p className="text-xs" key={item.componentId}>{bundleComponentLabels([item.componentId],draft.bundle)}: start {bundleAssumptionText(item.start)}; finish {bundleAssumptionText(item.finish)}. Basis: {item.start.basis??'Unavailable'}; {item.finish.basis??'Unavailable'}.</p>)}{draft.bundle.components.map(component=><section key={component.id} className="rounded border p-3"><h4 className="font-semibold">{component.name}</h4><p>{bundleDisplayText(component.firstStep,draft.bundle)}</p><p className="text-xs">Suggested stakeholder role: {component.ownerRole}. Proposed responsibility: coordinate “{component.name}” and its first step. Prerequisites: {bundleComponentLabels(component.dependsOn,draft.bundle)||'None proposed'}.</p><p className="text-xs">References: {component.evidence.join(', ')}. {contextCurrent?'Observed context only; these references do not establish effectiveness.':'Original evidence context changed; references require review.'}</p><p className="text-xs">{bundleDisplayText(component.limitation,draft.bundle)}</p></section>)}
    {result&&<section><h4 className="font-semibold">{currentResult?'Current':'Stale'} shared ledger</h4><p>Shared entries count once. Employee time is separate. All amounts are planning assumptions and may include the labelled illustrative inputs.</p><ul>{result.ledger.map(line=><li key={line.id}>{line.label}: {money(line.total)} · {line.kind==='cash'?'cash':'employee time'} · linked to {bundleComponentLabels(line.componentIds,draft.bundle)||'unassigned'}</li>)}</ul><p>Distinct participants under current assumptions: {result.uniqueParticipants??'Unknown'}.</p>{result.issues.map(issue=><p key={issue}>{issue}</p>)}</section>}
   </div></details>



   {attachFlow===selected&&<section ref={attachmentReview} tabIndex={-1} aria-label="Review Action Plan attachment" className="space-y-3 rounded border border-primary/50 p-3">
   <h4 className="font-semibold">Review before attaching</h4><p className="text-sm">Check the saved goal and assumptions above. Review the calculation below, then confirm the attachment and any linked planning fields. Nothing is attached or approved by opening this review.</p>
   <details open={editor} onToggle={event=>setEditor(event.currentTarget.open)} className="rounded border p-3"><summary className="min-h-11 cursor-pointer py-2 font-medium focus-visible:ring-2 focus-visible:ring-ring">Review plan fields</summary><p className="mb-3 text-xs text-muted-foreground">Use these fields for staffing, budget limits, success measures, plan wording or other changes chat does not support. Changes remain in this working draft. Review a new calculation before confirming attachment. To open the separate capacity or retention scope review, return to general chat and type “Compare workforce options”.</p>
   {editor&&<HomeBundleEditor measurePack={measurePack} onPendingInput={setPendingInput} optionNumber={optionNumber(selected)} draft={draft} disabled={disabled||!contextCurrent} onChange={edit} onProposalChange={editProposal}/>}
   </details>
   <HomePlanIntegration key={bundleInputKey(draft)+String(contextCurrent&&!disabled)} draft={draft} disabled={disabled||!contextCurrent||pendingInput} isCurrent={()=>isCurrent()&&liveSelection.current===selected&&bundleInputKey(liveSession.current.drafts[selected])===bundleInputKey(draft)} onAccept={next=>{guard();remember({...session,drafts:{...session.drafts,[selected]:next}});setEditor(true);setNotice('Reviewed plan changes accepted into the working draft. Review costs, dates and measures; Save and Calculate explicitly.');}}/>
   {pendingInput&&<p role="status" className="text-xs">Complete the month as YYYY-MM before calculating, saving or attaching.</p>}
   <div className="space-y-2"><p className="text-xs">Calculate this exact draft for review. If inputs are missing, correct them in Review plan fields. You can save a draft for later without attaching it.</p><div className="flex flex-wrap gap-2"><button className={bundleButton} disabled={disabled||!contextCurrent||pendingInput} onClick={calculate}>Review calculation</button><button className={bundleButton} disabled={disabled||!contextCurrent||!workspace||pendingInput} onClick={()=>persist()}>Save draft for later</button></div></div>
   <section aria-label="Attach plan review" className="space-y-2 border-t pt-3"><h4 className="font-semibold">Attach plan to goal</h4><p className="text-xs">You can edit this Action Plan in chat later. Revised inputs require a new calculation and confirmation; previous attachments remain in history.</p>{!currentResult&&<p className="text-xs">Choose Review calculation to check this version before continuing.</p>}{currentResult&&<><p>Review {bundleDisplayName(draft.bundle.name)}, revision {draft.revision}, with these exact assumptions and results.</p><label className="my-2 flex items-start gap-2"><input type="checkbox" checked={reviewed===bundleInputKey(draft)} onChange={event=>setReviewed(event.target.checked?bundleInputKey(draft):null)}/><span>I reviewed this Action Plan for “{binding.goal}”. This is not operational approval.</span></label>{currentResult.issues.length>0&&<label className="my-2 flex items-start gap-2"><input type="checkbox" checked={unknowns===bundleInputKey(draft)} onChange={event=>setUnknowns(event.target.checked?bundleInputKey(draft):null)}/><span>I acknowledge the unresolved assumptions listed in Why these plans.</span></label>}</>}<button className={bundleButton+' bg-primary text-primary-foreground'} disabled={disabled||pendingInput||!currentResult||reviewed!==bundleInputKey(draft)||!!currentResult?.issues.length&&unknowns!==bundleInputKey(draft)} onClick={()=>{if(projectBinding)setAttachmentOpen(bundleInputKey(draft));else if(persist(true))setAttachFlow(null);}}>{projectBinding?(existing?'Review replacement attachment':'Continue to attachment'):(existing?'Confirm replacement attachment':'Confirm attachment')}</button></section>
   {attachmentOpen===bundleInputKey(draft)&&currentResult&&projectBinding&&<HomeLinkedAttachment preparedAt={preparedAt} key={bundleInputKey(draft)+(existing?.id??'')} draft={draft} result={currentResult} replaceId={existing?.id??null} reviewed={reviewed===bundleInputKey(draft)} acknowledgeUnknowns={unknowns===bundleInputKey(draft)} disabled={disabled||!contextCurrent||pendingInput} isCurrent={()=>isCurrent()&&liveSelection.current===selected&&bundleInputKey(liveSession.current.drafts[selected])===bundleInputKey(draft)} projectBinding={projectBinding} onClose={()=>setAttachmentOpen(null)} onComplete={changes=>{saveView({collapsed,appliedId:draft.bundle.id});setAttachmentOpen(null);setAttachFlow(null);setNotice(`Reviewed Action Plan attached with ${changes} planning-field changes saved locally. Destination calculations remain explicit. It is not operational approval.`);}}/>}
   {existing&&!projectBinding&&!draft.bundle.origin&&<HomeActionPlanApplication binding={binding} draft={draft} attachmentId={existing.id} disabled={disabled||!contextCurrent||pendingInput} isCurrent={()=>isCurrent()&&bundleInputKey(liveSession.current.drafts[selected])===bundleInputKey(draft)}/>}
   <button className={bundleButton} onClick={()=>{setAttachFlow(null);setAttachmentOpen(null);}}>Cancel attachment review</button>
   </section>}
  </article></section></div>
   {notice&&<p role="status">{notice}</p>}{!workspace&&<p role="alert">Saved bundle records cannot be verified. They are kept; saving is blocked.</p>}
  <div className="flex flex-wrap gap-2">{!collapsed&&<button className={bundleButton+' bg-primary text-primary-foreground'} disabled={disabled||!contextCurrent||!workspace} onClick={()=>{setAttachFlow(selected);requestAnimationFrame(()=>{attachmentReview.current?.focus();attachmentReview.current?.scrollIntoView({block:'nearest'});});}}>Attach Action Plan</button>}<button type="button" className={bundleButton} disabled={!canApply} aria-describedby={applyHintId} onClick={()=>{if(canApply)chatChange!.apply();}}>Apply changes</button><button type="button" className={bundleButton} aria-expanded={comparing} aria-controls={panelId+'-comparison'} disabled={disabled||!contextCurrent||proposal.bundles.length<2} onClick={()=>{setComparing(value=>!value);if(!comparing)requestAnimationFrame(()=>{comparisonRef.current?.focus({preventScroll:true});comparisonRef.current?.scrollIntoView({block:'start'});});}}>{comparing?'Hide comparison':'Compare Action Plans'}</button></div>
  <p id={applyHintId} className="text-xs text-muted-foreground">{canApply?'Review the proposed chat changes below, then Apply changes. This saves the working draft; attachment review remains separate.':chatChange?'The proposed changes are not current for this plan and chat text. Send the intended change again.':'No pending changes. Describe a change in chat and Send to review it.'}</p>
  {proposal.bundles.length<2&&<p className="text-xs text-muted-foreground">Only one proposal is available. Comparison needs another distinct proposal; no alternatives are generated here.</p>}
  {comparing&&proposal.bundles.length>1&&<section ref={comparisonRef} id={panelId+'-comparison'} tabIndex={-1} aria-label="Action Plan comparison" className="space-y-3 border-t pt-3"><h3 className="font-semibold">Compare Action Plans</h3><p className="text-xs">Conditional drafts, not ranked recommendations. Check population, period and assumptions; different scopes or targets are not like-for-like outcomes.</p><div className="grid gap-3 xl:grid-cols-3">{proposal.bundles.map((bundle,index)=>{const item=session.drafts[bundle.id],scenario=calculatePlanWhatIf(item.inputs),calculation=session.results[bundle.id],fresh=calculation?.inputKey===bundleInputKey(item);return <article key={bundle.id} aria-label={`Comparison Action Plan ${index+1}`} className="min-w-0 space-y-2 break-words rounded border p-3 text-sm"><h4 className="font-semibold">Action Plan #{index+1}: {bundleDisplayName(bundle.name)}</h4><p>{bundleDisplayText(item.bundle.objective,item.bundle)}</p><p>Population: {bundleAssumptionText(item.inputs.scope.population)}. Period: {bundleAssumptionText(item.inputs.scope.startMonth)} / {bundleAssumptionText(item.inputs.scope.months)} months.</p><p>Conditional cash: {scenario?.status==='ready'?money(scenario.cash):'Needs assumption review'}. Assumes distinct listed costs; excludes unentered costs and employee time.</p><p>{whatIfOutcomeText(item.inputs)}</p><p>Reviewed full budget: {fresh?money(calculation.cashTotal):'No current calculation'}.</p><p>Activities: {item.bundle.components.map(component=>component.name).join('; ')}.</p></article>})}</div></section>}
  {!!workspace?.attachments.length&&<details><summary className="min-h-11 cursor-pointer py-2 font-medium">Attached Action Plans and version history ({workspace.attachments.length})</summary>{workspace.attachments.map(item=><div key={item.id} className="mb-3 rounded border p-3"><p>{item.draft.bundle.name} · revision {item.draft.revision} · {workspace.attachments.some(next=>next.supersedes===item.id)?'Previous attached version':contextCurrent?attachedBundleState(item,binding,session.drafts[item.draft.bundle.id]??null).replaceAll('_',' '):'context changed'}</p><p>Snapshot cash: {money(item.result.cashTotal)}. Timeline: {item.result.planFinish??'Unknown'}. Attached {item.attachedAt.slice(0,10)}.</p><p className="text-xs">{bundleDisplayText(item.draft.bundle.coordination,item.draft.bundle)} This preserved proposal is not operational approval.</p></div>)}</details>}
 </div>;
}

function PlanAssumptions({draft}:{draft:BundleDraft}){
 const [expanded,setExpanded]=useState(false),contentId=useId();
 const input=draft.inputs,end=bundleHorizonEnd(input.scope).value,lastFinish=input.timing.map(item=>item.finish.value).filter((date):date is string=>!!date).sort().at(-1);
 return <section aria-label={draft.pilot?'Editable illustrative starting assumptions':'Plan assumptions'} className="space-y-2 text-xs">
  <h4><button type="button" aria-expanded={expanded} aria-controls={contentId} onClick={()=>setExpanded(value=>!value)} className="min-h-11 rounded px-2 py-2 text-left font-semibold underline underline-offset-4 focus-visible:ring-2 focus-visible:ring-ring">{expanded?'Hide assumptions':'Show assumptions'}</button></h4>
  <div id={contentId} hidden={!expanded} className="space-y-2">
  <p><span>{draft.pilot?'Illustrative pilot assumptions · editable, not observed facts or market estimates.':'Editable planning assumptions; not observed outcomes.'}</span> Review before calculating or applying.</p>
  {draft.inputs.whatIf&&<p>Conditional scenario inputs: {Object.entries(draft.inputs.whatIf).filter(([key])=>['baseline','target','population','unitCost'].includes(key)).map(([key,value])=>{const assumption=value as {value:number|null;kind:string};return assumption.value===null?null:<span key={key}>{key}: {assumption.value} ({assumption.kind}); </span>})}change these in chat, then review before attachment.</p>}
  <p>Population: {bundleAssumptionText(input.scope.population)}.</p>
  {input.expenses.length>0&&<ul className="list-disc space-y-1 pl-5" aria-label="Individual cost assumptions">{input.expenses.map(expense=><li key={expense.id}>{pilotAllowances[expense.id.slice(6) as keyof typeof pilotAllowances]?.label??expense.label}: {bundleAssumptionText(expense.amount,money)} · {bundleAssumptionText(expense.months,value=>value>1?`Monthly × ${value}`:'One-time')}. {expense.kind==='employee_time'?'Employee time, separate from cash.':'Cash allowance.'}</li>)}</ul>}
  <p>Individual allowances are not a complete budget. Participants are hypothetical or reviewed assumptions, not selected employees. Evidence, exclusions and provenance are in Why these plans.</p>
  {lastFinish&&end&&lastFinish>end&&<p role="alert">Proposed component dates extend beyond the shared horizon. Review the actual dates before calculating.</p>}
  </div>
 </section>;
}
