"use client";
import {marketEvidence,marketCarryEvidence,oewsOccupations,oewsAreas} from "@/lib/oews-reference.mjs";
export type MarketSelection={soc:string;area:string};
export type MarketCarry=MarketSelection&{goal:string};
const money=(value:number|null|undefined)=>value===null||value===undefined?"Unavailable":new Intl.NumberFormat("en-US",{style:"currency",currency:"USD",maximumFractionDigits:0}).format(value);
export function MarketComparison({selection,onChange,goal,onCarry}:{selection:MarketSelection;onChange:(value:MarketSelection)=>void;goal:string;onCarry:(value:MarketCarry)=>void}) {
 const evidence=marketEvidence(selection);if(!evidence)return <p role="alert">This occupation/location is not in the reference extract.</p>;
 const rows=evidence.selected.AREA==="99"?[evidence.national]:[evidence.national,evidence.selected];
 return <section aria-label="Occupation and location comparison" className="space-y-4"><div className="grid gap-3 sm:grid-cols-2"><label className="text-sm">Occupation<select aria-label="Market occupation" className="mt-1 w-full rounded border bg-background p-2" value={selection.soc} onChange={e=>onChange({...selection,soc:e.target.value})}>{oewsOccupations.map(o=><option key={o.value} value={o.value}>{o.label}</option>)}</select></label><label className="text-sm">Location<select aria-label="Market location" className="mt-1 w-full rounded border bg-background p-2" value={selection.area} onChange={e=>onChange({...selection,area:e.target.value})}>{oewsAreas.map(a=><option key={a.value} value={a.value}>{a.label}</option>)}</select></label></div>
 <p className="text-sm text-muted-foreground">BLS OEWS · May 2025 · Annual USD wages · All industries</p>
 <div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr className="border-b"><th className="py-2 pr-3">Area</th><th className="py-2 pr-3">Employment</th><th className="py-2 pr-3">Median pay</th><th className="py-2">25th–75th percentile</th></tr></thead><tbody>{rows.map(row=><tr key={row.AREA} className="border-b"><th className="max-w-48 py-3 pr-3 font-medium">{row.AREA_TITLE}{row.AREA==="36"?" (state)":""}</th><td className="px-2">{row.TOT_EMP===null?"Unavailable":row.TOT_EMP.toLocaleString("en-US")}</td><td className="px-2">{money(row.A_MEDIAN)}</td><td className="py-3">{money(row.A_PCT25)}–{money(row.A_PCT75)}</td></tr>)}</tbody></table></div>
 {selection.area!=="99"&&<p className="text-sm">Median pay is {evidence.medianDifferencePct===null?"unavailable":`${Math.abs(evidence.medianDifferencePct)}% ${evidence.medianDifferencePct>=0?"above":"below"} the U.S. median`} for this occupation.</p>}
 <p className="text-sm">Employment is not available candidates. Wages are not total employer costs{selection.area==="35620"?"; this metro is broader than NYC":""}.</p>
 <button disabled={!goal} onClick={()=>onCarry({...selection,goal})} className="min-h-11 rounded bg-primary px-4 py-2 font-semibold text-primary-foreground disabled:opacity-50">Carry reference to Planning</button>{!goal&&<p className="text-xs text-muted-foreground">Pin a goal above to carry this reference.</p>}
 <details className="text-sm"><summary className="cursor-pointer font-semibold text-primary">Data details</summary><p className="mt-3">Released May 15, 2026. Initial coverage: three occupations across the U.S., New York State and the full New York–Newark–Jersey City, NY-NJ metro. SOC {selection.soc}. Geography code {selection.area}. Public-domain BLS data; versioned extract.</p><p className="mt-2">Location quotient: {evidence.selected.LOC_QUOTIENT??"Not applicable nationally"}. This measures occupational employment concentration relative to the U.S., not recruiting ease. Employment sampling error (percent relative standard error): {evidence.selected.EMP_PRSE??"Unavailable"}%.</p><p className="mt-2">Missing or suppressed values remain unavailable. Do not add overlapping geography counts or infer annual trends from this snapshot. O*NET skills and internal Compensation are separate evidence. Carrying does not change model inputs, approve spending or infer ROI.</p><a href={evidence.sourceUrl} target="_blank" rel="noreferrer" className="mt-3 inline-block text-primary underline">Official BLS source workbook</a></details>
 </section>;
}
export function CarriedMarketReference({carry,onClear}:{carry:MarketCarry;onClear:()=>void}) {
 const evidence=marketCarryEvidence(carry);if(!evidence)return null;
 return <section aria-label="Carried market reference" className="mx-6 mt-5 border-b pb-4 text-sm"><div className="flex flex-wrap items-center justify-between gap-2"><h2 className="font-semibold">Market reference for your goal</h2><button onClick={onClear} className="rounded border px-2 py-1">Remove market reference</button></div><p className="mt-2">{evidence.selected.OCC_TITLE} · {evidence.selected.AREA_TITLE} · Median annual pay {money(evidence.selected.A_MEDIAN)} · BLS OEWS May 2025</p><p className="mt-1 text-xs text-muted-foreground">Reference only. Model assumptions are unchanged; wages exclude other employer costs.</p><details className="mt-2"><summary className="cursor-pointer text-primary">Reference details</summary><p className="mt-2">Carried goal: {evidence.goal}</p><p className="mt-1">25th–75th percentile: {money(evidence.selected.A_PCT25)}–{money(evidence.selected.A_PCT75)}. Employment: {evidence.selected.TOT_EMP?.toLocaleString("en-US")??"Unavailable"}, not available candidates. {evidence.selected.AREA==="35620"?"Metro coverage extends beyond New York City.":""}</p><a href={evidence.sourceUrl} target="_blank" rel="noreferrer" className="text-primary underline">Official source · released May 15, 2026</a></details></section>;
}
