"use client";
import { datasetFetch } from "@/lib/dataset-client.mjs";

import {useEffect,useRef,useState} from "react";
import {decisionStore,useDecisionStorage} from "@/components/decision-store";
import {agentFingerprint,appendAgentToBrief,emptyAgentSettings,type AgentInput,type AgentRun,type AgentSettings,type AgentEvaluation} from "@/lib/capability-agent";
import {emptyDecisionBrief,type DecisionBrief} from "@/lib/decision-brief";
import type {DevelopmentOption} from "@/lib/development-costs";
import type {JourneyLimits} from "@/lib/capability-journey";
type Attempt={error:string;trace:string[];partialResults:AgentEvaluation[]};
type Saved={settings:AgentSettings;run:AgentRun|null;imported:string[];lastAttempt:Attempt|null};
const empty=():Saved=>({settings:emptyAgentSettings(),run:null,imported:[],lastAttempt:null});
const button="min-h-10 rounded border px-3 py-2 text-sm font-medium disabled:opacity-50";
const conclusion={constraints_met_outcomes_unknown:"Calculated constraints met; capability outcomes unknown",no_feasible_option:"No evaluated option meets all calculated constraints",insufficient_inputs:"Insufficient inputs for a passing comparison"};
function Results({items}:{items:AgentEvaluation[]}){return <div className="space-y-3">{items.map(e=><article key={e.id} className="rounded border p-3 text-sm"><h4 className="font-semibold">{e.id}: {e.candidate.option.quote.provider}{e.revisionOf?` — revised from ${e.revisionOf}`:" — initial"}</h4><p>{e.candidate.option.quote.provenance==="simulated"?"Fictional quote":"User-provided, unverified quote"}. AI-selected what-if: {e.candidate.option.inputs.participants} participants; {e.scenario.assumptions.fill_rate_pct}% fill rate.</p><p className="mt-2 font-semibold">{e.candidate.status}</p><p>Calculated total: {e.candidate.option.quote.currency} {e.candidate.cost.total??"unknown"}; employee hours {e.candidate.cost.employeeHours??"unknown"}. Starting / peak / ending headcount: {e.scenario.summary.starting_headcount} / {Math.max(...e.scenario.points.map(p=>p.modeled_headcount))} / {e.scenario.summary.modeled_end_headcount}.</p><ul className="mt-2 list-disc pl-5">{e.candidate.reasons.map(r=><li key={r}>{r}</li>)}</ul></article>)}</div>}
export function ModelCapabilityPlanner({goalId,goal,options,limits}:{goalId:string;goal:string;options:DevelopmentOption[];limits:JourneyLimits}){
 const storage=useDecisionStorage(),saved=(storage.data.workspaces[goalId]?.fields.capabilityAgent as unknown as Saved|undefined)??empty();
 const [busy,setBusy]=useState(false),[notice,setNotice]=useState("");const controller=useRef<AbortController|null>(null);
 useEffect(()=>()=>controller.current?.abort(),[]);
 const input:AgentInput={version:1,goal,options,limits:{...limits,allowRevision:false},settings:saved.settings};
 const fingerprint=agentFingerprint(input),current=saved.run?agentFingerprint(saved.run.input)===fingerprint:false;
 useEffect(()=>()=>controller.current?.abort(),[fingerprint]);
 const persist=(patch:Partial<Saved>)=>decisionStore.setField(goalId,"capabilityAgent",{...decisionStore.getField<Saved>(goalId,"capabilityAgent",empty()),...patch});
 const valid=(c:AbortController)=>!c.signal.aborted&&controller.current===c&&decisionStore.getSnapshot().data.goals.activeId===goalId&&decisionStore.getSnapshot().data.goals.goals.some(g=>g.id===goalId&&g.statement===goal);
 async function run(){if(controller.current)return;const c=new AbortController();controller.current=c;setBusy(true);setNotice("");const timer=setTimeout(()=>c.abort(),95000);
  try{const response=await datasetFetch("/api/capability-agent",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(input),signal:c.signal});const body=await response.json();if(!valid(c))return;
   if(!response.ok){persist({lastAttempt:{error:typeof body.error==="string"?body.error:"Planner failed; retry explicitly.",trace:Array.isArray(body.trace)?body.trace:[],partialResults:Array.isArray(body.partialResults)?body.partialResults:[]}});return}
   const result=body as AgentRun;if(result.version!==1||!Array.isArray(result.evaluations)||agentFingerprint(result.input)!==fingerprint)throw Error("Planner response did not match this goal and inputs; no result replaced.");
   persist({run:result,lastAttempt:null});setNotice("AI review completed and calculations validated. No actions were executed.");
  }catch(e){if(controller.current===c)setNotice(c.signal.aborted?"AI planning cancelled or timed out; previous completed results remain.":e instanceof Error?e.message:"Planner unavailable; previous results remain.")}
  finally{clearTimeout(timer);if(controller.current===c){controller.current=null;setBusy(false)}}
 }
 function append(){if(!saved.run||!current)return;try{const brief=decisionStore.getField<DecisionBrief>(goalId,"brief",emptyDecisionBrief());decisionStore.setField(goalId,"brief",appendAgentToBrief(brief,saved.run));persist({imported:[...saved.imported,saved.run.id].slice(-20)});setNotice("Verified calculation notes appended; your owner, writing and approvals are preserved.")}catch(e){setNotice((e as Error).message)}}
 return <details className="mt-5 border-t border-primary/50 pt-4"><summary className="cursor-pointer text-lg font-semibold">Model-directed planning</summary>
 <p className="mt-3 text-sm">AI chooses which carried option to calculate, reads actual results, and may propose one permitted revision. It can only select the bounded evaluator or finish review. Calculators determine costs and constraint status; AI cannot approve actions or establish capability gains.</p>
 <p className="mt-2 text-xs text-muted-foreground">Pressing Run AI planning sends this selected goal, carried quotes and the limits above to the existing AI model. Brief notes, owner, approvals and conversation history are excluded. Source: synthetic enterprise Baseline; no workforce-filter or person-level scope.</p>
 <fieldset disabled={busy} className="mt-4 space-y-3"><label className="flex items-start gap-2 text-sm"><input type="checkbox" checked={saved.settings.allowRevision} onChange={e=>persist({settings:{...saved.settings,allowRevision:e.target.checked}})}/>Permit one AI-selected revision within my bounds. Participants may decrease only to my minimum; fees, sessions, hours, budget and other baseline assumptions cannot change.</label><div className="grid gap-3 sm:grid-cols-2">{([["minFillRate","Minimum allowed modeled fill rate (%)"],["maxFillRate","Maximum allowed modeled fill rate (%)"]] as const).map(([k,label])=><label key={k} className="text-sm">{label}<input value={saved.settings[k]} inputMode="decimal" maxLength={6} className="mt-1 w-full rounded border bg-background p-2" onChange={e=>persist({settings:{...saved.settings,[k]:e.target.value}})}/></label>)}</div><p className="text-xs text-muted-foreground">Leave both blank to keep the Baseline fill rate. Enter both to permit AI what-ifs inside that range (0–100%). This models gross hiring flows, not actual hiring or staffing decisions. Growth and assumed productivity gain stay zero. A shrinking modeled workforce is not proof of unchanged capacity.</p></fieldset>
 <div className="mt-4 flex flex-wrap gap-2"><button className={button} disabled={busy||options.length<1||options.length>2||!limits.minimumParticipants.trim()} onClick={()=>void run()}>Run AI planning</button>{busy&&<button className={button} onClick={()=>controller.current?.abort()}>Cancel AI planning</button>}</div><p className="mt-2 text-xs text-muted-foreground">At most 4 model turns × 1,200 output tokens; 3 evaluations, each using the existing company-scenario and development-cost calculators; 1 revision. 90-second server limit, no automatic retry. Stop or switch goals to cancel further calls. No external actions or database writes.</p>
 <p role="status" aria-live="polite" className="mt-3 text-sm">{busy?"AI is selecting allowed scenarios and inspecting returned calculations…":notice}</p>
 {saved.lastAttempt&&<section className="mt-3 rounded border p-3"><p role="alert" className="text-sm text-destructive">{saved.lastAttempt.error}</p><p className="mt-1 text-xs">This attempt did not complete. Previous completed review is retained; retry is explicit.</p><details className="mt-2"><summary className="cursor-pointer text-sm">Partial calculation trace (not a completed review)</summary><ol className="my-2 list-decimal pl-5 text-xs">{saved.lastAttempt.trace.map((t,i)=><li key={i}>{t}</li>)}</ol><Results items={saved.lastAttempt.partialResults}/></details></section>}
 {saved.run&&<section aria-label="AI planning review" className="mt-5 space-y-3"><h3 className="font-semibold">{conclusion[saved.run.conclusion]}</h3><p className="text-sm">Historical review: {new Date(saved.run.completedAt).toLocaleString()}; synthetic source as of {saved.run.source.as_of}. {current?"Uses the displayed inputs.":"Inputs changed; run again before carrying to the brief."} {saved.run.modelCalls} model calls; {saved.run.calculatorCalls} completed calculator calls.</p>{saved.run.preferredId&&<p className="text-sm">Model preference for constraint review: {saved.run.preferredId}. Provider suitability and capability outcomes remain unverified.</p>}<Results items={saved.run.evaluations}/><details><summary className="cursor-pointer text-sm font-semibold">Actual tool trace and retained inputs</summary><ol className="mt-2 list-decimal pl-5 text-xs">{saved.run.trace.map((t,i)=><li key={i}>{t}</li>)}</ol><pre className="mt-2 max-h-72 overflow-auto whitespace-pre-wrap break-words text-xs">{JSON.stringify({input:saved.run.input,source:saved.run.source,evaluations:saved.run.evaluations.map(e=>({id:e.id,revisionOf:e.revisionOf,assumptions:e.scenario.assumptions}))},null,2)}</pre></details><button className={button} disabled={busy||!current||saved.imported.includes(saved.run.id)||!saved.run.evaluations.length} onClick={append}>{saved.imported.includes(saved.run.id)?"AI calculation notes appended":"Append verified AI calculation notes"}</button><p className="text-xs text-muted-foreground">Appends only labeled returned calculations and assumptions. No model-authored cost, ROI or approval is inserted.</p></section>}
 </details>;
}
