"use client";
import {planContextDiagnosticText,type PlanContextDiagnostic} from '@/lib/home-evidence-identity';
import {PlanDirections} from '@/components/plan-directions';
import {HomePlanSummary} from '@/components/home-plan-summary';
import {PlanAssumptions} from '@/components/home-bundle-plans';
import type {PlanAlternative,PlanAlternatives} from '@/lib/home-plan-alternatives';
import {actionEvidenceCatalog} from '@/lib/home-action-proposal';
import {bundleDisplayText,bundleComponentLabels,bundleDisplayName,bundleAssumptionText,bundleAssumptionCopy} from '@/lib/home-bundle-display';
const money=(value:number|null|undefined)=>value==null?'Unknown':`$${value.toLocaleString('en-US',{maximumFractionDigits:2})} USD`;
export function PlanAlternativeCard({plan,catalog,compact=false,snapshot=false,contextCurrent=true,measurePack,contextDiagnostic}:{contextDiagnostic?:PlanContextDiagnostic|null;measurePack?:unknown;plan:PlanAlternative;catalog:PlanAlternatives;compact?:boolean;snapshot?:boolean;contextCurrent?:boolean}){
 const {draft,result}=plan,currentResult=result,key=plan.id,selected=plan.id;
 const referenceCatalog=contextCurrent&&!snapshot?actionEvidenceCatalog(measurePack):[];
 const referenceNotice='Saved reference only; review its population and period against current evidence. It does not establish effectiveness.';
 return <article aria-label={compact?`Comparison Action Plan ${plan.number}`:`Action Plan option ${plan.number}`} className="min-w-0 space-y-3 break-words rounded border p-3 text-sm">
 <h3 className="font-semibold">{compact?`Action Plan #${plan.number}: `:""}{bundleDisplayName(draft.bundle.name)}</h3>
 <p>{snapshot?'Attached snapshot':!plan.operation?'Original plan snapshot':plan.applied?'Applied alternative':'Proposed alternative · not yet applied'} · revision {draft.revision}{plan.sourceRefs.length?` · based on ${plan.sourceRefs.map(ref=>'Action Plan #'+catalog.plans.find(item=>item.id===ref.id)!.number).join(' and ')}`:''}.</p>
 {(!contextCurrent||snapshot)&&<p>Historical assumptions; review current evidence before acting.</p>}
 {plan.notes.map((note,index)=><p key={index}>{note}</p>)}
   <p aria-label="Plan description" className="text-sm leading-relaxed">{bundleDisplayText(draft.bundle.objective,draft.bundle,draft.inputs)}</p>
   <PlanDirections draft={draft} snapshot={snapshot}/>
   <HomePlanSummary draft={draft} result={currentResult} measurePack={measurePack}/>
   <PlanAssumptions key={key+selected} draft={draft} result={currentResult} contextCurrent={contextCurrent}/>
   <details><summary className="min-h-11 cursor-pointer py-2 font-medium">Why these plans</summary><div className="space-y-3">{contextDiagnostic&&<p aria-label="Action Plan context check" className="text-xs">{planContextDiagnosticText(contextDiagnostic)}</p>}<p className="text-xs">{draft.bundle.origin==='local-demo-v1'?'This example was prepared locally from fictional assumptions; no model ran.':'Plans start with one preparation response and can include reviewed local edits.'} The staffing section reports only combinations actually evaluated for the current assumptions. Attach checks the selected draft and preserves any executed search with it.</p><p className="text-xs">References describe observed context; they do not establish causes, effectiveness or a ranking. Availability and combined retention impact are not established. Proposed roles are not assigned people or operational approvals.</p><ul className="list-disc space-y-2 pl-5">
    <li><strong>Working together:</strong> {draft.bundle.components.map(item=>item.name).join('; ')}. Dependencies below show which steps can run in parallel.</li>
    <li><strong>Suggested stakeholders:</strong> {[...new Set(draft.bundle.components.map(item=>item.ownerRole))].join('; ')}. <strong>Plan limitations:</strong> {bundleDisplayText(draft.bundle.limitation,draft.bundle)} Proposed owner roles are not assigned people or operational approvals.</li></ul><p className="text-xs">Costs exclude unentered salaries, pay changes, backfill, recruiting fees and vendor quotes. Availability, retention effects, overlap and complete-budget coverage require review.</p>{draft.pilot&&<p className="text-xs">{bundleAssumptionCopy(draft.pilot.version)} · frozen at {draft.pilot.preparedAt} · UTC calendar. Preset dates and allowances are assumed values, not readiness guarantees.</p>}{draft.inputs.timing.map(item=><p className="text-xs" key={item.componentId}>{bundleComponentLabels([item.componentId],draft.bundle)}: start {bundleAssumptionText(item.start)}; finish {bundleAssumptionText(item.finish)}. Basis: {bundleAssumptionCopy(item.start.basis??'Unavailable')}; {bundleAssumptionCopy(item.finish.basis??'Unavailable')}.</p>)}{draft.bundle.components.map(component=><section key={component.id} className="rounded border p-3"><h4 className="font-semibold">{component.name}</h4><p>{bundleDisplayText(component.firstStep,draft.bundle,draft.inputs)}</p><p className="text-xs">Suggested stakeholder role: {component.ownerRole}. Proposed responsibility: coordinate “{component.name}” and its first step. Prerequisites: {bundleComponentLabels(component.dependsOn,draft.bundle)||'None proposed'}.</p><div className="space-y-1 text-xs" aria-label={`Evidence scope for ${component.name}`}><p>References: {component.evidence.join(', ')}. {referenceNotice}</p>{component.evidence.map(id=>{const reference=referenceCatalog.find(item=>item.id===id);return <p key={id}>[{id}] {reference?`${reference.scope} · ${reference.date??'Date unavailable'}. ${reference.limitation}`:'Original source scope unavailable for this context; review before using it.'}</p>})}</div><p className="text-xs">{bundleDisplayText(component.limitation,draft.bundle)}</p></section>)}
    {result&&<section><h4 className="font-semibold">{snapshot||!contextCurrent?'Saved':'Current'} shared ledger</h4><p>Shared cash entries count once. Staff effort is tracked in hours. All amounts are planning assumptions and may include the labelled assumed inputs.</p><ul>{result.ledger.filter(line=>line.kind==='cash').map(line=><li key={line.id}>{line.label}: {money(line.total)} · {line.kind==='cash'?'cash':'employee time'} · linked to {bundleComponentLabels(line.componentIds,draft.bundle)||'unassigned'}</li>)}</ul><p>Distinct participants under these saved assumptions: {result.uniqueParticipants??'Unknown'}.</p>{result.issues.map(issue=><p key={issue}>{bundleAssumptionCopy(issue)}</p>)}</section>}
   </div></details>
 </article>;
}
