"use client";
import {PlanDirections} from '@/components/plan-directions';
import {PlanAssumptions} from '@/components/home-bundle-plans';
import type {PlanAlternative,PlanAlternatives} from '@/lib/home-plan-alternatives';
import {actionEvidenceCatalog} from '@/lib/home-action-proposal';
import {planBudgetText} from '@/lib/home-plan-revisions';
import {planDeliveryEstimate,planStaffEffortText} from '@/lib/home-plan-delivery-estimate';
import {planCashEstimate} from '@/lib/home-plan-cash';
import {calculatePlanWhatIf,whatIfOutcomeText} from '@/lib/home-plan-what-if';
import {suggestSuccessMeasure,successMeasureText,measurementScope} from '@/lib/home-success-measures';
import {bundleIsAnalysisOnly,bundleDisplayText,bundleComponentLabels,bundleDisplayName,bundleAssumptionText,bundleHorizonEnd,bundleAssumptionCopy} from '@/lib/home-bundle-display';
const money=(value:number|null|undefined)=>value==null?'Unknown':`$${value.toLocaleString('en-US',{maximumFractionDigits:2})} USD`;
export function PlanAlternativeCard({plan,catalog,compact=false,snapshot=false,contextCurrent=true,measurePack}:{measurePack?:unknown;plan:PlanAlternative;catalog:PlanAlternatives;compact?:boolean;snapshot?:boolean;contextCurrent?:boolean}){
 const {draft,result}=plan,binding=draft.binding,currentResult=result,delivery=planDeliveryEstimate(draft),whatIf=calculatePlanWhatIf(draft.inputs),cash=planCashEstimate(draft,result.cashTotal),suggestedMeasure=suggestSuccessMeasure(binding.goal,undefined),key=plan.id,selected=plan.id;
 const referenceCatalog=contextCurrent&&!snapshot?actionEvidenceCatalog(measurePack):[];
 const referenceNotice='Saved reference only; review its population and period against current evidence. It does not establish effectiveness.';
 return <article aria-label={compact?`Comparison Action Plan ${plan.number}`:`Action Plan option ${plan.number}`} className="min-w-0 space-y-3 break-words rounded border p-3 text-sm">
 <h3 className="font-semibold">{compact?`Action Plan #${plan.number}: `:""}{bundleDisplayName(draft.bundle.name)}</h3>
 <p>{snapshot?'Attached snapshot':!plan.operation?'Original plan snapshot':plan.applied?'Applied alternative':'Proposed alternative · not yet applied'} · revision {draft.revision}{plan.sourceRefs.length?` · based on ${plan.sourceRefs.map(ref=>'Action Plan #'+catalog.plans.find(item=>item.id===ref.id)!.number).join(' and ')}`:''}.</p>
 {(!contextCurrent||snapshot)&&<p>Historical assumptions; review current evidence before acting.</p>}
 {plan.notes.map((note,index)=><p key={index}>{note}</p>)}
   {currentResult?.budget&&<p aria-label="Plan budget check" className="text-sm">{draft.inputs.budget?.basis.kind==='illustrative'&&<strong>Proposed cash-budget assumption: </strong>}{planBudgetText(currentResult)}</p>}
   <p aria-label="Plan description" className="text-sm leading-relaxed">{bundleDisplayText(draft.bundle.objective,draft.bundle,draft.inputs)}</p>
   <PlanDirections draft={draft} snapshot={snapshot}/>
   {bundleIsAnalysisOnly(draft.bundle)&&<p className="text-sm font-medium">The listed first steps are analytical; a delivery intervention still needs review.</p>}
   <ul aria-label="Selected plan summary" className="list-disc space-y-1.5 pl-5 text-sm">
    <li><strong>Approach:</strong> {bundleDisplayText(draft.bundle.coordination,draft.bundle,draft.inputs)}</li>
    <li><strong>Stakeholders:</strong> {[...new Set(draft.bundle.components.map(item=>item.ownerRole))].slice(0,2).join('; ')} (proposed roles){new Set(draft.bundle.components.map(item=>item.ownerRole)).size>2?`; ${new Set(draft.bundle.components.map(item=>item.ownerRole)).size-2} more in details`:''}. Owners are not assigned.</li>
    <li><strong>People needed:</strong> {draft.inputs.capacity&&<span>{planStaffEffortText(draft)} </span>} {delivery&&!draft.inputs.capacity&&<span>{delivery.participants??'Unresolved'} assumed participants; {delivery.hours??'unresolved'} total staff hours across the proposed owner roles. </span>}{!delivery&&<>{currentResult?.conditionalCoverage?`${currentResult.conditionalCoverage.at(-1)??'Not yet assessed'} conditional roles covered; ${currentResult.plannedAddedEmployees??'Not yet assessed'} planned added employees`:draft.inputs.groups.find(group=>group.id==='pilot-group')?`${bundleAssumptionText(draft.inputs.groups.find(group=>group.id==='pilot-group')!.count,value=>`${value} hypothetical pilot participants`)}; staffing not yet assessed`:'Not yet assessed'}.</>}</li>
    <li><strong>Cost:</strong> <span>Assumed cash {money(cash?.cash)}. {!draft.inputs.capacity&&whatIf?.status==='ready'&&whatIf.kind==='capacity'&&cash?.cash!==null&&<span>Scenario cost basis: {money(whatIf.listedCash)} listed cash allowances plus {whatIf.target} roles × {money(whatIf.unitCost)} per role per month × {whatIf.months} months = {money(whatIf.roleCash)} new-hire payroll/cash. Assumes all roles are new hires paid for the full horizon; internal moves or partial schedules require staffing review. </span>}Staff effort is listed in hours above. {cash?.reason} Reviewed full budget: {money(currentResult?.cashTotal)}.</span></li>
    <li><strong>Timeline:</strong> {delivery?.finish?`Assumed deliverables by ${delivery.finish}; planning horizon ${bundleAssumptionText(draft.inputs.scope.startMonth)} through ${bundleAssumptionText(bundleHorizonEnd(draft.inputs.scope))}`:currentResult?.planFinish?`Assumed component finish ${currentResult.planFinish}${currentResult.capacityReadyMonth?`; conditional capacity from ${currentResult.capacityReadyMonth}`:''}`:`Start ${bundleAssumptionText(draft.inputs.scope.startMonth)}; duration ${bundleAssumptionText(draft.inputs.scope.months,value=>`${value} months`)}; horizon end ${bundleAssumptionText(bundleHorizonEnd(draft.inputs.scope))}; readiness not yet assessed`}.</li>
    <li><strong>Expected outcome:</strong> {delivery&&<span>Proposed deliverables: {delivery.deliverables.join('; ')}. These are deliverable targets, not completed work; analytical work does not imply skill growth or retention improvement. </span>}{draft.inputs.whatIf&&<span>{whatIfOutcomeText(draft.inputs)} </span>}Intended contribution to “{binding.goal}”. This is a proposed outcome, not a predicted effect. Retention effects are not established.</li>
    <li><strong>How success is measured:</strong> {delivery?<span>{draft.inputs.successMeasure&&<>{successMeasureText(draft.inputs.successMeasure,draft.inputs.successMeasure.scopeKey===measurementScope(draft.inputs))} </>}{delivery.acceptance} Deliverable target: {delivery.deliverables.join('; ')}. {whatIf?.status==='ready'?'The what-if target is conditional, not a validated prediction.':'No intervention effect is inferred.'}</span>:<>{whatIf?.status==='ready'&&!draft.inputs.successMeasure&&<span>Proposed target: {whatIf.target}{whatIf.kind==='turnover'?'% turnover using voluntary exits / average workforce for the same period':' additional roles covered from the planning start'}, over {whatIf.months} months from {whatIf.start}. Track the same population and period; this is a target, not a prediction. </span>}{!draft.inputs.successMeasure&&!draft.inputs.whatIf&&<span>Suggested measure: {suggestedMeasure.name}. {suggestedMeasure.baseline?'A recorded contextual baseline is available for review; confirm the plan population and period before adopting it.':'No matching recorded baseline is available.'} Set a target as a planning assumption, not a prediction. </span>}{(draft.inputs.successMeasure||!draft.inputs.whatIf)&&successMeasureText(draft.inputs.successMeasure,!draft.inputs.successMeasure||draft.inputs.successMeasure.scopeKey===measurementScope(draft.inputs))}{draft.inputs.successMeasure?.baseline.value!==null&&draft.inputs.successMeasure?.baseline.basis&&<span className="block text-xs">{contextCurrent?'Saved baseline provenance:':'Historical baseline; current context needs review: '}{draft.inputs.successMeasure.baseline.basis}</span>}</>}</li>
   </ul>
   {draft.inputs.scope.requirements.value&&<p className="text-sm"><strong>Planning constraints:</strong> {draft.inputs.scope.requirements.value}</p>}
   <p aria-label="Plan population and source scope" className="text-xs">Plan population: {bundleAssumptionText(draft.inputs.scope.population)}. Business unit: {bundleAssumptionText(draft.inputs.scope.businessUnit)}. These are planning inputs, separate from the workforce filters and each source’s population. Department scope is not verified by Home evidence.</p>
   <PlanAssumptions key={key+selected} draft={draft}/>
   <details><summary className="min-h-11 cursor-pointer py-2 font-medium">Why these plans</summary><div className="space-y-3"><p className="text-xs">{draft.bundle.origin==='local-demo-v1'?'This example was prepared locally from fictional assumptions; no model ran.':'Plans start with one preparation response and can include reviewed local edits.'} The staffing section reports only combinations actually evaluated for the current assumptions. Attach checks the selected draft and preserves any executed search with it.</p><p className="text-xs">References describe observed context; they do not establish causes, effectiveness or a ranking. Availability and combined retention impact are not established. Proposed roles are not assigned people or operational approvals.</p><ul className="list-disc space-y-2 pl-5">
    <li><strong>Working together:</strong> {draft.bundle.components.map(item=>item.name).join('; ')}. Dependencies below show which steps can run in parallel.</li>
    <li><strong>Suggested stakeholders:</strong> {[...new Set(draft.bundle.components.map(item=>item.ownerRole))].join('; ')}. <strong>Plan limitations:</strong> {bundleDisplayText(draft.bundle.limitation,draft.bundle)} Proposed owner roles are not assigned people or operational approvals.</li></ul><p className="text-xs">Costs exclude unentered salaries, pay changes, backfill, recruiting fees and vendor quotes. Availability, retention effects, overlap and complete-budget coverage require review.</p>{draft.pilot&&<p className="text-xs">{bundleAssumptionCopy(draft.pilot.version)} · frozen at {draft.pilot.preparedAt} · UTC calendar. Preset dates and allowances are assumed values, not readiness guarantees.</p>}{draft.inputs.timing.map(item=><p className="text-xs" key={item.componentId}>{bundleComponentLabels([item.componentId],draft.bundle)}: start {bundleAssumptionText(item.start)}; finish {bundleAssumptionText(item.finish)}. Basis: {bundleAssumptionCopy(item.start.basis??'Unavailable')}; {bundleAssumptionCopy(item.finish.basis??'Unavailable')}.</p>)}{draft.bundle.components.map(component=><section key={component.id} className="rounded border p-3"><h4 className="font-semibold">{component.name}</h4><p>{bundleDisplayText(component.firstStep,draft.bundle,draft.inputs)}</p><p className="text-xs">Suggested stakeholder role: {component.ownerRole}. Proposed responsibility: coordinate “{component.name}” and its first step. Prerequisites: {bundleComponentLabels(component.dependsOn,draft.bundle)||'None proposed'}.</p><div className="space-y-1 text-xs" aria-label={`Evidence scope for ${component.name}`}><p>References: {component.evidence.join(', ')}. {referenceNotice}</p>{component.evidence.map(id=>{const reference=referenceCatalog.find(item=>item.id===id);return <p key={id}>[{id}] {reference?`${reference.scope} · ${reference.date??'Date unavailable'}. ${reference.limitation}`:'Original source scope unavailable for this context; review before using it.'}</p>})}</div><p className="text-xs">{bundleDisplayText(component.limitation,draft.bundle)}</p></section>)}
    {result&&<section><h4 className="font-semibold">{snapshot||!contextCurrent?'Saved':'Current'} shared ledger</h4><p>Shared cash entries count once. Staff effort is tracked in hours. All amounts are planning assumptions and may include the labelled assumed inputs.</p><ul>{result.ledger.filter(line=>line.kind==='cash').map(line=><li key={line.id}>{line.label}: {money(line.total)} · {line.kind==='cash'?'cash':'employee time'} · linked to {bundleComponentLabels(line.componentIds,draft.bundle)||'unassigned'}</li>)}</ul><p>Distinct participants under these saved assumptions: {result.uniqueParticipants??'Unknown'}.</p>{result.issues.map(issue=><p key={issue}>{bundleAssumptionCopy(issue)}</p>)}</section>}
   </div></details>
 </article>;
}
