import {resolveProjectionBacktest,type RankedDomain} from '@/lib/projection-backtest';
import {demoMethodLabels} from '@/lib/synthetic-domain-demo';
const labels:Record<string,string>={...demoMethodLabels,carryForward:'Last count',recentMean:'Recent mean (3)',dampedChange:'Damped change'};
export function ProjectionBacktestDetails({domain,data}:{domain:RankedDomain;data:unknown}){
 const result=resolveProjectionBacktest(domain,data);
 if(!result)return <p>Historical ranking unavailable: this source is not the verified backtest population, or fewer than three methods have comparable held-out scores. The methods remain an unranked comparison.</p>;
 const exclusions=Object.entries(result.excluded.reduce<Record<string,number>>((counts,row)=>{for(const reason of row.reasons)counts[reason]=(counts[reason]??0)+1;return counts},{}));
 return <div className="min-w-0 space-y-2 break-words" data-backtest-version="projection-backtest-ranking-v1">
  <p><strong>Historical backtest ranking:</strong> lower mean absolute error (MAE) is better, in {result.unit}. Only the existing three-method pool was tested: {result.pool.map(method=>labels[method]).join(', ')}. All three remain displayed; this is not selection from a broader search.</p>
  <p>{result.scope} Forecast values are unchanged; this historical ordering does not establish future accuracy or an operational winner.</p>
  <p><strong>Evaluation:</strong> {result.eligibleOrigins} common rolling origins, {result.scoredTargets} origin-target pairs ({result.uniqueTargetPeriods.length} distinct target periods). {result.horizons}. Each method used only releases available at its origin. Labels were restricted to those available by {result.cutoff}. Origins {result.cases[0].origin.slice(0,10)}–{result.cases.at(-1)!.origin.slice(0,10)}; targets {result.uniqueTargetPeriods[0]}–{result.uniqueTargetPeriods.at(-1)}.</p>
  <p><strong>Source:</strong> {result.source.version}; {'seed' in result.source?`seed ${result.source.seed}, ${result.source.family}; ${result.source.releasedHistoryCount} released historical periods.`:''} {result.source.basis} Source SHA-256: {result.source.sha256}.</p>
  {domain==='hiring'&&<p>The stock history was constructed and calibrated retrospectively at the current cutoff. Event-date availability is assumed; historical source vintages were not recovered. The cutoff-truncated fill ledger affects recent changes. These scores assess that one construction only.</p>}
  <p><strong>Ties and eligibility:</strong> {result.tiePolicy} At least {result.minimumOrigins} common origins are required. A whole origin is excluded unless all three methods and every requested target are eligible. Exclusions: {exclusions.length?exclusions.map(([reason,n])=>`${reason.replaceAll('-',' ')} (${n} origins)`).join('; '):'none'}.</p>
  <div className="overflow-x-auto"><table className="w-full text-xs"><caption className="text-left font-medium">Historical selection scores · MAE ({result.unit})</caption><thead><tr><th scope="col" className="text-left">Rank</th><th scope="col" className="text-left">Method</th><th scope="col" className="text-right">MAE</th><th scope="col" className="text-right">Pairs</th></tr></thead><tbody>{result.ranked.map(row=><tr key={row.method}><td>{row.rank}</td><th scope="row" className="text-left font-normal">{labels[row.method]}</th><td className="text-right tabular-nums">{row.mae.toFixed(4)}</td><td className="text-right">{row.n}</td></tr>)}</tbody></table></div>
  <div className="overflow-x-auto"><table className="w-full text-xs"><caption className="text-left font-medium">Exact scored origins and targets</caption><thead><tr><th scope="col" className="text-left">Origin</th><th scope="col" className="text-left">Last training period</th><th scope="col" className="text-left">Forecast targets</th><th scope="col" className="text-left">Latest target release</th></tr></thead><tbody>{result.cases.map(row=><tr key={row.origin}><th scope="row" className="text-left font-normal">{row.origin.slice(0,10)}</th><td>{row.trainingEnd?.slice(0,10)}</td><td>{row.targets.join(', ')}</td><td>{[...row.labelsAvailableAt].sort().at(-1)?.slice(0,10)}</td></tr>)}</tbody></table></div>
 </div>;
}
