'use client';
import {useEffectEvent,useLayoutEffect,useRef,useState,type RefObject} from 'react';
import type {ProblemConversation} from './problem-conversation';
import {decisionStore} from './decision-store';
import {PlanningCalculatorDialog} from './planning-calculator-dialog';
import {demandEditorIntent,reviewDemandEditor,type DemandEditorDraft} from '@/lib/swp-demand-editor';
import {solutionConversationEnabled} from '@/lib/home-solution-conversation';
import {SWP_DEMAND_MODE,serviceIllustrationScope,illustrativeServiceReview,readDemandReview,demandQuantityFields,type DemandContext,type DemandReview} from '@/lib/swp-demand';
export type DemandIntakeControl={begin:()=>void;close:()=>void;calculatorAvailable:()=>boolean;command:(text:string)=>Promise<string|null>};
export type ReviewedDemand={review:DemandReview;reviewedAt:string;priorAccepted:{review:DemandReview;reviewedAt:string}[]};
const button='min-h-11 rounded border px-3 py-2 text-sm font-medium disabled:opacity-50 focus-visible:ring-2 focus-visible:ring-ring';
const number=(n:number|null)=>n===null?'Unknown':n.toLocaleString('en-US',{maximumFractionDigits:2});
export function SwpDemandJourney({conversation,active,busy,beginRef,reviewRef,contextRef,onStaffing,onReview,staffingSummary,staffingInputs,seed,discussionKey=''}:{conversation:ProblemConversation;active:boolean;busy:boolean;beginRef:RefObject<DemandIntakeControl|null>;reviewRef:RefObject<((review:DemandReview)=>void)|null>;contextRef:RefObject<unknown>;onStaffing:(value:ReviewedDemand)=>Promise<void>;onReview:()=>void;staffingSummary?:unknown;staffingInputs?:unknown;discussionKey?:string;seed?:Omit<ReviewedDemand,'priorAccepted'>&{priorAccepted?:ReviewedDemand['priorAccepted']}}){
 const [context,setContext]=useState<DemandContext|null>(null),[review,setReview]=useState<DemandReview|null>(null),[accepted,setAccepted]=useState<string|null>(null),[history,setHistory]=useState<ReviewedDemand['priorAccepted']>([]),[notice,setNotice]=useState(''),[editing,setEditing]=useState(false);
 const reviewLive=useRef<DemandReview|null>(null),editorBase=useRef<string|null>(null),accepting=useRef(false);
 const live=useRef(context),mounted=useRef(false),epoch=useRef(0);const token=decisionStore.getDatasetToken(),identity=JSON.stringify([token,conversation.activeGoalId,conversation.focusedIssue,conversation.resetEpoch,active,discussionKey]);const oldIdentity=useRef(identity);
 function close(){epoch.current++;reviewLive.current=null;editorBase.current=null;setEditing(false);live.current=null;contextRef.current=null;setContext(null);setReview(null);setAccepted(null);setNotice('');}
 function begin(){if(busy||!active||!conversation.storageReady)return;const c:DemandContext={conversationMode:SWP_DEMAND_MODE,classification:'unverified-business-inputs',intakeId:seed?.review.intakeId??'swp-demand-'+crypto.randomUUID(),datasetToken:token,boundGoal:{id:conversation.activeGoalId,statement:conversation.focusedIssue},revision:seed?.review.revision??1};epoch.current++;reviewLive.current=seed?.review??null;editorBase.current=null;setEditing(false);live.current=c;contextRef.current={...c,demandProposal:seed?.review??null,acceptedForScenario:!!seed,staffingComparison:staffingSummary??null};setContext(c);setReview(seed?.review??null);setAccepted(seed?.review.key??null);setHistory(seed?[...(seed.priorAccepted??[]),{review:seed.review,reviewedAt:seed.reviewedAt}]:[]);setNotice('Describe the business outcome in chat. We can propose editable assumptions where operating inputs are missing.');}
 useLayoutEffect(()=>{const lifecycle=epoch;mounted.current=true;return()=>{mounted.current=false;lifecycle.current++;contextRef.current=null;beginRef.current=null;reviewRef.current=null;};},[contextRef,beginRef,reviewRef]);
 const closeChanged=useEffectEvent(()=>{if(oldIdentity.current!==identity){oldIdentity.current=identity;close();}});
 useLayoutEffect(()=>{closeChanged();},[identity]);
 function current(){const c=live.current;return !!c&&oldIdentity.current===identity&&mounted.current&&active&&conversation.storageReady&&c.datasetToken===decisionStore.getDatasetToken()&&c.boundGoal.id===conversation.activeGoalId&&c.boundGoal.statement===conversation.focusedIssue;}
 function receive(value:DemandReview){const c=live.current;if(!c||!current())return;const checked=readDemandReview(value,c);epoch.current++;reviewLive.current=checked;editorBase.current=null;setEditing(false);setReview(checked);setAccepted(null);onReview();setNotice('Correct any assumption in normal chat, or use this provisional scenario to compare options.');}
 function reviewEdits(draft:DemandEditorDraft){const c=live.current,source=reviewLive.current;if(!c||!source||!current()||busy||accepting.current||editorBase.current!==draft.baseKey)throw Error('The decision changed or is busy. Reopen the editor on the current review.');receive(reviewDemandEditor(source,draft,c,'demand-editor-'+crypto.randomUUID()));}
 function openCalculator(){if(!current()||!reviewLive.current||busy||accepting.current)return false;if(editorBase.current===null){editorBase.current=reviewLive.current.key;setEditing(true);setNotice('');}return true;}
 function cancelEditor(){editorBase.current=null;setEditing(false);setNotice('Assumption edits cancelled. The current review and scenario acceptance are unchanged.');}
 async function accept(){if(!context||!review||busy||!current()||accepting.current)return '';if(editorBase.current!==null)return 'Review planning inputs or cancel the calculator first. The current scenario has not changed.';if(accepted===review.key)return 'These assumptions are already accepted for scenario use. Their provenance remains unverified; saving a plan still needs explicit review.';const checked=readDemandReview(review,context),value={review:checked,reviewedAt:new Date().toISOString(),priorAccepted:history},job=epoch.current;accepting.current=true;
  try{await onStaffing(value);if(!current()||epoch.current!==job||reviewLive.current?.key!==checked.key)return '';setAccepted(checked.key);setHistory(prior=>prior.some(p=>p.review.key===checked.key)?prior:[...prior,{review:checked,reviewedAt:value.reviewedAt}]);setNotice('Using these assumptions for the scenario. Their original proposed or reported provenance is retained; operational availability is not verified.');return 'The provisional comparison is below. Proposed assumptions remain unverified; review any workload shortfall before saving.';}catch(e){if(!mounted.current||epoch.current!==job)return '';setNotice((e as Error).message);return (e as Error).message;}finally{accepting.current=false;}
 }
 useLayoutEffect(()=>{beginRef.current={begin,close,calculatorAvailable:()=>current()&&!!reviewLive.current,command:async text=>{const intent=demandEditorIntent(text);if(intent){if(!context||!review)return 'I need a reviewed set of business assumptions first. Describe the intended work in chat.';if(!current()||busy||accepting.current)return 'Finish the current request before editing assumptions.';if(intent==='close'){cancelEditor();return 'The editor is closed; the current review and acceptance are kept.';}if(editorBase.current!==null)return 'Planning Calculator is already open. Your unsaved edits are kept.';openCalculator();return 'Planning Calculator is open. Review any edits before using them; no assumptions were accepted and no plan was saved.';}if(!context||!/^use (?:your|these|the) assumptions(?: for now| for this scenario)?[.!]?$/i.test(text.trim()))return null;if(!review)return 'I need to propose the operating assumptions first. Describe the intended work in chat.';return await accept();}};reviewRef.current=receive;contextRef.current=context?{...context,demandProposal:review,acceptedForScenario:accepted===review?.key,staffingComparison:staffingSummary??null}:null;});
 return <div className="space-y-3" aria-label="Business demand intake">
 {!context?<><button className={button} disabled={busy||!active||!conversation.storageReady} onClick={begin}>{seed?'Continue reviewed business assumptions':'Start with my business objective'}</button><p className="text-xs">Describe a project, managed-services opportunity or redeployment decision in normal chat. No headcount target, budget or engineered prompt is required.</p></>:<>
 <p className="text-sm">Start with the business outcome. Missing planning inputs can use proposed assumptions; correct one in chat, such as “Make that nine months” or “Assume 25% available”.</p>
 {!solutionConversationEnabled&&<p role="status" className="text-sm">Business intake AI is unavailable in this mode. The optional local illustration remains available.</p>}
 <button className={button} disabled={busy||!active} onClick={()=>context&&receive(illustrativeServiceReview(context,new Date().toISOString()))}>Review an illustrative managed-services example</button>
 {review&&<section aria-label="Review business demand assumptions" className="space-y-2 rounded border p-3 text-sm">
 <h3 className="font-semibold">{accepted===review.key?'Assumptions accepted for scenario use':'Using proposed assumptions'}</h3><p>{review.spec.objective}</p><p>{review.spec.scope??'Role slice needs clarification'} · {review.spec.startMonth??'Start unknown'} · {review.spec.months??'Unknown'} months.</p>
 {review.result.status==='calculated'?<div aria-label="Calculated managed-services workload bridge"><p>{number(review.spec.contracts.value)} contracts × {number(review.spec.hoursPerContract.value)} role-slice hours / {review.spec.hoursPerContract.period} → {number(review.result.workloadHours)} hours over the horizon.</p><p>{number(review.spec.existingRoles.value)} existing roles × {number(review.spec.existingFtePerRole.value)} FTE / role × {number(review.spec.availabilityPct.value)}% uncommitted = {number(review.result.availableFte)} available FTE; {number(review.result.capacityHours)} hours.</p><p><strong>Gap: {number(review.result.gapHours)} hours → {number(review.result.additionalFte)} FTE → {number(review.result.additionalRoles)} whole roles</strong> at {number(review.spec.ftePerRole.value)} FTE / role.</p>{review.result.additionalRoles===0&&<p>No additional staffing is implied. No hires are generated.</p>}</div>:<p role="status">Comparison needs clarification: {review.result.missing.join(' ')}</p>}
 <p className="text-xs">Single operational role slice; a full delivery plan, peak coverage and service levels remain unmodeled.</p>
 <details><summary className="min-h-11 cursor-pointer py-2">Details: values, rationale and provenance</summary>
 <p>Operating link: {review.spec.linkage??'Unknown'}</p>
 {(['scope','linkage','start','months'] as const).map(key=>{const b=review.spec[`${key}Basis`];return <p key={key}>{key}: {b.kind} · {b.explanation} {b.quote&&<q>{b.quote}</q>}</p>;})}
 <div className="overflow-x-auto"><table className="w-full text-left text-xs"><caption>Proposed or user-supplied inputs remain unverified after acceptance</caption><thead><tr><th>Input</th><th>Value / period</th><th>Basis</th></tr></thead><tbody>{demandQuantityFields.map(key=>{const q=review.spec[key];return <tr key={key} className="border-t"><th className="p-2 font-normal">{key.replace(/([A-Z])/g,' $1')}</th><td>{number(q.value)}{q.period?` / ${q.period}`:''}<p>{q.scope??'Scope unknown'}</p></td><td>{q.basis.kind}<p>{q.basis.explanation}</p>{q.basis.quote&&<q>{q.basis.quote}</q>}</td></tr>;})}</tbody></table></div>
 <p>Code-owned workforce facts do not establish allocations, effort or available capacity. An explicit staffing premise is not proof of business demand. Budget is optional for the workload calculation.</p><ul className="list-disc pl-5">{review.result.limitations.map(s=><li key={s}>{s}</li>)}</ul></details>
 <button className={button} disabled={busy||!active} onClick={openCalculator}>Open Planning Calculator</button>
 <PlanningCalculatorDialog open={editing} review={review} disabled={busy||!active} onReview={reviewEdits} onCancel={cancelEditor}/>
 {review.result.status==='calculated'&&review.result.additionalRoles!>0&&(review.spec.scope===serviceIllustrationScope&&review.spec.ftePerRole.value===1&&review.result.additionalRoles!<=20?<>{staffingInputs?<><p>Previously reviewed staffing inputs below are retained. A demand correction changes only coupled role/horizon quantities; it does not reset costs, dates or search constraints.</p><details><summary>Current retained staffing inputs</summary><pre className="overflow-auto whitespace-pre-wrap text-xs">{JSON.stringify(staffingInputs,null,2)}</pre></details></>:<p>Provisional staffing comparison adds separate illustrative inputs: {review.spec.budgetUsd.value===null?'$325,000 cash ceiling (not a supplied budget)':`$${number(review.spec.budgetUsd.value)} scenario cash ceiling`}; $96,000 annual hire cost + $3,000 fee, $24,000 annual internal uplift, $6,000 training cash and 80 training hours. Hire delivery is assumed at the start.</p>}{!staffingInputs&&<p>Conditional alternatives additionally assume up to three development places and two moves, distinct and releasable after two and one months, with zero backfills. These are invented pools, separate from already-counted uncommitted capacity; internal alternatives are disabled when that capacity is positive. The hire-only reference can remain over budget. Delayed starts can leave a workload shortfall even when end-date role limits fit.</p>}{staffingInputs&&<p>Retained internal pool and release assumptions remain conditional and separate from baseline capacity. Any positive baseline capacity disables the internal alternatives. Review the full-period effort gap as well as the end-date limits.</p>}<button className={button} disabled={busy||!active||editing||accepted===review.key} onClick={()=>void accept()}>{accepted===review.key?'Assumptions accepted for scenario use':'Use your assumptions for now'}</button></>:<p>The calculated gap is retained. This role slice or FTE schedule needs separately reviewed staffing inputs; the optional service-analyst example has not been substituted.</p>)}
 </section>}
 <button className={button} disabled={busy} onClick={close}>Close business demand discussion</button>
 </>}{notice&&<p role="status" className="text-sm">{notice}</p>}
 </div>;
}
