'use client';
import {useEffect,useEffectEvent,useLayoutEffect,useRef,useState,type RefObject} from 'react';
import {decisionStore,useDecisionStorage} from './decision-store';
import type {ProblemConversation} from './problem-conversation';
import {createSwpDemo,compareSwpDemo,prepareSwpSelection,readSwpSaveReview,swpDemoField,swpDemoPrompt,swpEnd,swpMetric,createServiceStaffingDemo,serviceOptionEffort,swpDemandBridgeField,validateDemandBridge,type SwpDemandBridge} from '@/lib/swp-demo';
import {bundleInputKey,type BundleDraft} from '@/lib/home-bundle-reconciliation';
import {previewBundleChatEdit,acceptBundleChatEdit,bundleChatEditIntent,type BundleEditPreview} from '@/lib/home-bundle-chat-edit';
import {SWP_CONVERSATION_MODE} from '@/lib/swp-conversation-model';
import {SwpDemandJourney,type DemandIntakeControl,type ReviewedDemand} from './swp-demand-journey';
import {serviceStaffingBundle} from '@/lib/home-demo-catalog';
import type {DemandReview} from '@/lib/swp-demand';
import {SwpOutcomeChart} from './swp-outcome-chart';
import {goalProgressField} from '@/lib/goal-progress';
import {readProgressSnapshot,readProgressLinkedPlan} from '@/lib/goal-progress-summary';
import {GoalProgressSummary} from './goal-progress-summary';
import {planAlternativesField,readPlanAlternatives} from '@/lib/home-plan-alternatives';
import type {AppPage} from '@/lib/types';
const button='min-h-11 rounded border px-3 py-2 text-sm font-medium focus-visible:ring-2 focus-visible:ring-ring disabled:opacity-50';
const money=(v:number|null|undefined)=>v==null?'Unknown':`$${v.toLocaleString('en-US')} USD`;
type Comparison=Awaited<ReturnType<typeof compareSwpDemo>>;
type Selection=Awaited<ReturnType<typeof prepareSwpSelection>>;
type Source={id:string;label:string;status:string;scope:string;date:string|null;limitation:string;facts?:unknown};
const effortText=(option:Comparison['options'][number],bridge:SwpDemandBridge)=>{const e=serviceOptionEffort(option,bridge),n=(v:number|null)=>v===null?'unknown':v.toLocaleString('en-US',{maximumFractionDigits:2});return `Whole-period conditional capacity: ${n(e.totalHours)} of ${n(bridge.review.result.workloadHours)} hours; remaining effort gap ${n(e.shortfallHours)} hours. Uniform monthly productive capacity is assumed; partial effective readiness months are excluded. Peak coverage and service levels remain unproven.`;};
type Props={conversation:ProblemConversation;active:boolean;busy:boolean;commandRef:RefObject<((text:string)=>Promise<string|null>)|null>;modelContextRef:RefObject<unknown>;demandControlRef:RefObject<DemandIntakeControl|null>;demandReviewRef:RefObject<((review:DemandReview)=>void)|null>;demandContextRef:RefObject<unknown>;sources:Source[];onNavigate:(page:AppPage)=>void};
export function SwpGuidedJourney({conversation,active,busy,commandRef,modelContextRef,demandControlRef,demandReviewRef,demandContextRef,sources,onNavigate}:Props){
 const storage=useDecisionStorage(),[draft,setDraft]=useState<BundleDraft|null>(null),[draftDataset,setDraftDataset]=useState<string|null>(null),[comparison,setComparison]=useState<Comparison|null>(null),[edit,setEdit]=useState<BundleEditPreview|null>(null),[selection,setSelection]=useState<string|null>(null),[review,setReview]=useState<Selection|null>(null),[pending,setPending]=useState(false),[notice,setNotice]=useState('');
 const [demandBridge,setDemandBridge]=useState<SwpDemandBridge|null>(null),[demandStale,setDemandStale]=useState(false);
 const ownedIsolation=useRef<string|null>(null),endIsolation=useRef(conversation.endGuidedExploration),resetSeen=useRef(conversation.resetEpoch);
 const opening=useRef(false),generation=useRef(0),abort=useRef<AbortController|null>(null),mounted=useRef(true),live=useRef({draft,active,busy,goalId:conversation.activeGoalId,resetEpoch:conversation.resetEpoch}),token=decisionStore.getDatasetToken();
 useLayoutEffect(()=>{endIsolation.current=conversation.endGuidedExploration;live.current={draft,active,busy,goalId:conversation.activeGoalId,resetEpoch:conversation.resetEpoch};});
 useEffect(()=>{const lifecycle=generation;mounted.current=true;return()=>{lifecycle.current++;if(ownedIsolation.current){endIsolation.current();ownedIsolation.current=null;}mounted.current=false;abort.current?.abort();commandRef.current=null;modelContextRef.current=null;};},[commandRef,modelContextRef]);
 const restored=useRef('');
 const restore=useEffectEvent(()=>{
  const id=conversation.activeGoalId;const identity=JSON.stringify([token,id,conversation.focusedIssue]);if(restored.current===identity)return;restored.current=identity;
  abort.current?.abort();setPending(false);setReview(null);setEdit(null);setComparison(null);setSelection(null);
  if(ownedIsolation.current&&id&&id!==ownedIsolation.current){endIsolation.current();ownedIsolation.current=null;}
  const saved=readSwpSaveReview(storage.data.workspaces[id]?.fields[swpDemoField]);
  if(saved&&saved.datasetToken===token&&saved.draft.binding.goal===conversation.focusedIssue){const b=storage.data.workspaces[id]?.fields[swpDemandBridgeField] as unknown as SwpDemandBridge|undefined;try{if(!b&&saved.draft.bundle.name===serviceStaffingBundle().name)throw Error('Saved operational bridge is missing.');if(b)validateDemandBridge(saved.draft,b,token);setDemandBridge(b??null);setDemandStale(false);}catch{setDemandBridge(null);setDemandStale(true);}setDraft(saved.draft);setDraftDataset(saved.datasetToken);setNotice('Saved proposal restored. Compare its exact assumptions again to review alternatives.');}
  else if(id||draft&&storage.data.workspaces[draft.binding.goalId]?.fields[swpDemoField]){if(ownedIsolation.current){endIsolation.current();ownedIsolation.current=null;}setDraft(null);setNotice('Earlier saved plans are kept. Select their exact goal to continue.');}
 });
 // eslint-disable-next-line react-hooks/set-state-in-effect -- Select the existing goal's local draft without committing a view change.
 useEffect(()=>{restore();},[conversation.activeGoalId,conversation.focusedIssue,token]);
 // eslint-disable-next-line react-hooks/set-state-in-effect -- Navigation cancels the currently owned calculation and closes its review.
 useEffect(()=>{if(!active){generation.current++;abort.current?.abort();if(opening.current&&ownedIsolation.current){endIsolation.current();ownedIsolation.current=null;}opening.current=false;setPending(false);setReview(null);}},[active]);
 function exit(){demandControlRef.current?.close();setDemandBridge(null);setDemandStale(false);generation.current++;opening.current=false;abort.current?.abort();if(ownedIsolation.current){endIsolation.current();ownedIsolation.current=null;}const goals=decisionStore.getSnapshot().data.goals;restored.current=JSON.stringify([decisionStore.getDatasetToken(),goals.activeId,goals.goals.find(g=>g.id===goals.activeId)?.statement??'']);setDraft(null);setComparison(null);setEdit(null);setReview(null);setSelection(null);setPending(false);setNotice('Example closed. Earlier goals and plans are kept.');}
 const handleReset=useEffectEvent(()=>{if(resetSeen.current!==conversation.resetEpoch){resetSeen.current=conversation.resetEpoch;exit();}});
 useEffect(()=>{handleReset();},[conversation.resetEpoch]);
 const draftKey=draft?bundleInputKey(draft):'',matches=!!draft&&(!conversation.activeGoalId||conversation.activeGoalId===draft.binding.goalId&&conversation.focusedIssue===draft.binding.goal)&&token===draftDataset;
 const currentComparison=comparison?.inputKey===draftKey&&!edit&&!demandStale?comparison:null;
 const saved=readSwpSaveReview(storage.data.workspaces[conversation.activeGoalId]?.fields[swpDemoField]);
 const exactSaved=!!saved&&!!draft&&bundleInputKey(saved.draft)===draftKey&&saved.candidateId===selection;
 function clearReview(){setReview(null);setNotice('');}
 async function handle(text:string):Promise<string|null>{
  if(!active||busy||pending||!storage.saved)return text===swpDemoPrompt?'':null;
  if(text===swpDemoPrompt){
   demandControlRef.current?.close();setDemandBridge(null);setDemandStale(false);
   const id='guided-swp-'+crypto.randomUUID(),job=++generation.current,reset=conversation.resetEpoch;conversation.beginGuidedExploration(id);ownedIsolation.current=id;opening.current=true;setPending(true);
   const current=()=>mounted.current&&live.current.active&&generation.current===job&&ownedIsolation.current===id&&live.current.resetEpoch===reset&&decisionStore.getDatasetToken()===token&&!decisionStore.getSnapshot().data.goals.activeId;
   try{const next=await createSwpDemo(id,new Date().toISOString());if(!current())return '';setDraft(next);setDraftDataset(token);setComparison(null);setEdit(null);setSelection(null);setReview(null);setNotice('');
    return 'Here is the fictional service-growth decision. Review the five-role demand assumption, unit, horizon and budget below, then compare the options. Nothing has been chosen or saved as your plan.';
   }catch(error){if(!current())return '';exit();throw error;}finally{if(generation.current===job){opening.current=false;setPending(false);}}
  }
  if(!matches||!draft||demandContextRef.current||!bundleChatEditIntent(text).edit)return null;
  clearReview();try{const preview=previewBundleChatEdit(draft,text);setEdit(preview);return 'Review the proposed assumption changes below. Existing results are stale until you accept the draft changes and compare again; saved plans stay unchanged.';}
  catch(error){setEdit(null);return `${(error as Error).message} The draft and saved plans are kept. Use a displayed assumption name, or discuss an unsupported choice without treating it as calculated.`;}
 }
 useLayoutEffect(()=>{commandRef.current=handle;modelContextRef.current=draft&&matches&&!demandStale?{conversationMode:SWP_CONVERSATION_MODE,goalId:draft.binding.goalId,classification:'fictional-scenario',acceptedOperationalReview:demandBridge?{spec:demandBridge.review.spec,result:demandBridge.review.result,reviewedAt:demandBridge.reviewedAt,acceptance:'Scenario use only; original provenance retained.'}:null,datasetToken:token,revision:draft.revision,selectedCandidateId:selection,selectedSavedPlanId:saved?.selectedPlanId??null,goal:draft.binding.goal,objective:draft.inputs.scope.requirements,scope:draft.inputs.scope,budget:draft.inputs.budget,reviewState:edit?'pending-edits':currentComparison?'calculated-unsaved':'not-calculated',options:currentComparison?.options.map(o=>({id:o.id,label:o.label,mix:o.candidate.mix,wholePeriodEffort:demandBridge?serviceOptionEffort(o,demandBridge):null,conditionalCoverage:o.coverage,fullCoverageDate:o.candidate.metrics?.fullCoverageDate??null,incrementalCash:o.candidate.cash.complete,staffHours:o.candidate.effort?.totalHours??null,addedCompanyEmployees:o.candidate.metrics?.addedEmployees??null,status:o.candidate.status}))??[],limitations:['End-date staffing and cash limits do not prove whole-period effort coverage; review any separately calculated shortfall.','Additional-role demand is a reviewed assumption, not inferred from growth.','Skill coverage does not establish available staff or causal uplift.','Contract and automate are discussion-only here; no calculated benefit.','Changing staffing inputs requires the displayed local assumption review and recalculation.']} : null;});
 async function calculate(){
  if(!draft||!matches||busy||pending||edit||demandStale||!active)return;abort.current?.abort();const job=new AbortController();abort.current=job;const key=draftKey,goalId=conversation.activeGoalId,dataset=token;setPending(true);clearReview();setComparison(null);
  try{const result=await compareSwpDemo(draft,job.signal);if(job.signal.aborted||!mounted.current||!live.current.active||live.current.goalId!==goalId||!live.current.draft||bundleInputKey(live.current.draft)!==key||decisionStore.getDatasetToken()!==dataset)return;setComparison(result);setSelection(null);}
  catch(error){if(!job.signal.aborted)setNotice((error as Error).message);}finally{if(abort.current===job){abort.current=null;setPending(false);}}
 }
 async function prepare(){
  if(!draft||!currentComparison||!selection||pending||busy)return;const key=draftKey,id=selection,job=new AbortController();abort.current=job;setPending(true);clearReview();
  try{const prepared=await prepareSwpSelection(decisionStore,draft,currentComparison.evaluation,id,new Date().toISOString(),()=>mounted.current&&live.current.active&&!live.current.busy&&!!live.current.draft&&bundleInputKey(live.current.draft)===key,job.signal,demandBridge??undefined);if(!job.signal.aborted)setReview(prepared);}
  catch(error){if(!job.signal.aborted)setNotice((error as Error).message);}finally{if(abort.current===job){abort.current=null;setPending(false);}}
 }
 function save(){
  if(!review||review.alreadySaved||!review.fields||!matches||pending||busy||!active)return;
  try{conversation.selectProposalGoal(review.goal,review.revision,review.fields);conversation.endGuidedExploration(true);ownedIsolation.current=null;setReview(null);setNotice('Reviewed Action Plan and goal saved together. Proposed owners and milestones are retained; this is not operational authorization.');}
  catch(error){setNotice((error as Error).message);setReview(null);}
 }
 function invalidateDemand(){setDemandStale(true);setComparison(null);setSelection(null);setReview(null);}
 async function useDemand(value:ReviewedDemand){
  if(busy||pending||!active||!storage.saved)throw Error('Finish the current request before reviewing this scenario.');
  const bridge:SwpDemandBridge={...value,staffingReviewedAt:new Date().toISOString()},id=draft&&demandBridge?draft.binding.goalId:'guided-swp-'+crypto.randomUUID(),job=++generation.current,expectedGoal=conversation.activeGoalId,expectedToken=token;
  const controller=new AbortController();abort.current=controller;setPending(true);try{const next=await createServiceStaffingDemo(id,bridge,bridge.staffingReviewedAt,draft&&demandBridge?{draft,bridge:demandBridge}:undefined),result=await compareSwpDemo(next,controller.signal);
   if(controller.signal.aborted||!mounted.current||!live.current.active||generation.current!==job||live.current.goalId!==expectedGoal||decisionStore.getDatasetToken()!==expectedToken)throw Error('The decision changed. Review the assumptions again.');
   if(conversation.activeGoalId&&conversation.activeGoalId!==id)throw Error('Start a new conversation before creating a separate business goal; the reviewed calculation is retained.');
   setDraft(next);setDraftDataset(token);setDemandBridge(bridge);setDemandStale(false);setComparison(result);setSelection(null);setReview(null);setEdit(null);setNotice('Provisional routes use separate illustrative staffing assumptions. End-date limits do not establish whole-period workload coverage.');
  }finally{if(abort.current===controller){abort.current=null;setPending(false);}}
 }
 const selected=currentComparison?.options.find(o=>o.id===selection),fields=storage.data.workspaces[conversation.activeGoalId]?.fields;
 const catalog=fields&&readPlanAlternatives(fields[planAlternativesField],{goalId:conversation.activeGoalId,goal:conversation.focusedIssue});
 let progress:ReturnType<typeof readProgressSnapshot>|null=null;
 try{if(fields?.[goalProgressField]&&saved)progress=readProgressSnapshot(fields[goalProgressField],conversation.activeGoalId,new Date().toISOString().slice(0,10));}catch{/* Retain malformed saved bytes without displaying invented progress. */}
 return <section aria-label="Strategic workforce planning journey" className="min-w-0 space-y-3 rounded-xl border border-primary/30 p-4">
  <div><h2 className="text-lg font-semibold">Plan the workforce for your business goal</h2><p className="text-sm">Define the outcome and horizon, compare options, then review a plan. People Analytics supplies supporting evidence.</p></div>
  {(!draft||demandBridge)&&<SwpDemandJourney conversation={conversation} active={active} busy={busy||pending} beginRef={demandControlRef} reviewRef={demandReviewRef} contextRef={demandContextRef} onReview={invalidateDemand} onStaffing={useDemand} seed={demandBridge??undefined} staffingInputs={demandBridge?draft?.inputs.capacity:undefined} staffingSummary={demandBridge&&currentComparison?currentComparison.options.map(o=>({mix:o.candidate.mix,cash:o.candidate.cash.complete,endDateLimits:o.candidate.status,effort:serviceOptionEffort(o,demandBridge)})):null}/>}
  {!draft||!matches?<><button className={button} disabled={busy||pending||!active||!conversation.storageReady||!storage.saved||!!conversation.input.trim()} onClick={()=>conversation.draftExample(swpDemoPrompt)}>Explore the five-role example</button><p className="text-xs text-muted-foreground">Fictional scenario. Review the question in chat and Send; opening it does not save a goal.</p></>:<>
   <p className="text-xs font-medium">{saved?'Saved example · new comparisons remain proposals':'Unsaved example proposal'} · synthetic data and fictional assumptions</p>
   <p className="text-sm"><strong>Business objective:</strong> {draft.inputs.scope.requirements.value}</p>
   <p className="text-sm"><strong>Scope:</strong> {draft.inputs.scope.population.value}. <strong>Demand:</strong> {draft.inputs.scope.demand.value??'Unknown'} additional whole roles. <strong>Horizon:</strong> {draft.inputs.scope.startMonth.value} through {swpEnd(draft)}. <strong>Cash ceiling:</strong> {money(draft.inputs.budget?.amount.value)}.</p>
   <details><summary className="min-h-11 cursor-pointer py-2 text-sm">Current workforce and skills evidence</summary><p className="text-xs">This illustrative role slice has no matched operational allocation baseline. Its additional-role requirement is a scenario premise or a code-calculated gap from separately reviewed assumptions. The company evidence below retains its own scope and does not verify internal availability.</p>{sources.filter(s=>['W1','T1','T2','R1'].includes(s.id)).map(s=><div key={s.id} className="my-2 text-xs"><strong>{s.label}</strong>: {s.status==='loaded'?'Available':'Unavailable'} · {s.scope} · {s.date||'Date unavailable'}.<p>{s.limitation}</p></div>)}<button className={button} onClick={()=>onNavigate('skills')}>Open supporting skill evidence</button><p className="text-xs">Training completion is not demonstrated capability; a work sample and manager validation are proposed before release.</p></details>
   <details><summary className="min-h-11 cursor-pointer py-2 text-sm">Review assumptions and edit in chat</summary><p className="text-xs">Say “Set budget to $100,000”, “Set training hours to 100”, or “Set Build effective month to {draft.inputs.capacity?.input.buildMonth}”. All entries remain assumptions. Demand, scope or horizon changes need coupled-input review; unsupported edits fail visibly.</p><ul className="list-disc pl-5 text-xs">{Object.entries(draft.inputs.capacity?.input??{}).filter(([,v])=>v!=='').map(([k,v])=><li key={k}>{k.replace(/([A-Z])/g,' $1').replace(/^./,c=>c.toUpperCase())}: {v}</li>)}</ul><p className="text-xs">Build group: {draft.inputs.groups.find(g=>g.id==='scenario-build')?.count.value??'Unknown'}; Move group: {draft.inputs.groups.find(g=>g.id==='scenario-move')?.count.value??'Unknown'}, assumed distinct and releasable; {draft.inputs.capacity?.input.backfills||'Unknown'} backfills is the displayed premise. Contracting and automation are not calculated by this example. Attrition and productivity effects are not included. Staff effort covers entered training hours; unentered recruiting and management effort remains unestimated.</p></details>
   {edit&&<section aria-label="Review workforce assumption changes" className="rounded border p-3 text-sm"><p>Calculations are stale while these edits await review.</p><ul>{edit.changes.map(c=><li key={c.field}>{c.field}: {String(c.before.value??'Unknown')} → {String(c.after.value??'Unknown')}</li>)}</ul><div className="flex flex-wrap gap-2"><button className={button} disabled={busy||pending||!active} onClick={()=>{if(busy||pending||!active)return;try{setDraft(acceptBundleChatEdit(draft,edit));setEdit(null);setComparison(null);setSelection(null);clearReview();}catch(e){setNotice((e as Error).message);}}}>Use changes in this draft</button><button className={button} disabled={busy||pending||!active} onClick={()=>{if(busy||pending||!active)return;setEdit(null);clearReview();}}>Cancel changes</button></div></section>}
   <div className="flex flex-wrap gap-2"><button className={button} disabled={busy||pending||!!edit||demandStale||!active||!storage.saved} onClick={()=>void calculate()}>Compare these demo assumptions</button>{pending&&<button className={button} onClick={()=>{generation.current++;abort.current?.abort();setPending(false);setReview(null);setNotice('Request cancelled. Saved work is kept.');}}>Cancel comparison</button>}</div>
   {demandStale&&<p role="status">Demand assumptions changed. Accept their current review before comparing or saving.</p>}
   {pending&&<p role="status" className="text-sm">Checking the existing staffing calculation…</p>}
   {currentComparison&&<>
    {currentComparison.evaluation.context.status==='needs-inputs'?<p role="status">No comparison yet: {currentComparison.evaluation.context.missing.map(m=>m.reason).join(' ')}</p>:<>
     <SwpOutcomeChart draft={draft} options={currentComparison.options}/>
     <p className="text-xs">{currentComparison.evaluation.report?.summary.enumerated} bounded combinations checked. {currentComparison.evaluation.report?.summary.counts.met} meet the entered limits; these are conditional results, not proof of staffing feasibility.</p>
     <fieldset disabled={busy||pending||!active} className="space-y-2"><legend className="font-semibold">Compare and select for review</legend>{currentComparison.options.map(o=><label key={o.id} className="block space-y-1 rounded border p-3 text-sm"><span className="flex min-h-11 items-center gap-2"><input type="radio" name="swp-option" checked={selection===o.id} disabled={o.candidate.status!=='met'} onChange={()=>{setSelection(o.id);clearReview();}}/><strong>{o.label}: develop {o.candidate.mix.build}, move {o.candidate.mix.move}, hire {o.candidate.mix.buy}</strong></span><span className="block">{money(o.candidate.cash.complete)} incremental cash · {o.candidate.effort?.totalHours??'Unknown'} staff hours · {o.candidate.metrics?.addedEmployees??'Unknown'} added employees including backfills.</span><span className="block">Conditional coverage: {o.candidate.metrics?.fullCoverageDate??'Unknown'}. {o.candidate.status==='met'?'Meets entered end-date staffing and cash limits.':'Does not meet entered limits.'}</span>{demandBridge&&<span className="block">{effortText(o,demandBridge)}</span>}<span className="block text-xs">{o.candidate.mix.build+o.candidate.mix.move>0?'Requires internal eligibility, skill readiness and source-team release; training does not guarantee capability.':'Requires hiring delivery and funding; recruiting history does not guarantee starts.'}</span></label>)}</fieldset>
     <button className={button} disabled={!selected||pending||busy||exactSaved} onClick={()=>void prepare()}>{exactSaved?'This choice is already saved':'Review selected Action Plan'}</button>
    </>}
   </>}
   {review&&selected&&<section aria-label="Review and save workforce plan" className="space-y-2 rounded border p-3 text-sm"><h3 className="font-semibold">Review before saving</h3>{demandBridge&&<><p>{effortText(selected,demandBridge)}</p><p>Accepted for scenario use only: demand inputs retain their original proposed/reported provenance. Internal pools, distinct membership, release, zero backfills and hire delivery are separate unverified staffing premises. This saves an incomplete conditional staffing proposal when effort remains uncovered.</p><details><summary>Accepted operational assumptions and history</summary><pre className="overflow-auto whitespace-pre-wrap text-xs">{JSON.stringify({spec:demandBridge.review.spec,reviewedAt:demandBridge.reviewedAt,priorAccepted:demandBridge.priorAccepted},null,2)}</pre></details></>}<p>{draft.binding.goal} · {draft.inputs.scope.population.value} · target {draft.inputs.scope.demand.value} roles by {swpEnd(draft)}.</p><p>Proposed owners are roles, not assigned people. Selecting this proposal acknowledges unknowns; funding, availability and capability are unverified. Changed staffing costs still require component cost review in the saved plan.</p><ul className="list-disc pl-5">{selected.draft.bundle.components.map(c=><li key={c.id}>{c.name} — proposed owner: {c.ownerRole}; checkpoint: {selected.draft.inputs.timing.find(t=>t.componentId===c.id)?.finish.value??'Unknown'}.</li>)}</ul><p><strong>Success measure:</strong> {swpMetric} in this unit and role. Assess readiness before deployment; training completion alone does not meet the target.</p><div className="flex flex-wrap gap-2"><button className={button} disabled={busy||pending||review.alreadySaved} onClick={save}>Save reviewed plan and goal</button><button className={button} onClick={()=>setReview(null)}>Cancel review</button></div></section>}
   {catalog&&saved&&<details><summary className="min-h-11 cursor-pointer py-2 text-sm">Saved plan versions and proposed owners ({catalog.attachments.length})</summary>{catalog.attachments.map(a=>{const p=catalog.plans.find(p=>p.id===a.planId)!;return <div key={a.id} className="my-2 text-xs"><strong>Action Plan #{p.number} · revision {p.draft.revision} · attached proposal</strong><p>{a.attachedAt}. {p.draft.bundle.components.map(c=>`${c.name}: ${c.ownerRole} (proposed)`).join('; ')}.</p><p>Saved cash estimate: {money(p.result.cashEstimate?.cash)}. Prior source inputs and search results are retained.</p></div>;})}</details>}
   {progress&&fields&&<details><summary className="min-h-11 cursor-pointer py-2 text-sm">Saved goal progress and plan link</summary><GoalProgressSummary context={progress.context} snapshot={progress} plan={readProgressLinkedPlan(fields[goalProgressField],fields,progress.context,conversation.focusedIssue,token)} goal={conversation.focusedIssue}/></details>}
  </>}
  {draft&&<button className={button} onClick={exit}>Exit workforce example</button>}
  {notice&&<p role="status" className="text-sm">{notice}</p>}
 </section>;
}
