'use client';
import {useEffect,useLayoutEffect,useRef,useState} from 'react';
import {calculateWorkloadCapacity,type WorkloadCapacityInput} from '@/lib/workload-capacity';
import {createWorkloadIllustration} from '@/lib/workload-capacity-illustration';
import {workloadFields,workloadValues,previewWorkloadValues,workloadChatChange,type WorkloadValues} from '@/lib/workload-capacity-edit';
import {actionBinding} from '@/lib/home-action-drafts';
import {reviewBundleProposal} from '@/lib/home-bundle-reconciliation';
import {HomePlanSummary} from '@/components/home-plan-summary';
import {decisionStore,useDecisionStorage} from '@/components/decision-store';
const button='min-h-11 rounded border px-3 py-2 text-sm font-medium disabled:opacity-50 focus-visible:ring-2 focus-visible:ring-ring';
const control='min-h-11 w-full min-w-0 rounded border bg-background px-3 py-2 text-base focus-visible:ring-2 focus-visible:ring-ring';
const quantity=(n:number|null)=>n===null?'Unknown':n.toLocaleString('en-US',{maximumFractionDigits:2});
type Identity=WorkloadCapacityInput['identity'];
type Preview=ReturnType<typeof previewWorkloadValues>;
function Editor({input,onReview,onCancel}:{input:WorkloadCapacityInput;onReview:(v:WorkloadValues)=>void;onCancel:()=>void}){
 const [values,setValues]=useState(()=>workloadValues(input)),first=useRef<HTMLInputElement>(null),[error,setError]=useState('');useEffect(()=>{first.current?.focus();},[]);
 return <section aria-label="Optional workload assumption editor" className="space-y-3 rounded border p-3" onKeyDown={e=>{if(e.key==='Escape'){e.preventDefault();onCancel();}}}><h2 className="font-semibold">Edit assumptions</h2><p>Monthly values apply to every month. Blank means unknown. Scope, staffing and readiness stay as reviewed.</p><div className="grid gap-3 sm:grid-cols-2">{workloadFields.map(([key,label],i)=><label key={key}>{label}<input ref={i===0?first:undefined} className={control} type="number" step="any" min="0" value={values[key]} onChange={e=>{setError('');setValues({...values,[key]:e.target.value});}}/></label>)}</div>{error&&<p role="alert">{error}</p>}<button className={button} onClick={()=>{try{onReview(values);}catch(e){setError((e as Error).message);}}}>Review edited assumptions</button> <button className={button} onClick={onCancel}>Cancel assumption edits</button></section>;
}
/** Local conversational preview. No provider, persistence or implicit plan acceptance. */
export function WorkloadCapacityPlanning({context,prepare}:{context:Identity;prepare?:(context:Identity)=>Promise<WorkloadCapacityInput>}){
 const [input,setInput]=useState<WorkloadCapacityInput|null>(null),[message,setMessage]=useState(''),[notice,setNotice]=useState(''),[editor,setEditor]=useState(false),[preview,setPreview]=useState<Preview|null>(null),[accepted,setAccepted]=useState(false),[selected,setSelected]=useState(''),[review,setReview]=useState(false),[loading,setLoading]=useState(false),[openingContext,setOpeningContext]=useState(''),[inputContext,setInputContext]=useState('');
 const chat=useRef<HTMLInputElement>(null),generation=useRef(0),mounted=useRef(true),live=useRef(JSON.stringify(context));useLayoutEffect(()=>{live.current=JSON.stringify(context);});useEffect(()=>{const jobs=generation;mounted.current=true;return()=>{mounted.current=false;jobs.current++;};},[]);
 const currentLoading=loading&&openingContext===JSON.stringify(context);
 const current=!!input&&inputContext===JSON.stringify(context)&&input.identity.goalId===context.goalId&&input.identity.goal===context.goal&&input.identity.datasetToken===context.datasetToken;
 let report:ReturnType<typeof calculateWorkloadCapacity>|null=null,error='';if(current)try{report=calculateWorkloadCapacity(input!);}catch(e){error=(e as Error).message;}
 const focus=()=>requestAnimationFrame(()=>chat.current?.focus()),close=()=>{setEditor(false);setPreview(null);focus();};
 async function open(){const key=JSON.stringify(context),job=++generation.current;setOpeningContext(key);setLoading(true);setNotice('');try{const next=prepare?await prepare(context):createWorkloadIllustration(context,{datasetToken:context.datasetToken,binding:await actionBinding(context.goalId,context.goal,{datasetToken:context.datasetToken,sources:[]},{origin:'illustrative-OPS-CLIENT-ticket-v1'})});calculateWorkloadCapacity(next);if(!mounted.current||live.current!==key||generation.current!==job)return;if(next.identity.goalId!==context.goalId||next.identity.goal!==context.goal||next.identity.datasetToken!==context.datasetToken||next.identity.revision!==context.revision)throw Error('Scenario no longer matches the current goal, dataset or revision.');setInput(next);setInputContext(key);setAccepted(false);setSelected('');setReview(false);setEditor(false);setPreview(null);}catch(e){if(mounted.current&&live.current===key)setNotice((e as Error).message);}finally{if(mounted.current&&live.current===key)setLoading(false);}}
 function propose(next:Preview){if(!current)throw Error('Current goal or dataset changed. Open a fresh scenario.');setPreview(next);setEditor(false);setReview(false);setNotice('Changes proposed; current assumptions remain unchanged until acceptance.');focus();}
 function send(){if(!current||!input){setNotice('Open the illustrative scenario for the current goal first.');return;}try{if(/^(?:please )?(?:open|show) (?:the )?(?:assumption )?editor[.!]?$/i.test(message.trim())){setEditor(true);setPreview(null);setReview(false);setNotice('');}else propose(workloadChatChange(input,message));setMessage('');}catch(e){setNotice((e as Error).message);}}
 const option=report?.options.find(o=>o.id===selected);
 return <section aria-label="Workload and Capacity Planning" className="min-w-0 space-y-4 p-4 text-sm"><header><h1 className="text-xl font-semibold">Workload &amp; Capacity Planning</h1><p>{context.goal}</p><p className="text-xs">OPS-CLIENT · Technical Support Specialist · Illustrative ticket scenario. Volumes, handling time, availability, costs and readiness are assumptions, not observed data.</p></header>
 <p>Describe a change in your own words, review it, then accept assumptions for scenario use. Plan review is a separate step.</p>
 {!current&&<p role="status">{input?'Current goal or dataset changed. Earlier preview is unavailable; open a fresh scenario.':'No workload assumptions loaded. Open the configured illustration to explore two staffing proposals.'}</p>}
 <button className={button} disabled={currentLoading} onClick={()=>void open()}>{currentLoading?'Preparing illustration…':'Open illustrative ticket scenario'}</button>
 {notice&&<p role="status">{notice}</p>}{error&&<p role="alert">Unsupported scenario: {error} No calculated plan or save is available.</p>}
 <form onSubmit={e=>{e.preventDefault();send();}} className="space-y-2"><label>Discuss workload assumptions<input ref={chat} className={control} value={message} onChange={e=>setMessage(e.target.value)} placeholder="Use 6000 tickets per month"/></label><button className={button} disabled={currentLoading}>Review message</button><p className="text-xs">Examples: “Use 6000 tickets per month”, “Set uncommitted manager hours per month to unknown”, or “Open the editor”. Other changes remain unsupported in this preview.</p></form>
 {current&&report&&input&&<>
 {editor&&<Editor key={report.sourceKey} input={input} onReview={values=>propose(previewWorkloadValues(input,values))} onCancel={close}/>}
 {preview&&<section aria-label="Review workload assumption changes" className="space-y-2 rounded border p-3"><h2 className="font-semibold">Proposed assumption changes</h2><ul>{preview.changes.map(c=><li key={c.label}>{c.label}: {c.from} → {c.to}</li>)}</ul><p>Not accepted or saved. No measurements or plan approvals change.</p><button className={button} onClick={()=>{if(!current)return;setInput(preview.input);setPreview(null);setAccepted(true);setSelected('');setReview(false);setNotice('Assumptions accepted for scenario use in this preview. No plan was saved.');focus();}}>Accept revised scenario assumptions</button> <button className={button} onClick={close}>Cancel proposed changes</button></section>}
 <p>{accepted?'Assumptions accepted for scenario use · not a saved or accepted plan.':'Proposed illustrative assumptions · not accepted.'}</p><button className={button} disabled={accepted||!!preview||editor} onClick={()=>{setAccepted(true);setNotice('Illustrative assumptions accepted for scenario use only.');}}>Use illustrative assumptions for scenario</button>
 <details><summary className="min-h-11 cursor-pointer py-2">Details: assumptions and readiness</summary><p>Monthly ticket volume × handling minutes gives workload hours. Productive hours and target availability are reviewed assumptions. Training does not prove readiness: target capacity is 0% before reviewed month-start prerequisites, then 100%.</p><p>Training absence reduces source capacity before redeployment. Redeployment removes source contribution permanently; only separately ready backfills restore it. Manager span and available coaching hours are independent constraints. No manager or senior-leadership hire cost is invented.</p><dl>{workloadFields.map(([key,label])=><div key={key}><dt className="font-medium">{label}</dt><dd>{workloadValues(input)[key]||'Unknown'} · scenario assumption</dd></div>)}</dl><p>Revision {input.identity.revision}. No dated workload observations are linked. Only one source and manager pool, month-start readiness and the configured profile are supported.</p></details>
 <div className="grid min-w-0 gap-4 lg:grid-cols-2">{report.options.map(o=><article key={o.id} aria-label={o.id} className="min-w-0 space-y-2 rounded border p-3"><h2 className="font-semibold">Hire {o.normalizedDraft.inputs.capacity!.input.buy} · train and redeploy {o.normalizedDraft.inputs.capacity!.input.build}</h2><p>Proposed scenario · {o.status==='met'?'Conditions met under assumptions':o.status==='unknown'?'Required assumptions unknown':'Constraints not met'}</p><p>Additional role need: {quantity(o.rows[0].requiredAdditionalRoles)} · conditional, not a measured shortage.</p><p>Complete cash: {o.cash===null?'Unknown':`USD ${quantity(o.cash)}`} · Added employees: {o.addedEmployees} including source backfills.</p>
 <div role="region" aria-label={`${o.id} monthly comparison`} tabIndex={0} className="overflow-x-auto focus-visible:ring-2 focus-visible:ring-ring"><table className="w-full min-w-[38rem] text-left text-xs"><caption>Monthly conditional workload, capacity and constraints (hours unless stated)</caption><thead><tr>{['Month','Workload','Target available','Target gap','Source gap','Manager hours gap','Manager count gap','Complete cash USD'].map(h=><th className="p-2" key={h} scope="col">{h}</th>)}</tr></thead><tbody>{o.rows.map(r=><tr key={r.month}><th className="p-2" scope="row">{r.month}</th>{[r.demandHours,r.targetCapacityHours,r.targetGapHours,r.sourceGapHours,r.managerGapHours,r.managerGapCount,r.cashTotal].map((v,i)=><td className="p-2" key={i}>{quantity(v)}</td>)}</tr>)}</tbody></table></div>
 <details><summary className="min-h-11 cursor-pointer py-2">Timing, source and management details</summary><ul>{o.rows.map(r=><li key={r.month}>{r.month}: target ready {quantity(r.targetReadyRoles)} roles; source available {quantity(r.sourceCapacityHours)} h, removed {quantity(r.sourceRemovedHours)} h, restored {quantity(r.restoredHours)} h; manager required {quantity(r.managerRequiredHours)} h, available {quantity(r.managerAvailableHours)} h; required managers {quantity(r.requiredManagerCount)}.</li>)}</ul><p>Assumed hire arrival: {o.normalizedDraft.inputs.capacity!.input.arrivalDate||'Unknown'}; internal target readiness: {o.normalizedDraft.inputs.capacity!.input.buildMonth||'Unknown'}; backfill arrival: {o.normalizedDraft.inputs.capacity!.input.backfillDate||'Unknown'}. Prerequisites can delay productive capacity independently.</p><ul>{Object.entries(o.checks).map(([name,status])=><li key={name}>{name}: {status}</li>)}</ul><p>Training: {quantity(o.training.wholeProgramHours)} whole-program hours, USD {quantity(o.training.wholeProgramCash)} whole-program cash.</p>{o.rows.map(r=><p key={r.month}>{r.month} cash components: {r.cashLines.map(l=>`${l.label} ${quantity(l.amount)}`).join('; ')}. Known components do not establish a complete budget when reviews are unknown.</p>)}</details>
 <label className="flex min-h-11 items-center gap-2"><input type="radio" name="workload-option" disabled={!accepted||!!preview||editor} checked={selected===o.id} onChange={()=>{setSelected(o.id);setReview(false);}}/>Select proposed staffing option</label></article>)}</div>
 <button className={button} disabled={!option||!accepted||!!preview||editor} onClick={()=>setReview(true)}>Review proposed plan</button>
 {review&&option&&<section aria-label="Review proposed workload plan" className="space-y-3 rounded border p-3"><h2 className="font-semibold">Proposed plan review</h2><HomePlanSummary draft={option.normalizedDraft} result={reviewBundleProposal(option.normalizedDraft)}/><p role="status">Not accepted or saved. Saving and linking this workload report need an integration contract that preserves source-team and manager constraints. Existing saved goals and plans remain unchanged.</p><button className={button} disabled>Save unavailable in this preview</button> <button className={button} onClick={()=>{setReview(false);focus();}}>Cancel plan review</button></section>}
 </>}
 </section>;
}
export function SelectedWorkloadCapacity(){const state=useDecisionStorage(),goal=state.data.goals.goals.find(g=>g.id===state.data.goals.activeId),datasetToken=decisionStore.getDatasetToken();if(!state.ready||!goal)return <section className="p-4"><h1>Workload &amp; Capacity Planning</h1><p role="status">Pin or select a goal in Home before opening a workload scenario. No plan has been created.</p></section>;const context={goalId:goal.id,goal:goal.statement,datasetToken,revision:1};return <WorkloadCapacityPlanning key={JSON.stringify(context)} context={context}/>;}
