"use client";
import {calculationStepFields,workforceCostBreakdown,workforceScenarioOutcomes} from '@/lib/workforce-scenario-outcomes';
import type {WorkforceIncrement,WorkforcePlanField} from '@/lib/workforce-increment';
import {workforceReviewEvidence,type WorkforceReview} from '@/lib/workforce-solution-review';
const amount=(n:number|null)=>n===null?'Unknown':n.toLocaleString('en-US',{maximumFractionDigits:2});
const names:Partial<Record<WorkforcePlanField,string>>={build:'Build count',move:'Move count',buy:'Buy count',backfills:'backfills',buildMonth:'Build readiness',moveMonth:'Move timing',recruitingStart:'recruiting launch',arrivalMode:'arrival mode',arrivalDate:'hire arrival',backfillDate:'backfill arrival',trainingCash:'training cash',trainingHours:'training hours',loadedHourlyCost:'hourly cost',annualHireCost:'annual hire cost',hireFee:'hire fee',annualBackfillCost:'annual backfill cost',backfillFee:'backfill fee',internalAnnualCostChange:'internal salary uplift',budget:'cash budget',maxAddedEmployees:'added-employee cap',deadlineMonth:'coverage deadline'};
export function WorkforceCalculationBreakdown({plan,review,editsDisabled,scopeDisabled,onEdit,onReviewScope}:{plan:WorkforceIncrement;review:WorkforceReview;editsDisabled:boolean;scopeDisabled:boolean;onEdit:(field:WorkforcePlanField)=>void;onReviewScope:()=>void}){
 const outcome=workforceScenarioOutcomes(plan),evidence=workforceReviewEvidence(review),cashNames={hireStaffingCost:'External hire staffing',backfillStaffingCost:'External backfill staffing',internalSalaryUplift:'Internal cohort salary uplift',recruitingFees:'One-time recruiting fees',trainingCash:'Training cash'};
 const links=(group:keyof typeof calculationStepFields)=><div className="flex flex-wrap gap-2">{calculationStepFields[group].map(field=><button key={field} className="min-h-11 rounded border px-2 py-1 text-xs disabled:opacity-50" disabled={editsDisabled} onClick={()=>onEdit(field)}>Edit {names[field]}</button>)}</div>;
 return <ol className="list-decimal space-y-4 pl-5">
  <li><h6 className="font-semibold">Reviewed inputs and evidence</h6><p>{outcome.roles} additional {evidence.role} roles in {evidence.businessUnit}; {plan.input.planningMonth}, {plan.input.months} months. This scope remains fixed while tailoring an option. Evidence retained as of {evidence.asOf??'Unknown'}.</p><p>These are calculator steps and explicit assumptions. Source snapshots are retained; recomputing is not a refresh.</p><button className="min-h-11 rounded border px-2 py-1 text-xs disabled:opacity-50" disabled={scopeDisabled} onClick={onReviewScope}>Review scope in input editor</button></li>
  <li><h6 className="font-semibold">Build, Move and Buy mix</h6><p>Build {plan.input.build} + Move {plan.input.move} + Buy {plan.input.buy} = {outcome.roles} roles. Added company employees = Buy plus explicit external backfills: {outcome.addedEmployees}. Internal paths do not add company employees. Candidate pools are not assignable capacity; readiness, availability and source-team impact need verification.</p>{links('mix')}</li>
  <li><h6 className="font-semibold">Conditional timing</h6><p>Build readiness {plan.input.buildMonth||'Unknown'}; Move effective month {plan.input.moveMonth||'Unknown'}; Buy batch arrival {plan.arrivalDate??(Number(plan.input.buy)===0?'Inactive':'Unknown')}; backfill batch arrival {plan.backfillArrival??(Number(plan.input.backfills||'0')===0?'Inactive':'Unknown')}. Counts contribute to conditional coverage from their assumed active month; backfills add employees but do not cover the additional target-role demand.</p><p>Historical comparison baseline: opening-to-start median {evidence.recruiting.medianDays===null?'unavailable':`${evidence.recruiting.medianDays} days`}, sample {evidence.recruiting.sample??'Unknown'}, {evidence.recruiting.periodStart??'Unknown'} to {evidence.recruiting.periodEnd??'Unknown'}. A historical-median arrival assumption adds the rounded-up median days to the entered recruiting launch only with at least five completed starts. This is not a validated prediction or promised start date.</p>{links('timing')}</li>
  <li><h6 className="font-semibold">Incremental costs and employee time</h6><p>Hire/backfill staffing = count × annual loaded cost ÷ 12 × active calendar-day fraction in each month. Fees apply once in the arrival month. Internal uplift = annual cohort uplift ÷ 12 × active internal roles ÷ (total Build + Move roles); cohort amounts are combined before monthly rounding.</p><p>For an active Build path, training cash is placed in the first planning month; employee time value = training hours × loaded hourly cost, separate from cash. Inactive Build training contributes zero. Unknown active costs or timing remain unknown. Monthly currency values use the existing calculator&apos;s cent rounding.</p><ul>{workforceCostBreakdown(plan).map(item=><li key={item.key}>{cashNames[item.key]}: USD {amount(item.value)}</li>)}</ul><p>Cash total: USD {amount(outcome.cash)}. Separate employee time value: USD {amount(outcome.employeeTime)}. Structural annual budget, existing payroll and unrelated hiring/departures are excluded.</p>{links('costs')}</li>
  <li><h6 className="font-semibold">Scenario outcomes and constraints</h6><p>By {outcome.deadline??'an unspecified deadline'}: {amount(outcome.covered)} of {outcome.roles} roles conditionally covered; {amount(outcome.remaining)} remaining. Full coverage {outcome.fullCoverageMonth??(outcome.coverageTiming==='unknown'?'unknown because active timing is missing':'not reached within this horizon')}. These are scenario estimates under the entered assumptions.</p><p>The calculator compares cash with budget, Buy plus backfills with the added-employee cap, and conditional coverage with demand by the deadline. A preferred option depends only on your selected priority among qualifying shown options; no composite score or benefit estimate is used.</p><p>ML forecast unavailable: {outcome.forecast.reason} No completion probability, confidence range or causal training impact is estimated.</p>{links('outcomes')}<p>Editing opens a temporary what-if and shows recalculated deltas. Review them, then explicitly save a revised solution. Earlier results, evidence and approvals stay attached to their original versions.</p><p className="text-xs">Deterministic method: {outcome.method}.</p></li>
 </ol>;
}
