"use client";
import type {WorkforceOptionActions} from "@/lib/workforce-option-actions";
import {useCallback,useEffect,useId,useRef,useState} from "react";
import {cancelOwnedWorkforceRequest} from "@/lib/workforce-request-cleanup";
import {WorkforceJourneyContinue,revealJourneyTarget} from "@/components/workforce-journey-continue";
import {selectWorkforceJourney,workforceJourneyContext,type JourneyTransient} from "@/lib/workforce-journey-state";
import {decisionStore,useDecisionStorage} from "@/components/decision-store";
import {readWorkforceSolution,createWorkforceSolution,currentSolutionVersion,emptySolutionInputs,reviseWorkforceSolution,beginSolutionRun,completeSolutionRun,solutionResultIsCurrent,recordSolutionApproval,type RunTicket,type WorkforceSolution,type SolutionInputs,type SolutionSection} from "@/lib/workforce-solution";
import {emptyWorkforcePlanInput,workforcePlanFields,validateWorkforcePlanInput,type WorkforcePlanInput,type WorkforcePlanField} from "@/lib/workforce-increment";
import type {AppPage,StructuralPositionCatalogResponse} from "@/lib/types";
import {WorkforceGoalStatementCopy} from "@/components/workforce-goal-statement-copy";
import {WorkforceInputReadiness} from "@/components/workforce-input-readiness";
import {workforceInputReadiness} from "@/lib/workforce-input-readiness";
import {cardVerificationIdentity} from "@/lib/workforce-solution-cards";
import {WorkforceSolutionCards} from "@/components/workforce-solution-cards";
import {WorkforceAlternatives} from "@/components/workforce-alternatives";
import {WorkforceSolutionEvidence} from "@/components/workforce-solution-evidence";
import {readSavedWorkforceReview,readWorkforceReview,workforceReviewEvidence} from "@/lib/workforce-solution-review";
import {clarificationFailureMessage,type WorkforceClarification} from "@/lib/workforce-clarification";
const button='min-h-10 rounded border px-3 py-2 text-sm font-medium disabled:opacity-50';
const control='mt-1 w-full min-w-0 rounded border bg-background p-2 text-sm';
const field='workforceSolution';
function clearOwnedCalculation(ticket:RunTicket|null){
 if(!ticket)return;
 const snapshot=decisionStore.getSnapshot();
 if(!snapshot.data.goals.goals.some(goal=>goal.id===ticket.goalId))return;
 const next=cancelOwnedWorkforceRequest(snapshot.data.workspaces[ticket.goalId]?.fields[field],ticket);
 if(next)decisionStore.setField(ticket.goalId,field,next);
}
const groups:[keyof SolutionInputs,string,[WorkforcePlanField,string][]][]=[
 ['scope','1. Which additional role requirement?',[['businessUnit','Business unit'],['jobProfile','Job profile'],['intent','Demand type'],['planningMonth','Planning start month (YYYY-MM)'],['months','Planning horizon (months)']]],
 ['demand','2. How many additional roles?',[['roles','Additional roles']]],
 ['response','3. Which response mix should be compared?',[['build','Build: existing employees after development'],['move','Move: existing employees already ready'],['buy','Buy: external hires'],['backfills','Additional external backfills for internal moves (explicit 0 if none)']]],
 ['timing','4. When would each path take effect?',[['recruitingStart','Proposed recruiting launch (YYYY-MM-DD)'],['arrivalMode','Hiring arrival assumption'],['arrivalDate','Explicit hire arrival (YYYY-MM-DD)'],['buildMonth','Assumed Build readiness month (YYYY-MM)'],['moveMonth','Assumed Move effective month (YYYY-MM)'],['backfillDate','Assumed backfill arrival (YYYY-MM-DD)']]],
 ['costs','5. Which incremental costs are known? USD only',[['annualHireCost','Annual loaded cost per external hire (USD)'],['hireFee','One-time recruiting fee per external hire (USD)'],['annualBackfillCost','Annual loaded cost per backfill (USD)'],['backfillFee','One-time fee per backfill (USD)'],['internalAnnualCostChange','Total annual salary uplift for internal cohort (USD)']]],
 ['training','6. Training assumptions',[['trainingCash','Total training cash (USD)'],['trainingHours','Total employee training hours'],['loadedHourlyCost','Loaded hourly cost (USD/hour)']]],
 ['constraints','7. What limits should the plan meet?',[['budget','Incremental cash budget over this horizon (USD)'],['maxAddedEmployees','Maximum additional employees, including backfills'],['deadlineMonth','Required coverage month (YYYY-MM)']]],
];
function toInputs(draft:WorkforcePlanInput):SolutionInputs{const inputs=emptySolutionInputs();for(const [section,,fields] of groups)for(const [key] of fields)inputs[section][key]=draft[key];return inputs}
function fromInputs(inputs:SolutionInputs):WorkforcePlanInput{const draft=emptyWorkforcePlanInput();for(const [section,,fields] of groups)for(const [key] of fields)draft[key]=typeof inputs[section][key]==='string'?inputs[section][key] as string:'';return draft}
const shown=(value:number|null)=>value===null?'Unknown':value.toLocaleString(undefined,{maximumFractionDigits:2});
export function WorkforceSolutionPanel({page,onNavigate,optionActions,hideEntry=false}:{hideEntry?:boolean;optionActions?:WorkforceOptionActions;page:AppPage;onNavigate:(page:AppPage)=>void}){
 const entryRoot=useRef<HTMLElement|null>(null);
 const storage=useDecisionStorage(),goalId=storage.data.goals.activeId;
 const goalStatement=storage.data.goals.goals.find(goal=>goal.id===goalId)?.statement??'';
 const rawSolution=storage.data.workspaces[goalId]?.fields[field],solution=readWorkforceSolution(rawSolution);
 if(!goalId||!['home','skills','learning-development','talent-acquisition','scenario-modeling','workforce-response','decision-brief','development-planning'].includes(page))return null;
 if(rawSolution!==undefined&&(!solution||solution.goalId!==goalId))return <section role="status" className="m-6 rounded-lg border p-4">This saved workforce solution cannot be read safely. The original record is retained; editing and approval are unavailable.</section>;
 if(!solution)return page==='home'&&!hideEntry?<section ref={entryRoot} className="m-6 rounded-lg border p-4"><h2 className="text-lg font-semibold">Plan one workforce decision</h2><WorkforceJourneyContinue root={entryRoot} journey={selectWorkforceJourney({ready:storage.ready,writable:storage.saved,goals:storage.data.goals,solution:null,alternativeHistory:[]})}/><p className="my-2 text-sm">Guided inputs for one additional role requirement and business unit. Compare internal development, moves and external hiring without leaving this page. Clarify a planning statement with AI, review the proposed inputs, then calculate saved assumptions.</p><button data-journey="start-inputs" className={button} disabled={!storage.ready||!storage.saved} onClick={()=>decisionStore.setField(goalId,field,createWorkforceSolution(crypto.randomUUID(),goalId,{...emptySolutionInputs(),scope:{goalStatement}},new Date().toISOString()))}>Start guided workforce plan</button></section>:null;
 return <Workspace optionActions={page==='home'?optionActions:undefined} key={goalId} goalId={goalId} goalStatement={goalStatement} solution={solution} page={page} onNavigate={onNavigate}/>;
}
function Workspace({goalId,goalStatement,solution,page,onNavigate,optionActions}:{optionActions?:WorkforceOptionActions;goalId:string;goalStatement:string;solution:WorkforceSolution;page:AppPage;onNavigate:(p:AppPage)=>void}){
 const storage=useDecisionStorage(),version=currentSolutionVersion(solution);
 const catalog=storage.data.workspaces[goalId]?.fields.workforceCatalog as unknown as Pick<StructuralPositionCatalogResponse,'as_of'|'business_units'|'job_profiles'>|undefined;
 const selected=storage.data.workspaces[goalId]?.fields.workforceInspection as unknown as string|undefined;
 const results=solution.results.filter(item=>item.kind==='brief'&&item.calculator.name==='single-role-workforce-review');
 const result=selected?results.find(item=>item.id===selected):results.at(-1),review=result?readSavedWorkforceReview(solution,result):null;
 const [notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[dirty,setDirty]=useState(false),[approval,setApproval]=useState('');const controller=useRef<AbortController|null>(null),calculation=useRef<RunTicket|null>(null);
 const [editorSection,setEditorSection]=useState<SolutionSection|undefined>();
 const statementControl=useRef<HTMLTextAreaElement|null>(null),[statementRevision,setStatementRevision]=useState(0);
 const [statement,setStatement]=useState(''),[proposal,setProposal]=useState<{baseVersion:number;result:WorkforceClarification}|null>(null),[editorDraft,setEditorDraft]=useState<WorkforcePlanInput|undefined>(),[editorRevision,setEditorRevision]=useState(0);
 const [cardsDirty,setCardsDirty]=useState(false),[alternativeDirty,setAlternativeDirty]=useState(false),[verifiedCardSource,setVerifiedCardSource]=useState<string|null>(null);
 const journeyRoot=useRef<HTMLElement|null>(null);
 const exploration=useRef<HTMLDetailsElement|null>(null);
 const focusResult=useRef<string|null>(null);
 useEffect(()=>{if(page==='home'&&result&&focusResult.current===result.id&&result.version===version.version){focusResult.current=null;revealJourneyTarget(journeyRoot.current?.querySelector<HTMLElement>('[aria-label="Workforce solution calculation"]')??null);}},[page,result,version.version]);
 const openExploration=()=>{const root=exploration.current;if(!root)throw Error('Unavailable');root.open=true;const nested=root.querySelector('details');if(nested)nested.open=true;const search=root.querySelector<HTMLElement>('[aria-label="Bounded local scenario search"]');if(!search)throw Error('Unavailable');search.querySelector<HTMLInputElement>('input')?.focus();search.scrollIntoView({block:'nearest'})};
 const [inputJourney,setInputJourney]=useState<JourneyTransient>(),[cardJourney,setCardJourney]=useState<JourneyTransient>(),[alternativeJourney,setAlternativeJourney]=useState<JourneyTransient>();
 const journeyRecords={ready:storage.ready,writable:storage.saved,goals:storage.data.goals,solution,selectedResultId:selected,alternativeHistory:storage.data.workspaces[goalId]?.fields.workforceAlternativeReviews??[]};
 const journeyContext=workforceJourneyContext(journeyRecords);
 const journeyVerified=!!result&&verifiedCardSource===cardVerificationIdentity(solution,result.id,journeyRecords.alternativeHistory);
 const journey=selectWorkforceJourney(journeyRecords,busy?{context:journeyContext,kind:'working',operation:'calculate'}:dirty?inputJourney:cardsDirty?cardJourney:alternativeDirty?alternativeJourney:proposal?.baseVersion===version.version&&proposal.result.changes.length?{context:journeyContext,kind:'proposal'}:undefined,journeyVerified?journeyContext:undefined);
 const editsDirty=dirty||cardsDirty||alternativeDirty;
 const verifiedResult=!result?.payload.localWhatIf||verifiedCardSource===cardVerificationIdentity(solution,result.id,storage.data.workspaces[goalId]?.fields.workforceAlternativeReviews??[]);
 const current=()=>decisionStore.getField<WorkforceSolution>(goalId,field,solution);
 const save=(next:WorkforceSolution)=>decisionStore.setField(goalId,field,next);
 const interruptCurrentRequest=useCallback(()=>{
  const request=controller.current,ticket=calculation.current;
  // Release ownership before abort/store notifications can reenter cleanup.
  controller.current=null;calculation.current=null;request?.abort();
  clearOwnedCalculation(ticket);setBusy(false);
 },[]);
 // Observe store transitions directly: React may batch an A → B → A switch
 // into one render, so unmount cleanup and final-goal equality are insufficient.
 useEffect(()=>{
  const off=decisionStore.subscribe(()=>{
   const goals=decisionStore.getSnapshot().data.goals;
   if(goals.activeId!==goalId||!goals.goals.some(goal=>goal.id===goalId&&goal.statement===goalStatement))interruptCurrentRequest();
  });
  return()=>{off();interruptCurrentRequest()};
 },[goalId,goalStatement,interruptCurrentRequest]);
 const isHere=()=>{const goals=decisionStore.getSnapshot().data.goals;return goals.activeId===goalId&&goals.goals.some(goal=>goal.id===goalId&&goal.statement===goalStatement)};
 async function clarify(){if(controller.current||dirty)return;const baseVersion=version.version,c=new AbortController();controller.current=c;setBusy(true);setNotice('');setProposal(null);let failureMessage=clarificationFailureMessage(null);const timer=setTimeout(()=>c.abort(),45000);try{const r=await fetch('/api/workforce-solution/intake',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({goal:goalStatement,statement,inputs:fromInputs(version.inputs)}),signal:c.signal});const body=await r.json();if(!r.ok){failureMessage=clarificationFailureMessage(body);throw Error('Intake failed.');}if(controller.current!==c||!isHere()||c.signal.aborted||currentSolutionVersion(current()).version!==baseVersion)return;setProposal({baseVersion,result:body});setNotice('Review the proposed inputs. Saved assumptions and calculations have not changed.');}catch{if(controller.current===c&&isHere())setNotice(c.signal.aborted?'Clarification cancelled or timed out; saved inputs retained.':failureMessage)}finally{clearTimeout(timer);if(controller.current===c){controller.current=null;setBusy(false)}}}
 async function loadCatalog(){if(controller.current)return;const c=new AbortController();controller.current=c;setBusy(true);setNotice('');try{const r=await fetch('/api/position-structure',{signal:c.signal,cache:'no-store'});const body=await r.json();if(!r.ok)throw Error(body.error||'Governed catalog unavailable.');if(controller.current===c&&isHere()&&!c.signal.aborted)decisionStore.setField(goalId,'workforceCatalog',{as_of:body.as_of,business_units:body.business_units,job_profiles:body.job_profiles});}catch(e){if(controller.current===c&&isHere())setNotice((e as Error).message)}finally{if(controller.current===c){controller.current=null;setBusy(false)}}}
 async function calculate(){if(controller.current||current().pending)return;let started;try{validateWorkforcePlanInput(fromInputs(version.inputs));started=beginSolutionRun(current(),version.version,crypto.randomUUID(),['brief'],new Date().toISOString());}catch(e){setNotice((e as Error).message);return}
  const c=new AbortController();controller.current=c;calculation.current=started.ticket;setBusy(true);setNotice('');const timer=setTimeout(()=>{if(controller.current===c){interruptCurrentRequest();setNotice('Cancelled or timed out; prior results retained.')}},65000);
  try{save(started.state);if(c.signal.aborted)return;const input=fromInputs(version.inputs),r=await fetch('/api/workforce-solution',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(input),signal:c.signal});const body=await r.json();if(!r.ok)throw Error(body.error||'Workforce comparison unavailable.');if(controller.current!==c||!isHere()||c.signal.aborted)return;
   if(!readWorkforceReview(body)||body.version!==1||!body.input||Object.keys(body.input).length!==workforcePlanFields.length||workforcePlanFields.some(key=>body.input[key]!==input[key])||!Array.isArray(body.proposed?.rows)||!Array.isArray(body.hireOnly?.rows))throw Error('Calculation did not match reviewed inputs.');
   const next=completeSolutionRun(current(),started.ticket,[{id:crypto.randomUUID(),kind:'brief',calculator:{name:'single-role-workforce-review',version:'1'},payload:body}],new Date().toISOString());focusResult.current=next.results.at(-1)!.id;save(next);decisionStore.setField(goalId,'workforceInspection',next.results.at(-1)!.id);setNotice('Calculated comparison saved. Evidence and inputs are retained with this result; no real-world action occurred.');
  }catch(e){if(controller.current===c&&isHere())setNotice(c.signal.aborted?'Cancelled or timed out; prior results retained.':(e as Error).message)}finally{clearTimeout(timer);clearOwnedCalculation(started.ticket);if(calculation.current?.id===started.ticket.id)calculation.current=null;if(controller.current===c){controller.current=null;setBusy(false)}}
 }
 const goalChanged=version.inputs.scope.goalStatement!==goalStatement;
 const currentResult=!goalChanged&&result?result.version===version.version&&solutionResultIsCurrent(solution,result):false;
 const evidence=review?workforceReviewEvidence(review):null;
 const goalCopyContext=()=>{
  const snapshot=decisionStore.getSnapshot(),saved=readWorkforceSolution(snapshot.data.workspaces[goalId]?.fields[field]);
  if(!saved)throw Error('Saved goal unavailable.');
  const latest=currentSolutionVersion(saved),goal=snapshot.data.goals.goals.find(item=>item.id===goalId);
  return {goalId:goalId,goalText:goal?.statement??'',solutionId:saved.id,version:latest.version,inputIdentity:JSON.stringify(latest.inputs),selectionId:String(snapshot.data.workspaces[goalId]?.fields.workforceInspection??''),blocked:busy||editsDirty||!!saved.pending||!snapshot.saved||snapshot.data.goals.activeId!==goalId||saved.id!==solution.id||latest.version!==version.version||goal?.statement!==latest.inputs.scope.goalStatement};
 };

 const reviewSection=(section:SolutionSection)=>{if(busy||editsDirty)return;setEditorDraft(undefined);setEditorSection(section);setEditorRevision(n=>n+1);setNotice('Review current saved assumptions. Historical evidence stays attached to its calculation; save and recalculate explicitly.');};
 return <section ref={journeyRoot} aria-label="Workforce solution workspace" className="m-6 min-w-0 space-y-4 rounded-lg border border-primary/40 p-4">
  <h2 tabIndex={-1} data-home-planner-heading className="text-xl font-semibold">Your workforce options</h2>
  {page==='home'&&<p className="text-sm break-words"><strong>Confirmed goal:</strong> {goalStatement}</p>}
  {journey.step!=='compare'&&<WorkforceJourneyContinue journey={journey} root={journeyRoot} tailoring={cardsDirty}/>}
  {!storage.saved&&<p data-journey="storage-blocked" tabIndex={-1} role="status">{storage.notice??'Browser storage is unavailable. Saved records are retained.'}</p>}
  <p data-journey="notice" tabIndex={-1} className="text-sm">Synthetic company evidence. Skills availability and hiring start dates remain unverified.</p>
  {page!=='home'&&<button className={button} disabled={editsDirty||busy} onClick={()=>onNavigate('home')}>Return to this goal on Home</button>}
  <details open={!result||dirty||!!proposal?true:undefined}><summary className="min-h-11 cursor-pointer py-2 font-semibold">Review assumptions and goal statement</summary>
  <button className={button} disabled={busy||cardsDirty||alternativeDirty} onClick={()=>void loadCatalog()}>{catalog?'Refresh governed role and BU choices':'Load governed role and BU choices'}</button>{catalog&&<p className="text-xs">Catalog snapshot {catalog.as_of}; calculations retrieve and retain their actual source snapshot. Global workforce filters do not change this explicitly selected role/BU.</p>}
  <section aria-label="Workforce clarification" className="space-y-2 rounded border p-3"><h3 className="font-semibold">Clarify your workforce statement</h3><p className="text-sm">Send only this goal, your statement, saved planning inputs and the synthetic BU/role catalog to the existing AI model. Enter planning assumptions only; leave out employee details, owner or approval notes, and credentials.</p><label className="block text-sm">Planning statement<textarea aria-label="Planning statement" ref={statementControl} className={control} maxLength={3000} value={statement} disabled={busy||cardsDirty||alternativeDirty} onChange={e=>{setStatement(e.target.value);setStatementRevision(value=>value+1);setProposal(null)}}/></label><WorkforceGoalStatementCopy key={JSON.stringify([goalId,version.version,goalStatement,dirty,statementRevision])} statement={statement} currentContext={goalCopyContext} disabled={busy||editsDirty||goalChanged||!!solution.pending||!goalStatement.trim()} onCopy={text=>{setStatement(text);setProposal(null)}} onFocusStatement={()=>statementControl.current?.focus()}/><button className={button} disabled={busy||editsDirty||goalChanged||!statement.trim()} onClick={()=>void clarify()}>Clarify statement with AI</button>{proposal&&proposal.baseVersion===version.version&&<div className="space-y-2 text-sm"><p>{proposal.result.summary}</p><ul className="list-disc pl-5">{proposal.result.questions.map((q,i)=><li key={i}>{q}</li>)}</ul><ul className="list-disc pl-5">{proposal.result.changes.map(change=><li key={change.field}>{groups.flatMap(g=>g[2]).find(f=>f[0]===change.field)?.[1]}: {change.value} — from “{change.evidence}”</li>)}</ul><button data-journey="review-proposal" className={button} disabled={busy||editsDirty||goalChanged||!proposal.result.changes.length} onClick={()=>{setEditorSection(undefined);setEditorDraft(proposal.result.draft);setEditorRevision(n=>n+1);setDirty(true);setInputJourney({context:journeyContext,kind:'input-draft',input:proposal.result.draft});setNotice('Proposed changes opened for review. Save reviewed inputs explicitly to use them.')}}>Review proposed changes</button></div>}</section>
  <InputEditor key={`${version.version}:${editorRevision}`} initialDraft={editorDraft} focusSection={editorSection} inputs={version.inputs} catalog={catalog} version={version.version} dirty={dirty} goalChanged={goalChanged} selectedVersion={result?.version} selectedCurrent={!!currentResult} disabled={busy||cardsDirty||alternativeDirty} onDirty={(changed,draft)=>{setDirty(changed);setInputJourney({context:journeyContext,kind:'input-draft',input:draft})}} onSave={draft=>{try{save(reviseWorkforceSolution(current(),version.version,{...toInputs(draft),scope:{...toInputs(draft).scope,goalStatement}},page==='home'?'conversation':'sidebar','Updated workforce assumptions',new Date().toISOString()));if(!decisionStore.getSnapshot().saved)throw Error('Browser storage did not save; keep this working copy for review.');setDirty(false);setInputJourney(undefined);setEditorDraft(undefined);setEditorSection(undefined);setProposal(null);setNotice('Inputs saved; dependent prior results need explicit recalculation.')}catch(e){setNotice((e as Error).message)}}}/>
  <p className="text-xs text-muted-foreground">Review before running: all cash amounts are USD; budget excludes employee time value. Each path uses one common arrival/effective date. Annual costs are divided by 12 with calendar-day arrival-month proration. Training cash/time is placed in the first planning month. Blank amounts stay unknown. Source-team backfills require an explicit count, including 0 if none. Replacement-only demand is not supported by this initial workflow.</p>
  </details>
  <details open={!currentResult||busy||!!solution.pending||undefined}><summary className="min-h-11 cursor-pointer py-2">Calculate or update options</summary><div className="flex flex-wrap gap-2"><button data-journey="calculate" className={button} disabled={busy||editsDirty||goalChanged||!!solution.pending} onClick={()=>void calculate()}>{page==='home'?'Calculate options':'Calculate saved assumptions and compare hiring-only'}</button>{(busy||solution.pending)&&<button data-journey="working" className={button} onClick={()=>{const pending=readWorkforceSolution(decisionStore.getSnapshot().data.workspaces[goalId]?.fields[field])?.pending;interruptCurrentRequest();clearOwnedCalculation(pending??null);setNotice('Request cancelled; saved inputs and previous results retained.')}}>Cancel pending request</button>}</div></details>
  {selected&&!result&&<p role="status">The selected saved calculation is unavailable. Its reference and history are retained.</p>}
  {goalChanged&&<p className="text-sm">The goal wording changed. Review and save the inputs to bind them to the current goal before calculating or recording approval.</p>}
  {dirty&&<p className="text-sm">Unsaved input changes: save reviewed inputs before recalculating, inspecting another destination or recording approval.</p>}
  {notice&&<p role="status" className="text-sm">{notice}</p>}
  {results.length>0&&<details><summary className="min-h-11 cursor-pointer py-2">Saved calculations</summary><label className="block text-sm">Inspect a saved calculation<select aria-label="Inspect a saved calculation" data-journey="unavailable" className={control} disabled={editsDirty||busy} value={selected??result?.id??''} onChange={e=>decisionStore.setField(goalId,'workforceInspection',e.target.value)}>{!result&&<option value={selected??''}>Unavailable saved calculation</option>}{results.map(item=><option key={item.id} value={item.id}>Version {item.version} — {new Date(item.completedAt).toLocaleString()}</option>)}</select></label></details>}
  {result&&!review&&<p role="status" className="text-sm">This saved workforce calculation cannot be read safely. The original record is retained; approval is unavailable. Select another saved calculation to inspect retained history, or review saved inputs and calculate explicitly to create a new result.</p>}
  {result&&review&&<section tabIndex={-1} aria-label="Workforce solution calculation" className="space-y-3 border-t pt-4"><h3 className="sr-only">Calculated decision brief — version {result.version}</h3>{!currentResult&&<p className="text-sm">Historical result: assumptions changed; recalculate before approval.</p>}
   <p className="text-sm font-medium">{review.input.roles} additional {evidence?.role} positions in {evidence?.businessUnit} · {review.input.planningMonth}, {review.input.months} months.</p>
   <WorkforceSolutionCards optionActions={optionActions} onExplore={currentResult?openExploration:undefined} solution={solution} resultId={result.id} blocked={dirty||alternativeDirty||busy||!!solution.pending} onDraftChange={setCardsDirty} onVerified={setVerifiedCardSource} journeyContext={journeyContext} onJourneyChange={setCardJourney} onReviewScope={()=>reviewSection('scope')}/>
   <details><summary className="min-h-11 cursor-pointer py-2 font-medium">Calculation evidence and methodology</summary>
   <p className="text-sm">Modeled structural annual budget reference: USD {shown(review.structural.authorizedAnnualBudgetDelta as number|null)}. {String(review.structural.costBasisPeriod)}. This is not added to incremental cash.</p>
   <details><summary className="cursor-pointer font-medium">Monthly incremental plan</summary><div className="max-h-80 overflow-auto" tabIndex={0}><table className="min-w-[700px] text-left text-sm"><caption>Proposed mix: conditional role coverage, incremental employees and USD cash. Existing workforce/payroll and unrelated hiring or departures are excluded.</caption><thead><tr>{['Month','Conditional role coverage','Added employees','Incremental cash','Employee time value'].map(x=><th className="p-2" key={x}>{x}</th>)}</tr></thead><tbody>{review.proposed.rows.map(row=><tr key={row.month}><th className="p-2">{row.month}</th><td className="p-2">{shown(row.conditionalRoleCoverage)}</td><td className="p-2">{shown(row.addedEmployees)}</td><td className="p-2">{shown(row.incrementalCash)}</td><td className="p-2">{shown(row.employeeTimeValue)}</td></tr>)}</tbody></table></div></details>
   <details><summary className="cursor-pointer font-medium">Unknowns and limitations</summary><ul className="list-disc space-y-1 pl-5 text-xs">{[...review.limitations,...review.proposed.warnings,...((review.response.warnings??[]) as string[])].map((text,i)=><li key={i}>{text}</li>)}</ul></details>
   </details>
   <details ref={exploration} open={alternativeDirty||undefined}><summary className="min-h-11 cursor-pointer py-2 font-medium">{currentResult?'Explore more options':'Saved alternative reviews'}</summary><p className="text-sm">Explore different Build, Move and Buy bounds using the saved assumptions. Confirm the bounds and run the local search explicitly; more eligible options are not guaranteed.</p><WorkforceAlternatives key={`${result.id}:${version.version}`} solution={solution} evidenceResultId={result.id} input={review.input} blocked={dirty||cardsDirty||busy||!currentResult||!!solution.pending} onDirty={setAlternativeDirty} journeyContext={journeyContext} onJourneyChange={setAlternativeJourney}/></details>
   <details><summary className="min-h-11 cursor-pointer py-2 font-medium">Source evidence and supporting pages</summary><WorkforceSolutionEvidence review={review} page={page} editsBlocked={editsDirty||busy} onReview={reviewSection}/>
   <div className="flex flex-wrap gap-2">{([['skills','Inspect Skills evidence'],['learning-development','Inspect L&D pathways'],['talent-acquisition','Inspect hiring timing evidence'],['scenario-modeling','Customize Planning assumptions'],['decision-brief','Open decision notes for this calculation']] as [AppPage,string][]).filter(([destination])=>destination!==page).map(([destination,label])=><button key={destination} className={button} disabled={editsDirty||busy} onClick={()=>{decisionStore.setField(goalId,'workforceInspection',result.id);onNavigate(destination)}}>{label}</button>)}</div>
   <details><summary className="cursor-pointer font-medium">Exact evidence, assumptions and calculations used</summary><p className="text-xs">Saved calculation {result.id}, solution {solution.id}, version {result.version}. These are returned data and formulas, not hidden model reasoning. Other charts on this page may show newer or differently scoped evidence.</p><pre className="max-h-96 overflow-auto whitespace-pre-wrap break-words rounded bg-muted p-2 text-xs">{JSON.stringify(page==='talent-acquisition'?{source:review.source,timing:review.timing,assumption:review.proposed.arrivalBasis,arrival:review.proposed.arrivalDate}:page==='skills'||page==='learning-development'?{source:review.source,internalReadiness:review.response.internal_talent_readiness,skillBundle:review.response.skill_bundle}:review,null,2)}</pre></details>
   </details>
   {!verifiedResult&&<p role="status">Local result lineage is not verified. Approval is unavailable; saved records are retained.</p>}
   {alternativeDirty&&<p role="status">Save or cancel temporary alternative edits before tailoring another option.</p>}
   <details><summary className="min-h-11 cursor-pointer py-2 font-medium">Approval records</summary><label className="block text-sm">Approval note for this solution version (local record only)<input className={control} value={approval} maxLength={1000} onChange={e=>setApproval(e.target.value)}/></label><button className={button} disabled={!currentResult||!verifiedResult||editsDirty||busy||!approval.trim()} onClick={()=>{try{save(recordSolutionApproval(current(),version.version,crypto.randomUUID(),[result.id],approval,new Date().toISOString()));setApproval('');setNotice('Approval note recorded for this version only. Nothing executed.')}catch(e){setNotice((e as Error).message)}}}>Record version-specific approval note</button>
   <ul className="space-y-1 text-xs">{solution.approvals.map(item=><li key={item.id}>Version {item.version}{item.version!==version.version?' (historical)':''}: {item.text}</li>)}</ul></details>
  </section>}
 </section>;
}
function InputEditor({inputs,initialDraft,focusSection,catalog,version,dirty,goalChanged,selectedVersion,selectedCurrent,disabled,onSave,onDirty}:{version:number;dirty:boolean;goalChanged:boolean;selectedVersion?:number;selectedCurrent:boolean;disabled:boolean;inputs:SolutionInputs;initialDraft?:WorkforcePlanInput;focusSection?:SolutionSection;catalog:Pick<StructuralPositionCatalogResponse,'business_units'|'job_profiles'>|undefined;onSave:(draft:WorkforcePlanInput)=>void;onDirty:(dirty:boolean,draft:WorkforcePlanInput)=>void}){
 const focusedSection=useRef<HTMLFieldSetElement|null>(null),editor=useRef<HTMLDetailsElement|null>(null),controls=useRef<Partial<Record<WorkforcePlanField,HTMLInputElement|HTMLSelectElement>>>({}),idPrefix=useId();
 useEffect(()=>{if(focusSection){revealJourneyTarget(focusedSection.current);}},[focusSection]);
 const [draft,setDraft]=useState(()=>initialDraft??fromInputs(inputs));const change=(key:WorkforcePlanField,value:string)=>{const next={...draft,[key]:value};setDraft(next);onDirty(true,next)};
 const readiness=workforceInputReadiness(draft),labels=Object.fromEntries(groups.flatMap(group=>group[2])) as Record<WorkforcePlanField,string>;
 const focusField=(key:WorkforcePlanField)=>{if(disabled)return;if(editor.current)editor.current.open=true;controls.current[key]?.focus();controls.current[key]?.scrollIntoView({block:'center'})};
 const description=(key:WorkforcePlanField)=>{const index=readiness.corrections.findIndex(issue=>issue.fields.includes(key));return index<0?undefined:`${idPrefix}-correction-${index}`};
 return <><WorkforceInputReadiness input={draft} version={version} dirty={dirty} goalChanged={goalChanged} selectedVersion={selectedVersion} selectedCurrent={selectedCurrent} disabled={disabled} labels={labels} onFocus={focusField} idPrefix={idPrefix}/><details ref={editor} open={initialDraft||focusSection?true:undefined}><summary data-journey="historical" className="cursor-pointer font-semibold"><span data-journey="align-goal" tabIndex={-1}>Review and customize inputs</span></summary><div className="mt-3 space-y-4">{groups.map(([section,title,fields])=><fieldset disabled={disabled} key={section} ref={section===focusSection?focusedSection:undefined} tabIndex={section===focusSection?-1:undefined} className="rounded border p-3 focus:outline-2 focus:outline-primary"><legend className="px-1 text-sm font-semibold">{title}</legend><div className="grid gap-3 sm:grid-cols-2">{fields.map(([key,label])=>{const choices=key==='businessUnit'?catalog?.business_units.map(row=>[row.org_code,row.org_name]):key==='jobProfile'?catalog?.job_profiles.map(row=>[row.job_profile_code,row.job_profile_name]):key==='intent'?[['additional','Additional positions'],['replacement','Replacement-only (not supported here)']]:key==='arrivalMode'?[['historical-median','Use historical opening-to-start median as an assumption'],['explicit','Use my explicit arrival date']]:undefined;return <label key={key} className="min-w-0 text-sm">{label}{choices?<select ref={node=>{if(node)controls.current[key]=node;else delete controls.current[key]}} data-journey-field={key} aria-invalid={!!description(key)} aria-describedby={description(key)} aria-label={label} className={control} value={draft[key]} onChange={e=>change(key,e.target.value)}><option value="">Unknown / choose</option>{choices.map(([value,text])=><option key={value} value={value}>{text}</option>)}</select>:<input ref={node=>{if(node)controls.current[key]=node;else delete controls.current[key]}} data-journey-field={key} aria-invalid={!!description(key)} aria-describedby={description(key)} aria-label={label} className={control} value={draft[key]} maxLength={100} onChange={e=>change(key,e.target.value)}/>}</label>})}</div></fieldset>)}<button data-journey="save-inputs" className={button} disabled={disabled} onClick={()=>onSave(draft)}>Save reviewed inputs</button><p className="text-xs">Saving creates a new solution version. It does not run calculations, change source evidence or carry approvals to the new version.</p></div></details></>;
}
