// Illustrative timing only; no headcount, execution-allocation or model-agent mutation.
// @ts-expect-error Native Node tests run the shared TypeScript source.
import {developmentCost,validateQuote,type DevelopmentOption} from "./development-costs.ts";
export type TrainingTimingInputs={planningMonth:string;startOffset:string;duration:string;impactLag:string;ramp:string;completionPct:string;successPct:string;workTimePct:string;metric:string;gainPerSuccess:string;hireOffset:string;hireLead:string;hireRamp:string};
export const emptyTrainingTiming=():TrainingTimingInputs=>({planningMonth:"",startOffset:"0",duration:"",impactLag:"",ramp:"",completionPct:"",successPct:"",workTimePct:"",metric:"",gainPerSuccess:"",hireOffset:"",hireLead:"",hireRamp:""});
export const timingFingerprint=(option:DevelopmentOption,input:TrainingTimingInputs)=>JSON.stringify({option,input});
function number(value:string,label:string,max:number,integer=false,required=false,min=0):number|null{if(typeof value!=="string"||value.length>16)throw Error(`${label}: invalid input.`);if(value===""){if(required)throw Error(`Enter ${label.toLowerCase()}.`);return null}if(!/^\d+(\.\d{1,2})?$/.test(value))throw Error(`${label}: use a nonnegative number with up to two decimals.`);const n=Number(value);if(!Number.isFinite(n)||n<min||n>max||integer&&!Number.isInteger(n))throw Error(`${label}: enter ${integer?"a whole number":"a number"} from ${min} to ${max}.`);return n}
function monthIndex(value:string){const m=/^(\d{4})-(\d{2})$/.exec(value);if(!m||Number(m[1])<1900||Number(m[1])>2200||Number(m[2])<1||Number(m[2])>12)throw Error("Enter a valid planning start month (1900-2200).");return Number(m[1])*12+Number(m[2])-1}
const month=(index:number)=>`${Math.floor(index/12)}-${String(index%12+1).padStart(2,"0")}`;
const round=(n:number)=>Math.round((n+Number.EPSILON)*100)/100;
function spread(total:number|null,count:number,index:number){if(total===null)return null;const units=Math.round(total*100);if(!Number.isSafeInteger(units))throw Error("The cost or hours total is too large for exact monthly allocation.");return (Math.floor(units/count)+(index<units%count?1:0))/100}
function fraction(index:number,start:number|null,ramp:number|null){return start===null||ramp===null?null:index<start?0:ramp===0?1:Math.min(1,(index-start+1)/ramp)}
export function calculateTrainingTiming(option:DevelopmentOption,input:TrainingTimingInputs){
 const base=monthIndex(input.planningMonth),start=number(input.startOffset,"Training start offset",24,true,true)! ,duration=number(input.duration,"Training duration",24,true,true,1)!;
 const lag=number(input.impactLag,"Impact lag",24,true),ramp=number(input.ramp,"Training ramp",24,true),completion=number(input.completionPct,"Completion rate",100),success=number(input.successPct,"Success among completers",100),workTime=number(input.workTimePct,"Working-time share",100),gain=number(input.gainPerSuccess,"Capability units per successful completer",1000000);
 const hireOffset=number(input.hireOffset,"Hiring start offset",24,true),hireLead=number(input.hireLead,"Hiring lead time",24,true),hireRamp=number(input.hireRamp,"Hiring ramp",24,true);
 if(typeof input.metric!=="string"||input.metric.length>80||gain!==null&&!input.metric.trim())throw Error("Name the capability measure when entering a per-person gain (up to 80 characters).");
 const cost=developmentCost(option.quote,option.inputs),errors=[...validateQuote(option.quote),...cost.errors];if(errors.length)throw Error(errors.join(" "));
 const completionIndex=start+duration-1,impactStart=lag===null?null:start+duration+lag,fullImpact=impactStart===null||ramp===null?null:impactStart+Math.max(0,ramp-1),hireStart=hireOffset===null||hireLead===null?null:hireOffset+hireLead,hireFull=hireStart===null||hireRamp===null?null:hireStart+Math.max(0,hireRamp-1);
 if([completionIndex,impactStart,fullImpact,hireStart,hireFull].some(n=>n!==null&&n>=36))throw Error("Keep training completion, impact and hiring milestones within the 36-month comparison horizon.");
 const participants=option.inputs.participants===""?null:Number(option.inputs.participants),completers=participants===null||completion===null?null:participants*completion/100,successful=completers===null||success===null?null:completers*success/100,capability=successful===null||gain===null?null:successful*gain;
 const diverted=cost.employeeHours===null||workTime===null?null:round(cost.employeeHours*workTime/100);
 const rows=Array.from({length:36},(_,i)=>{const training=i>=start&&i<=completionIndex,elapsed=i-start,trainingRamp=fraction(i,impactStart,ramp),hiringRamp=fraction(i,hireStart,hireRamp);const cash=training?spread(cost.cashCost,duration,elapsed):0,time=training?spread(cost.timeCost,duration,elapsed):0;return {month:month(base+i),phase:i<start?"Not started":training?"Training":impactStart===null?"Impact timing unknown":i<impactStart?"Post-training lag":trainingRamp===null?"Ramp unknown":trainingRamp<1?"Assumed ramp":"Assumed full effect",cashCost:cash,timeCost:time,totalCost:cash===null||time===null?null:round(cash+time),employeeHours:training?spread(cost.employeeHours,duration,elapsed):0,divertedHours:training?spread(diverted,duration,elapsed):0,expectedCompleters:i<completionIndex?0:completers===null?null:round(completers),capabilityUnits:trainingRamp===0?0:trainingRamp===null||capability===null?null:round(capability*trainingRamp),trainingRampPct:trainingRamp===null?null:round(trainingRamp*100),hiringReadinessPct:hiringRamp===null?null:round(hiringRamp*100)}});
 return {version:1 as const,calculatedAt:new Date().toISOString(),fingerprint:timingFingerprint(option,input),option:JSON.parse(JSON.stringify(option)) as DevelopmentOption,input:{...input},trainingStart:month(base+start),completionMonth:month(base+completionIndex),firstPossibleImpact:impactStart===null?null:month(base+impactStart),fullImpact:fullImpact===null?null:month(base+fullImpact),hireArrival:hireStart===null?null:month(base+hireStart),hireFullReadiness:hireFull===null?null:month(base+hireFull),expectedCompleters:completers===null?null:round(completers),expectedSuccessfulCompleters:successful===null?null:round(successful),fullCapabilityUnits:capability===null?null:round(capability),cost,divertedHours:diverted,rows};
}
export type TrainingTimingResult=ReturnType<typeof calculateTrainingTiming>;
